/* =====================================================================
   Conteúdo v5: +50 missões, +63 conquistas (nova categoria Singularidade),
   títulos novos e as descrições EN/ES das bolas novas.
   Carregado depois de skins.js (as conquistas de coleção contam o catálogo).
   ===================================================================== */
window.HR = window.HR || {};

(function () {
  const M = (id, icon, kind, src, tiers, weekly) => HR.MISSIONS.push(Object.assign({ id, icon, kind, src, tiers }, weekly ? { weekly: true } : {}));
  // Égide e Jato
  M('aegis_use', 'aegis', 'total', 'aegisUsed', [[1, 80, 0, 40], [2, 150, 0, 70], [4, 250, 5, 120]]);
  M('aegis_save', 'shieldHalf', 'total', 'aegisSaves', [[1, 90, 0, 40], [2, 160, 5, 80], [4, 260, 8, 130]], true);
  M('aegis_run', 'aegis', 'run', 'aegisSaves', [[1, 100, 0, 50], [2, 180, 5, 90], [3, 280, 8, 140]]);
  M('jet_use', 'jet', 'total', 'jetsUsed', [[1, 80, 0, 40], [2, 150, 0, 70], [3, 240, 5, 120]], true);
  M('aegis_week', 'aegis', 'total', 'aegisSaves', [[3, 240, 8, 120], [6, 400, 12, 200], [10, 620, 18, 300]], true);
  // poderes novos
  ['blackhole', 'prism', 'phoenix', 'goldrush', 'micro', 'comet', 'supernova', 'chrono'].forEach(a => M(a, (HR.ABILITIES.find(x => x.id === a) || {}).icon || 'powers', 'total', 'ab_' + a, [[2, 60, 0, 30], [5, 110, 0, 50], [10, 190, 5, 90]]));
  // Galáxia v5 e Singularidade
  M('systems', 'system', 'total', 'systemDone', [[1, 150, 5, 80], [2, 260, 10, 140], [3, 400, 15, 220]], true);
  M('galaxy_clear', 'galaxy', 'total', 'galaxyDone', [[1, 400, 20, 250], [1, 500, 25, 300], [1, 800, 40, 450]], true);
  M('speed_run', 'speed', 'run', 'speedPct', [[200, 90, 0, 40], [260, 160, 5, 80], [320, 260, 8, 140]]);
  M('eco_find', 'eco', 'total', 'ecoFound', [[1, 150, 5, 80], [2, 260, 10, 140], [3, 400, 15, 220]], true);
  M('sg_passage', 'light', 'total', 'sgPassage', [[1, 150, 5, 80], [3, 280, 10, 150], [5, 450, 15, 240]], true);
  M('sg_trial', 'sigil', 'total', 'sgTrial', [[1, 500, 25, 300], [1, 600, 30, 350], [1, 900, 45, 500]], true);
  // exigências: a missão só entra no sorteio quando dá para cumprir (e as grandes não triplicam na semanal)
  const X = (id, o) => Object.assign(HR.MISSIONS.find(t => t.id === id), o);
  const CP = () => HR.Campaign, SG = () => HR.Singularity, owns = k => () => HR.Consumables.count(k) > 0;
  const sgLeft = () => SG().isOpen() && SG().passedCount() < HR.ARCHONS.length;
  ['aegis_use', 'aegis_save', 'aegis_run'].forEach(id => X(id, { req: owns('aegis') }));
  X('aegis_week', { req: owns('aegis'), noMul: true });
  X('jet_use', { noMul: true, req: () => HR.Consumables.count('jet') + HR.Consumables.count('megajet') > 0 });
  X('systems', { weeklyOnly: true, noMul: true, req: () => CP().systemsCleared() < HR.REGIONS.length * 10 });
  X('galaxy_clear', { weeklyOnly: true, noMul: true, req: () => { const ri = CP().currentRegion(); return !CP().regionCleared(ri) && CP().systemsClearedIn(ri) >= 8; } });
  X('speed_run', { req: () => ((HR.Store.data.stats5 || {}).speedPct || 0) >= 180 });
  X('eco_find', { noMul: true, req: () => { if (!sgLeft()) return false; let all = 0; for (let i = 0; i < HR.ARCHONS.length; i++) all += SG().layer(i).ecos.length; return all - SG().totalEcos() >= 3; } });
  X('sg_passage', { noMul: true, req: sgLeft });
  X('sg_trial', { weeklyOnly: true, noMul: true, req: () => sgLeft() && SG().trialReady(SG().current()).ok });
  // desafios de uma partida
  M('perfects_huge', 'target', 'run', 'perfects', [[30, 120, 0, 60], [45, 200, 5, 100], [60, 320, 10, 160]]);
  M('combo_huge', 'flame', 'run', 'maxCombo', [[15, 120, 0, 60], [25, 210, 5, 110], [40, 330, 10, 170]]);
  M('coins_huge', 'coins', 'run', 'coins', [[300, 140, 0, 60], [500, 230, 5, 110], [800, 360, 10, 180]]);
  M('near_huge', 'wind', 'run', 'nearMisses', [[8, 100, 0, 50], [15, 180, 5, 90], [25, 280, 8, 140]]);
  M('items_huge', 'gift', 'run', 'pickups', [[10, 110, 0, 50], [15, 190, 5, 90], [25, 300, 8, 150]]);
  M('center_run', 'target', 'run', 'centerPickups', [[2, 90, 0, 40], [4, 160, 5, 80], [6, 260, 8, 130]]);
  M('flow_run', 'wind', 'run', 'flowTime', [[20, 100, 0, 50], [40, 180, 5, 90], [80, 290, 8, 150]]);
  M('obstacles_run', 'asteroid', 'run', 'obstaclesDestroyed', [[3, 90, 0, 40], [6, 160, 5, 80], [10, 260, 8, 130]]);
  M('shattered_run', 'sparkles', 'run', 'shattered', [[3, 90, 0, 40], [6, 160, 5, 80], [10, 260, 8, 130]]);
  M('gold_run', 'goldRing', 'run', 'goldRings', [[5, 100, 0, 50], [10, 180, 5, 90], [20, 300, 8, 150]]);
  M('double_run', 'layers', 'run', 'doubleRings', [[5, 90, 0, 40], [10, 170, 5, 85], [15, 270, 8, 135]]);
  M('dir_huge', 'compass', 'run', 'dirChanges', [[4, 100, 0, 50], [6, 180, 5, 90], [8, 280, 8, 140]]);
  M('time_huge', 'clock', 'run', 'duration', [[180, 100, 0, 50], [300, 190, 5, 95], [480, 300, 8, 150]]);
  M('score_huge', 'ring', 'run', 'score', [[150, 150, 5, 70], [200, 250, 8, 120], [260, 380, 12, 190]]);
  M('perks_huge', 'card', 'run', 'perksCount', [[6, 110, 0, 55], [8, 190, 5, 95], [10, 300, 8, 150]]);
  M('anomaly_run', 'orbit', 'run', 'anomaliesBeaten', [[1, 120, 0, 60], [2, 220, 5, 110], [3, 340, 10, 170]]);
  M('guardian_run', 'guardianRing', 'run', 'guardians', [[1, 110, 0, 55], [2, 200, 5, 100], [3, 320, 10, 160]]);
  M('sentinel_run', 'sentinel', 'run', 'sentinels', [[1, 110, 0, 55], [2, 200, 5, 100], [3, 320, 10, 160]]);
  M('warp_run', 'warp', 'run', 'warps', [[1, 100, 0, 50], [2, 180, 5, 90], [3, 290, 8, 145]]);
  M('asteroid_run', 'asteroid', 'run', 'asteroidsDestroyed', [[3, 100, 0, 50], [6, 180, 5, 90], [10, 290, 8, 145]]);
  M('clean_huge', 'sparkle', 'run', 'cleanRings', [[30, 120, 0, 60], [50, 210, 5, 105], [80, 330, 10, 165]]);
  M('events_huge', 'zap', 'run', 'eventsDone', [[3, 150, 5, 70], [4, 240, 8, 120], [5, 360, 12, 180]]);
  // semanais grandes
  M('endless_week', 'infinity', 'total', 'endlessRun', [[10, 200, 5, 100], [20, 350, 10, 180], [35, 550, 15, 280]], true);
  M('campaign_week', 'galaxy', 'total', 'campaignRun', [[10, 200, 5, 100], [20, 350, 10, 180], [35, 550, 15, 280]], true);
  M('perfects_week', 'target', 'total', 'perfects', [[150, 220, 5, 110], [300, 380, 10, 190], [500, 600, 15, 300]], true);
  M('coins_week', 'coins', 'total', 'coins', [[1500, 220, 5, 110], [3000, 380, 10, 190], [5000, 600, 15, 300]], true);
  M('rings_week', 'ring', 'total', 'score', [[800, 220, 5, 110], [1500, 380, 10, 190], [2500, 600, 15, 300]], true);
  M('stars_week', 'star', 'total', 'starsGot', [[15, 220, 5, 110], [30, 380, 10, 190], [50, 600, 15, 300]], true);
  M('three_week', 'starGlow', 'total', 'threeStar', [[5, 220, 5, 110], [10, 380, 10, 190], [20, 600, 15, 300]], true);
  M('boss_week', 'crown', 'total', 'bossDone', [[3, 260, 8, 130], [6, 420, 12, 210], [10, 650, 20, 320]], true);
  M('ability_week', 'powers', 'total', 'abilitiesUsed', [[30, 200, 5, 100], [60, 340, 10, 170], [100, 520, 15, 260]], true);
  // metas já pensadas para a semana: só na semanal e sem multiplicar
  ['aegis_week', 'endless_week', 'campaign_week', 'perfects_week', 'coins_week', 'rings_week', 'stars_week', 'three_week', 'boss_week', 'ability_week'].forEach(id => X(id, { weeklyOnly: true, noMul: true }));

  const A = (id, cat, stat, target, gems, icon, extra) => HR.ACHIEVEMENTS.push(Object.assign({ id, cat, stat, target, gems, icon }, extra || {}));
  // Galáxia
  A('systems_1', 'galaxy', 'systemsCleared', 1, 10, 'system');
  A('systems_10', 'galaxy', 'systemsCleared', 10, 40, 'system');
  A('systems_50', 'galaxy', 'systemsCleared', 50, 150, 'system');
  A('systems_100', 'galaxy', 'systemsCleared', 100, 500, 'system', { title: 't_system_lord' });
  A('regions_5', 'galaxy', 'regionsCleared', 5, 120, 'galaxy');
  A('regions_10', 'galaxy', 'regionsCleared', 10, 400, 'galaxy', { title: 't_voyager' });
  A('levels_250', 'galaxy', 'levelsCleared', 250, 80, 'flag');
  A('levels_500', 'galaxy', 'levelsCleared', 500, 200, 'flag');
  A('levels_1000', 'galaxy', 'levelsCleared', 1000, 800, 'map', { title: 't_cartographer' });
  A('stars_600', 'galaxy', 'starsTotal', 600, 100, 'star');
  A('stars_1500', 'galaxy', 'starsTotal', 1500, 300, 'starGlow');
  A('stars_3000', 'galaxy', 'starsTotal', 3000, 1000, 'crown', { title: 't_starlord' });
  // Singularidade
  A('archons_1', 'singularity', 'archonsPassed', 1, 100, 'light');
  A('archons_5', 'singularity', 'archonsPassed', 5, 300, 'light');
  A('archons_11', 'singularity', 'archonsPassed', 11, 1500, 'light', { title: 't_beyond' });
  A('understood_1', 'singularity', 'understood', 1, 80, 'pathLight');
  A('understood_5', 'singularity', 'understood', 5, 250, 'pathLight');
  A('understood_11', 'singularity', 'understood', 11, 1000, 'pathLight', { hidden: true });
  A('questioned_3', 'singularity', 'questioned', 3, 120, 'pathQuestion', { hidden: true });
  A('forced_3', 'singularity', 'forced', 3, 120, 'sword', { hidden: true });
  A('ecos_10', 'singularity', 'ecosFound', 10, 60, 'eco');
  A('ecos_30', 'singularity', 'ecosFound', 30, 150, 'eco');
  A('ecos_55', 'singularity', 'ecosFound', 55, 500, 'eco', { title: 't_listener' });
  A('words_5', 'singularity', 'wordsEarned', 5, 150, 'word');
  A('words_11', 'singularity', 'wordsEarned', 11, 800, 'word');
  A('dialogues_5', 'singularity', 'dialogues', 5, 60, 'dialogue');
  A('journey_10', 'singularity', 'journeyPct', 10, 80, 'percent');
  A('journey_50', 'singularity', 'journeyPct', 50, 400, 'percent');
  A('journey_100', 'singularity', 'journeyPct', 100, 2000, 'percent', { title: 't_complete' });
  // Poder e precisão
  A('aegis_10', 'power', 'aegisUsed', 10, 30, 'aegis');
  A('aegis_100', 'power', 'aegisUsed', 100, 150, 'aegis');
  A('aegis_save_10', 'power', 'aegisSaves', 10, 40, 'shieldHalf');
  A('aegis_save_50', 'power', 'aegisSaves', 50, 150, 'shieldHalf', { title: 't_untouchable' });
  A('jets_10', 'power', 'jetsUsed', 10, 40, 'jet');
  A('jets_50', 'power', 'jetsUsed', 50, 150, 'jet');
  A('megajets_10', 'power', 'megajetsUsed', 10, 80, 'megajet');
  A('abilities_all', 'power', 'abilitiesOwned', HR.ABILITIES.length, 300, 'powers', { title: 't_arsenal' });
  A('speed_250', 'precision', 'speedPct', 250, 60, 'speed');
  A('speed_320', 'precision', 'speedPct', 320, 150, 'speed');
  A('speed_400', 'precision', 'speedPct', 400, 400, 'speed', { title: 't_lightspeed' });
  // Coleção
  A('skins_40', 'collection', 'skinsOwned', 40, 150, 'ball');
  A('skins_80', 'collection', 'skinsOwned', 80, 400, 'ball');
  A('skins_all', 'collection', 'skinsOwned', HR.CONFIG.SKINS.length, 2000, 'ball', { title: 't_collector_supreme' });
  const colGems = { blackholes: 500, archons: 800, galaxies: 400, season: 200 };
  (HR.COLLECTIONS || []).filter(c => c.id !== 'classic' && c.id !== 'season').forEach(c => {
    const size = HR.CONFIG.SKINS.filter(s => s.col === c.id).length;
    A('col_' + c.id, 'collection', 'col_' + c.id, size, colGems[c.id] || 120, c.icon, c.id === 'blackholes' ? { title: 't_event_horizon' } : null);
  });
  A('collections_5', 'collection', 'collectionsDone', 5, 300, 'layers');
  A('themes_12', 'collection', 'themesOwned', 12, 150, 'palette');
  A('themes_all', 'collection', 'themesOwned', HR.CONFIG.THEMES.length, 500, 'palette');
  A('aegisskins_5', 'collection', 'aegisSkins', 5, 120, 'aegis');
  A('aegisskins_10', 'collection', 'aegisSkins', 10, 400, 'aegis');
  A('jetskins_5', 'collection', 'jetSkins', 5, 200, 'jet');
  A('ton618', 'collection', 'ownTon618', 1, 1000, 'blackhole', { hidden: true, title: 't_singular_owner' });

  HR.ACH_CATS.push('singularity');
  ['t_system_lord', 't_voyager', 't_cartographer', 't_starlord', 't_beyond', 't_listener', 't_complete', 't_untouchable', 't_arsenal', 't_lightspeed', 't_collector_supreme', 't_event_horizon', 't_singular_owner', 't_light_servant', 't_seeker', 't_conqueror'].forEach(t => { if (!HR.TITLES.includes(t)) HR.TITLES.push(t); });
})();

/* ---------------- textos ---------------- */
Object.assign(HR.I18N.pt, {
  ach_singularity: 'Singularidade', title_50: 'Guardião das Galáxias', title_60: 'Arauto da Luz', title_70: 'Eterno',
  m_aegis_use: 'Ative a Égide {n} vezes', m_aegis_save: 'A Égide te salva {n} vezes', m_aegis_run: 'A Égide te salva {n} vezes numa partida', m_jet_use: 'Use o Jato {n} vezes', m_aegis_week: 'A Égide te salva {n} vezes nesta semana',
  m_blackhole: 'Use o Buraco Negro {n} vezes', m_prism: 'Use o Prisma {n} vezes', m_phoenix: 'Use a Fênix {n} vezes', m_goldrush: 'Use a Febre do Ouro {n} vezes', m_micro: 'Use o Micro {n} vezes', m_comet: 'Use o Cometa {n} vezes', m_supernova: 'Use a Supernova {n} vezes', m_chrono: 'Use o Cronos {n} vezes',
  m_systems: 'Vença {n} chefes de sistema', m_galaxy_clear: 'Vença {n} chefes de galáxia', m_speed_run: 'Voe a {n} % da velocidade inicial', m_eco_find: 'Encontre {n} Ecos na Singularidade', m_sg_passage: 'Conclua {n} fases de passagem', m_sg_trial: 'Vença {n} Provas de Arconte',
  m_perfects_huge: 'Faça {n} PERFEITOS numa partida', m_combo_huge: 'Faça um combo de {n}', m_coins_huge: 'Ganhe {n} moedas numa partida', m_near_huge: 'Passe {n} vezes por um fio numa partida', m_items_huge: 'Pegue {n} itens numa partida', m_center_run: 'Pegue {n} itens no centro dos arcos numa partida', m_flow_run: 'Fique {n} s no fluxo máximo numa partida', m_obstacles_run: 'Destrua {n} obstáculos numa partida', m_shattered_run: 'Despedace {n} arcos numa partida', m_gold_run: 'Passe por {n} anéis dourados numa partida', m_double_run: 'Passe por {n} arcos duplos numa partida', m_dir_huge: 'Enfrente {n} trocas de direção numa partida', m_time_huge: 'Sobreviva {n} s numa partida', m_score_huge: 'Faça {n} pontos numa partida', m_perks_huge: 'Junte {n} perks numa partida', m_anomaly_run: 'Vença {n} anomalias numa partida', m_guardian_run: 'Vença {n} Guardiões numa partida', m_sentinel_run: 'Sobreviva a {n} Sentinelas numa partida', m_warp_run: 'Atravesse {n} Dobras numa partida', m_asteroid_run: 'Destrua {n} asteroides numa partida', m_clean_huge: 'Passe {n} arcos seguidos sem dano', m_events_huge: 'Vença {n} eventos numa partida',
  m_endless_week: 'Jogue {n} partidas no Infinito', m_campaign_week: 'Jogue {n} fases da Galáxia', m_perfects_week: 'Faça {n} PERFEITOS', m_coins_week: 'Ganhe {n} moedas', m_rings_week: 'Passe por {n} arcos', m_stars_week: 'Ganhe {n} estrelas novas', m_three_week: 'Faça 3 estrelas em {n} fases', m_boss_week: 'Vença {n} chefes', m_ability_week: 'Use habilidades {n} vezes',
  a_systems_1: 'Primeiro sistema', a_systems_10: 'Dez sóis', a_systems_50: 'Meio universo', a_systems_100: 'Senhor dos Sistemas', a_regions_5: 'Cinco galáxias', a_regions_10: 'Até Andrômeda', a_levels_250: 'Viajante', a_levels_500: 'Desbravador', a_levels_1000: 'Mil fases', a_stars_600: 'Constelação', a_stars_1500: 'Via Láctea', a_stars_3000: 'Todas as estrelas',
  a_archons_1: 'O primeiro guardião', a_archons_5: 'Metade do caminho', a_archons_11: 'Além do horizonte', a_understood_1: 'Entendeu', a_understood_5: 'Olhos abertos', a_understood_11: 'Luz inteira', a_questioned_3: 'Buscador', a_forced_3: 'Punho fechado', a_ecos_10: 'Ouvinte', a_ecos_30: 'Guardador de ecos', a_ecos_55: 'Todas as vozes', a_words_5: 'Cinco palavras', a_words_11: 'O caminho de volta', a_dialogues_5: 'Boa conversa', a_journey_10: '10 % da jornada', a_journey_50: 'Metade da jornada', a_journey_100: 'Jornada completa',
  a_aegis_10: 'Protegido', a_aegis_100: 'Sempre protegido', a_aegis_save_10: 'Salvo pela Égide', a_aegis_save_50: 'Intocável', a_jets_10: 'Decolagem', a_jets_50: 'Piloto de jato', a_megajets_10: 'Mega decolagem', a_abilities_all: 'Arsenal completo', a_speed_250: 'Rápido', a_speed_320: 'Supersônico', a_speed_400: 'Velocidade da luz',
  a_skins_40: 'Colecionador', a_skins_80: 'Grande coleção', a_skins_all: 'Todas as bolas', a_col_planets: 'Sistema Solar completo', a_col_stars: 'Céu estrelado', a_col_nebulae: 'Berçário completo', a_col_blackholes: 'Horizonte de eventos', a_col_gems: 'Tesouro', a_col_sports: 'Atleta', a_col_creatures: 'Zoológico cósmico', a_col_elements: 'Mestre dos elementos', a_col_tech: 'Laboratório', a_col_arts: 'Galeria', a_col_sweets: 'Confeitaria', a_col_galaxies: 'Mapa das galáxias', a_col_archons: 'Os onze', a_collections_5: 'Cinco coleções', a_themes_12: 'Paisagens', a_themes_all: 'Todos os mundos', a_aegisskins_5: 'Guarda-roupa da Égide', a_aegisskins_10: 'Todas as Égides', a_jetskins_5: 'Todas as chamas', a_ton618: 'Dono de TON 618',
  a_d_systemsCleared: 'Vença {n} chefes de sistema', a_d_archonsPassed: 'Atravesse {n} camadas da Singularidade', a_d_understood: 'Atravesse {n} camadas pelo entendimento', a_d_questioned: 'Atravesse {n} camadas perguntando', a_d_forced: 'Atravesse {n} camadas pela força', a_d_ecosFound: 'Encontre {n} Ecos', a_d_wordsEarned: 'Receba {n} Palavras', a_d_dialogues: 'Converse {n} vezes com os Arcontes', a_d_journeyPct: 'Complete {n} % da jornada', a_d_aegisUsed: 'Ative a Égide {n} vezes', a_d_aegisSaves: 'Seja salvo pela Égide {n} vezes', a_d_jetsUsed: 'Use o Jato {n} vezes', a_d_megajetsUsed: 'Use o Mega Jato {n} vezes', a_d_abilitiesOwned: 'Tenha {n} habilidades', a_d_speedPct: 'Voe a {n} % da velocidade inicial', a_d_collectionsDone: 'Complete {n} coleções de bolas', a_d_aegisSkins: 'Tenha {n} visuais de Égide', a_d_jetSkins: 'Tenha {n} chamas de Jato', a_d_ownTon618: 'Tenha a bola TON 618',
  a_d_col_planets: 'Tenha as {n} bolas do Sistema Solar', a_d_col_stars: 'Tenha as {n} Estrelas', a_d_col_nebulae: 'Tenha as {n} Nebulosas', a_d_col_blackholes: 'Tenha os {n} Buracos Negros', a_d_col_gems: 'Tenha as {n} Gemas', a_d_col_sports: 'Tenha as {n} bolas de Esportes', a_d_col_creatures: 'Tenha as {n} Criaturas', a_d_col_elements: 'Tenha os {n} Elementos', a_d_col_tech: 'Tenha as {n} bolas de Tecnologia', a_d_col_arts: 'Tenha as {n} Artes', a_d_col_sweets: 'Tenha os {n} Doces', a_d_col_galaxies: 'Tenha as {n} Galáxias', a_d_col_archons: 'Tenha as {n} bolas dos Arcontes',
  t_system_lord: 'Senhor dos Sistemas', t_voyager: 'Viajante das Galáxias', t_cartographer: 'Cartógrafo', t_starlord: 'Dono das Estrelas', t_beyond: 'Além do Horizonte', t_listener: 'O que Ouve', t_complete: 'Jornada Completa', t_untouchable: 'Intocável', t_arsenal: 'Arsenal', t_lightspeed: 'Velocidade da Luz', t_collector_supreme: 'Colecionador Supremo', t_event_horizon: 'Horizonte de Eventos', t_singular_owner: 'Singular'
});
Object.assign(HR.I18N.en, {
  ach_singularity: 'Singularity', title_50: 'Guardian of Galaxies', title_60: 'Herald of Light', title_70: 'Eternal',
  m_aegis_use: 'Activate the Aegis {n} times', m_aegis_save: 'The Aegis saves you {n} times', m_aegis_run: 'The Aegis saves you {n} times in one run', m_jet_use: 'Use the Jet {n} times', m_aegis_week: 'The Aegis saves you {n} times this week',
  m_blackhole: 'Use Black Hole {n} times', m_prism: 'Use Prism {n} times', m_phoenix: 'Use Phoenix {n} times', m_goldrush: 'Use Gold Rush {n} times', m_micro: 'Use Micro {n} times', m_comet: 'Use Comet {n} times', m_supernova: 'Use Supernova {n} times', m_chrono: 'Use Chronos {n} times',
  m_systems: 'Beat {n} system bosses', m_galaxy_clear: 'Beat {n} galaxy bosses', m_speed_run: 'Fly at {n}% of the starting speed', m_eco_find: 'Find {n} Echoes in the Singularity', m_sg_passage: 'Clear {n} passage levels', m_sg_trial: 'Win {n} Archon Trials',
  m_perfects_huge: 'Make {n} PERFECTS in one run', m_combo_huge: 'Reach a {n} combo', m_coins_huge: 'Earn {n} coins in one run', m_near_huge: 'Pass by a hair {n} times in one run', m_items_huge: 'Grab {n} items in one run', m_center_run: 'Grab {n} ring-center items in one run', m_flow_run: 'Stay {n} s at max flow in one run', m_obstacles_run: 'Destroy {n} obstacles in one run', m_shattered_run: 'Shatter {n} rings in one run', m_gold_run: 'Pass {n} golden rings in one run', m_double_run: 'Pass {n} double rings in one run', m_dir_huge: 'Face {n} direction changes in one run', m_time_huge: 'Survive {n} s in one run', m_score_huge: 'Score {n} in one run', m_perks_huge: 'Collect {n} perks in one run', m_anomaly_run: 'Beat {n} anomalies in one run', m_guardian_run: 'Beat {n} Guardians in one run', m_sentinel_run: 'Survive {n} Sentinels in one run', m_warp_run: 'Cross {n} Warps in one run', m_asteroid_run: 'Destroy {n} asteroids in one run', m_clean_huge: 'Pass {n} rings in a row without damage', m_events_huge: 'Win {n} events in one run',
  m_endless_week: 'Play {n} Endless runs', m_campaign_week: 'Play {n} Galaxy levels', m_perfects_week: 'Make {n} PERFECTS', m_coins_week: 'Earn {n} coins', m_rings_week: 'Pass {n} rings', m_stars_week: 'Earn {n} new stars', m_three_week: 'Get 3 stars on {n} levels', m_boss_week: 'Beat {n} bosses', m_ability_week: 'Use abilities {n} times',
  a_systems_1: 'First system', a_systems_10: 'Ten suns', a_systems_50: 'Half a universe', a_systems_100: 'Lord of Systems', a_regions_5: 'Five galaxies', a_regions_10: 'All the way to Andromeda', a_levels_250: 'Traveler', a_levels_500: 'Pathfinder', a_levels_1000: 'A thousand levels', a_stars_600: 'Constellation', a_stars_1500: 'Milky Way', a_stars_3000: 'Every star',
  a_archons_1: 'The first guardian', a_archons_5: 'Halfway there', a_archons_11: 'Beyond the horizon', a_understood_1: 'Understood', a_understood_5: 'Open eyes', a_understood_11: 'Whole light', a_questioned_3: 'Seeker', a_forced_3: 'Closed fist', a_ecos_10: 'Listener', a_ecos_30: 'Keeper of echoes', a_ecos_55: 'Every voice', a_words_5: 'Five words', a_words_11: 'The way back', a_dialogues_5: 'Good talk', a_journey_10: '10% of the journey', a_journey_50: 'Half the journey', a_journey_100: 'Journey complete',
  a_aegis_10: 'Protected', a_aegis_100: 'Always protected', a_aegis_save_10: 'Saved by the Aegis', a_aegis_save_50: 'Untouchable', a_jets_10: 'Liftoff', a_jets_50: 'Jet pilot', a_megajets_10: 'Mega liftoff', a_abilities_all: 'Full arsenal', a_speed_250: 'Fast', a_speed_320: 'Supersonic', a_speed_400: 'Lightspeed',
  a_skins_40: 'Collector', a_skins_80: 'Big collection', a_skins_all: 'Every ball', a_col_planets: 'Solar System complete', a_col_stars: 'Starry sky', a_col_nebulae: 'Full nursery', a_col_blackholes: 'Event horizon', a_col_gems: 'Treasure', a_col_sports: 'Athlete', a_col_creatures: 'Cosmic zoo', a_col_elements: 'Master of elements', a_col_tech: 'Laboratory', a_col_arts: 'Gallery', a_col_sweets: 'Candy shop', a_col_galaxies: 'Galaxy map', a_col_archons: 'The eleven', a_collections_5: 'Five collections', a_themes_12: 'Landscapes', a_themes_all: 'Every world', a_aegisskins_5: 'Aegis wardrobe', a_aegisskins_10: 'Every Aegis', a_jetskins_5: 'Every flame', a_ton618: 'Owner of TON 618',
  a_d_systemsCleared: 'Beat {n} system bosses', a_d_archonsPassed: 'Cross {n} Singularity layers', a_d_understood: 'Cross {n} layers through understanding', a_d_questioned: 'Cross {n} layers by questioning', a_d_forced: 'Cross {n} layers by force', a_d_ecosFound: 'Find {n} Echoes', a_d_wordsEarned: 'Receive {n} Words', a_d_dialogues: 'Talk to the Archons {n} times', a_d_journeyPct: 'Complete {n}% of the journey', a_d_aegisUsed: 'Activate the Aegis {n} times', a_d_aegisSaves: 'Be saved by the Aegis {n} times', a_d_jetsUsed: 'Use the Jet {n} times', a_d_megajetsUsed: 'Use the Mega Jet {n} times', a_d_abilitiesOwned: 'Own {n} abilities', a_d_speedPct: 'Fly at {n}% of the starting speed', a_d_collectionsDone: 'Complete {n} ball collections', a_d_aegisSkins: 'Own {n} Aegis looks', a_d_jetSkins: 'Own {n} Jet flames', a_d_ownTon618: 'Own the TON 618 ball',
  a_d_col_planets: 'Own all {n} Solar System balls', a_d_col_stars: 'Own all {n} Stars', a_d_col_nebulae: 'Own all {n} Nebulae', a_d_col_blackholes: 'Own all {n} Black Holes', a_d_col_gems: 'Own all {n} Gems', a_d_col_sports: 'Own all {n} Sports balls', a_d_col_creatures: 'Own all {n} Creatures', a_d_col_elements: 'Own all {n} Elements', a_d_col_tech: 'Own all {n} Tech balls', a_d_col_arts: 'Own all {n} Arts', a_d_col_sweets: 'Own all {n} Sweets', a_d_col_galaxies: 'Own all {n} Galaxies', a_d_col_archons: 'Own all {n} Archon balls',
  t_system_lord: 'Lord of Systems', t_voyager: 'Galaxy Voyager', t_cartographer: 'Cartographer', t_starlord: 'Keeper of Stars', t_beyond: 'Beyond the Horizon', t_listener: 'The One Who Listens', t_complete: 'Journey Complete', t_untouchable: 'Untouchable', t_arsenal: 'Arsenal', t_lightspeed: 'Lightspeed', t_collector_supreme: 'Supreme Collector', t_event_horizon: 'Event Horizon', t_singular_owner: 'Singular',
  flavor_skin_mercury: 'Closest to the Sun, full of craters.', flavor_skin_venus: 'Golden clouds that never stop.', flavor_skin_earth: 'Oceans, continents and clouds: our home.', flavor_skin_mars: 'Red dust and ice caps.', flavor_skin_jupiter: 'Giant bands and the Great Red Spot.', flavor_skin_uranus: 'Spins on its side with a faint ring.', flavor_skin_neptune: 'Deep blue and supersonic winds.', flavor_skin_pluto: 'Small, distant, with a heart of ice.', flavor_skin_io: 'Volcanoes everywhere.', flavor_skin_europa: 'Cracked ice over a hidden ocean.', flavor_skin_titan: 'Orange haze and methane lakes.', flavor_skin_ganymede: 'The largest moon in the Solar System.', flavor_skin_ceres: 'A dwarf planet with bright spots.',
  flavor_skin_reddwarf: 'Small, cool and patient.', flavor_skin_whitedwarf: 'The glow a star leaves behind.', flavor_skin_bluegiant: 'Hot, young and dazzling.', flavor_skin_betelgeuse: 'A pulsing supergiant on Orion’s shoulder.', flavor_skin_pulsar: 'A spinning cosmic lighthouse.', flavor_skin_magnetar: 'The strongest magnetic field in the universe.', flavor_skin_neutron: 'A spoonful would weigh a mountain.', flavor_skin_nova: 'It bursts again and again.', flavor_skin_binary: 'Two stars dancing together.', flavor_skin_sirius: 'The brightest star in the night sky.',
  flavor_skin_orion: 'The most famous star nursery.', flavor_skin_crab: 'What remains of the supernova of 1054.', flavor_skin_helix: 'A giant eye in the sky.', flavor_skin_carina: 'Golden clouds of gas and dust.', flavor_skin_pillars: 'Columns of gas where stars are born.', flavor_skin_horsehead: 'A dark silhouette against red.', flavor_skin_ringneb: 'A ring of cosmic smoke.', flavor_skin_catseye: 'Layers upon layers of light.', flavor_skin_butterfly: 'Wings of gas open in space.', flavor_skin_eagle: 'An eagle of dust and light.',
  flavor_skin_cygnus: 'It steals gas from a blue neighbor star.', flavor_skin_sgra: 'The dark heart of the Milky Way.', flavor_skin_m87: 'The first black hole ever photographed.', flavor_skin_ton618: 'Sixty-six billion suns. The largest we know.',
  flavor_skin_ruby: 'Cut red fire.', flavor_skin_sapphire: 'Deep sky blue.', flavor_skin_emerald: 'Green that glows from within.', flavor_skin_amethyst: 'Calm crystal violet.', flavor_skin_topaz: 'Transparent gold.', flavor_skin_diamond: 'Light trapped in every facet.', flavor_skin_obsidian: 'Volcanic glass with a purple sheen.', flavor_skin_opal: 'Every color in a single stone.',
  flavor_skin_basketball: 'Up, spin and swish.', flavor_skin_tennis: 'Fuzzy and fast.', flavor_skin_volleyball: 'Three colors in the air.', flavor_skin_baseball: 'Red stitches and a long hit.', flavor_skin_bowling: 'Heavy and glossy.', flavor_skin_golf: 'Small dimples, long distance.',
  flavor_skin_smile: 'Impossible not to smile along.', flavor_skin_cat: 'Curious about every ring.', flavor_skin_panda: 'Calm, round and fluffy.', flavor_skin_alien: 'Came from very far away to play.', flavor_skin_robot: 'LED eyes always watching.', flavor_skin_slime: 'Wobbles, drips and never quits.', flavor_skin_owl: 'Sees everything in the dark.', flavor_skin_frog: 'Hops from ring to ring.',
  flavor_skin_fire: 'Flames rising non-stop.', flavor_skin_water: 'Waves and bubbles inside the ball.', flavor_skin_storm: 'Lightning trapped in a sphere.', flavor_skin_rock: 'Steady as a mountain.', flavor_skin_wind: 'Light whirlwinds.', flavor_skin_light: 'Radiates in every direction.', flavor_skin_shadow: 'Tendrils of violet darkness.',
  flavor_skin_chip: 'Data pulses running along the traces.', flavor_skin_hologram: 'A flickering projection.', flavor_skin_glitch: 'A system error with style.', flavor_skin_vinyl: 'The sound spinning.', flavor_skin_radar: 'Continuous sweep.', flavor_skin_pixel: 'Straight out of an 8-bit game.', flavor_skin_ufo: 'Tractor beam included.', flavor_skin_disco: 'Space is the dance floor.',
  flavor_skin_mandala: 'Petals in harmony.', flavor_skin_stainedglass: 'Light passing through colors.', flavor_skin_compass: 'Always knows north.', flavor_skin_clock: 'Time runs while you fly.', flavor_skin_origami: 'Precisely folded paper.', flavor_skin_maze: 'A spinning labyrinth.',
  flavor_skin_donut: 'Pink frosting and sprinkles.', flavor_skin_orange: 'Juice of energy.', flavor_skin_watermelon: 'Refreshing in summer.', flavor_skin_marble: 'Glass with colored ribbons.', flavor_skin_cookie: 'Chocolate chips.', flavor_skin_candy: 'A peppermint swirl.',
  flavor_skin_ornament: 'Straight from the Christmas tree.', flavor_skin_snowglobe: 'Snow falling forever.', flavor_skin_sugarskull: 'Colorful and festive.', flavor_skin_mask: 'Carnival feathers and shine.', flavor_skin_lantern: 'Festival colors.',
  flavor_skin_gal_magellan: 'The neighbor cloud, irregular and alive.', flavor_skin_gal_whirlpool: 'Whirling arms and a companion.', flavor_skin_gal_sunflower: 'Fluffy arms like petals.', flavor_skin_gal_cigar: 'Red plumes bursting from the core.', flavor_skin_gal_sombrero: 'A brim of dark dust.', flavor_skin_gal_pinwheel: 'Many spinning arms.', flavor_skin_gal_antennae: 'Two galaxies colliding.', flavor_skin_gal_blackeye: 'A dark band over the core.', flavor_skin_gal_cartwheel: 'A ring of newborn stars.', flavor_skin_gal_andromeda: 'The big tilted neighbor.',
  flavor_skin_arc_1: 'Whoever sees themselves as they are, sees others better.', flavor_skin_arc_2: 'Everything that blooms started small.', flavor_skin_arc_3: 'Light is the one who lets go of what is owed.', flavor_skin_arc_4: 'The road gets shorter when you stop for someone.', flavor_skin_arc_5: 'Truth does not need to shout.', flavor_skin_arc_6: 'The right light arrives at the right time.', flavor_skin_arc_7: 'Shining is so others can come back.', flavor_skin_arc_8: 'The greatest is the one who serves.', flavor_skin_arc_9: 'Whoever drops the weight, flies.', flavor_skin_arc_10: 'Some steps are only taken in trust.', flavor_skin_arc_11: 'We return to the light we came from.'
});
Object.assign(HR.I18N.es, {
  ach_singularity: 'Singularidad', title_50: 'Guardián de las Galaxias', title_60: 'Heraldo de la Luz', title_70: 'Eterno',
  m_aegis_use: 'Activa la Égida {n} veces', m_aegis_save: 'La Égida te salva {n} veces', m_aegis_run: 'La Égida te salva {n} veces en una partida', m_jet_use: 'Usa el Propulsor {n} veces', m_aegis_week: 'La Égida te salva {n} veces esta semana',
  m_blackhole: 'Usa Agujero Negro {n} veces', m_prism: 'Usa Prisma {n} veces', m_phoenix: 'Usa Fénix {n} veces', m_goldrush: 'Usa Fiebre del Oro {n} veces', m_micro: 'Usa Micro {n} veces', m_comet: 'Usa Cometa {n} veces', m_supernova: 'Usa Supernova {n} veces', m_chrono: 'Usa Cronos {n} veces',
  m_systems: 'Vence a {n} jefes de sistema', m_galaxy_clear: 'Vence a {n} jefes de galaxia', m_speed_run: 'Vuela al {n} % de la velocidad inicial', m_eco_find: 'Encuentra {n} Ecos en la Singularidad', m_sg_passage: 'Completa {n} niveles de pasaje', m_sg_trial: 'Gana {n} Pruebas de Arconte',
  m_perfects_huge: 'Haz {n} PERFECTOS en una partida', m_combo_huge: 'Haz un combo de {n}', m_coins_huge: 'Gana {n} monedas en una partida', m_near_huge: 'Pasa {n} veces por un pelo en una partida', m_items_huge: 'Recoge {n} objetos en una partida', m_center_run: 'Recoge {n} objetos del centro de los aros en una partida', m_flow_run: 'Quédate {n} s en flujo máximo en una partida', m_obstacles_run: 'Destruye {n} obstáculos en una partida', m_shattered_run: 'Rompe {n} aros en una partida', m_gold_run: 'Pasa {n} aros dorados en una partida', m_double_run: 'Pasa {n} aros dobles en una partida', m_dir_huge: 'Enfrenta {n} cambios de dirección en una partida', m_time_huge: 'Sobrevive {n} s en una partida', m_score_huge: 'Haz {n} puntos en una partida', m_perks_huge: 'Junta {n} perks en una partida', m_anomaly_run: 'Vence {n} anomalías en una partida', m_guardian_run: 'Vence {n} Guardianes en una partida', m_sentinel_run: 'Sobrevive a {n} Centinelas en una partida', m_warp_run: 'Cruza {n} Saltos en una partida', m_asteroid_run: 'Destruye {n} asteroides en una partida', m_clean_huge: 'Pasa {n} aros seguidos sin daño', m_events_huge: 'Gana {n} eventos en una partida',
  m_endless_week: 'Juega {n} partidas en Infinito', m_campaign_week: 'Juega {n} niveles de la Galaxia', m_perfects_week: 'Haz {n} PERFECTOS', m_coins_week: 'Gana {n} monedas', m_rings_week: 'Pasa {n} aros', m_stars_week: 'Gana {n} estrellas nuevas', m_three_week: 'Consigue 3 estrellas en {n} niveles', m_boss_week: 'Vence a {n} jefes', m_ability_week: 'Usa habilidades {n} veces',
  a_systems_1: 'Primer sistema', a_systems_10: 'Diez soles', a_systems_50: 'Medio universo', a_systems_100: 'Señor de los Sistemas', a_regions_5: 'Cinco galaxias', a_regions_10: 'Hasta Andrómeda', a_levels_250: 'Viajero', a_levels_500: 'Explorador', a_levels_1000: 'Mil niveles', a_stars_600: 'Constelación', a_stars_1500: 'Vía Láctea', a_stars_3000: 'Todas las estrellas',
  a_archons_1: 'El primer guardián', a_archons_5: 'Mitad del camino', a_archons_11: 'Más allá del horizonte', a_understood_1: 'Entendió', a_understood_5: 'Ojos abiertos', a_understood_11: 'Luz entera', a_questioned_3: 'Buscador', a_forced_3: 'Puño cerrado', a_ecos_10: 'Oyente', a_ecos_30: 'Guardián de ecos', a_ecos_55: 'Todas las voces', a_words_5: 'Cinco palabras', a_words_11: 'El camino de vuelta', a_dialogues_5: 'Buena charla', a_journey_10: '10 % del viaje', a_journey_50: 'Mitad del viaje', a_journey_100: 'Viaje completo',
  a_aegis_10: 'Protegido', a_aegis_100: 'Siempre protegido', a_aegis_save_10: 'Salvado por la Égida', a_aegis_save_50: 'Intocable', a_jets_10: 'Despegue', a_jets_50: 'Piloto de propulsor', a_megajets_10: 'Mega despegue', a_abilities_all: 'Arsenal completo', a_speed_250: 'Rápido', a_speed_320: 'Supersónico', a_speed_400: 'Velocidad de la luz',
  a_skins_40: 'Coleccionista', a_skins_80: 'Gran colección', a_skins_all: 'Todas las bolas', a_col_planets: 'Sistema Solar completo', a_col_stars: 'Cielo estrellado', a_col_nebulae: 'Vivero completo', a_col_blackholes: 'Horizonte de sucesos', a_col_gems: 'Tesoro', a_col_sports: 'Atleta', a_col_creatures: 'Zoológico cósmico', a_col_elements: 'Maestro de los elementos', a_col_tech: 'Laboratorio', a_col_arts: 'Galería', a_col_sweets: 'Confitería', a_col_galaxies: 'Mapa de galaxias', a_col_archons: 'Los once', a_collections_5: 'Cinco colecciones', a_themes_12: 'Paisajes', a_themes_all: 'Todos los mundos', a_aegisskins_5: 'Armario de la Égida', a_aegisskins_10: 'Todas las Égidas', a_jetskins_5: 'Todas las llamas', a_ton618: 'Dueño de TON 618',
  a_d_systemsCleared: 'Vence a {n} jefes de sistema', a_d_archonsPassed: 'Cruza {n} capas de la Singularidad', a_d_understood: 'Cruza {n} capas por el entendimiento', a_d_questioned: 'Cruza {n} capas preguntando', a_d_forced: 'Cruza {n} capas por la fuerza', a_d_ecosFound: 'Encuentra {n} Ecos', a_d_wordsEarned: 'Recibe {n} Palabras', a_d_dialogues: 'Habla {n} veces con los Arcontes', a_d_journeyPct: 'Completa el {n} % del viaje', a_d_aegisUsed: 'Activa la Égida {n} veces', a_d_aegisSaves: 'Sé salvado por la Égida {n} veces', a_d_jetsUsed: 'Usa el Propulsor {n} veces', a_d_megajetsUsed: 'Usa el Mega Propulsor {n} veces', a_d_abilitiesOwned: 'Ten {n} habilidades', a_d_speedPct: 'Vuela al {n} % de la velocidad inicial', a_d_collectionsDone: 'Completa {n} colecciones de bolas', a_d_aegisSkins: 'Ten {n} estilos de Égida', a_d_jetSkins: 'Ten {n} llamas de Propulsor', a_d_ownTon618: 'Ten la bola TON 618',
  a_d_col_planets: 'Ten las {n} bolas del Sistema Solar', a_d_col_stars: 'Ten las {n} Estrellas', a_d_col_nebulae: 'Ten las {n} Nebulosas', a_d_col_blackholes: 'Ten los {n} Agujeros Negros', a_d_col_gems: 'Ten las {n} Gemas', a_d_col_sports: 'Ten las {n} bolas de Deportes', a_d_col_creatures: 'Ten las {n} Criaturas', a_d_col_elements: 'Ten los {n} Elementos', a_d_col_tech: 'Ten las {n} bolas de Tecnología', a_d_col_arts: 'Ten las {n} Artes', a_d_col_sweets: 'Ten los {n} Dulces', a_d_col_galaxies: 'Ten las {n} Galaxias', a_d_col_archons: 'Ten las {n} bolas de los Arcontes',
  t_system_lord: 'Señor de los Sistemas', t_voyager: 'Viajero de Galaxias', t_cartographer: 'Cartógrafo', t_starlord: 'Dueño de las Estrellas', t_beyond: 'Más allá del Horizonte', t_listener: 'El que Escucha', t_complete: 'Viaje Completo', t_untouchable: 'Intocable', t_arsenal: 'Arsenal', t_lightspeed: 'Velocidad de la Luz', t_collector_supreme: 'Coleccionista Supremo', t_event_horizon: 'Horizonte de Sucesos', t_singular_owner: 'Singular',
  flavor_skin_mercury: 'El más cercano al Sol, lleno de cráteres.', flavor_skin_venus: 'Nubes doradas que nunca paran.', flavor_skin_earth: 'Océanos, continentes y nubes: nuestro hogar.', flavor_skin_mars: 'Polvo rojo y casquetes de hielo.', flavor_skin_jupiter: 'Bandas gigantes y la Gran Mancha Roja.', flavor_skin_uranus: 'Gira de lado, con un anillo discreto.', flavor_skin_neptune: 'Azul profundo y vientos supersónicos.', flavor_skin_pluto: 'Pequeño, lejano y con un corazón de hielo.', flavor_skin_io: 'Volcanes por todas partes.', flavor_skin_europa: 'Hielo agrietado sobre un océano escondido.', flavor_skin_titan: 'Neblina naranja y lagos de metano.', flavor_skin_ganymede: 'La luna más grande del Sistema Solar.', flavor_skin_ceres: 'Un planeta enano con puntos brillantes.',
  flavor_skin_reddwarf: 'Pequeña, fría y paciente.', flavor_skin_whitedwarf: 'El brillo que deja una estrella.', flavor_skin_bluegiant: 'Caliente, joven y deslumbrante.', flavor_skin_betelgeuse: 'Una supergigante que late en el hombro de Orión.', flavor_skin_pulsar: 'Un faro cósmico girando.', flavor_skin_magnetar: 'El campo magnético más fuerte del universo.', flavor_skin_neutron: 'Una cucharada pesaría una montaña.', flavor_skin_nova: 'Estalla una y otra vez.', flavor_skin_binary: 'Dos estrellas bailando juntas.', flavor_skin_sirius: 'La estrella más brillante del cielo nocturno.',
  flavor_skin_orion: 'El vivero de estrellas más famoso.', flavor_skin_crab: 'Lo que quedó de la supernova de 1054.', flavor_skin_helix: 'Un ojo gigante en el cielo.', flavor_skin_carina: 'Nubes doradas de gas y polvo.', flavor_skin_pillars: 'Columnas de gas donde nacen estrellas.', flavor_skin_horsehead: 'Una silueta oscura contra el rojo.', flavor_skin_ringneb: 'Un anillo de humo cósmico.', flavor_skin_catseye: 'Capas y capas de luz.', flavor_skin_butterfly: 'Alas de gas abiertas en el espacio.', flavor_skin_eagle: 'El águila de polvo y luz.',
  flavor_skin_cygnus: 'Roba gas a una estrella azul vecina.', flavor_skin_sgra: 'El corazón oscuro de la Vía Láctea.', flavor_skin_m87: 'El primer agujero negro fotografiado.', flavor_skin_ton618: 'Sesenta y seis mil millones de soles. El mayor que conocemos.',
  flavor_skin_ruby: 'Fuego rojo tallado.', flavor_skin_sapphire: 'Azul de cielo profundo.', flavor_skin_emerald: 'Verde que brilla por dentro.', flavor_skin_amethyst: 'Violeta tranquilo y cristalino.', flavor_skin_topaz: 'Oro transparente.', flavor_skin_diamond: 'Luz atrapada en cada faceta.', flavor_skin_obsidian: 'Vidrio volcánico con brillo morado.', flavor_skin_opal: 'Todos los colores en una sola piedra.',
  flavor_skin_basketball: 'Sube, gira y entra.', flavor_skin_tennis: 'Peluda y veloz.', flavor_skin_volleyball: 'Tres colores en el aire.', flavor_skin_baseball: 'Costura roja y batazo largo.', flavor_skin_bowling: 'Pesada y brillante.', flavor_skin_golf: 'Pequeños hoyuelos, gran distancia.',
  flavor_skin_smile: 'Imposible no sonreír.', flavor_skin_cat: 'Curioso con cada aro.', flavor_skin_panda: 'Tranquilo, redondo y suave.', flavor_skin_alien: 'Vino de muy lejos a jugar.', flavor_skin_robot: 'Ojos LED siempre atentos.', flavor_skin_slime: 'Se tambalea, gotea y no se rinde.', flavor_skin_owl: 'Lo ve todo en la oscuridad.', flavor_skin_frog: 'Salta de aro en aro.',
  flavor_skin_fire: 'Llamas que suben sin parar.', flavor_skin_water: 'Olas y burbujas dentro de la bola.', flavor_skin_storm: 'Rayos atrapados en una esfera.', flavor_skin_rock: 'Firme como una montaña.', flavor_skin_wind: 'Remolinos ligeros.', flavor_skin_light: 'Irradia hacia todos lados.', flavor_skin_shadow: 'Tentáculos de oscuridad violeta.',
  flavor_skin_chip: 'Pulsos de datos corriendo por las pistas.', flavor_skin_hologram: 'Una proyección que parpadea.', flavor_skin_glitch: 'Un error de sistema con estilo.', flavor_skin_vinyl: 'El sonido girando.', flavor_skin_radar: 'Barrido continuo.', flavor_skin_pixel: 'Directo de un juego de 8 bits.', flavor_skin_ufo: 'Con rayo tractor incluido.', flavor_skin_disco: 'La pista es el espacio.',
  flavor_skin_mandala: 'Pétalos en armonía.', flavor_skin_stainedglass: 'La luz atravesando colores.', flavor_skin_compass: 'Siempre sabe dónde está el norte.', flavor_skin_clock: 'El tiempo corre mientras vuelas.', flavor_skin_origami: 'Papel doblado con precisión.', flavor_skin_maze: 'Un laberinto que gira.',
  flavor_skin_donut: 'Glaseado rosa y chispas.', flavor_skin_orange: 'Jugo de energía.', flavor_skin_watermelon: 'Refrescante en verano.', flavor_skin_marble: 'Vidrio con cintas de colores.', flavor_skin_cookie: 'Chispas de chocolate.', flavor_skin_candy: 'Un remolino de menta.',
  flavor_skin_ornament: 'Directo del árbol de Navidad.', flavor_skin_snowglobe: 'Nieve cayendo sin parar.', flavor_skin_sugarskull: 'Colorida y festiva.', flavor_skin_mask: 'Plumas y brillo de Carnaval.', flavor_skin_lantern: 'Colores de fiesta.',
  flavor_skin_gal_magellan: 'La nube vecina, irregular y viva.', flavor_skin_gal_whirlpool: 'Brazos en remolino y una compañera.', flavor_skin_gal_sunflower: 'Brazos esponjosos como pétalos.', flavor_skin_gal_cigar: 'Plumas rojas saliendo del centro.', flavor_skin_gal_sombrero: 'Un ala de polvo oscuro.', flavor_skin_gal_pinwheel: 'Muchos brazos girando.', flavor_skin_gal_antennae: 'Dos galaxias chocando.', flavor_skin_gal_blackeye: 'Una franja oscura sobre el núcleo.', flavor_skin_gal_cartwheel: 'Un anillo de estrellas nuevas.', flavor_skin_gal_andromeda: 'La gran vecina, inclinada.',
  flavor_skin_arc_1: 'Quien se ve como es, ve mejor a los demás.', flavor_skin_arc_2: 'Todo lo que florece empezó pequeño.', flavor_skin_arc_3: 'Ligero es quien suelta lo que le deben.', flavor_skin_arc_4: 'El camino se acorta cuando te detienes por alguien.', flavor_skin_arc_5: 'La verdad no necesita gritar.', flavor_skin_arc_6: 'La luz justa llega a su tiempo.', flavor_skin_arc_7: 'Brillar es para que otros vuelvan.', flavor_skin_arc_8: 'El mayor es el que sirve.', flavor_skin_arc_9: 'Vuela quien deja el peso.', flavor_skin_arc_10: 'Hay pasos que solo se dan confiando.', flavor_skin_arc_11: 'Volvemos a la luz de donde venimos.'
});
