/* =====================================================================
   Conteúdo: 50 conquistas (8 categorias) e 50 modelos de missão
   (diárias e semanais). Dados + textos PT/EN/ES.
   Estatísticas usadas (HR.Achievements.stats()):
     runs best totalCoins totalPerfects bestPhase level bestCombo skinsOwned trailsOwned themesOwned
     revives abilitiesUsed perksTaken levelsCleared starsTotal bossesBeaten regionsCleared
     dirChanges nearMisses timePlayed distance itemsBought coinsSpent gemsSpent dailyClaims
     bestStreak flawlessLevels shieldsAbsorbed practiceRuns bestPerksRun abilitiesMaxed endlessRuns
   ===================================================================== */
window.HR = window.HR || {};

// cat: flight precision wealth galaxy power collection dedication secret · hidden: só aparece ao desbloquear
HR.ACHIEVEMENTS = [
  // Voo
  { id: 'first_run',   cat: 'flight',     stat: 'runs',            target: 1,     gems: 5,   icon: 'play' },
  { id: 'score_10',    cat: 'flight',     stat: 'best',            target: 10,    gems: 10,  icon: 'ring' },
  { id: 'score_25',    cat: 'flight',     stat: 'best',            target: 25,    gems: 15,  icon: 'ring' },
  { id: 'score_50',    cat: 'flight',     stat: 'best',            target: 50,    gems: 25,  icon: 'ring' },
  { id: 'score_100',   cat: 'flight',     stat: 'best',            target: 100,   gems: 50,  icon: 'ring', title: 't_centurion' },
  { id: 'score_200',   cat: 'flight',     stat: 'best',            target: 200,   gems: 100, icon: 'ring' },
  { id: 'score_300',   cat: 'flight',     stat: 'best',            target: 300,   gems: 200, icon: 'orbit', title: 't_singular' },
  { id: 'phase_9',     cat: 'flight',     stat: 'bestPhase',       target: 9,     gems: 50,  icon: 'layers' },
  // Precisão
  { id: 'perfect_50',   cat: 'precision', stat: 'totalPerfects',   target: 50,    gems: 10,  icon: 'target' },
  { id: 'perfect_250',  cat: 'precision', stat: 'totalPerfects',   target: 250,   gems: 25,  icon: 'target' },
  { id: 'perfect_1000', cat: 'precision', stat: 'totalPerfects',   target: 1000,  gems: 60,  icon: 'target', title: 't_surgeon' },
  { id: 'combo_10',     cat: 'precision', stat: 'bestCombo',       target: 10,    gems: 20,  icon: 'flame' },
  { id: 'combo_20',     cat: 'precision', stat: 'bestCombo',       target: 20,    gems: 40,  icon: 'flame' },
  { id: 'combo_35',     cat: 'precision', stat: 'bestCombo',       target: 35,    gems: 80,  icon: 'flame' },
  { id: 'flawless_10',  cat: 'precision', stat: 'flawlessLevels',  target: 10,    gems: 40,  icon: 'sparkle' },
  // Riqueza
  { id: 'coins_1000',  cat: 'wealth',     stat: 'totalCoins',      target: 1000,  gems: 15,  icon: 'coin' },
  { id: 'coins_5000',  cat: 'wealth',     stat: 'totalCoins',      target: 5000,  gems: 40,  icon: 'coin' },
  { id: 'coins_25000', cat: 'wealth',     stat: 'totalCoins',      target: 25000, gems: 120, icon: 'coins', title: 't_tycoon' },
  { id: 'spend_2000',  cat: 'wealth',     stat: 'coinsSpent',      target: 2000,  gems: 20,  icon: 'bag' },
  { id: 'items_5',     cat: 'wealth',     stat: 'itemsBought',     target: 5,     gems: 25,  icon: 'shop' },
  // Galáxia
  { id: 'level_1',    cat: 'galaxy',      stat: 'levelsCleared',   target: 1,     gems: 5,   icon: 'flag' },
  { id: 'levels_25',  cat: 'galaxy',      stat: 'levelsCleared',   target: 25,    gems: 30,  icon: 'flag' },
  { id: 'levels_50',  cat: 'galaxy',      stat: 'levelsCleared',   target: 50,    gems: 60,  icon: 'flag' },
  { id: 'levels_100', cat: 'galaxy',      stat: 'levelsCleared',   target: 100,   gems: 250, icon: 'galaxy', title: 't_navigator' },
  { id: 'stars_30',   cat: 'galaxy',      stat: 'starsTotal',      target: 30,    gems: 20,  icon: 'star' },
  { id: 'stars_100',  cat: 'galaxy',      stat: 'starsTotal',      target: 100,   gems: 60,  icon: 'star' },
  { id: 'stars_300',  cat: 'galaxy',      stat: 'starsTotal',      target: 300,   gems: 300, icon: 'crown', title: 't_supreme' },
  { id: 'boss_1',     cat: 'galaxy',      stat: 'bossesBeaten',    target: 1,     gems: 20,  icon: 'pulse' },
  { id: 'boss_5',     cat: 'galaxy',      stat: 'bossesBeaten',    target: 5,     gems: 60,  icon: 'tornado' },
  { id: 'boss_10',    cat: 'galaxy',      stat: 'bossesBeaten',    target: 10,    gems: 200, icon: 'orbit' },
  { id: 'regions_3',  cat: 'galaxy',      stat: 'regionsCleared',  target: 3,     gems: 40,  icon: 'map' },
  // Poder
  { id: 'ability_25',  cat: 'power',      stat: 'abilitiesUsed',   target: 25,    gems: 15,  icon: 'zap' },
  { id: 'ability_200', cat: 'power',      stat: 'abilitiesUsed',   target: 200,   gems: 50,  icon: 'zap' },
  { id: 'perks_50',    cat: 'power',      stat: 'perksTaken',      target: 50,    gems: 30,  icon: 'sparkle' },
  { id: 'build_5',     cat: 'power',      stat: 'bestPerksRun',    target: 5,     gems: 30,  icon: 'layers' },
  { id: 'ab_max',      cat: 'power',      stat: 'abilitiesMaxed',  target: 1,     gems: 40,  icon: 'arrowUp' },
  { id: 'shields_50',  cat: 'power',      stat: 'shieldsAbsorbed', target: 50,    gems: 30,  icon: 'shield' },
  // Coleção
  { id: 'skins_3',  cat: 'collection',    stat: 'skinsOwned',      target: 3,     gems: 15,  icon: 'ring' },
  { id: 'skins_6',  cat: 'collection',    stat: 'skinsOwned',      target: 6,     gems: 40,  icon: 'ring' },
  { id: 'trails_3', cat: 'collection',    stat: 'trailsOwned',     target: 3,     gems: 20,  icon: 'sparkle' },
  { id: 'themes_3', cat: 'collection',    stat: 'themesOwned',     target: 3,     gems: 20,  icon: 'layers' },
  // Dedicação
  { id: 'runs_10',   cat: 'dedication',   stat: 'runs',            target: 10,    gems: 10,  icon: 'gamepad' },
  { id: 'runs_50',   cat: 'dedication',   stat: 'runs',            target: 50,    gems: 20,  icon: 'gamepad' },
  { id: 'runs_250',  cat: 'dedication',   stat: 'runs',            target: 250,   gems: 50,  icon: 'gamepad' },
  { id: 'streak_3',  cat: 'dedication',   stat: 'bestStreak',      target: 3,     gems: 10,  icon: 'calendar' },
  { id: 'streak_7',  cat: 'dedication',   stat: 'bestStreak',      target: 7,     gems: 30,  icon: 'calendar' },
  { id: 'daily_30',  cat: 'dedication',   stat: 'dailyClaims',     target: 30,    gems: 60,  icon: 'gift' },
  { id: 'time_1h',   cat: 'dedication',   stat: 'timePlayed',      target: 3600,  gems: 30,  icon: 'clock' },
  // Segredos (ocultas)
  { id: 'near_50',     cat: 'secret', hidden: true, stat: 'nearMisses',  target: 50,  gems: 30, icon: 'wind' },
  { id: 'dir_100',     cat: 'secret', hidden: true, stat: 'dirChanges',  target: 100, gems: 30, icon: 'compass' },
  { id: 'revive_1',    cat: 'secret', hidden: true, stat: 'revives',     target: 1,   gems: 10, icon: 'undo' },
  { id: 'practice_10', cat: 'secret', hidden: true, stat: 'practiceRuns', target: 10, gems: 20, icon: 'school' },
  // v3.1: itens, anomalias, álbum
  { id: 'pickups_25',  cat: 'power',      stat: 'pickups',         target: 25,   gems: 20,  icon: 'star' },
  { id: 'pickups_150', cat: 'power',      stat: 'pickups',         target: 150,  gems: 60,  icon: 'star' },
  { id: 'anomaly_10',  cat: 'flight',     stat: 'anomaliesBeaten', target: 10,   gems: 60,  icon: 'orbit' },
  { id: 'rings_found', cat: 'collection', stat: 'ringsFound',      target: 7,    gems: 30,  icon: 'ring' },
  { id: 'items_found', cat: 'collection', stat: 'itemsFound',      target: 7,    gems: 30,  icon: 'gift' },
  { id: 'star_10',     cat: 'secret', hidden: true, stat: 'starsUsed', target: 10, gems: 25, icon: 'sparkle' }
];
HR.ACH_CATS = ['flight', 'precision', 'wealth', 'galaxy', 'power', 'collection', 'dedication', 'secret'];

// kind: run (máximo numa partida) | total (acumula) · src = campo do resumo da partida
// tiers: [alvo, moedas, gemas, xp] × 3 · weekly: entra no sorteio semanal (alvos ×3, prêmios ×4)
HR.MISSIONS = [
  { id: 'rings_run',     icon: 'ring',     kind: 'run',   src: 'score',          tiers: [[15, 80, 0, 40], [25, 130, 0, 60], [40, 220, 5, 100]] },
  { id: 'rings_total',   icon: 'refresh',  kind: 'total', src: 'score',          tiers: [[50, 80, 0, 40], [120, 150, 0, 70], [250, 240, 5, 120]], weekly: true },
  { id: 'coins_run',     icon: 'coin',     kind: 'run',   src: 'coins',          tiers: [[15, 70, 0, 30], [30, 120, 0, 50], [60, 200, 5, 90]] },
  { id: 'coins_total',   icon: 'coins',    kind: 'total', src: 'coins',          tiers: [[25, 70, 0, 30], [60, 130, 0, 50], [120, 210, 5, 90]], weekly: true },
  { id: 'perfects_run',  icon: 'target',   kind: 'run',   src: 'perfects',       tiers: [[6, 80, 0, 40], [12, 140, 0, 70], [25, 230, 5, 120]] },
  { id: 'perfects_total', icon: 'target',  kind: 'total', src: 'perfects',       tiers: [[8, 80, 0, 40], [20, 150, 0, 70], [45, 240, 5, 120]], weekly: true },
  { id: 'runs',          icon: 'gamepad',  kind: 'total', src: 'one',            tiers: [[3, 60, 0, 30], [6, 110, 0, 50], [10, 190, 5, 90]], weekly: true },
  { id: 'phase',         icon: 'layers',   kind: 'run',   src: 'phase',          tiers: [[3, 80, 0, 40], [4, 150, 0, 80], [6, 240, 10, 140]] },
  { id: 'combo',         icon: 'flame',    kind: 'run',   src: 'maxCombo',       tiers: [[4, 80, 0, 40], [7, 150, 0, 80], [10, 240, 8, 140]] },
  { id: 'perks_run',     icon: 'sparkle',  kind: 'run',   src: 'perksCount',     tiers: [[1, 60, 0, 30], [3, 120, 0, 60], [5, 200, 5, 100]] },
  { id: 'perks_total',   icon: 'sparkle',  kind: 'total', src: 'perksCount',     tiers: [[3, 70, 0, 30], [8, 140, 0, 60], [15, 220, 5, 100]], weekly: true },
  { id: 'abilities_run', icon: 'zap',      kind: 'run',   src: 'abilitiesUsed',  tiers: [[2, 60, 0, 30], [4, 110, 0, 50], [8, 190, 5, 90]] },
  { id: 'abilities_total', icon: 'zap',    kind: 'total', src: 'abilitiesUsed',  tiers: [[5, 70, 0, 30], [12, 130, 0, 60], [25, 210, 5, 100]], weekly: true },
  { id: 'time_run',      icon: 'clock',    kind: 'run',   src: 'duration',       tiers: [[45, 70, 0, 30], [90, 130, 0, 60], [150, 220, 5, 100]] },
  { id: 'time_total',    icon: 'clock',    kind: 'total', src: 'duration',       tiers: [[300, 80, 0, 40], [600, 150, 0, 70], [1200, 240, 5, 120]], weekly: true },
  { id: 'dir_run',       icon: 'compass',  kind: 'run',   src: 'dirChanges',     tiers: [[1, 60, 0, 30], [3, 120, 0, 60], [5, 200, 5, 100]] },
  { id: 'dir_total',     icon: 'compass',  kind: 'total', src: 'dirChanges',     tiers: [[3, 70, 0, 30], [8, 130, 0, 60], [15, 210, 5, 100]], weekly: true },
  { id: 'near_run',      icon: 'wind',     kind: 'run',   src: 'nearMisses',     tiers: [[2, 60, 0, 30], [5, 120, 0, 60], [10, 200, 5, 100]] },
  { id: 'near_total',    icon: 'wind',     kind: 'total', src: 'nearMisses',     tiers: [[5, 70, 0, 30], [12, 130, 0, 60], [25, 210, 5, 100]], weekly: true },
  { id: 'dist_run',      icon: 'route',    kind: 'run',   src: 'distKm',         tiers: [[3, 60, 0, 30], [6, 120, 0, 60], [12, 200, 5, 100]] },
  { id: 'dist_total',    icon: 'route',    kind: 'total', src: 'distKm',         tiers: [[10, 80, 0, 40], [25, 150, 0, 70], [50, 240, 5, 120]], weekly: true },
  { id: 'shields_run',   icon: 'shield',   kind: 'run',   src: 'shieldsAbsorbed', tiers: [[1, 60, 0, 30], [2, 110, 0, 50], [3, 190, 5, 90]] },
  { id: 'shields_total', icon: 'shield',   kind: 'total', src: 'shieldsAbsorbed', tiers: [[2, 70, 0, 30], [5, 130, 0, 60], [10, 210, 5, 100]], weekly: true },
  { id: 'clean_run',     icon: 'sparkle',  kind: 'run',   src: 'cleanRings',     tiers: [[10, 80, 0, 40], [20, 150, 0, 80], [35, 240, 8, 140]] },
  { id: 'levels',        icon: 'flag',     kind: 'total', src: 'levelDone',      tiers: [[1, 80, 0, 40], [3, 160, 0, 80], [6, 260, 8, 140]], weekly: true },
  { id: 'stars',         icon: 'star',     kind: 'total', src: 'starsGot',       tiers: [[3, 80, 0, 40], [6, 160, 0, 80], [12, 260, 8, 140]], weekly: true },
  { id: 'three_stars',   icon: 'star',     kind: 'total', src: 'threeStar',      tiers: [[1, 100, 0, 50], [2, 180, 5, 90], [4, 300, 10, 160]], weekly: true },
  { id: 'boss',          icon: 'crown',    kind: 'total', src: 'bossDone',       tiers: [[1, 150, 5, 80], [2, 260, 10, 140], [3, 400, 20, 220]], weekly: true },
  { id: 'flawless',      icon: 'sparkle',  kind: 'total', src: 'flawless',       tiers: [[1, 100, 0, 50], [2, 180, 5, 90], [4, 300, 10, 160]], weekly: true },
  { id: 'endless_runs',  icon: 'infinity', kind: 'total', src: 'endlessRun',     tiers: [[2, 60, 0, 30], [4, 110, 0, 50], [8, 190, 5, 90]], weekly: true },
  { id: 'campaign_runs', icon: 'galaxy',   kind: 'total', src: 'campaignRun',    tiers: [[2, 60, 0, 30], [4, 110, 0, 50], [8, 190, 5, 90]], weekly: true },
  { id: 'practice_runs', icon: 'school',   kind: 'total', src: 'practiceRun',    tiers: [[1, 50, 0, 20], [2, 90, 0, 40], [4, 150, 0, 70]] },
  { id: 'score_endless', icon: 'infinity', kind: 'run',   src: 'endlessScore',   tiers: [[20, 90, 0, 40], [35, 160, 0, 80], [60, 260, 8, 140]] },
  { id: 'gold_rings',    icon: 'coins',    kind: 'total', src: 'goldRings',      tiers: [[1, 70, 0, 30], [3, 130, 0, 60], [6, 210, 5, 100]] },
  { id: 'double_rings',  icon: 'layers',   kind: 'total', src: 'doubleRings',    tiers: [[3, 70, 0, 30], [8, 130, 0, 60], [15, 210, 5, 100]], weekly: true },
  { id: 'combos_total',  icon: 'flame',    kind: 'total', src: 'comboBonuses',   tiers: [[2, 70, 0, 30], [5, 130, 0, 60], [10, 210, 5, 100]], weekly: true },
  { id: 'slowmo',        icon: 'hourglass', kind: 'total', src: 'ab_slowmo',     tiers: [[2, 60, 0, 30], [5, 110, 0, 50], [10, 190, 5, 90]] },
  { id: 'magnet',        icon: 'magnet',   kind: 'total', src: 'ab_magnet',      tiers: [[2, 60, 0, 30], [5, 110, 0, 50], [10, 190, 5, 90]] },
  { id: 'shieldpulse',   icon: 'shield',   kind: 'total', src: 'ab_shieldpulse', tiers: [[2, 60, 0, 30], [5, 110, 0, 50], [10, 190, 5, 90]] },
  { id: 'autopilot',     icon: 'bot',      kind: 'total', src: 'ab_autopilot',   tiers: [[2, 60, 0, 30], [5, 110, 0, 50], [10, 190, 5, 90]] },
  { id: 'ghost',         icon: 'ghost',    kind: 'total', src: 'ab_ghost',       tiers: [[2, 60, 0, 30], [5, 110, 0, 50], [10, 190, 5, 90]] },
  { id: 'freeze',        icon: 'snow',     kind: 'total', src: 'ab_freeze',      tiers: [[2, 60, 0, 30], [5, 110, 0, 50], [10, 190, 5, 90]] },
  { id: 'rare_perk',     icon: 'sparkle',  kind: 'total', src: 'rarePerks',      tiers: [[1, 70, 0, 30], [2, 130, 0, 60], [4, 210, 5, 100]], weekly: true },
  { id: 'lives',         icon: 'heart',    kind: 'total', src: 'livesUsed',      tiers: [[1, 70, 0, 30], [2, 130, 0, 60], [4, 210, 5, 100]] },
  { id: 'coins_bonus',   icon: 'coin',     kind: 'run',   src: 'bonus',          tiers: [[5, 60, 0, 30], [10, 120, 0, 60], [20, 200, 5, 100]] },
  { id: 'region_play',   icon: 'map',      kind: 'total', src: 'regionRun',      tiers: [[2, 70, 0, 30], [4, 130, 0, 60], [8, 210, 5, 100]], weekly: true },
  { id: 'no_ability',    icon: 'ring',     kind: 'run',   src: 'noAbilityScore', tiers: [[10, 80, 0, 40], [20, 150, 0, 80], [35, 240, 8, 140]] },
  { id: 'top_dir',       icon: 'arrowUp',  kind: 'total', src: 'ringsTop',       tiers: [[10, 70, 0, 30], [25, 130, 0, 60], [50, 210, 5, 100]] },
  { id: 'side_dir',      icon: 'arrowLeft', kind: 'total', src: 'ringsLeft',     tiers: [[10, 70, 0, 30], [25, 130, 0, 60], [50, 210, 5, 100]] },
  { id: 'coins_taken',   icon: 'coin',     kind: 'run',   src: 'coinsTaken',     tiers: [[8, 60, 0, 30], [15, 120, 0, 60], [25, 200, 5, 100]] },
  { id: 'pickups',       icon: 'star',     kind: 'total', src: 'pickups',        tiers: [[3, 70, 0, 30], [6, 130, 0, 60], [12, 210, 5, 100]], weekly: true },
  { id: 'anomalies',     icon: 'orbit',    kind: 'total', src: 'anomaliesBeaten', tiers: [[1, 100, 0, 50], [2, 180, 5, 90], [4, 300, 10, 160]], weekly: true },
  { id: 'no_miss',       icon: 'target',   kind: 'run',   src: 'noMissRings',    tiers: [[12, 80, 0, 40], [20, 150, 0, 80], [35, 240, 8, 140]] }
];

// títulos de jogador dados por conquistas (além dos títulos por nível)
HR.TITLES = ['t_centurion', 't_singular', 't_surgeon', 't_tycoon', 't_navigator', 't_supreme'];

/* ---------------- textos ---------------- */
Object.assign(HR.I18N.pt, {
  a_pickups_25: 'Catador', a_pickups_150: 'Colecionador de itens', a_anomaly_10: 'Caça-anomalias', a_rings_found: 'Leitor de cores', a_items_found: 'Todos os itens', a_star_10: 'Invencível',
  a_d_pickups: 'Pegue {n} itens no campo', a_d_anomaliesBeaten: 'Vença {n} anomalias', a_d_ringsFound: 'Descubra {n} tipos de arco', a_d_itemsFound: 'Descubra {n} itens', a_d_starsUsed: 'Pegue {n} estrelas',
  m_pickups: 'Pegue {n} itens no campo', m_anomalies: 'Vença {n} anomalias', m_no_miss: 'Passe {n} arcos seguidos sem errar',
  ach_flight: 'Voo', ach_precision: 'Precisão', ach_wealth: 'Riqueza', ach_galaxy: 'Galáxia', ach_power: 'Poder', ach_collection: 'Coleção', ach_dedication: 'Dedicação', ach_secret: 'Segredos',
  ach_hidden: 'Conquista secreta', ach_progress: '{a}/{b} conquistas', achievements: 'Conquistas', ach_unlocked: 'Desbloqueada', ach_title_get: 'Título: {t}',
  t_centurion: 'Centurião', t_singular: 'Singular', t_surgeon: 'Cirurgião', t_tycoon: 'Magnata', t_navigator: 'Navegador', t_supreme: 'Halo Supremo',
  a_first_run: 'Primeiro voo', a_score_10: 'Dez arcos', a_score_25: 'Vinte e cinco', a_score_50: 'Meio cento', a_score_100: 'Centurião', a_score_200: 'Duzentos!', a_score_300: 'Singular', a_phase_9: 'Modo Hiper',
  a_perfect_50: 'Mira', a_perfect_250: 'Precisão', a_perfect_1000: 'Cirúrgico', a_combo_10: 'Combo 10', a_combo_20: 'Combo 20', a_combo_35: 'Combo 35', a_flawless_10: 'Impecável',
  a_coins_1000: 'Pé de meia', a_coins_5000: 'Cofre cheio', a_coins_25000: 'Magnata', a_spend_2000: 'Gastador', a_items_5: 'Cliente fiel',
  a_level_1: 'Primeira fase', a_levels_25: 'Um quarto', a_levels_50: 'Metade do caminho', a_levels_100: 'Navegador', a_stars_30: 'Constelação', a_stars_100: 'Céu estrelado', a_stars_300: 'Galáxia perfeita',
  a_boss_1: 'Caçador', a_boss_5: 'Domador', a_boss_10: 'Senhor da Singularidade', a_regions_3: 'Explorador',
  a_ability_25: 'Ligado', a_ability_200: 'Sobrecarga', a_perks_50: 'Colecionador de poderes', a_build_5: 'Build completa', a_ab_max: 'Potência máxima', a_shields_50: 'Muralha',
  a_skins_3: 'Colecionador', a_skins_6: 'Vitrine', a_trails_3: 'Rastros', a_themes_3: 'Decorador',
  a_runs_10: 'Aquecendo', a_runs_50: 'Viciado', a_runs_250: 'Lendário', a_streak_3: 'Três dias', a_streak_7: 'Uma semana', a_daily_30: 'Todo dia', a_time_1h: 'Uma hora no ar',
  a_near_50: 'Por um fio', a_dir_100: 'Girassol', a_revive_1: 'Segunda chance', a_practice_10: 'Estudioso',
  a_d_runs: 'Jogue {n} partidas', a_d_best: 'Faça {n} pontos em uma partida', a_d_bestPhase: 'Alcance a fase {n} no infinito', a_d_totalPerfects: 'Faça {n} perfeitos no total', a_d_bestCombo: 'Faça um combo de {n}',
  a_d_flawlessLevels: 'Conclua {n} fases sem dano', a_d_totalCoins: 'Colete {n} moedas no total', a_d_coinsSpent: 'Gaste {n} moedas', a_d_itemsBought: 'Compre {n} itens', a_d_levelsCleared: 'Conclua {n} fases',
  a_d_starsTotal: 'Junte {n} estrelas', a_d_bossesBeaten: 'Vença {n} chefes', a_d_regionsCleared: 'Conclua {n} regiões', a_d_abilitiesUsed: 'Use habilidades {n} vezes', a_d_perksTaken: 'Escolha {n} perks',
  a_d_bestPerksRun: 'Tenha {n} perks em uma partida', a_d_abilitiesMaxed: 'Leve uma habilidade ao nível máximo', a_d_shieldsAbsorbed: 'Absorva {n} erros com escudos', a_d_skinsOwned: 'Tenha {n} bolas', a_d_trailsOwned: 'Tenha {n} rastros',
  a_d_themesOwned: 'Tenha {n} temas', a_d_bestStreak: 'Resgate o diário {n} dias seguidos', a_d_dailyClaims: 'Resgate {n} recompensas diárias', a_d_timePlayed: 'Jogue {n} minutos', a_d_nearMisses: 'Raspe a borda {n} vezes',
  a_d_dirChanges: 'Sobreviva a {n} trocas de direção', a_d_revives: 'Use um continuar', a_d_practiceRuns: 'Treine {n} vezes',
  missions: 'Missões', tab_daily_missions: 'Diárias', tab_weekly: 'Semanais', weekly_resets: 'Semanais renovam em {t}', m_done_n: '{a}/{b} concluídas',
  m_rings_run: 'Passe por {n} arcos em uma partida', m_rings_total: 'Passe por {n} arcos no total', m_coins_run: 'Colete {n} moedas em uma partida', m_coins_total: 'Colete {n} moedas',
  m_perfects_run: 'Faça {n} perfeitos em uma partida', m_perfects_total: 'Faça {n} perfeitos', m_runs: 'Jogue {n} partidas', m_phase: 'Alcance a fase {n} no infinito', m_combo: 'Faça um combo de {n} perfeitos',
  m_perks_run: 'Tenha {n} perks em uma partida', m_perks_total: 'Escolha {n} perks', m_abilities_run: 'Use habilidades {n} vezes em uma partida', m_abilities_total: 'Use habilidades {n} vezes',
  m_time_run: 'Sobreviva {n} segundos em uma partida', m_time_total: 'Jogue {n} segundos no total', m_dir_run: 'Sobreviva a {n} trocas de direção em uma partida', m_dir_total: 'Sobreviva a {n} trocas de direção',
  m_near_run: 'Raspe a borda {n} vezes em uma partida', m_near_total: 'Raspe a borda {n} vezes', m_dist_run: 'Voe {n} km em uma partida', m_dist_total: 'Voe {n} km no total',
  m_shields_run: 'Absorva {n} erros com escudo em uma partida', m_shields_total: 'Absorva {n} erros com escudo', m_clean_run: 'Passe {n} arcos seguidos sem erro', m_levels: 'Conclua {n} fases da galáxia',
  m_stars: 'Ganhe {n} estrelas', m_three_stars: 'Faça 3 estrelas em {n} fases', m_boss: 'Vença {n} chefes', m_flawless: 'Conclua {n} fases sem dano', m_endless_runs: 'Jogue {n} partidas na Singularidade',
  m_campaign_runs: 'Jogue {n} fases da galáxia', m_practice_runs: 'Treine {n} vezes', m_score_endless: 'Faça {n} pontos na Singularidade', m_gold_rings: 'Atravesse {n} anéis dourados', m_double_rings: 'Atravesse {n} arcos duplos',
  m_combos_total: 'Ganhe {n} bônus de combo', m_slowmo: 'Use Câmera Lenta {n} vezes', m_magnet: 'Use Ímã Turbo {n} vezes', m_shieldpulse: 'Use Pulso de Escudo {n} vezes', m_autopilot: 'Use Piloto Automático {n} vezes',
  m_ghost: 'Use Fantasma {n} vezes', m_freeze: 'Use Congelar {n} vezes', m_rare_perk: 'Escolha {n} perks raros ou melhores', m_lives: 'Use {n} vidas extras', m_coins_bonus: 'Ganhe {n} moedas de bônus final em uma partida',
  m_region_play: 'Jogue {n} fases em regiões diferentes', m_no_ability: 'Faça {n} pontos sem usar habilidades', m_top_dir: 'Passe {n} arcos vindos de cima', m_side_dir: 'Passe {n} arcos vindos da esquerda', m_coins_taken: 'Pegue {n} moedas de arco em uma partida'
});
Object.assign(HR.I18N.en, {
  a_pickups_25: 'Gatherer', a_pickups_150: 'Item collector', a_anomaly_10: 'Anomaly hunter', a_rings_found: 'Color reader', a_items_found: 'Every item', a_star_10: 'Invincible',
  a_d_pickups: 'Grab {n} field items', a_d_anomaliesBeaten: 'Beat {n} anomalies', a_d_ringsFound: 'Discover {n} ring types', a_d_itemsFound: 'Discover {n} items', a_d_starsUsed: 'Grab {n} stars',
  m_pickups: 'Grab {n} field items', m_anomalies: 'Beat {n} anomalies', m_no_miss: 'Pass {n} rings in a row without missing',
  ach_flight: 'Flight', ach_precision: 'Precision', ach_wealth: 'Wealth', ach_galaxy: 'Galaxy', ach_power: 'Power', ach_collection: 'Collection', ach_dedication: 'Dedication', ach_secret: 'Secrets',
  ach_hidden: 'Secret achievement', ach_progress: '{a}/{b} achievements', achievements: 'Achievements', ach_unlocked: 'Unlocked', ach_title_get: 'Title: {t}',
  t_centurion: 'Centurion', t_singular: 'Singular', t_surgeon: 'Surgeon', t_tycoon: 'Tycoon', t_navigator: 'Navigator', t_supreme: 'Supreme Halo',
  a_first_run: 'First flight', a_score_10: 'Ten rings', a_score_25: 'Twenty-five', a_score_50: 'Half a hundred', a_score_100: 'Centurion', a_score_200: 'Two hundred!', a_score_300: 'Singular', a_phase_9: 'Hyper mode',
  a_perfect_50: 'Aim', a_perfect_250: 'Precision', a_perfect_1000: 'Surgical', a_combo_10: 'Combo 10', a_combo_20: 'Combo 20', a_combo_35: 'Combo 35', a_flawless_10: 'Flawless',
  a_coins_1000: 'Nest egg', a_coins_5000: 'Full vault', a_coins_25000: 'Tycoon', a_spend_2000: 'Big spender', a_items_5: 'Loyal customer',
  a_level_1: 'First level', a_levels_25: 'A quarter', a_levels_50: 'Halfway', a_levels_100: 'Navigator', a_stars_30: 'Constellation', a_stars_100: 'Starry sky', a_stars_300: 'Perfect galaxy',
  a_boss_1: 'Hunter', a_boss_5: 'Tamer', a_boss_10: 'Lord of the Singularity', a_regions_3: 'Explorer',
  a_ability_25: 'Switched on', a_ability_200: 'Overload', a_perks_50: 'Power collector', a_build_5: 'Full build', a_ab_max: 'Max power', a_shields_50: 'Wall',
  a_skins_3: 'Collector', a_skins_6: 'Showcase', a_trails_3: 'Trails', a_themes_3: 'Decorator',
  a_runs_10: 'Warming up', a_runs_50: 'Hooked', a_runs_250: 'Legendary', a_streak_3: 'Three days', a_streak_7: 'One week', a_daily_30: 'Every day', a_time_1h: 'One hour airborne',
  a_near_50: 'By a hair', a_dir_100: 'Sunflower', a_revive_1: 'Second chance', a_practice_10: 'Scholar',
  a_d_runs: 'Play {n} runs', a_d_best: 'Score {n} in one run', a_d_bestPhase: 'Reach phase {n} in endless', a_d_totalPerfects: 'Score {n} perfects in total', a_d_bestCombo: 'Hit a {n} combo',
  a_d_flawlessLevels: 'Clear {n} levels without damage', a_d_totalCoins: 'Collect {n} coins in total', a_d_coinsSpent: 'Spend {n} coins', a_d_itemsBought: 'Buy {n} items', a_d_levelsCleared: 'Clear {n} levels',
  a_d_starsTotal: 'Collect {n} stars', a_d_bossesBeaten: 'Beat {n} bosses', a_d_regionsCleared: 'Clear {n} regions', a_d_abilitiesUsed: 'Use abilities {n} times', a_d_perksTaken: 'Pick {n} perks',
  a_d_bestPerksRun: 'Hold {n} perks in one run', a_d_abilitiesMaxed: 'Max out an ability', a_d_shieldsAbsorbed: 'Absorb {n} mistakes with shields', a_d_skinsOwned: 'Own {n} balls', a_d_trailsOwned: 'Own {n} trails',
  a_d_themesOwned: 'Own {n} themes', a_d_bestStreak: 'Claim the daily {n} days in a row', a_d_dailyClaims: 'Claim {n} daily rewards', a_d_timePlayed: 'Play {n} minutes', a_d_nearMisses: 'Graze the rim {n} times',
  a_d_dirChanges: 'Survive {n} direction changes', a_d_revives: 'Use a continue', a_d_practiceRuns: 'Practice {n} times',
  missions: 'Missions', tab_daily_missions: 'Daily', tab_weekly: 'Weekly', weekly_resets: 'Weekly reset in {t}', m_done_n: '{a}/{b} done',
  m_rings_run: 'Pass {n} rings in one run', m_rings_total: 'Pass {n} rings in total', m_coins_run: 'Collect {n} coins in one run', m_coins_total: 'Collect {n} coins',
  m_perfects_run: 'Score {n} perfects in one run', m_perfects_total: 'Score {n} perfects', m_runs: 'Play {n} runs', m_phase: 'Reach phase {n} in endless', m_combo: 'Hit a {n} perfect combo',
  m_perks_run: 'Hold {n} perks in one run', m_perks_total: 'Pick {n} perks', m_abilities_run: 'Use abilities {n} times in one run', m_abilities_total: 'Use abilities {n} times',
  m_time_run: 'Survive {n} seconds in one run', m_time_total: 'Play {n} seconds in total', m_dir_run: 'Survive {n} direction changes in one run', m_dir_total: 'Survive {n} direction changes',
  m_near_run: 'Graze the rim {n} times in one run', m_near_total: 'Graze the rim {n} times', m_dist_run: 'Fly {n} km in one run', m_dist_total: 'Fly {n} km in total',
  m_shields_run: 'Absorb {n} mistakes with a shield in one run', m_shields_total: 'Absorb {n} mistakes with a shield', m_clean_run: 'Pass {n} rings in a row without a mistake', m_levels: 'Clear {n} galaxy levels',
  m_stars: 'Earn {n} stars', m_three_stars: 'Get 3 stars on {n} levels', m_boss: 'Beat {n} bosses', m_flawless: 'Clear {n} levels without damage', m_endless_runs: 'Play {n} Singularity runs',
  m_campaign_runs: 'Play {n} galaxy levels', m_practice_runs: 'Practice {n} times', m_score_endless: 'Score {n} in the Singularity', m_gold_rings: 'Pass {n} golden rings', m_double_rings: 'Pass {n} double rings',
  m_combos_total: 'Earn {n} combo bonuses', m_slowmo: 'Use Slow Motion {n} times', m_magnet: 'Use Turbo Magnet {n} times', m_shieldpulse: 'Use Shield Pulse {n} times', m_autopilot: 'Use Autopilot {n} times',
  m_ghost: 'Use Ghost {n} times', m_freeze: 'Use Freeze {n} times', m_rare_perk: 'Pick {n} rare or better perks', m_lives: 'Use {n} extra lives', m_coins_bonus: 'Earn {n} end-of-run bonus coins in one run',
  m_region_play: 'Play {n} levels in different regions', m_no_ability: 'Score {n} without using abilities', m_top_dir: 'Pass {n} rings coming from the top', m_side_dir: 'Pass {n} rings coming from the left', m_coins_taken: 'Grab {n} ring coins in one run'
});
Object.assign(HR.I18N.es, {
  a_pickups_25: 'Recolector', a_pickups_150: 'Coleccionista de objetos', a_anomaly_10: 'Cazador de anomalías', a_rings_found: 'Lector de colores', a_items_found: 'Todos los objetos', a_star_10: 'Invencible',
  a_d_pickups: 'Recoge {n} objetos del campo', a_d_anomaliesBeaten: 'Vence {n} anomalías', a_d_ringsFound: 'Descubre {n} tipos de aro', a_d_itemsFound: 'Descubre {n} objetos', a_d_starsUsed: 'Recoge {n} estrellas',
  m_pickups: 'Recoge {n} objetos del campo', m_anomalies: 'Vence {n} anomalías', m_no_miss: 'Pasa {n} aros seguidos sin fallar',
  ach_flight: 'Vuelo', ach_precision: 'Precisión', ach_wealth: 'Riqueza', ach_galaxy: 'Galaxia', ach_power: 'Poder', ach_collection: 'Colección', ach_dedication: 'Dedicación', ach_secret: 'Secretos',
  ach_hidden: 'Logro secreto', ach_progress: '{a}/{b} logros', achievements: 'Logros', ach_unlocked: 'Desbloqueado', ach_title_get: 'Título: {t}',
  t_centurion: 'Centurión', t_singular: 'Singular', t_surgeon: 'Cirujano', t_tycoon: 'Magnate', t_navigator: 'Navegante', t_supreme: 'Halo Supremo',
  a_first_run: 'Primer vuelo', a_score_10: 'Diez aros', a_score_25: 'Veinticinco', a_score_50: 'Medio centenar', a_score_100: 'Centurión', a_score_200: '¡Doscientos!', a_score_300: 'Singular', a_phase_9: 'Modo Híper',
  a_perfect_50: 'Puntería', a_perfect_250: 'Precisión', a_perfect_1000: 'Quirúrgico', a_combo_10: 'Combo 10', a_combo_20: 'Combo 20', a_combo_35: 'Combo 35', a_flawless_10: 'Impecable',
  a_coins_1000: 'Ahorros', a_coins_5000: 'Bóveda llena', a_coins_25000: 'Magnate', a_spend_2000: 'Gastador', a_items_5: 'Cliente fiel',
  a_level_1: 'Primer nivel', a_levels_25: 'Un cuarto', a_levels_50: 'Mitad del camino', a_levels_100: 'Navegante', a_stars_30: 'Constelación', a_stars_100: 'Cielo estrellado', a_stars_300: 'Galaxia perfecta',
  a_boss_1: 'Cazador', a_boss_5: 'Domador', a_boss_10: 'Señor de la Singularidad', a_regions_3: 'Explorador',
  a_ability_25: 'Encendido', a_ability_200: 'Sobrecarga', a_perks_50: 'Coleccionista de poderes', a_build_5: 'Build completa', a_ab_max: 'Potencia máxima', a_shields_50: 'Muralla',
  a_skins_3: 'Coleccionista', a_skins_6: 'Vitrina', a_trails_3: 'Estelas', a_themes_3: 'Decorador',
  a_runs_10: 'Calentando', a_runs_50: 'Enganchado', a_runs_250: 'Legendario', a_streak_3: 'Tres días', a_streak_7: 'Una semana', a_daily_30: 'Cada día', a_time_1h: 'Una hora en el aire',
  a_near_50: 'Por un pelo', a_dir_100: 'Girasol', a_revive_1: 'Segunda oportunidad', a_practice_10: 'Estudioso',
  a_d_runs: 'Juega {n} partidas', a_d_best: 'Haz {n} puntos en una partida', a_d_bestPhase: 'Llega a la fase {n} en infinito', a_d_totalPerfects: 'Haz {n} perfectos en total', a_d_bestCombo: 'Haz un combo de {n}',
  a_d_flawlessLevels: 'Completa {n} niveles sin daño', a_d_totalCoins: 'Recoge {n} monedas en total', a_d_coinsSpent: 'Gasta {n} monedas', a_d_itemsBought: 'Compra {n} objetos', a_d_levelsCleared: 'Completa {n} niveles',
  a_d_starsTotal: 'Reúne {n} estrellas', a_d_bossesBeaten: 'Vence a {n} jefes', a_d_regionsCleared: 'Completa {n} regiones', a_d_abilitiesUsed: 'Usa habilidades {n} veces', a_d_perksTaken: 'Elige {n} perks',
  a_d_bestPerksRun: 'Ten {n} perks en una partida', a_d_abilitiesMaxed: 'Lleva una habilidad al nivel máximo', a_d_shieldsAbsorbed: 'Absorbe {n} errores con escudos', a_d_skinsOwned: 'Ten {n} bolas', a_d_trailsOwned: 'Ten {n} estelas',
  a_d_themesOwned: 'Ten {n} temas', a_d_bestStreak: 'Reclama el diario {n} días seguidos', a_d_dailyClaims: 'Reclama {n} recompensas diarias', a_d_timePlayed: 'Juega {n} minutos', a_d_nearMisses: 'Roza el borde {n} veces',
  a_d_dirChanges: 'Sobrevive a {n} cambios de dirección', a_d_revives: 'Usa un continuar', a_d_practiceRuns: 'Practica {n} veces',
  missions: 'Misiones', tab_daily_missions: 'Diarias', tab_weekly: 'Semanales', weekly_resets: 'Semanales se renuevan en {t}', m_done_n: '{a}/{b} completadas',
  m_rings_run: 'Pasa {n} aros en una partida', m_rings_total: 'Pasa {n} aros en total', m_coins_run: 'Recoge {n} monedas en una partida', m_coins_total: 'Recoge {n} monedas',
  m_perfects_run: 'Haz {n} perfectos en una partida', m_perfects_total: 'Haz {n} perfectos', m_runs: 'Juega {n} partidas', m_phase: 'Llega a la fase {n} en infinito', m_combo: 'Haz un combo de {n} perfectos',
  m_perks_run: 'Ten {n} perks en una partida', m_perks_total: 'Elige {n} perks', m_abilities_run: 'Usa habilidades {n} veces en una partida', m_abilities_total: 'Usa habilidades {n} veces',
  m_time_run: 'Sobrevive {n} segundos en una partida', m_time_total: 'Juega {n} segundos en total', m_dir_run: 'Sobrevive a {n} cambios de dirección en una partida', m_dir_total: 'Sobrevive a {n} cambios de dirección',
  m_near_run: 'Roza el borde {n} veces en una partida', m_near_total: 'Roza el borde {n} veces', m_dist_run: 'Vuela {n} km en una partida', m_dist_total: 'Vuela {n} km en total',
  m_shields_run: 'Absorbe {n} errores con escudo en una partida', m_shields_total: 'Absorbe {n} errores con escudo', m_clean_run: 'Pasa {n} aros seguidos sin error', m_levels: 'Completa {n} niveles de la galaxia',
  m_stars: 'Gana {n} estrellas', m_three_stars: 'Consigue 3 estrellas en {n} niveles', m_boss: 'Vence a {n} jefes', m_flawless: 'Completa {n} niveles sin daño', m_endless_runs: 'Juega {n} partidas en la Singularidad',
  m_campaign_runs: 'Juega {n} niveles de la galaxia', m_practice_runs: 'Practica {n} veces', m_score_endless: 'Haz {n} puntos en la Singularidad', m_gold_rings: 'Atraviesa {n} aros dorados', m_double_rings: 'Atraviesa {n} aros dobles',
  m_combos_total: 'Gana {n} bonos de combo', m_slowmo: 'Usa Cámara Lenta {n} veces', m_magnet: 'Usa Imán Turbo {n} veces', m_shieldpulse: 'Usa Pulso de Escudo {n} veces', m_autopilot: 'Usa Piloto Automático {n} veces',
  m_ghost: 'Usa Fantasma {n} veces', m_freeze: 'Usa Congelar {n} veces', m_rare_perk: 'Elige {n} perks raros o mejores', m_lives: 'Usa {n} vidas extra', m_coins_bonus: 'Gana {n} monedas de bono final en una partida',
  m_region_play: 'Juega {n} niveles en regiones distintas', m_no_ability: 'Haz {n} puntos sin usar habilidades', m_top_dir: 'Pasa {n} aros que vienen de arriba', m_side_dir: 'Pasa {n} aros que vienen de la izquierda', m_coins_taken: 'Recoge {n} monedas de aro en una partida'
});
