/* =====================================================================
   ORBO v7 — texto da história: Galáxia 3 (O Jardim · Colmeia) + o Ninho.
   Ver docs/HISTORIA_V7.md.

   O degrau: tudo aqui nasceu no MESMO instante — e no meio do instante,
   "uma luz saiu andando". Da cor dela.
   A virtude: cuidado. O ponto alto: ela escolhe Poeira, o grão que não
   brilha, em vez do enxame que segue quem brilha.
   A carta diz "nossa" pela primeira vez: são dois.
   ===================================================================== */
Object.assign(HR.I18N.pt, {
  skin_poeira: 'Poeira', flavor_skin_poeira: 'Todo grão já foi luz.',
  a_nest_stay: 'Quem fica', a_d_nest: 'Deixe de voar para ficar com quem não voa.',

  /* ---------------- entrada ---------------- */
  st_g3_k: 'Capítulo 3 · O Jardim',
  st_g3_1: '~O Jardim é a primeira coisa viva que você vê desde que acordou.',
  st_g3_2: '~Aqui os anéis vêm em pares e trios, porque aqui nada anda sozinho.',
  st_g3_3: '~Um enxame de luzinhas se aproxima. Elas seguem quem brilha.',
  st_g3_ask: 'Bem-vinda. Você é de fora. Isso se resolve.',
  st_g3_oU: 'Estou de passagem. Obrigada.',
  st_g3_oQ: 'Resolve como?',
  st_g3_oF: 'Não vim ser resolvida.',
  st_g3_rU: 'De passagem. Todas dizem isso e ficam.',
  st_g3_rQ: 'Com regra. É sempre com regra.',
  st_g3_rF: 'Então vai ser um jardim difícil para você.',

  /* ---------------- visitas ---------------- */
  st_g3v2_who: 'cardume',
  st_g3v2_1: 'Você brilha! A gente vai com você!',
  st_g3v2_2: 'Pra onde? Não importa! A gente vai!',
  st_g3v2_3: '~Eles vão mesmo. Por enquanto.',

  st_g3v7_who: 'poeira',
  st_g3v7_1: '~Um grão escuro está parado na beira do caminho.',
  st_g3v7_2: 'Eu sou Poeira.',
  st_g3v7_3: 'Não brilho. E não atrapalho.',
  st_g3v7_4: '@faisca Você é daqui?',
  st_g3v7_5: 'Ninguém sabe de onde eu sou. Nem eu.',

  st_g3v9_who: 'casco',
  st_g3v9_1: 'A Colmeia não é má. É assustada.',
  st_g3v9_2: 'O pior portão do mundo é o medo com razão.',

  /* ---------------- chefes dos sistemas ---------------- */
  st_g3b1_ask: 'Nós cuidamos de quem entra. Aceita?',
  st_g3b1_oU: 'Aceito. E agradeço.',
  st_g3b1_oQ: 'Cuidar tem regra?',
  st_g3b1_oF: 'Eu me cuido.',
  st_g3b1_rU: 'Agradecer. Anotado. Nós lembramos de tudo.',
  st_g3b1_rQ: 'Tem. Toda casa tem.',
  st_g3b1_rF: "Aqui não existe 'me'. Existe 'nós'.",

  st_g3b2_ask: 'Aqui ninguém voa fora do par. Combinado?',
  st_g3b2_oU: 'Combinado, enquanto eu estiver aqui.',
  st_g3b2_oQ: 'E quem não tem par?',
  st_g3b2_oF: 'Eu voo como sei.',
  st_g3b2_rU: 'Justo. Você é de passagem.',
  st_g3b2_rQ: 'Esse é o problema, não é?',
  st_g3b2_rF: 'Então voe longe da colmeia.',

  st_g3b3_ask: 'Quem te ensinou a voar?',
  st_g3b3_oU: 'Não sei. Acordei sabendo.',
  st_g3b3_oQ: 'Isso se aprende ou já vem?',
  st_g3b3_oF: 'Eu aprendi sozinha.',
  st_g3b3_rU: 'Ninguém acorda sabendo. Alguém ensinou antes.',
  st_g3b3_rQ: 'Vem um pouco. O resto alguém mostra.',
  st_g3b3_rF: 'Sozinha? Nem nós, e nós somos muitas.',

  st_g3b4_1: '@cardume Olha aquilo ali! Não brilha nada!',
  st_g3b4_ask: 'Aquilo ali não brilha. Serve para quê?',
  st_g3b4_oU: 'Não sei. Quero por perto mesmo assim.',
  st_g3b4_oQ: 'Precisa servir?',
  st_g3b4_oF: 'Para nada.',
  st_g3b4_rU: 'Perto é onde as coisas viram gente.',
  st_g3b4_rQ: 'No jardim, precisa.',
  st_g3b4_rF: '@poeira Tudo bem. Eu já sabia.',

  st_g3b5_ask: 'Vamos medir a sua luz. Pode ser?',
  st_g3b5_oU: 'Pode. Ela é pequena.',
  st_g3b5_oQ: 'Medir para quê?',
  st_g3b5_oF: 'Mede a sua.',
  st_g3b5_rU: 'Pequena. E mais velha que a nossa. Estranho.',
  st_g3b5_rQ: 'Para saber de quando ela é. E a sua não é de agora.',
  st_g3b5_rF: 'A nossa nasceu num dia só. A sua, não.',

  st_g3b6_1: '~As luzes do jardim cercam Poeira.',
  st_g3b6_ask: 'O grão vai embora hoje. É o certo.',
  st_g3b6_oU: 'Então eu vou junto.',
  st_g3b6_oQ: 'Certo para quem?',
  st_g3b6_oF: 'Tanto faz.',
  st_g3b6_rU: 'Você mal chegou.',
  st_g3b6_rQ: 'Para o jardim. Sempre para o jardim.',
  st_g3b6_rF: '@poeira Tanto faz. É o que dizem de mim.',

  st_g3b7_ask: 'Uma luz parou de voar no ninho. No meio. Nós vimos.',
  st_g3b7_oU: 'Por quê?',
  st_g3b7_oQ: 'Deixou de voar como?',
  st_g3b7_oF: 'Perdeu, então.',
  st_g3b7_rU: 'Não sabemos. Só que ficou.',
  st_g3b7_rQ: 'Parou. No meio. De propósito.',
  st_g3b7_rF: 'Talvez. Ou ganhou outra coisa.',

  st_g3b8_1: '@cardume Se ficar com o grão, a gente vai embora!',
  st_g3b8_ask: 'Se ficar com ele, você deixa de ser nossa.',
  st_g3b8_oU: 'Tudo bem. Obrigada mesmo assim.',
  st_g3b8_oQ: 'Vocês perdem o quê com isso?',
  st_g3b8_oF: 'Eu nunca fui de vocês.',
  st_g3b8_rU: '@poeira Você ficou. Ninguém fica.',
  st_g3b8_rQ: 'Uma a menos. E nós contamos tudo.',
  st_g3b8_rF: 'Não. E ainda assim comeu do jardim.',

  st_g3b9_ask: 'Você ouviu a nossa história. Ainda nos julga?',
  st_g3b9_oU: 'Não. Medo antigo é pesado.',
  st_g3b9_oQ: 'Quantas vezes já aconteceu?',
  st_g3b9_oF: 'Julgo. Vocês viraram o portão.',
  st_g3b9_rU: 'É. E nós passamos esse medo adiante.',
  st_g3b9_rQ: 'Uma. Uma foi suficiente.',
  st_g3b9_rF: 'Viramos. O portão também tem medo.',

  /* ---------------- chefe da galáxia ---------------- */
  st_g3b10_k: 'Colmeia',
  st_g3b10_1: '~O enxame se fecha e se abre como uma coisa só.',
  st_g3b10_2: 'Você acha que nós somos duras.',
  st_g3b10_3: 'Nós nascemos todas juntas. No mesmo instante.',
  st_g3b10_4: 'E no meio de nós, naquele instante, uma luz saiu andando.',
  st_g3b10_5: '@faisca Uma luz como?',
  st_g3b10_6: 'Pequena. Da sua cor.',
  st_g3b10_ask: 'Diga: o que nós fazemos com quem chega de fora?',
  st_g3b10_oU: 'Recebe. Vocês também chegaram.',
  st_g3b10_oQ: 'Pergunta o nome antes de decidir.',
  st_g3b10_oF: 'Fecha. Foi o que fizeram com vocês.',
  st_g3b10_rU: 'Vá. Leve o grão. E não conte que nós deixamos.',
  st_g3b10_rQ: 'Nome. O seu nós já guardamos: a luz que saiu andando.',
  st_g3b10_rF: 'É o que fazemos. Dói ouvir de fora.',

  /* ---------------- a carta ---------------- */
  st_g3c_who: 'vela', st_g3c_k: 'Uma carta',
  st_g3c_1: '~Entre duas flores de luz, um bilhete dobrado.',
  st_g3c_2: 'Faísca: nenhuma luz se acende sozinha.',
  st_g3c_3: 'A sua começou com a nossa.',
  st_g3c_4: 'Diga obrigada enquanto dá tempo.',
  st_g3c_5: '— V.',
  st_g3c_6: '@faisca "Nossa"?',
  st_g3c_7: '@poeira São dois. Eu sabia.',

  /* ---------------- o Ninho (segredo) ---------------- */
  st_nest_win_who: 'poeira',
  st_nest_win_1: 'Você voa bonito.',
  st_nest_win_2: 'Eu não consigo. Mas eu vi você passar.',
  st_nest_hint_who: 'poeira',
  st_nest_hint_1: 'Todo mundo passa por aqui.',
  st_nest_hint_2: 'Ninguém nunca fica.',
  st_nest_stay_who: 'poeira', st_nest_stay_k: 'O Ninho',
  st_nest_stay_1: '~Você para no meio do caminho. Não é queda: é escolha.',
  st_nest_stay_2: '~Desce até o ninho e fica ali, com Poeira.',
  st_nest_stay_3: 'Você perdeu por minha causa.',
  st_nest_stay_4: '@faisca Eu não perdi. Eu fiquei.',
  st_nest_stay_5: '~O jardim inteiro se apaga devagar. Só vocês duas ficam acesas.'
});

Object.assign(HR.I18N.en, {
  skin_poeira: 'Dust', flavor_skin_poeira: 'Every speck was light once.',
  a_nest_stay: 'The one who stays', a_d_nest: 'Stop flying to stay with the one who cannot fly.',

  st_g3_k: 'Chapter 3 · The Garden',
  st_g3_1: '~The Garden is the first living thing you have seen since you woke.',
  st_g3_2: '~Here the rings come in pairs and threes, because nothing here goes alone.',
  st_g3_3: '~A swarm of little lights comes closer. They follow whoever shines.',
  st_g3_ask: 'Welcome. You are from outside. That can be fixed.',
  st_g3_oU: 'I am passing through. Thank you.',
  st_g3_oQ: 'Fixed how?',
  st_g3_oF: 'I did not come to be fixed.',
  st_g3_rU: 'Passing through. They all say that and stay.',
  st_g3_rQ: 'With rules. It is always with rules.',
  st_g3_rF: 'Then this will be a hard garden for you.',

  st_g3v2_who: 'cardume',
  st_g3v2_1: 'You shine! We are coming with you!',
  st_g3v2_2: 'Where? Does not matter! We are coming!',
  st_g3v2_3: '~And they do. For now.',

  st_g3v7_who: 'poeira',
  st_g3v7_1: '~A dark speck sits still at the edge of the path.',
  st_g3v7_2: 'I am Dust.',
  st_g3v7_3: 'I do not shine. And I am not in the way.',
  st_g3v7_4: '@faisca Are you from here?',
  st_g3v7_5: 'Nobody knows where I am from. Not even me.',

  st_g3v9_who: 'casco',
  st_g3v9_1: 'The Hive is not bad. It is scared.',
  st_g3v9_2: 'The worst gate in the world is a fear with a reason.',

  st_g3b1_ask: 'We look after whoever comes in. Do you accept?',
  st_g3b1_oU: 'I accept. And thank you.',
  st_g3b1_oQ: 'Does looking after have rules?',
  st_g3b1_oF: 'I look after myself.',
  st_g3b1_rU: 'Thank you. Noted. We remember everything.',
  st_g3b1_rQ: 'It does. Every home has them.',
  st_g3b1_rF: "Here there is no 'me'. There is 'us'.",

  st_g3b2_ask: 'Here no one flies without a pair. Agreed?',
  st_g3b2_oU: 'Agreed, while I am here.',
  st_g3b2_oQ: 'And the ones with no pair?',
  st_g3b2_oF: 'I fly the way I know.',
  st_g3b2_rU: 'Fair. You are passing through.',
  st_g3b2_rQ: 'That is the problem, is it not?',
  st_g3b2_rF: 'Then fly far from the hive.',

  st_g3b3_ask: 'Who taught you to fly?',
  st_g3b3_oU: 'I do not know. I woke knowing.',
  st_g3b3_oQ: 'Is it learned or born?',
  st_g3b3_oF: 'I learned by myself.',
  st_g3b3_rU: 'No one wakes up knowing. Someone taught you before.',
  st_g3b3_rQ: 'A little is born. Someone shows the rest.',
  st_g3b3_rF: 'Alone? Not even us, and we are many.',

  st_g3b4_1: '@cardume Look at that! It does not shine at all!',
  st_g3b4_ask: 'That one does not shine. What is it for?',
  st_g3b4_oU: 'Not sure. I want it near anyway.',
  st_g3b4_oQ: 'Does it have to be for something?',
  st_g3b4_oF: 'For nothing.',
  st_g3b4_rU: 'Near is where things become someone.',
  st_g3b4_rQ: 'In the garden, it does.',
  st_g3b4_rF: '@poeira It is fine. I knew.',

  st_g3b5_ask: 'Let us measure your light. May we?',
  st_g3b5_oU: 'You may. It is small.',
  st_g3b5_oQ: 'Measure it for what?',
  st_g3b5_oF: 'Measure yours.',
  st_g3b5_rU: 'Small. And older than ours. Strange.',
  st_g3b5_rQ: 'To know when it is from. And yours is not from now.',
  st_g3b5_rF: 'Ours was born on a single day. Yours was not.',

  st_g3b6_1: '~The garden lights surround Dust.',
  st_g3b6_ask: 'The speck leaves today. It is the right thing.',
  st_g3b6_oU: 'Then I go too.',
  st_g3b6_oQ: 'Right for whom?',
  st_g3b6_oF: 'Whatever.',
  st_g3b6_rU: 'You have barely arrived.',
  st_g3b6_rQ: 'For the garden. Always for the garden.',
  st_g3b6_rF: '@poeira Whatever. That is what they say of me.',

  st_g3b7_ask: 'A light stopped flying in the nest. Halfway. We saw it.',
  st_g3b7_oU: 'Why?',
  st_g3b7_oQ: 'Stopped flying how?',
  st_g3b7_oF: 'Lost, then.',
  st_g3b7_rU: 'We do not know. Only that it stayed.',
  st_g3b7_rQ: 'Stopped. Halfway. On purpose.',
  st_g3b7_rF: 'Maybe. Or won something else.',

  st_g3b8_1: '@cardume If you stay with the speck, we are leaving!',
  st_g3b8_ask: 'If you stay with it, you stop being ours.',
  st_g3b8_oU: 'That is fine. Thank you anyway.',
  st_g3b8_oQ: 'What do you lose by it?',
  st_g3b8_oF: 'I was never yours.',
  st_g3b8_rU: '@poeira You stayed. Nobody stays.',
  st_g3b8_rQ: 'One fewer. And we count everything.',
  st_g3b8_rF: 'No. And still you ate from the garden.',

  st_g3b9_ask: 'You heard our story. Do you still judge us?',
  st_g3b9_oU: 'No. Old fear is heavy.',
  st_g3b9_oQ: 'How many times has it happened?',
  st_g3b9_oF: 'I do. You became the gate.',
  st_g3b9_rU: 'Yes. And we pass that fear along.',
  st_g3b9_rQ: 'Once. Once was enough.',
  st_g3b9_rF: 'We did. The gate is afraid too.',

  st_g3b10_k: 'Hive',
  st_g3b10_1: '~The swarm closes and opens like a single thing.',
  st_g3b10_2: 'You think we are hard.',
  st_g3b10_3: 'We were all born together. In the same instant.',
  st_g3b10_4: 'And in the middle of us, in that instant, a light walked out.',
  st_g3b10_5: '@faisca What kind of light?',
  st_g3b10_6: 'Small. Your colour.',
  st_g3b10_ask: 'Tell us: what do we do with those who come from outside?',
  st_g3b10_oU: 'Welcome them. You arrived too.',
  st_g3b10_oQ: 'Ask the name before deciding.',
  st_g3b10_oF: 'Close. They did that to you.',
  st_g3b10_rU: 'Go. Take the speck. And do not say we let you.',
  st_g3b10_rQ: 'A name. Yours we already keep: the light that walked out.',
  st_g3b10_rF: 'It is what we do. It hurts to hear it from outside.',

  st_g3c_who: 'vela', st_g3c_k: 'A letter',
  st_g3c_1: '~Between two flowers of light, a folded note.',
  st_g3c_2: 'Spark: no light switches itself on.',
  st_g3c_3: 'Yours started with ours.',
  st_g3c_4: 'Say thank you while there is time.',
  st_g3c_5: '— S.',
  st_g3c_6: '@faisca "Ours"?',
  st_g3c_7: '@poeira There are two. I knew.',

  st_nest_win_who: 'poeira',
  st_nest_win_1: 'You fly beautifully.',
  st_nest_win_2: 'I cannot. But I saw you go by.',
  st_nest_hint_who: 'poeira',
  st_nest_hint_1: 'Everybody comes through here.',
  st_nest_hint_2: 'Nobody ever stays.',
  st_nest_stay_who: 'poeira', st_nest_stay_k: 'The Nest',
  st_nest_stay_1: '~You stop halfway. It is not a fall: it is a choice.',
  st_nest_stay_2: '~You come down to the nest and stay there, with Dust.',
  st_nest_stay_3: 'You lost because of me.',
  st_nest_stay_4: '@faisca I did not lose. I stayed.',
  st_nest_stay_5: '~The whole garden dims. Only the two of you stay lit.'
});

Object.assign(HR.I18N.es, {
  skin_poeira: 'Polvo', flavor_skin_poeira: 'Cada grano fue luz alguna vez.',
  a_nest_stay: 'Quien se queda', a_d_nest: 'Deja de volar para quedarte con quien no vuela.',

  st_g3_k: 'Capítulo 3 · El Jardín',
  st_g3_1: '~El Jardín es lo primero vivo que ves desde que despertaste.',
  st_g3_2: '~Aquí los anillos vienen en pares y tríos, porque aquí nada va solo.',
  st_g3_3: '~Un enjambre de lucecitas se acerca. Siguen a quien brilla.',
  st_g3_ask: 'Bienvenida. Eres de afuera. Eso se arregla.',
  st_g3_oU: 'Estoy de paso. Gracias.',
  st_g3_oQ: '¿Se arregla cómo?',
  st_g3_oF: 'No vine a que me arreglen.',
  st_g3_rU: 'De paso. Todas dicen eso y se quedan.',
  st_g3_rQ: 'Con reglas. Siempre es con reglas.',
  st_g3_rF: 'Entonces será un jardín difícil para ti.',

  st_g3v2_who: 'cardume',
  st_g3v2_1: '¡Brillas! ¡Vamos contigo!',
  st_g3v2_2: '¿Adónde? ¡No importa! ¡Vamos!',
  st_g3v2_3: '~Y van. Por ahora.',

  st_g3v7_who: 'poeira',
  st_g3v7_1: '~Un grano oscuro está quieto en el borde del camino.',
  st_g3v7_2: 'Soy Polvo.',
  st_g3v7_3: 'No brillo. Y no estorbo.',
  st_g3v7_4: '@faisca ¿Eres de aquí?',
  st_g3v7_5: 'Nadie sabe de dónde soy. Ni yo.',

  st_g3v9_who: 'casco',
  st_g3v9_1: 'La Colmena no es mala. Está asustada.',
  st_g3v9_2: 'El peor portón del mundo es el miedo con razón.',

  st_g3b1_ask: 'Cuidamos de quien entra. ¿Aceptas?',
  st_g3b1_oU: 'Acepto. Y agradezco.',
  st_g3b1_oQ: '¿Cuidar tiene reglas?',
  st_g3b1_oF: 'Yo me cuido.',
  st_g3b1_rU: 'Gracias. Anotado. Nosotras recordamos todo.',
  st_g3b1_rQ: 'Las tiene. Toda casa las tiene.',
  st_g3b1_rF: "Aquí no existe 'me'. Existe 'nosotras'.",

  st_g3b2_ask: 'Aquí nadie vuela sin pareja. ¿De acuerdo?',
  st_g3b2_oU: 'De acuerdo, mientras esté aquí.',
  st_g3b2_oQ: '¿Y quien no tiene pareja?',
  st_g3b2_oF: 'Vuelo como sé.',
  st_g3b2_rU: 'Justo. Estás de paso.',
  st_g3b2_rQ: 'Ese es el problema, ¿no?',
  st_g3b2_rF: 'Entonces vuela lejos de la colmena.',

  st_g3b3_ask: '¿Quién te enseñó a volar?',
  st_g3b3_oU: 'No sé. Desperté sabiendo.',
  st_g3b3_oQ: '¿Se aprende o ya viene?',
  st_g3b3_oF: 'Aprendí sola.',
  st_g3b3_rU: 'Nadie despierta sabiendo. Alguien enseñó antes.',
  st_g3b3_rQ: 'Viene un poco. El resto alguien lo muestra.',
  st_g3b3_rF: '¿Sola? Ni nosotras, y somos muchas.',

  st_g3b4_1: '@cardume ¡Mira eso! ¡No brilla nada!',
  st_g3b4_ask: 'Eso de ahí no brilla. ¿Para qué sirve?',
  st_g3b4_oU: 'No sé. Lo quiero cerca igual.',
  st_g3b4_oQ: '¿Tiene que servir?',
  st_g3b4_oF: 'Para nada.',
  st_g3b4_rU: 'Cerca es donde las cosas se vuelven alguien.',
  st_g3b4_rQ: 'En el jardín, sí.',
  st_g3b4_rF: '@poeira Está bien. Ya lo sabía.',

  st_g3b5_ask: 'Vamos a medir tu luz. ¿Podemos?',
  st_g3b5_oU: 'Pueden. Es pequeña.',
  st_g3b5_oQ: '¿Medirla para qué?',
  st_g3b5_oF: 'Midan la suya.',
  st_g3b5_rU: 'Pequeña. Y más vieja que la nuestra. Qué raro.',
  st_g3b5_rQ: 'Para saber de cuándo es. Y la tuya no es de ahora.',
  st_g3b5_rF: 'La nuestra nació en un solo día. La tuya, no.',

  st_g3b6_1: '~Las luces del jardín rodean a Polvo.',
  st_g3b6_ask: 'El grano se va hoy. Es lo correcto.',
  st_g3b6_oU: 'Entonces me voy con él.',
  st_g3b6_oQ: '¿Correcto para quién?',
  st_g3b6_oF: 'Me da igual.',
  st_g3b6_rU: 'Apenas llegaste.',
  st_g3b6_rQ: 'Para el jardín. Siempre para el jardín.',
  st_g3b6_rF: '@poeira Da igual. Es lo que dicen de mí.',

  st_g3b7_ask: 'Una luz dejó de volar en el nido. A la mitad. Lo vimos.',
  st_g3b7_oU: '¿Por qué?',
  st_g3b7_oQ: '¿Dejó de volar cómo?',
  st_g3b7_oF: 'Perdió, entonces.',
  st_g3b7_rU: 'No sabemos. Solo que se quedó.',
  st_g3b7_rQ: 'Se detuvo. A la mitad. A propósito.',
  st_g3b7_rF: 'Tal vez. O ganó otra cosa.',

  st_g3b8_1: '@cardume ¡Si te quedas con el grano, nos vamos!',
  st_g3b8_ask: 'Si te quedas con él, dejas de ser nuestra.',
  st_g3b8_oU: 'Está bien. Gracias igual.',
  st_g3b8_oQ: '¿Qué pierden ustedes con eso?',
  st_g3b8_oF: 'Nunca fui de ustedes.',
  st_g3b8_rU: '@poeira Te quedaste. Nadie se queda.',
  st_g3b8_rQ: 'Una menos. Y contamos todo.',
  st_g3b8_rF: 'No. Y aun así comiste del jardín.',

  st_g3b9_ask: 'Oíste nuestra historia. ¿Todavía nos juzgas?',
  st_g3b9_oU: 'No. El miedo viejo pesa.',
  st_g3b9_oQ: '¿Cuántas veces pasó?',
  st_g3b9_oF: 'Sí. Se volvieron el portón.',
  st_g3b9_rU: 'Sí. Y pasamos ese miedo adelante.',
  st_g3b9_rQ: 'Una. Una bastó.',
  st_g3b9_rF: 'Nos volvimos. El portón también tiene miedo.',

  st_g3b10_k: 'Colmena',
  st_g3b10_1: '~El enjambre se cierra y se abre como una sola cosa.',
  st_g3b10_2: 'Crees que somos duras.',
  st_g3b10_3: 'Nacimos todas juntas. En el mismo instante.',
  st_g3b10_4: 'Y en medio de nosotras, en ese instante, una luz salió andando.',
  st_g3b10_5: '@faisca ¿Una luz cómo?',
  st_g3b10_6: 'Pequeña. De tu color.',
  st_g3b10_ask: 'Dinos: ¿qué hacemos con quien llega de afuera?',
  st_g3b10_oU: 'Recibirlo. Ustedes también llegaron.',
  st_g3b10_oQ: 'Preguntar el nombre antes de decidir.',
  st_g3b10_oF: 'Cerrar. Es lo que les hicieron.',
  st_g3b10_rU: 'Ve. Llévate el grano. Y no digas que te dejamos.',
  st_g3b10_rQ: 'Nombre. El tuyo ya lo guardamos: la luz que salió andando.',
  st_g3b10_rF: 'Es lo que hacemos. Duele oírlo de afuera.',

  st_g3c_who: 'vela', st_g3c_k: 'Una carta',
  st_g3c_1: '~Entre dos flores de luz, una nota doblada.',
  st_g3c_2: 'Chispa: ninguna luz se enciende sola.',
  st_g3c_3: 'La tuya empezó con la nuestra.',
  st_g3c_4: 'Da las gracias mientras hay tiempo.',
  st_g3c_5: '— V.',
  st_g3c_6: '@faisca ¿"Nuestra"?',
  st_g3c_7: '@poeira Son dos. Lo sabía.',

  st_nest_win_who: 'poeira',
  st_nest_win_1: 'Vuelas bonito.',
  st_nest_win_2: 'Yo no puedo. Pero te vi pasar.',
  st_nest_hint_who: 'poeira',
  st_nest_hint_1: 'Todos pasan por aquí.',
  st_nest_hint_2: 'Nadie se queda nunca.',
  st_nest_stay_who: 'poeira', st_nest_stay_k: 'El Nido',
  st_nest_stay_1: '~Te detienes a mitad de camino. No es caída: es elección.',
  st_nest_stay_2: '~Bajas hasta el nido y te quedas ahí, con Polvo.',
  st_nest_stay_3: 'Perdiste por mí.',
  st_nest_stay_4: '@faisca No perdí. Me quedé.',
  st_nest_stay_5: '~Todo el jardín se apaga despacio. Solo ustedes dos siguen encendidas.'
});
