/* =====================================================================
   ORBO v5.9 — texto da história: Galáxia 4 (Forja · Fornalha · Humildade
   no trabalho). Ver docs/HISTORIA.md §13.
   ===================================================================== */
Object.assign(HR.I18N.pt, {
  st_g4_1: '~A Forja é quente, é barulhenta e é honesta: aqui tudo custa.',
  st_g4_2: '~Os anéis encolhem quando você chega perto. Quem decide cedo, passa.',
  st_g4_3: '~No meio, uma boca acesa mede a sua luz e dá um preço.',
  st_g4_ask: 'Você chega lá em dez anos. Comigo, em um. Quer?',
  st_g4_oU: 'Quero chegar inteira. Mesmo que demore.',
  st_g4_oQ: 'Um ano custa o quê?',
  st_g4_oF: 'Quero. Acende.',
  st_g4_rU: 'Inteira. Todo mundo diz isso antes de sentir pressa.',
  st_g4_rQ: 'Custa calor. O seu.',
  st_g4_rF: 'Boa menina. Chega mais perto.',

  st_g4v3_who: 'iris',
  st_g4v3_1: 'Eu passei pelo fogo. Olha só.',
  st_g4v3_2: '~Ela brilha mais. E você sente menos calor perto dela.',
  st_g4v6_who: 'casco',
  st_g4v6_1: 'Eu também vim aqui uma vez. Com alguém.',
  st_g4v6_2: 'Ela quis o fogo. Eu quis esperar do lado de fora.',
  st_g4v6_3: '~Ele não termina a frase.',
  st_g4v9_who: 'poeira',
  st_g4v9_1: 'Aqui ninguém me vê. É bom.',
  st_g4v9_2: 'Poeira não queima. Poeira já queimou.',

  st_g4b1_ask: 'Tudo aqui tem preço. O que você tem?',
  st_g4b1_oU: 'Tempo.',
  st_g4b1_oQ: 'Você cobra em quê?',
  st_g4b1_oF: 'Vontade.',
  st_g4b1_rU: 'Tempo é a moeda mais cara. E você gasta sem ver.',
  st_g4b1_rQ: 'Em calor. Em tempo. No que você tiver.',
  st_g4b1_rF: 'Vontade eu aceito. Dá liga com fogo.',

  st_g4b2_ask: 'A primeira têmpera dói um pouco. Continua?',
  st_g4b2_oU: 'Continuo, se a dor for do meu esforço.',
  st_g4b2_oQ: 'Essa dor melhora o quê, exatamente?',
  st_g4b2_oF: 'Continuo. Mais forte.',
  st_g4b2_rU: 'Aí é outra coisa. Aí é trabalho.',
  st_g4b2_rQ: 'O que você quiser. Ela não escolhe.',
  st_g4b2_rF: 'Mais forte é a palavra que mais se ouve aqui.',

  st_g4b3_ask: 'Repare na cometa agora.',
  st_g4b3_oU: 'Ela está linda. E longe.',
  st_g4b3_oQ: 'Ela ainda é ela?',
  st_g4b3_oF: 'Ela está na frente.',
  st_g4b3_rU: 'Longe é o preço. Ninguém lê isso na placa.',
  st_g4b3_rQ: 'É. Com menos de alguma coisa.',
  st_g4b3_rF: 'Está. E acelerando.',

  st_g4b4_ask: 'Notou que ela não esquenta mais ninguém?',
  st_g4b4_oU: 'Notei. Isso me assusta.',
  st_g4b4_oQ: 'Dá para voltar atrás?',
  st_g4b4_oF: 'Calor não ganha corrida.',
  st_g4b4_rU: 'Bom susto. Guarde.',
  st_g4b4_rQ: 'Devagar, dá. Ninguém tem paciência para isso.',
  st_g4b4_rF: 'Não ganha. Só serve para ficar.',

  st_g4b5_ask: 'Uma luz se apagou trabalhando. Segue o trabalho?',
  st_g4b5_oU: 'Não. Vamos parar um instante.',
  st_g4b5_oQ: 'Isso acontece sempre?',
  st_g4b5_oF: 'Um a menos.',
  st_g4b5_rU: '…Um instante. Só um.',
  st_g4b5_rQ: 'Toda semana. A gente parou de contar.',
  st_g4b5_rF: 'Foi o que eu disse da primeira vez.',

  st_g4b6_ask: 'Você está lenta hoje.',
  st_g4b6_oU: 'Estou. Ontem eu carreguei alguém.',
  st_g4b6_oQ: 'Lenta comparada com quem?',
  st_g4b6_oF: 'Aumenta o fogo.',
  st_g4b6_rU: 'Carregar pesa. E não aparece no número.',
  st_g4b6_rQ: '…Com a de ontem. Sempre com a de ontem.',
  st_g4b6_rF: 'Aumentado.',

  st_g4b7_ask: 'Última oferta: metade do preço.',
  st_g4b7_oU: 'Não. Obrigada.',
  st_g4b7_oQ: 'Por que insistir tanto comigo?',
  st_g4b7_oF: 'Aceito.',
  st_g4b7_rU: 'Ninguém agradece uma recusa. Você agradeceu.',
  st_g4b7_rQ: 'Porque quem recusa duas vezes nunca mais volta.',
  st_g4b7_rF: 'Então segure firme.',

  st_g4b8_ask: 'Quem recusa sai daqui de mãos vazias.',
  st_g4b8_oU: 'Saio com as mãos minhas.',
  st_g4b8_oQ: 'Vazias, ou só sem as suas coisas?',
  st_g4b8_oF: 'Eu levo o que vim buscar.',
  st_g4b8_rU: '…Isso não estava na conta.',
  st_g4b8_rQ: 'Bem observado. Você me deve essa.',
  st_g4b8_rF: 'Leva. E paga depois, como todo mundo.',

  st_g4b9_ask: 'O velho está falando demais sobre mim.',
  st_g4b9_oU: 'Deixa ele falar. Ele viu coisas.',
  st_g4b9_oQ: 'Por que isso te incomoda tanto?',
  st_g4b9_oF: 'Ele fala demais mesmo.',
  st_g4b9_rU: 'Viu. Foi ele que esperou do lado de fora.',
  st_g4b9_rQ: 'Porque ele lembra de mim antes do fogo.',
  st_g4b9_rF: 'Fala. E está certo.',

  st_g4b10_1: '~A boca abre inteira. Dentro dela cabe uma vida acelerada.',
  st_g4b10_2: 'Eu me acendi primeiro. Olha o que eu virei.',
  st_g4b10_3: 'Forte. Rápida. E sozinha desde então.',
  st_g4b10_ask: 'Me diga: para que serve ficar inteira?',
  st_g4b10_oU: 'Para ainda dar calor quando eu chegar lá.',
  st_g4b10_oQ: 'Ninguém aqui pergunta isso, né?',
  st_g4b10_oF: 'Não serve. Serve chegar primeiro.',
  st_g4b10_rU: '…Sai daqui antes que eu mude de ideia sobre mim.',
  st_g4b10_rQ: '…Não. Ninguém pergunta. Eu já tinha esquecido a pergunta.',
  st_g4b10_rF: '…Então você já é minha. Pode ir.',

  st_g4c_who: 'vela', st_g4c_k: 'Carta de Vela',
  st_g4c_1: '~Preso na brasa de um anel, um bilhete que não queimou.',
  st_g4c_2: 'Faísca: teu pai era o mais lento de nós três.',
  st_g4c_3: 'Foi ele que segurou a porta.',
  st_g4c_4: '— V.'
});

Object.assign(HR.I18N.en, {
  st_g4_1: '~The Forge is hot, loud and honest: everything here has a price.',
  st_g4_2: '~The rings shrink as you get closer. Decide early and you pass.',
  st_g4_3: '~In the middle, a lit mouth measures your light and names a price.',
  st_g4_ask: 'You get there in ten years. With me, in one. Want it?',
  st_g4_oU: 'I want to get there whole. Even if it takes longer.',
  st_g4_oQ: 'What does one year cost?',
  st_g4_oF: 'I want it. Light me up.',
  st_g4_rU: 'Whole. Everyone says that before they feel the hurry.',
  st_g4_rQ: 'It costs warmth. Yours.',
  st_g4_rF: 'Good girl. Come closer.',

  st_g4v3_who: 'iris',
  st_g4v3_1: 'I went through the fire. Look at me.',
  st_g4v3_2: '~She shines more. And you feel less warmth near her.',
  st_g4v6_who: 'casco',
  st_g4v6_1: 'I came here once too. With someone.',
  st_g4v6_2: 'She wanted the fire. I wanted to wait outside.',
  st_g4v6_3: '~He does not finish the sentence.',
  st_g4v9_who: 'poeira',
  st_g4v9_1: 'Nobody sees me here. It is good.',
  st_g4v9_2: 'Dust does not burn. Dust has already burned.',

  st_g4b1_ask: 'Everything here has a price. What do you have?',
  st_g4b1_oU: 'Time.',
  st_g4b1_oQ: 'What do you charge in?',
  st_g4b1_oF: 'Will.',
  st_g4b1_rU: 'Time is the dearest coin. And you spend it without looking.',
  st_g4b1_rQ: 'In warmth. In time. In whatever you have.',
  st_g4b1_rF: 'Will I accept. It binds well with fire.',

  st_g4b2_ask: 'The first tempering hurts a little. Go on?',
  st_g4b2_oU: 'I go on, if the pain is my own effort.',
  st_g4b2_oQ: 'What exactly does that pain improve?',
  st_g4b2_oF: 'Go on. Stronger.',
  st_g4b2_rU: 'Then it is another thing. Then it is work.',
  st_g4b2_rQ: 'Whatever you want. Pain does not choose.',
  st_g4b2_rF: 'Stronger is the most spoken word around here.',

  st_g4b3_ask: 'Take a look at the comet now.',
  st_g4b3_oU: 'She is beautiful. And far away.',
  st_g4b3_oQ: 'Is she still herself?',
  st_g4b3_oF: 'She is ahead of me.',
  st_g4b3_rU: 'Far is the price. Nobody reads that on the sign.',
  st_g4b3_rQ: 'She is. With less of something.',
  st_g4b3_rF: 'She is. And speeding up.',

  st_g4b4_ask: 'Noticed she does not warm anyone anymore?',
  st_g4b4_oU: 'I noticed. It frightens me.',
  st_g4b4_oQ: 'Can it be undone?',
  st_g4b4_oF: 'Warmth does not win races.',
  st_g4b4_rU: 'Good fright. Keep it.',
  st_g4b4_rQ: 'Slowly, yes. Nobody has the patience for it.',
  st_g4b4_rF: 'It does not. It is only good for staying.',

  st_g4b5_ask: 'A light went out working. Keep working?',
  st_g4b5_oU: 'No. Let us stop for a moment.',
  st_g4b5_oQ: 'Does this happen often?',
  st_g4b5_oF: 'One less.',
  st_g4b5_rU: '…A moment. Only one.',
  st_g4b5_rQ: 'Every week. We stopped counting.',
  st_g4b5_rF: 'That is what I said the first time.',

  st_g4b6_ask: 'You are slow today.',
  st_g4b6_oU: 'I am. Yesterday I carried someone.',
  st_g4b6_oQ: 'Slow compared to whom?',
  st_g4b6_oF: 'Turn the fire up.',
  st_g4b6_rU: 'Carrying is heavy. And it never shows in the numbers.',
  st_g4b6_rQ: '…To yesterday. Always to yesterday.',
  st_g4b6_rF: 'Turned up.',

  st_g4b7_ask: 'Final offer: half price.',
  st_g4b7_oU: 'No. Thank you.',
  st_g4b7_oQ: 'Why insist so much with me?',
  st_g4b7_oF: 'I accept.',
  st_g4b7_rU: 'Nobody thanks a refusal. You did.',
  st_g4b7_rQ: 'Because whoever refuses twice never comes back.',
  st_g4b7_rF: 'Then hold on tight.',

  st_g4b8_ask: 'Whoever refuses leaves here empty-handed.',
  st_g4b8_oU: 'I leave with my own hands.',
  st_g4b8_oQ: 'Empty, or just without your things?',
  st_g4b8_oF: 'I take what I came for.',
  st_g4b8_rU: '…That was not in the accounts.',
  st_g4b8_rQ: 'Well spotted. I owe you that one.',
  st_g4b8_rF: 'Take it. And pay later, like everyone.',

  st_g4b9_ask: 'The old hull talks too much about me.',
  st_g4b9_oU: 'Let him talk. He has seen things.',
  st_g4b9_oQ: 'Why does that bother you so much?',
  st_g4b9_oF: 'He does talk too much.',
  st_g4b9_rU: 'He has. He is the one who waited outside.',
  st_g4b9_rQ: 'Because he remembers me before the fire.',
  st_g4b9_rF: 'He does. And he is right.',

  st_g4b10_1: '~The mouth opens wide. A whole sped-up life would fit inside.',
  st_g4b10_2: 'I lit myself first. Look what I became.',
  st_g4b10_3: 'Strong. Fast. And alone ever since.',
  st_g4b10_ask: 'Tell me: what is staying whole good for?',
  st_g4b10_oU: 'For still giving warmth when I get there.',
  st_g4b10_oQ: 'Nobody here asks that, do they?',
  st_g4b10_oF: 'It is good for nothing. Arriving first is.',
  st_g4b10_rU: '…Get out of here before I change my mind about myself.',
  st_g4b10_rQ: '…No. Nobody asks. I had forgotten the question.',
  st_g4b10_rF: '…Then you are already mine. Off you go.',

  st_g4c_who: 'vela', st_g4c_k: 'A letter from Sail',
  st_g4c_1: '~Caught in the embers of a ring, a note that did not burn.',
  st_g4c_2: 'Spark: your father was the slowest of the three of us.',
  st_g4c_3: 'He is the one who held the door.',
  st_g4c_4: '— S.'
});

Object.assign(HR.I18N.es, {
  st_g4_1: '~La Forja es caliente, ruidosa y honesta: aquí todo cuesta.',
  st_g4_2: '~Los anillos encogen cuando te acercas. Quien decide pronto, pasa.',
  st_g4_3: '~En el medio, una boca encendida mide tu luz y pone un precio.',
  st_g4_ask: 'Llegas allá en diez años. Conmigo, en uno. ¿Quieres?',
  st_g4_oU: 'Quiero llegar entera. Aunque tarde.',
  st_g4_oQ: '¿Un año cuesta qué?',
  st_g4_oF: 'Quiero. Enciende.',
  st_g4_rU: 'Entera. Todas lo dicen antes de sentir la prisa.',
  st_g4_rQ: 'Cuesta calor. El tuyo.',
  st_g4_rF: 'Buena chica. Acércate.',

  st_g4v3_who: 'iris',
  st_g4v3_1: 'Pasé por el fuego. Mírame.',
  st_g4v3_2: '~Brilla más. Y cerca de ella sientes menos calor.',
  st_g4v6_who: 'casco',
  st_g4v6_1: 'Yo también vine aquí una vez. Con alguien.',
  st_g4v6_2: 'Ella quiso el fuego. Yo quise esperar afuera.',
  st_g4v6_3: '~No termina la frase.',
  st_g4v9_who: 'poeira',
  st_g4v9_1: 'Aquí nadie me ve. Está bien.',
  st_g4v9_2: 'El polvo no se quema. El polvo ya se quemó.',

  st_g4b1_ask: 'Aquí todo tiene precio. ¿Qué tienes?',
  st_g4b1_oU: 'Tiempo.',
  st_g4b1_oQ: '¿En qué cobras?',
  st_g4b1_oF: 'Ganas.',
  st_g4b1_rU: 'El tiempo es la moneda más cara. Y la gastas sin mirar.',
  st_g4b1_rQ: 'En calor. En tiempo. En lo que tengas.',
  st_g4b1_rF: 'Ganas acepto. Liga bien con el fuego.',

  st_g4b2_ask: 'El primer temple duele un poco. ¿Sigues?',
  st_g4b2_oU: 'Sigo, si el dolor es de mi esfuerzo.',
  st_g4b2_oQ: '¿Ese dolor mejora qué, exactamente?',
  st_g4b2_oF: 'Sigo. Más fuerte.',
  st_g4b2_rU: 'Entonces es otra cosa. Entonces es trabajo.',
  st_g4b2_rQ: 'Lo que tú quieras. El dolor no elige.',
  st_g4b2_rF: 'Más fuerte es la palabra que más se oye aquí.',

  st_g4b3_ask: 'Fíjate en la cometa ahora.',
  st_g4b3_oU: 'Está hermosa. Y lejos.',
  st_g4b3_oQ: '¿Sigue siendo ella?',
  st_g4b3_oF: 'Va adelante.',
  st_g4b3_rU: 'Lejos es el precio. Nadie lo lee en el cartel.',
  st_g4b3_rQ: 'Lo sigue. Con menos de algo.',
  st_g4b3_rF: 'Va. Y acelerando.',

  st_g4b4_ask: '¿Notaste que ya no calienta a nadie?',
  st_g4b4_oU: 'Lo noté. Me asusta.',
  st_g4b4_oQ: '¿Se puede volver atrás?',
  st_g4b4_oF: 'El calor no gana carreras.',
  st_g4b4_rU: 'Buen susto. Guárdalo.',
  st_g4b4_rQ: 'Despacio, sí. Nadie tiene paciencia para eso.',
  st_g4b4_rF: 'No gana. Solo sirve para quedarse.',

  st_g4b5_ask: 'Una luz se apagó trabajando. ¿Sigue el trabajo?',
  st_g4b5_oU: 'No. Paremos un momento.',
  st_g4b5_oQ: '¿Esto pasa siempre?',
  st_g4b5_oF: 'Una menos.',
  st_g4b5_rU: '…Un momento. Solo uno.',
  st_g4b5_rQ: 'Cada semana. Dejamos de contar.',
  st_g4b5_rF: 'Eso dije yo la primera vez.',

  st_g4b6_ask: 'Estás lenta hoy.',
  st_g4b6_oU: 'Lo estoy. Ayer cargué a alguien.',
  st_g4b6_oQ: '¿Lenta comparada con quién?',
  st_g4b6_oF: 'Sube el fuego.',
  st_g4b6_rU: 'Cargar pesa. Y nunca aparece en el número.',
  st_g4b6_rQ: '…Con la de ayer. Siempre con la de ayer.',
  st_g4b6_rF: 'Subido.',

  st_g4b7_ask: 'Última oferta: mitad de precio.',
  st_g4b7_oU: 'No. Gracias.',
  st_g4b7_oQ: '¿Por qué insistes tanto conmigo?',
  st_g4b7_oF: 'Acepto.',
  st_g4b7_rU: 'Nadie agradece un rechazo. Tú sí.',
  st_g4b7_rQ: 'Porque quien rechaza dos veces no vuelve nunca.',
  st_g4b7_rF: 'Entonces agárrate fuerte.',

  st_g4b8_ask: 'Quien rechaza sale de aquí con las manos vacías.',
  st_g4b8_oU: 'Salgo con mis manos.',
  st_g4b8_oQ: '¿Vacías, o solo sin tus cosas?',
  st_g4b8_oF: 'Me llevo lo que vine a buscar.',
  st_g4b8_rU: '…Eso no estaba en la cuenta.',
  st_g4b8_rQ: 'Bien visto. Te debo esa.',
  st_g4b8_rF: 'Llévatelo. Y paga después, como todos.',

  st_g4b9_ask: 'El viejo habla demasiado de mí.',
  st_g4b9_oU: 'Déjalo hablar. Ha visto cosas.',
  st_g4b9_oQ: '¿Por qué te molesta tanto?',
  st_g4b9_oF: 'Habla demasiado, sí.',
  st_g4b9_rU: 'Las ha visto. Él fue el que esperó afuera.',
  st_g4b9_rQ: 'Porque él me recuerda antes del fuego.',
  st_g4b9_rF: 'Habla. Y tiene razón.',

  st_g4b10_1: '~La boca se abre entera. Dentro cabe una vida acelerada.',
  st_g4b10_2: 'Yo me encendí primero. Mira en qué me convertí.',
  st_g4b10_3: 'Fuerte. Rápida. Y sola desde entonces.',
  st_g4b10_ask: 'Dime: ¿para qué sirve quedarse entera?',
  st_g4b10_oU: 'Para todavía dar calor cuando llegue allá.',
  st_g4b10_oQ: 'Nadie aquí pregunta eso, ¿no?',
  st_g4b10_oF: 'No sirve. Sirve llegar primero.',
  st_g4b10_rU: '…Vete antes de que cambie de idea sobre mí.',
  st_g4b10_rQ: '…No. Nadie pregunta. Yo ya había olvidado la pregunta.',
  st_g4b10_rF: '…Entonces ya eres mía. Puedes irte.',

  st_g4c_who: 'vela', st_g4c_k: 'Carta de Vela',
  st_g4c_1: '~Atrapada en la brasa de un anillo, una nota que no se quemó.',
  st_g4c_2: 'Chispa: tu padre era el más lento de los tres.',
  st_g4c_3: 'Fue él quien sostuvo la puerta.',
  st_g4c_4: '— V.'
});
