/* =====================================================================
   ORBO v8 — texto da história: Galáxia 8 (O Eclipse · Eclipse).
   Ver docs/HISTORIA_V7.md e a crítica (secao 9.4).

   A queda continua, mas aqui acende a primeira luz de fundo: a carta.
   O degrau: Casco lê os anéis em voz alta. As marcas são das mãos dos
   dois, e eles seguram aberto desde o começo — desde o Berço.
   O que acontece:
     - o risco fundo é a mão dele; o risco leve, sem terminar, é a dela.
       Por isso a luz atravessa e vira anel, e por isso ela nunca assina;
     - Poeira diz de que lado veio: do que segura leve;
     - Íris esquenta um pouco, nas costas, e conta a verdade que faltava:
       o fim estava vazio porque ela chegou sozinha;
     - o Eclipse é a imagem do final U antes do final U: alguém que ficou
       no meio de duas luzes que se querem, e virou lugar;
     - a carta desfaz o portão: "Não é peso. É abraço, de longe."
   ===================================================================== */
Object.assign(HR.I18N.pt, {
  /* ---------------- entrada ---------------- */
  st_g8_who: 'casco',
  st_g8_k: 'Capítulo 8 · O Eclipse',
  st_g8_1: '~O Abismo é escuro de verdade. A luz vai só até onde você está.',
  st_g8_2: '~Os anéis somem e voltam, como uma coisa que respira devagar.',
  st_g8_3: 'Aqui não se vê, menina. Aqui se lê.',
  st_g8_ask: 'Deixa eu ler para você. Em voz alta. Pode?',
  st_g8_oU: 'Pode. Eu quero ouvir.',
  st_g8_oQ: 'Por que só agora?',
  st_g8_oF: 'Lê logo.',
  st_g8_rU: 'Então segura. É pesado do jeito bom.',
  st_g8_rQ: 'Porque agora eu sei ler os dois lados.',
  st_g8_rF: 'Vou. Devagar. É a única velocidade que letra aceita.',

  /* ---------------- visitas ---------------- */
  st_g8v2_who: 'casco', st_g8v2_k: 'As marcas',
  st_g8v2_1: '~Ele passa o dedo pelo risco. Depois pelo outro lado do anel.',
  st_g8v2_2: 'Deste lado: fundo, firme. Alguém apertou com força.',
  st_g8v2_3: 'Do outro: leve, sem terminar. Como quem escreve com pressa.',
  st_g8v2_4: '@faisca Dois.',
  st_g8v2_5: 'Duas mãos, menina. Uma de cada lado. Em todos os anéis desde o Berço.',
  st_g8v2_6: '@faisca Segurando o quê?',
  st_g8v2_7: 'Aberto.',

  st_g8v5_who: 'poeira', st_g8v5_k: 'De que lado',
  st_g8v5_1: 'Aqui eu enxergo. Sempre enxerguei no escuro.',
  st_g8v5_2: '@faisca Você é daqui?',
  st_g8v5_3: 'Sou de fora. De um lado.',
  st_g8v5_4: '@faisca De qual?',
  st_g8v5_5: 'Do que segura leve.',

  st_g8v8_who: 'iris', st_g8v8_k: 'Esquentando',
  st_g8v8_1: 'Está escuro.',
  st_g8v8_2: '@faisca Está.',
  st_g8v8_3: '…Eu estou esquentando?',
  st_g8v8_4: '@faisca Um pouco.',
  st_g8v8_5: 'Não conta para o velho.',
  st_g8v8_6: '@casco Ouvi.',

  /* ---------------- chefes de sistema ---------------- */
  st_g8b1_ask: 'Você só vê até onde a sua luz chega. É pouco?',
  st_g8b1_oU: 'É o bastante. Um anel por vez.',
  st_g8b1_oQ: 'Dá para ver mais?',
  st_g8b1_oF: 'É. Eu queria ver tudo.',
  st_g8b1_rU: 'Um por vez. Foi assim que o velho leu todos.',
  st_g8b1_rQ: 'Dá. Quando eu passo, por um instante. Depois cubro de novo.',
  st_g8b1_rF: 'Tudo de uma vez cega. Eu cubro por isso.',

  st_g8b2_ask: 'Eu cubro uma luz com a outra. Sabe por quê?',
  st_g8b2_oU: 'Para as duas descansarem.',
  st_g8b2_oQ: 'Elas pediram?',
  st_g8b2_oF: 'Porque você pode.',
  st_g8b2_rU: 'Para uma lembrar da outra. Escuro é onde se lembra.',
  st_g8b2_rQ: 'Nunca pediram. Eu fiquei. Alguém tinha que ficar.',
  st_g8b2_rF: 'Não é poder. É lugar. Alguém tinha que ficar no meio.',

  st_g8b3_1: '@casco Eclipse. Você fica entre. Há quanto tempo?',
  st_g8b3_2: 'Desde que há duas. Antes eu era nada. O meio me fez.',
  st_g8b3_ask: 'O velho pergunta muito. Você pergunta pouco. Por quê?',
  st_g8b3_oU: 'Porque eu escuto.',
  st_g8b3_oQ: 'Eu pergunto pouco?',
  st_g8b3_oF: 'Porque já sei o bastante.',
  st_g8b3_rU: 'Escutar no escuro. É o meu ofício também.',
  st_g8b3_rQ: 'Pergunta. Só não a pergunta que importa.',
  st_g8b3_rF: 'Sabe pouco. O bastante é o que o velho lê.',

  st_g8b4_k: 'O que não foi dito',
  st_g8b4_ask: 'O que você não disse ao velho?',
  st_g8b4_oU: 'Que tenho medo de ele ficar.',
  st_g8b4_oQ: 'Ele precisa saber tudo?',
  st_g8b4_oF: 'Nada. Eu digo tudo.',
  st_g8b4_rU: 'Diga a ele. O escuro guarda mal segredo.',
  st_g8b4_rQ: 'Precisa do que é dele. Isso é dele.',
  st_g8b4_rF: 'Dizer tudo é o que o Eco faz. Você não é ele.',

  st_g8b5_k: 'A letra dele',
  st_g8b5_1: '@casco Este risco é o fundo. O da força. Ele desenha.',
  st_g8b5_2: '@casco A luz atravessa a beira e vira anel. Por isso os anéis brilham.',
  st_g8b5_ask: 'Você já sentiu a mão dele?',
  st_g8b5_oU: 'Sinto. Em todo anel.',
  st_g8b5_oQ: 'Mão se sente?',
  st_g8b5_oF: 'Nunca. Só o risco.',
  st_g8b5_rU: '@casco Todo anel. Ele nunca te soltou. Nem um.',
  st_g8b5_rQ: '@casco Sente. É o que aperta quando você erra e não cai.',
  st_g8b5_rF: '@casco O risco é a mão. Não tem outra.',

  st_g8b6_ask: 'Eu fico entre duas que se querem. Sabe o que é isso?',
  st_g8b6_oU: 'Um abraço no meio.',
  st_g8b6_oQ: 'Elas se querem?',
  st_g8b6_oF: 'Um obstáculo.',
  st_g8b6_rU: 'Ainda não. Está chegando lá.',
  st_g8b6_rQ: 'Desde antes de haver meio. Por isso eu fico.',
  st_g8b6_rF: 'Já me chamaram assim. Dói e não muda nada.',

  st_g8b7_k: 'A letra dela',
  st_g8b7_1: '@casco O outro lado é leve. Não termina. Escreve com pressa, para não esquecer.',
  st_g8b7_2: '@casco Ela não atravessa. Ela é a beira. A beira segura.',
  st_g8b7_3: '@faisca Por isso ela nunca assina.',
  st_g8b7_4: '@casco Por isso.',
  st_g8b7_ask: 'Quem segura leve segura menos?',
  st_g8b7_oU: 'Não. Segura mais tempo.',
  st_g8b7_oQ: 'Leve é menos?',
  st_g8b7_oF: 'Segura menos, sim.',
  st_g8b7_rU: '@casco Isso. Força cansa. Leve dura.',
  st_g8b7_rQ: '@poeira Leve é diferente.',
  st_g8b7_rF: 'Diga isso a quem segura há todo esse tempo sem soltar.',

  st_g8b8_k: 'Sem cara',
  st_g8b8_1: '@eco Faísca. Está escuro. Não vejo cara para usar.',
  st_g8b8_2: '@eco Vou usar a sua.',
  st_g8b8_ask: '@eco Eles seguram desde o começo. Cansados desde o começo. Por quem?',
  st_g8b8_oU: 'Por mim. Eu sei.',
  st_g8b8_oQ: 'Eles disseram cansados?',
  st_g8b8_oF: 'Por eles. Foi escolha.',
  st_g8b8_rU: '@eco Sabe. Então por que continua?',
  st_g8b8_rQ: '@eco Sete anéis, seis, cinco. Precisa dizer?',
  st_g8b8_rF: '@eco Escolha. Que palavra fácil para quem está dentro.',

  st_g8b9_k: 'O que Íris não disse',
  st_g8b9_1: '@iris Faísca. Eu vi o fim. Estava vazio.',
  st_g8b9_2: '@iris Eu não disse tudo. Estava vazio porque eu cheguei sozinha.',
  st_g8b9_3: '@faisca E agora?',
  st_g8b9_4: '@iris Agora estou nas suas costas. Não sei se conta.',
  st_g8b9_ask: 'Ela disse a verdade. Você responde com o quê?',
  st_g8b9_oU: 'Conta. Você é a primeira que carrego.',
  st_g8b9_oQ: 'Vazio de quem?',
  st_g8b9_oF: 'Com o caminho. Vamos.',
  st_g8b9_rU: '@iris Não conta para o velho.',
  st_g8b9_rQ: '@iris De quem eu deixei para trás.',
  st_g8b9_rF: '@iris …Tá. Vamos.',

  /* ---------------- chefe da galáxia ---------------- */
  st_g8b10_k: 'Eclipse',
  st_g8b10_1: '~O Eclipse é uma coisa parada entre duas luzes. Não brilha: cobre.',
  st_g8b10_2: 'Eu fico entre. Faz tanto tempo que virei lugar.',
  st_g8b10_3: 'Quando eu passo, as duas se veem por um instante. Depois eu volto.',
  st_g8b10_4: '@faisca Você escolheu ficar?',
  st_g8b10_5: 'Alguém precisava.',
  st_g8b10_ask: 'Se eu saísse do meio, o que sobrava?',
  st_g8b10_oU: 'As duas se vendo. Vale a pena.',
  st_g8b10_oQ: 'Por que precisa de alguém no meio?',
  st_g8b10_oF: 'Sai. Eu fico no seu lugar.',
  st_g8b10_rU: 'Vale. E custa. Você vai saber quanto.',
  st_g8b10_rQ: 'Porque as duas querem se encostar. E não podem.',
  st_g8b10_rF: 'Você diz isso agora. Diga na porta.',

  /* ---------------- carta ---------------- */
  st_g8c_who: 'vela', st_g8c_k: 'A carta do anel aceso',
  st_g8c_1: '~No fundo do Abismo, um anel inteiro aceso. Dentro dele, um bilhete.',
  st_g8c_2: 'Faísca: seguramos desde o dia em que você chegou.',
  st_g8c_3: 'Não é peso. É abraço, de longe.',
  st_g8c_4: '— V.',
  st_g8c_5: '~Na margem, com a letra leve:',
  st_g8c_6: '@ancora de longe, mas é',
  st_g8c_7: '@faisca Abraço. Eu achei que fosse portão.',
  st_g8c_8: '@casco Nunca foi.'
});

Object.assign(HR.I18N.en, {
  st_g8_who: 'casco',
  st_g8_k: 'Chapter 8 · The Eclipse',
  st_g8_1: '~The Abyss is properly dark. Light reaches only as far as you are.',
  st_g8_2: '~The rings vanish and return, like something breathing slowly.',
  st_g8_3: 'You do not see here, kid. Here you read.',
  st_g8_ask: 'Let me read it to you. Out loud. May I?',
  st_g8_oU: 'You may. I want to hear.',
  st_g8_oQ: 'Why only now?',
  st_g8_oF: 'Read it already.',
  st_g8_rU: 'Then hold on. It is heavy in the good way.',
  st_g8_rQ: 'Because now I can read both sides.',
  st_g8_rF: 'I will. Slowly. It is the only speed letters accept.',

  st_g8v2_who: 'casco', st_g8v2_k: 'The marks',
  st_g8v2_1: '~He runs a finger along the scratch. Then along the other side of the ring.',
  st_g8v2_2: 'This side: deep, firm. Someone gripped hard.',
  st_g8v2_3: 'The other: light, unfinished. Like someone writing in a hurry.',
  st_g8v2_4: '@faisca Two.',
  st_g8v2_5: 'Two hands, kid. One on each side. On every ring since the Cradle.',
  st_g8v2_6: '@faisca Holding what?',
  st_g8v2_7: 'Open.',

  st_g8v5_who: 'poeira', st_g8v5_k: 'Which side',
  st_g8v5_1: 'I can see here. I always could, in the dark.',
  st_g8v5_2: '@faisca Are you from here?',
  st_g8v5_3: 'I am from outside. From one side.',
  st_g8v5_4: '@faisca Which one?',
  st_g8v5_5: 'The one that holds lightly.',

  st_g8v8_who: 'iris', st_g8v8_k: 'Warming',
  st_g8v8_1: 'It is dark.',
  st_g8v8_2: '@faisca It is.',
  st_g8v8_3: '…Am I warming up?',
  st_g8v8_4: '@faisca A little.',
  st_g8v8_5: 'Do not tell the old one.',
  st_g8v8_6: '@casco Heard you.',

  st_g8b1_ask: 'You see only as far as your light goes. Is that little?',
  st_g8b1_oU: 'Enough. One ring at a time.',
  st_g8b1_oQ: 'Can one see further?',
  st_g8b1_oF: 'It is. I wanted to see everything.',
  st_g8b1_rU: 'One at a time. That is how the old one read them all.',
  st_g8b1_rQ: 'One can. When I pass, for an instant. Then I cover again.',
  st_g8b1_rF: 'Everything at once blinds. That is why I cover.',

  st_g8b2_ask: 'I cover one light with the other. Do you know why?',
  st_g8b2_oU: 'So both can rest.',
  st_g8b2_oQ: 'Did they ask you to?',
  st_g8b2_oF: 'Because you can.',
  st_g8b2_rU: 'So one remembers the other. Dark is where remembering happens.',
  st_g8b2_rQ: 'They never asked. I stayed. Someone had to stay.',
  st_g8b2_rF: 'It is not power. It is a place. Someone had to be in the middle.',

  st_g8b3_1: '@casco Eclipse. You stand between. For how long?',
  st_g8b3_2: 'Since there were two. Before that I was nothing. The middle made me.',
  st_g8b3_ask: 'The old one asks a lot. You ask little. Why?',
  st_g8b3_oU: 'Because I listen.',
  st_g8b3_oQ: 'Do I ask little?',
  st_g8b3_oF: 'Because I know enough.',
  st_g8b3_rU: 'Listening in the dark. That is my trade as well.',
  st_g8b3_rQ: 'You ask. Only never the question that matters.',
  st_g8b3_rF: 'You know little. Enough is what the old one reads.',

  st_g8b4_k: 'What went unsaid',
  st_g8b4_ask: 'What have you not told the old one?',
  st_g8b4_oU: 'That I fear he will stay behind.',
  st_g8b4_oQ: 'Does he need to know everything?',
  st_g8b4_oF: 'Nothing. I say everything.',
  st_g8b4_rU: 'Tell him. The dark keeps a secret badly.',
  st_g8b4_rQ: 'He needs what is his. That is his.',
  st_g8b4_rF: 'Saying everything is what the Echo does. You are not him.',

  st_g8b5_k: 'His hand',
  st_g8b5_1: '@casco This scratch is the deep one. The strong one. He draws.',
  st_g8b5_2: '@casco Light crosses the rim and becomes a ring. That is why rings shine.',
  st_g8b5_ask: 'Have you ever felt his hand?',
  st_g8b5_oU: 'I feel it. On every ring.',
  st_g8b5_oQ: 'Can a hand be felt?',
  st_g8b5_oF: 'Never. Only the scratch.',
  st_g8b5_rU: '@casco Every ring. He never let go of you. Not one.',
  st_g8b5_rQ: '@casco It can. It is what grips when you miss and do not fall.',
  st_g8b5_rF: '@casco The scratch is the hand. There is no other.',

  st_g8b6_ask: 'I stand between two that want each other. Do you know what that is?',
  st_g8b6_oU: 'An embrace in the middle.',
  st_g8b6_oQ: 'Do they want each other?',
  st_g8b6_oF: 'An obstacle.',
  st_g8b6_rU: 'Not yet. You are getting there.',
  st_g8b6_rQ: 'Since before there was a middle. That is why I stay.',
  st_g8b6_rF: 'I have been called that. It hurts and changes nothing.',

  st_g8b7_k: 'Her hand',
  st_g8b7_1: '@casco The other side is light. Unfinished. Written in a hurry, so as not to forget.',
  st_g8b7_2: '@casco She does not cross. She is the rim. The rim holds.',
  st_g8b7_3: '@faisca That is why she never signs.',
  st_g8b7_4: '@casco That is why.',
  st_g8b7_ask: 'Does holding lightly mean holding less?',
  st_g8b7_oU: 'No. It means holding longer.',
  st_g8b7_oQ: 'Is light less?',
  st_g8b7_oF: 'Less, yes.',
  st_g8b7_rU: '@casco That is it. Force tires. Light lasts.',
  st_g8b7_rQ: '@poeira Light is different.',
  st_g8b7_rF: 'Say that to the one who has held all this time without letting go.',

  st_g8b8_k: 'No face',
  st_g8b8_1: '@eco Spark. It is dark. I see no face to wear.',
  st_g8b8_2: '@eco I will wear yours.',
  st_g8b8_ask: '@eco They have held since the beginning. Tired since the beginning. For whom?',
  st_g8b8_oU: 'For me. I know.',
  st_g8b8_oQ: 'Did they say they were tired?',
  st_g8b8_oF: 'For themselves. It was a choice.',
  st_g8b8_rU: '@eco You know. So why go on?',
  st_g8b8_rQ: '@eco Seven rings, six, five. Does it need saying?',
  st_g8b8_rF: '@eco Choice. Such an easy word from inside.',

  st_g8b9_k: 'What Iris left out',
  st_g8b9_1: '@iris Spark. I saw the end. It was empty.',
  st_g8b9_2: '@iris I did not say all of it. It was empty because I got there alone.',
  st_g8b9_3: '@faisca And now?',
  st_g8b9_4: '@iris Now I am on your back. I do not know if that counts.',
  st_g8b9_ask: 'She told the truth. What do you answer with?',
  st_g8b9_oU: 'It counts. You are my first.',
  st_g8b9_oQ: 'Empty of whom?',
  st_g8b9_oF: 'With the road. Let us go.',
  st_g8b9_rU: '@iris Do not tell the old one.',
  st_g8b9_rQ: '@iris Of the ones I left behind.',
  st_g8b9_rF: '@iris …Fine. Let us go.',

  st_g8b10_k: 'Eclipse',
  st_g8b10_1: '~The Eclipse is a still thing between two lights. It does not shine: it covers.',
  st_g8b10_2: 'I stand between. So long that I became a place.',
  st_g8b10_3: 'When I move on, the two see each other for an instant. Then I return.',
  st_g8b10_4: '@faisca Did you choose to stay?',
  st_g8b10_5: 'Someone had to.',
  st_g8b10_ask: 'If I left the middle, what would be left?',
  st_g8b10_oU: 'The two seeing each other. Worth it.',
  st_g8b10_oQ: 'Why does it need someone between?',
  st_g8b10_oF: 'Leave. I will take your place.',
  st_g8b10_rU: 'Worth it. And costly. You will learn how much.',
  st_g8b10_rQ: 'Because the two want to touch. And cannot.',
  st_g8b10_rF: 'You say that now. Say it at the door.',

  st_g8c_who: 'vela', st_g8c_k: 'The lit ring',
  st_g8c_1: '~Deep in the Abyss, one whole ring is alight. Inside it, a note.',
  st_g8c_2: 'Spark: we have been holding since the day you arrived.',
  st_g8c_3: 'It is not weight. It is an embrace, from far away.',
  st_g8c_4: '— S.',
  st_g8c_5: '~In the margin, in the light hand:',
  st_g8c_6: '@ancora from far away, but it is',
  st_g8c_7: '@faisca An embrace. I thought it was a gate.',
  st_g8c_8: '@casco It never was.'
});

Object.assign(HR.I18N.es, {
  st_g8_who: 'casco',
  st_g8_k: 'Capítulo 8 · El Eclipse',
  st_g8_1: '~El Abismo es oscuro de verdad. La luz llega solo hasta donde estás.',
  st_g8_2: '~Los aros desaparecen y vuelven, como algo que respira despacio.',
  st_g8_3: 'Aquí no se ve, niña. Aquí se lee.',
  st_g8_ask: 'Déjame leértelo. En voz alta. ¿Puedo?',
  st_g8_oU: 'Puedes. Quiero oírlo.',
  st_g8_oQ: '¿Por qué solo ahora?',
  st_g8_oF: 'Lee ya.',
  st_g8_rU: 'Entonces agárrate. Pesa del modo bueno.',
  st_g8_rQ: 'Porque ahora sé leer los dos lados.',
  st_g8_rF: 'Voy. Despacio. Es la única velocidad que acepta una letra.',

  st_g8v2_who: 'casco', st_g8v2_k: 'Las marcas',
  st_g8v2_1: '~Pasa el dedo por la raya. Después por el otro lado del aro.',
  st_g8v2_2: 'De este lado: honda, firme. Alguien apretó con fuerza.',
  st_g8v2_3: 'Del otro: leve, sin terminar. Como quien escribe con prisa.',
  st_g8v2_4: '@faisca Dos.',
  st_g8v2_5: 'Dos manos, niña. Una de cada lado. En todos los aros desde la Cuna.',
  st_g8v2_6: '@faisca ¿Sujetando qué?',
  st_g8v2_7: 'Abierto.',

  st_g8v5_who: 'poeira', st_g8v5_k: 'De qué lado',
  st_g8v5_1: 'Aquí yo veo. Siempre vi en lo oscuro.',
  st_g8v5_2: '@faisca ¿Eres de aquí?',
  st_g8v5_3: 'Soy de fuera. De un lado.',
  st_g8v5_4: '@faisca ¿De cuál?',
  st_g8v5_5: 'Del que sujeta leve.',

  st_g8v8_who: 'iris', st_g8v8_k: 'Calentando',
  st_g8v8_1: 'Está oscuro.',
  st_g8v8_2: '@faisca Lo está.',
  st_g8v8_3: '…¿Estoy calentando?',
  st_g8v8_4: '@faisca Un poco.',
  st_g8v8_5: 'No se lo cuentes al viejo.',
  st_g8v8_6: '@casco Te oí.',

  st_g8b1_ask: 'Solo ves hasta donde llega tu luz. ¿Es poco?',
  st_g8b1_oU: 'Es bastante. Un aro cada vez.',
  st_g8b1_oQ: '¿Se puede ver más?',
  st_g8b1_oF: 'Lo es. Yo quería verlo todo.',
  st_g8b1_rU: 'Uno cada vez. Así los leyó todos el viejo.',
  st_g8b1_rQ: 'Se puede. Cuando paso, un instante. Luego cubro otra vez.',
  st_g8b1_rF: 'Todo de golpe ciega. Por eso cubro.',

  st_g8b2_ask: 'Cubro una luz con la otra. ¿Sabes por qué?',
  st_g8b2_oU: 'Para que las dos descansen.',
  st_g8b2_oQ: '¿Te lo pidieron?',
  st_g8b2_oF: 'Porque puedes.',
  st_g8b2_rU: 'Para que una recuerde a la otra. Lo oscuro es donde se recuerda.',
  st_g8b2_rQ: 'Nunca lo pidieron. Yo me quedé. Alguien tenía que quedarse.',
  st_g8b2_rF: 'No es poder. Es lugar. Alguien tenía que estar en medio.',

  st_g8b3_1: '@casco Eclipse. Tú estás en medio. ¿Desde cuándo?',
  st_g8b3_2: 'Desde que hay dos. Antes yo no era nada. El medio me hizo.',
  st_g8b3_ask: 'El viejo pregunta mucho. Tú preguntas poco. ¿Por qué?',
  st_g8b3_oU: 'Porque yo escucho.',
  st_g8b3_oQ: '¿Pregunto poco?',
  st_g8b3_oF: 'Porque ya sé bastante.',
  st_g8b3_rU: 'Escuchar en lo oscuro. También es mi oficio.',
  st_g8b3_rQ: 'Preguntas. Solo que nunca la que importa.',
  st_g8b3_rF: 'Sabes poco. Lo bastante es lo que lee el viejo.',

  st_g8b4_k: 'Lo que no se dijo',
  st_g8b4_ask: '¿Qué no le has dicho al viejo?',
  st_g8b4_oU: 'Que temo que él se quede.',
  st_g8b4_oQ: '¿Tiene que saberlo todo?',
  st_g8b4_oF: 'Nada. Yo lo digo todo.',
  st_g8b4_rU: 'Díselo. Lo oscuro guarda mal un secreto.',
  st_g8b4_rQ: 'Necesita lo que es suyo. Eso es suyo.',
  st_g8b4_rF: 'Decirlo todo es lo que hace el Eco. Tú no eres él.',

  st_g8b5_k: 'Su letra',
  st_g8b5_1: '@casco Esta raya es la honda. La de la fuerza. Él dibuja.',
  st_g8b5_2: '@casco La luz atraviesa el borde y se hace aro. Por eso los aros brillan.',
  st_g8b5_ask: '¿Alguna vez sentiste su mano?',
  st_g8b5_oU: 'La siento. En cada aro.',
  st_g8b5_oQ: '¿Una mano se siente?',
  st_g8b5_oF: 'Nunca. Solo la raya.',
  st_g8b5_rU: '@casco Cada aro. Nunca te soltó. Ni uno.',
  st_g8b5_rQ: '@casco Se siente. Es lo que aprieta cuando fallas y no caes.',
  st_g8b5_rF: '@casco La raya es la mano. No hay otra.',

  st_g8b6_ask: 'Estoy entre dos que se quieren. ¿Sabes lo que es eso?',
  st_g8b6_oU: 'Un abrazo en medio.',
  st_g8b6_oQ: '¿Se quieren?',
  st_g8b6_oF: 'Un estorbo.',
  st_g8b6_rU: 'Todavía no. Vas llegando.',
  st_g8b6_rQ: 'Desde antes de que hubiera medio. Por eso me quedo.',
  st_g8b6_rF: 'Ya me llamaron así. Duele y no cambia nada.',

  st_g8b7_k: 'Su letra leve',
  st_g8b7_1: '@casco El otro lado es leve. No termina. Escribe con prisa, para no olvidar.',
  st_g8b7_2: '@casco Ella no atraviesa. Ella es el borde. El borde sujeta.',
  st_g8b7_3: '@faisca Por eso nunca firma.',
  st_g8b7_4: '@casco Por eso.',
  st_g8b7_ask: '¿Quien sujeta leve sujeta menos?',
  st_g8b7_oU: 'No. Sujeta más tiempo.',
  st_g8b7_oQ: '¿Leve es menos?',
  st_g8b7_oF: 'Sujeta menos, sí.',
  st_g8b7_rU: '@casco Eso. La fuerza cansa. Lo leve dura.',
  st_g8b7_rQ: '@poeira Leve es distinto.',
  st_g8b7_rF: 'Díselo a quien sujeta desde hace tanto sin soltar.',

  st_g8b8_k: 'Sin cara',
  st_g8b8_1: '@eco Chispa. Está oscuro. No veo cara que ponerme.',
  st_g8b8_2: '@eco Usaré la tuya.',
  st_g8b8_ask: '@eco Sujetan desde el comienzo. Cansados desde el comienzo. ¿Por quién?',
  st_g8b8_oU: 'Por mí. Lo sé.',
  st_g8b8_oQ: '¿Dijeron que estaban cansados?',
  st_g8b8_oF: 'Por ellos. Fue su elección.',
  st_g8b8_rU: '@eco Lo sabes. ¿Y entonces por qué sigues?',
  st_g8b8_rQ: '@eco Siete aros, seis, cinco. ¿Hace falta decirlo?',
  st_g8b8_rF: '@eco Elección. Qué palabra fácil desde dentro.',

  st_g8b9_k: 'Lo que Iris calló',
  st_g8b9_1: '@iris Chispa. Vi el final. Estaba vacío.',
  st_g8b9_2: '@iris No lo dije todo. Estaba vacío porque llegué sola.',
  st_g8b9_3: '@faisca ¿Y ahora?',
  st_g8b9_4: '@iris Ahora voy en tu espalda. No sé si cuenta.',
  st_g8b9_ask: 'Ella dijo la verdad. ¿Con qué respondes?',
  st_g8b9_oU: 'Cuenta. Eres la primera que llevo.',
  st_g8b9_oQ: '¿Vacío de quién?',
  st_g8b9_oF: 'Con el camino. Vamos.',
  st_g8b9_rU: '@iris No se lo cuentes al viejo.',
  st_g8b9_rQ: '@iris De los que dejé atrás.',
  st_g8b9_rF: '@iris …Vale. Vamos.',

  st_g8b10_k: 'Eclipse',
  st_g8b10_1: '~El Eclipse es algo quieto entre dos luces. No brilla: cubre.',
  st_g8b10_2: 'Estoy en medio. Hace tanto que me volví lugar.',
  st_g8b10_3: 'Cuando paso, las dos se ven un instante. Después vuelvo.',
  st_g8b10_4: '@faisca ¿Elegiste quedarte?',
  st_g8b10_5: 'Alguien hacía falta.',
  st_g8b10_ask: 'Si yo saliera del medio, ¿qué quedaría?',
  st_g8b10_oU: 'Las dos viéndose. Vale la pena.',
  st_g8b10_oQ: '¿Por qué hace falta alguien en medio?',
  st_g8b10_oF: 'Sal. Yo ocupo tu lugar.',
  st_g8b10_rU: 'Vale. Y cuesta. Vas a saber cuánto.',
  st_g8b10_rQ: 'Porque las dos quieren tocarse. Y no pueden.',
  st_g8b10_rF: 'Eso lo dices ahora. Dilo en la puerta.',

  st_g8c_who: 'vela', st_g8c_k: 'El aro encendido',
  st_g8c_1: '~En el fondo del Abismo, un aro entero encendido. Dentro, una nota.',
  st_g8c_2: 'Chispa: sujetamos desde el día en que llegaste.',
  st_g8c_3: 'No es peso. Es abrazo, de lejos.',
  st_g8c_4: '— V.',
  st_g8c_5: '~En el margen, con la letra leve:',
  st_g8c_6: '@ancora de lejos, pero lo es',
  st_g8c_7: '@faisca Abrazo. Yo creía que era portón.',
  st_g8c_8: '@casco Nunca lo fue.'
});
