/* =====================================================================
   ORBO v7 — texto da história: comum + abertura + Galáxia 1 (O Berço).
   Ver docs/HISTORIA_V7.md — a bíblia manda aqui.

   Formato de cada linha:
     "~texto"        narração (sem voz, em itálico)
     "@casco texto"  aquela linha é do Casco (e usa a voz dele)
     "texto"         fala quem a cena define em _who (padrão: o guardião)

   Galáxia 1 — o degrau: TEM UM FORA. E ela dormiu mais que todo mundo.
   A virtude: coragem. O ponto alto: o Guardião que perdeu onze a deixa ir.
   ===================================================================== */
Object.assign(HR.I18N.pt, {
  /* ---------------- comum ---------------- */
  st_cast_faisca: 'Faísca', st_cast_vela: 'Vela', st_cast_ancora: 'Âncora', st_cast_casco: 'Casco',
  st_cast_iris: 'Íris', st_cast_poeira: 'Poeira', st_cast_cardume: 'Cardume', st_cast_porta: 'A Porta',
  st_cast_eco: 'O Eco',
  st_set: 'História', st_set_d: 'Cenas entre as fases. Pular nunca muda o jogo.',
  st_set_full: 'Completa', st_set_short: 'Curta', st_set_off: 'Desligada',
  st_ring_bonus: 'O anel de Vela: +{n} % de moedas no Infinito',

  /* ---------------- abertura ---------------- */
  st_open_k: 'O primeiro giro', st_open_who: 'faisca',
  st_open_1: '~Ela acordou girando. Não sabia fazer outra coisa.',
  st_open_2: '~Não lembrava de nome, nem de rosto, nem de antes.',
  st_open_3: '~Só de uma falta. E a falta tinha formato.',
  st_open_4: '~O lugar também parecia novo. Nada ali tinha sido usado.',
  st_open_5: '~No meio do Berço, uma coisa velha pulsa.',
  st_open_6: '@guardiao Você dormiu mais que todo mundo aqui.',
  st_open_7: '@guardiao Mais do que eu. E eu sou o mais velho.',
  st_open_ask: '@guardiao Você lembra de alguma coisa?',
  st_open_oU: 'De uma falta. Só isso.',
  st_open_oQ: 'Não. Eu deveria lembrar?',
  st_open_oF: 'Não. Mas eu vou lembrar.',
  st_open_rU: '@guardiao É pouco. E é o bastante para começar.',
  st_open_rQ: '@guardiao Deveria. E vai doer quando lembrar.',
  st_open_rF: '@guardiao Todo mundo que acorda diz isso.',

  /* ---------------- entrada ---------------- */
  st_g1_k: 'Capítulo 1 · O Berço',
  st_g1_1: '~O Berço é morno. Os anéis são grandes e vêm devagar.',
  st_g1_2: '~Todo anel tem um risco no mesmo lugar. Como marca de dedo.',
  st_g1_3: '~No meio, a coisa velha pulsa, e tudo volta a dormir.',
  st_g1_ask: 'Dorme. Lá fora não tem nada seu.',
  st_g1_oU: 'Tem uma falta. Eu vou atrás.',
  st_g1_oQ: 'Como sabe o que tem lá fora?',
  st_g1_oF: 'Sai da frente.',
  st_g1_rU: 'Falta é um motivo ruim. E é o único que funciona.',
  st_g1_rQ: '…Não sei. Ninguém voltou para contar.',
  st_g1_rF: 'Ninguém está na sua frente. Eu estou no seu caminho.',

  /* ---------------- visitas ---------------- */
  st_g1v3_who: 'casco',
  st_g1v3_1: '~Um casco amassado gira devagar ao lado do caminho.',
  st_g1v3_2: 'Casco. Sou um casco. O nome pegou.',
  st_g1v3_3: 'Eu leio anéis. Cada risco é uma letra.',
  st_g1v3_4: '@faisca E o que está escrito?',
  st_g1v3_5: 'A mesma coisa em todos. Ainda não sei o quê.',

  st_g1v6_who: 'casco',
  st_g1v6_1: 'Vai doer hoje. Não é castigo: é o caminho ficando sério.',
  st_g1v6_2: 'Quando doer, olhe o próximo anel. Só o próximo.',

  st_g1v9_who: 'casco',
  st_g1v9_1: 'O Guardião perdeu onze. Sabe o nome dos onze.',
  st_g1v9_2: '@faisca Perdeu como?',
  st_g1v9_3: 'Eles saíram. Nenhum voltou.',
  st_g1v9_4: 'Não é portão, menina. É um velho com medo.',

  /* ---------------- chefes dos sistemas ---------------- */
  st_g1b1_ask: 'Para onde você pensa que vai?',
  st_g1b1_oU: 'Para onde a falta aponta.',
  st_g1b1_oQ: 'Para fora. Tem um fora?',
  st_g1b1_oF: 'Para o meio do escuro.',
  st_g1b1_rU: 'Devagar é como se chega longe.',
  st_g1b1_rQ: 'Tem. É por isso que eu não quero que vá.',
  st_g1b1_rF: 'O escuro também já ouviu isso.',

  st_g1b2_ask: 'Quem você acha que desenha esses anéis?',
  st_g1b2_oU: 'Alguém que passou antes de mim.',
  st_g1b2_oQ: 'Eles não aparecem sozinhos?',
  st_g1b2_oF: 'Não importa. Eu passo por eles.',
  st_g1b2_rU: 'Passou, não. Ainda passa. Toda noite.',
  st_g1b2_rQ: 'Nada aqui aparece sozinho. Nem você.',
  st_g1b2_rF: 'Passa. E não lê nenhum.',

  st_g1b3_ask: 'Vai levar esse casco amassado junto?',
  st_g1b3_oU: 'Ele lê os anéis. Vou ouvir.',
  st_g1b3_oQ: 'Ele sabe algo que eu não sei?',
  st_g1b3_oF: 'Ele vai me atrasar.',
  st_g1b3_rU: 'Ouvir. Onze passaram por mim sem ouvir.',
  st_g1b3_rQ: 'Sabe. E vai demorar a dizer.',
  st_g1b3_rF: '@casco Vou. Velho atrasa. E lembra.',

  st_g1b4_ask: 'Sabe por que eu pulso?',
  st_g1b4_oU: 'Para dizer: fica.',
  st_g1b4_oQ: 'Pulsar é medo?',
  st_g1b4_oF: 'Para me atrasar.',
  st_g1b4_rU: 'Fica. É a única palavra que eu tenho.',
  st_g1b4_rQ: 'É. Eu já vi o que sai e não volta.',
  st_g1b4_rF: 'Não. Para você achar o ritmo. Só isso ajuda.',

  st_g1b5_ask: 'Você acha que eu errei em fechar as portas?',
  st_g1b5_oU: 'Não. Você tentou cuidar.',
  st_g1b5_oQ: 'Quantos você perdeu?',
  st_g1b5_oF: 'Acho. Você prendeu todo mundo.',
  st_g1b5_rU: 'Tentei. Tentar não é acertar.',
  st_g1b5_rQ: 'Onze. Eu sei o nome dos onze.',
  st_g1b5_rF: 'Prendi. E perdi mesmo assim.',

  st_g1b6_ask: 'Doeu. Quer voltar a dormir?',
  st_g1b6_oU: 'Doeu. E eu continuo.',
  st_g1b6_oQ: 'Vai doer assim o caminho todo?',
  st_g1b6_oF: 'Não senti nada.',
  st_g1b6_rU: 'Foi o que os onze disseram.',
  st_g1b6_rQ: 'Não. Vai doer de jeitos diferentes.',
  st_g1b6_rF: 'Sentiu. Só não quis contar.',

  st_g1b7_1: '@casco Menina. Olhe o risco deste anel.',
  st_g1b7_2: '@casco Está mais fundo que o dos outros.',
  st_g1b7_ask: '@casco Como se alguém tivesse apertado mais forte.',
  st_g1b7_oU: 'Alguém segurando com cuidado.',
  st_g1b7_oQ: 'Apertado por quem?',
  st_g1b7_oF: 'É só um risco.',
  st_g1b7_rU: '@casco Cuidado. É isso que eu leio também.',
  st_g1b7_rQ: '@casco Se eu soubesse, não leria anéis. Leria gente.',
  st_g1b7_rF: '@casco Nada aqui é só nada.',

  st_g1b8_ask: 'Quando sair, olhe para trás uma vez. Promete?',
  st_g1b8_oU: 'Prometo. Uma vez.',
  st_g1b8_oQ: 'Para ver o quê?',
  st_g1b8_oF: 'Não olho para trás.',
  st_g1b8_rU: 'Uma basta. Os onze não olharam.',
  st_g1b8_rQ: 'Se eu ainda pulso.',
  st_g1b8_rF: 'Então vá ser a décima segunda.',

  st_g1b9_ask: 'O que dizem de mim por aí?',
  st_g1b9_oU: 'Que você segurou todo mundo. Até eu.',
  st_g1b9_oQ: 'Dizem. Isso te incomoda?',
  st_g1b9_oF: 'Que você é um portão.',
  st_g1b9_rU: 'Segurar era tudo que eu sabia fazer.',
  st_g1b9_rQ: 'Incomoda. Ainda assim eu pulso.',
  st_g1b9_rF: 'Portão. É uma palavra honesta.',

  /* ---------------- chefe da galáxia ---------------- */
  st_g1b10_k: 'Guardião Pulsante',
  st_g1b10_1: '~O Guardião não ataca. Ele pulsa, e os anéis pulsam com ele.',
  st_g1b10_2: '~É o jeito dele de dizer: fica.',
  st_g1b10_3: 'Eu segurei todos vocês para que ninguém se perdesse.',
  st_g1b10_4: 'Perdi assim mesmo. Onze.',
  st_g1b10_5: '@faisca Eles não se perderam. Eles saíram.',
  st_g1b10_6: 'Saíram para onde?',
  st_g1b10_ask: 'Me diga por que eu deveria abrir.',
  st_g1b10_oU: 'Porque segurar não é cuidar.',
  st_g1b10_oQ: 'Porque você também quer saber.',
  st_g1b10_oF: 'Porque eu passo com licença ou sem.',
  st_g1b10_rU: 'Então vá. Se achar algum dos onze, diga que eu esperei.',
  st_g1b10_rQ: 'Quero. Há muito tempo. Vá perguntar por mim.',
  st_g1b10_rF: 'Passe. E veja quanto pesa carregar isso sozinha.',

  /* ---------------- a carta ---------------- */
  st_g1c_who: 'vela', st_g1c_k: 'Uma carta',
  st_g1c_1: '~Na saída do Berço, um anel ficou girando sozinho.',
  st_g1c_2: '~Dentro dele, um bilhete.',
  st_g1c_3: 'Faísca: se você está lendo isto, já sabe voar.',
  st_g1c_4: 'Não corra. O caminho foi feito do seu tamanho.',
  st_g1c_5: 'Deixei este anel girando. É para quando sentir falta.',
  st_g1c_6: '— V.',
  st_g1c_7: '@faisca Faísca. Então é assim que me chamam.',
  st_g1c_8: '@faisca E ele sabe da falta.'
});

Object.assign(HR.I18N.en, {
  st_cast_faisca: 'Spark', st_cast_vela: 'Sail', st_cast_ancora: 'Anchor', st_cast_casco: 'Hull',
  st_cast_iris: 'Iris', st_cast_poeira: 'Dust', st_cast_cardume: 'The Shoal', st_cast_porta: 'The Door',
  st_cast_eco: 'The Echo',
  st_set: 'Story', st_set_d: 'Scenes between levels. Skipping never changes the game.',
  st_set_full: 'Full', st_set_short: 'Short', st_set_off: 'Off',
  st_ring_bonus: "Sail's ring: +{n}% coins in Endless",

  st_open_k: 'The first spin', st_open_who: 'faisca',
  st_open_1: '~She woke up spinning. She knew nothing else.',
  st_open_2: '~No name, no face, no before.',
  st_open_3: '~Only an absence. And the absence had a shape.',
  st_open_4: '~The place felt new too. Nothing here had ever been used.',
  st_open_5: '~In the middle of the Cradle, something old pulses.',
  st_open_6: '@guardiao You slept longer than anyone here.',
  st_open_7: '@guardiao Longer than me. And I am the oldest.',
  st_open_ask: '@guardiao Do you remember anything?',
  st_open_oU: 'An absence. That is all.',
  st_open_oQ: 'No. Should I?',
  st_open_oF: 'No. But I will.',
  st_open_rU: '@guardiao It is little. It is enough to start.',
  st_open_rQ: '@guardiao You should. And it will hurt when you do.',
  st_open_rF: '@guardiao Everyone who wakes up says that.',

  st_g1_k: 'Chapter 1 · The Cradle',
  st_g1_1: '~The Cradle is warm. The rings are wide and slow.',
  st_g1_2: '~Every ring has a scratch in the same place. Like a fingermark.',
  st_g1_3: '~In the middle, the old thing pulses, and everything sleeps again.',
  st_g1_ask: 'Sleep. There is nothing of yours out there.',
  st_g1_oU: 'There is an absence. I am going.',
  st_g1_oQ: 'How do you know what is outside?',
  st_g1_oF: 'Get out of the way.',
  st_g1_rU: 'An absence is a bad reason. And the only one that works.',
  st_g1_rQ: '…I do not. Nobody came back to tell.',
  st_g1_rF: 'Nobody is in your way. I am in your path.',

  st_g1v3_who: 'casco',
  st_g1v3_1: '~A dented hull spins slowly beside the path.',
  st_g1v3_2: 'Hull. I am a hull. The name stuck.',
  st_g1v3_3: 'I read rings. Every scratch is a letter.',
  st_g1v3_4: '@faisca And what do they say?',
  st_g1v3_5: 'The same thing, all of them. I do not know what yet.',

  st_g1v6_who: 'casco',
  st_g1v6_1: 'It will hurt today. Not a punishment: the path getting serious.',
  st_g1v6_2: 'When it hurts, look at the next ring. Only the next one.',

  st_g1v9_who: 'casco',
  st_g1v9_1: 'The Guardian lost eleven. He knows all eleven names.',
  st_g1v9_2: '@faisca Lost them how?',
  st_g1v9_3: 'They left. Not one came back.',
  st_g1v9_4: 'He is no gate, girl. He is an old one who is afraid.',

  st_g1b1_ask: 'Where do you think you are going?',
  st_g1b1_oU: 'Where the absence points.',
  st_g1b1_oQ: 'Out. Is there an out?',
  st_g1b1_oF: 'Into the middle of the dark.',
  st_g1b1_rU: 'Slowly is how you get far.',
  st_g1b1_rQ: 'There is. That is why I do not want you to go.',
  st_g1b1_rF: 'The dark has heard that before.',

  st_g1b2_ask: 'Who do you think draws these rings?',
  st_g1b2_oU: 'Someone who came before me.',
  st_g1b2_oQ: 'Do they not just appear?',
  st_g1b2_oF: 'It does not matter. I get through.',
  st_g1b2_rU: 'Came, no. Still comes. Every night.',
  st_g1b2_rQ: 'Nothing here just appears. Not even you.',
  st_g1b2_rF: 'You get through. And read none of them.',

  st_g1b3_ask: 'Are you taking that dented hull along?',
  st_g1b3_oU: 'He reads the rings. I will listen.',
  st_g1b3_oQ: 'Does he know something I do not?',
  st_g1b3_oF: 'He will slow me down.',
  st_g1b3_rU: 'Listening. Eleven passed me without listening.',
  st_g1b3_rQ: 'He does. And he will take long to say it.',
  st_g1b3_rF: '@casco I will. Old ones slow you down. And remember.',

  st_g1b4_ask: 'Do you know why I pulse?',
  st_g1b4_oU: 'To say: stay.',
  st_g1b4_oQ: 'Is pulsing fear?',
  st_g1b4_oF: 'To slow me down.',
  st_g1b4_rU: 'Stay. It is the only word I have.',
  st_g1b4_rQ: 'It is. I have seen what leaves and does not return.',
  st_g1b4_rF: 'No. So you find the rhythm. Nothing else helps.',

  st_g1b5_ask: 'Do you think I was wrong to close the doors?',
  st_g1b5_oU: 'No. You tried to take care.',
  st_g1b5_oQ: 'How many did you lose?',
  st_g1b5_oF: 'I do. You trapped everyone.',
  st_g1b5_rU: 'I tried. Trying is not getting it right.',
  st_g1b5_rQ: 'Eleven. I know all eleven names.',
  st_g1b5_rF: 'I did. And I lost them anyway.',

  st_g1b6_ask: 'It hurt. Want to go back to sleep?',
  st_g1b6_oU: 'It hurt. I keep going.',
  st_g1b6_oQ: 'Will it hurt like this all along?',
  st_g1b6_oF: 'I felt nothing.',
  st_g1b6_rU: 'That is what the eleven said.',
  st_g1b6_rQ: 'No. It will hurt in different ways.',
  st_g1b6_rF: 'You felt it. You just did not want to say.',

  st_g1b7_1: '@casco Girl. Look at the scratch on this ring.',
  st_g1b7_2: '@casco It is deeper than the others.',
  st_g1b7_ask: '@casco As if someone held it tighter.',
  st_g1b7_oU: 'Someone holding with care.',
  st_g1b7_oQ: 'Held by whom?',
  st_g1b7_oF: 'It is just a scratch.',
  st_g1b7_rU: '@casco Care. That is what I read too.',
  st_g1b7_rQ: '@casco If I knew, I would not read rings. I would read people.',
  st_g1b7_rF: '@casco Nothing here is just nothing.',

  st_g1b8_ask: 'When you leave, look back once. Promise?',
  st_g1b8_oU: 'I promise. Once.',
  st_g1b8_oQ: 'To see what?',
  st_g1b8_oF: 'I do not look back.',
  st_g1b8_rU: 'Once is enough. The eleven did not.',
  st_g1b8_rQ: 'Whether I still pulse.',
  st_g1b8_rF: 'Then go and be the twelfth.',

  st_g1b9_ask: 'What do they say about me?',
  st_g1b9_oU: 'That you held everyone. Me too.',
  st_g1b9_oQ: 'They talk. Does that bother you?',
  st_g1b9_oF: 'That you are a gate.',
  st_g1b9_rU: 'Holding was all I knew how to do.',
  st_g1b9_rQ: 'It does. I pulse anyway.',
  st_g1b9_rF: 'A gate. It is an honest word.',

  st_g1b10_k: 'Pulsing Guardian',
  st_g1b10_1: '~The Guardian does not attack. He pulses, and the rings pulse with him.',
  st_g1b10_2: '~It is his way of saying: stay.',
  st_g1b10_3: 'I held all of you so that no one would be lost.',
  st_g1b10_4: 'I lost them anyway. Eleven.',
  st_g1b10_5: '@faisca They were not lost. They left.',
  st_g1b10_6: 'Left for where?',
  st_g1b10_ask: 'Tell me why I should open.',
  st_g1b10_oU: 'Because holding is not caring.',
  st_g1b10_oQ: 'Because you want to know too.',
  st_g1b10_oF: 'Because I pass, allowed or not.',
  st_g1b10_rU: 'Then go. If you find one of the eleven, tell them I waited.',
  st_g1b10_rQ: 'I do. For a long time. Go and ask for me.',
  st_g1b10_rF: 'Pass. And see how heavy it is to carry that alone.',

  st_g1c_who: 'vela', st_g1c_k: 'A letter',
  st_g1c_1: '~At the Cradle exit, a ring was left spinning on its own.',
  st_g1c_2: '~Inside it, a note.',
  st_g1c_3: 'Spark: if you are reading this, you can already fly.',
  st_g1c_4: 'Do not rush. The path was made your size.',
  st_g1c_5: 'I left this ring spinning. It is for when the absence comes.',
  st_g1c_6: '— S.',
  st_g1c_7: '@faisca Spark. So that is what they call me.',
  st_g1c_8: '@faisca And he knows about the absence.'
});

Object.assign(HR.I18N.es, {
  st_cast_faisca: 'Chispa', st_cast_vela: 'Vela', st_cast_ancora: 'Ancla', st_cast_casco: 'Casco',
  st_cast_iris: 'Iris', st_cast_poeira: 'Polvo', st_cast_cardume: 'El Cardumen', st_cast_porta: 'La Puerta',
  st_cast_eco: 'El Eco',
  st_set: 'Historia', st_set_d: 'Escenas entre fases. Saltarlas nunca cambia el juego.',
  st_set_full: 'Completa', st_set_short: 'Corta', st_set_off: 'Apagada',
  st_ring_bonus: 'El anillo de Vela: +{n} % de monedas en Infinito',

  st_open_k: 'El primer giro', st_open_who: 'faisca',
  st_open_1: '~Despertó girando. No sabía hacer otra cosa.',
  st_open_2: '~No recordaba nombre, ni rostro, ni antes.',
  st_open_3: '~Solo una falta. Y la falta tenía forma.',
  st_open_4: '~El lugar también parecía nuevo. Nada allí se había usado.',
  st_open_5: '~En medio de la Cuna, algo viejo late.',
  st_open_6: '@guardiao Dormiste más que nadie aquí.',
  st_open_7: '@guardiao Más que yo. Y yo soy el más viejo.',
  st_open_ask: '@guardiao ¿Recuerdas algo?',
  st_open_oU: 'Una falta. Nada más.',
  st_open_oQ: 'No. ¿Debería?',
  st_open_oF: 'No. Pero voy a recordar.',
  st_open_rU: '@guardiao Es poco. Alcanza para empezar.',
  st_open_rQ: '@guardiao Deberías. Y va a doler cuando lo hagas.',
  st_open_rF: '@guardiao Todos los que despiertan dicen eso.',

  st_g1_k: 'Capítulo 1 · La Cuna',
  st_g1_1: '~La Cuna es tibia. Los anillos son grandes y vienen despacio.',
  st_g1_2: '~Cada anillo tiene una raya en el mismo lugar. Como una huella.',
  st_g1_3: '~En el medio, lo viejo late, y todo vuelve a dormir.',
  st_g1_ask: 'Duerme. Allá afuera no hay nada tuyo.',
  st_g1_oU: 'Hay una falta. Voy a buscarla.',
  st_g1_oQ: '¿Cómo sabes lo que hay afuera?',
  st_g1_oF: 'Quítate del medio.',
  st_g1_rU: 'La falta es mal motivo. Y el único que funciona.',
  st_g1_rQ: '…No lo sé. Nadie volvió a contarlo.',
  st_g1_rF: 'Nadie está delante de ti. Yo estoy en tu camino.',

  st_g1v3_who: 'casco',
  st_g1v3_1: '~Un casco abollado gira despacio junto al camino.',
  st_g1v3_2: 'Casco. Soy un casco. El nombre se quedó.',
  st_g1v3_3: 'Leo anillos. Cada raya es una letra.',
  st_g1v3_4: '@faisca ¿Y qué dicen?',
  st_g1v3_5: 'Lo mismo, todos. Todavía no sé qué.',

  st_g1v6_who: 'casco',
  st_g1v6_1: 'Hoy va a doler. No es castigo: es el camino poniéndose serio.',
  st_g1v6_2: 'Cuando duela, mira el siguiente anillo. Solo el siguiente.',

  st_g1v9_who: 'casco',
  st_g1v9_1: 'El Guardián perdió once. Sabe el nombre de los once.',
  st_g1v9_2: '@faisca ¿Perdió cómo?',
  st_g1v9_3: 'Se fueron. Ninguno volvió.',
  st_g1v9_4: 'No es un portón, niña. Es un viejo con miedo.',

  st_g1b1_ask: '¿Adónde crees que vas?',
  st_g1b1_oU: 'Adonde apunta la falta.',
  st_g1b1_oQ: 'Afuera. ¿Hay un afuera?',
  st_g1b1_oF: 'Al medio de lo oscuro.',
  st_g1b1_rU: 'Despacio es como se llega lejos.',
  st_g1b1_rQ: 'Lo hay. Por eso no quiero que vayas.',
  st_g1b1_rF: 'Lo oscuro también ya oyó eso.',

  st_g1b2_ask: '¿Quién crees que dibuja estos anillos?',
  st_g1b2_oU: 'Alguien que pasó antes que yo.',
  st_g1b2_oQ: '¿No aparecen solos?',
  st_g1b2_oF: 'No importa. Paso por ellos.',
  st_g1b2_rU: 'Pasó, no. Todavía pasa. Cada noche.',
  st_g1b2_rQ: 'Nada aquí aparece solo. Ni tú.',
  st_g1b2_rF: 'Pasas. Y no lees ninguno.',

  st_g1b3_ask: '¿Te llevas a ese casco abollado?',
  st_g1b3_oU: 'Lee los anillos. Voy a escuchar.',
  st_g1b3_oQ: '¿Sabe algo que yo no?',
  st_g1b3_oF: 'Me va a atrasar.',
  st_g1b3_rU: 'Escuchar. Once pasaron por mí sin escuchar.',
  st_g1b3_rQ: 'Sabe. Y tardará en decirlo.',
  st_g1b3_rF: '@casco Voy. Lo viejo atrasa. Y recuerda.',

  st_g1b4_ask: '¿Sabes por qué lato?',
  st_g1b4_oU: 'Para decir: quédate.',
  st_g1b4_oQ: '¿Latir es miedo?',
  st_g1b4_oF: 'Para atrasarme.',
  st_g1b4_rU: 'Quédate. Es la única palabra que tengo.',
  st_g1b4_rQ: 'Lo es. Ya vi lo que sale y no vuelve.',
  st_g1b4_rF: 'No. Para que encuentres el ritmo. Solo eso ayuda.',

  st_g1b5_ask: '¿Crees que me equivoqué al cerrar las puertas?',
  st_g1b5_oU: 'No. Intentaste cuidar.',
  st_g1b5_oQ: '¿Cuántos perdiste?',
  st_g1b5_oF: 'Sí. Encerraste a todos.',
  st_g1b5_rU: 'Lo intenté. Intentar no es acertar.',
  st_g1b5_rQ: 'Once. Sé el nombre de los once.',
  st_g1b5_rF: 'Los encerré. Y los perdí igual.',

  st_g1b6_ask: 'Dolió. ¿Quieres volver a dormir?',
  st_g1b6_oU: 'Dolió. Y sigo.',
  st_g1b6_oQ: '¿Dolerá así todo el camino?',
  st_g1b6_oF: 'No sentí nada.',
  st_g1b6_rU: 'Eso dijeron los once.',
  st_g1b6_rQ: 'No. Dolerá de maneras distintas.',
  st_g1b6_rF: 'Lo sentiste. Solo no quisiste decirlo.',

  st_g1b7_1: '@casco Niña. Mira la raya de este anillo.',
  st_g1b7_2: '@casco Es más honda que la de los otros.',
  st_g1b7_ask: '@casco Como si alguien lo hubiera apretado más fuerte.',
  st_g1b7_oU: 'Alguien sosteniendo con cuidado.',
  st_g1b7_oQ: '¿Apretado por quién?',
  st_g1b7_oF: 'Es solo una raya.',
  st_g1b7_rU: '@casco Cuidado. Eso es lo que leo yo también.',
  st_g1b7_rQ: '@casco Si lo supiera, no leería anillos. Leería gente.',
  st_g1b7_rF: '@casco Nada aquí es solo nada.',

  st_g1b8_ask: 'Cuando salgas, mira atrás una vez. ¿Lo prometes?',
  st_g1b8_oU: 'Lo prometo. Una vez.',
  st_g1b8_oQ: '¿Para ver qué?',
  st_g1b8_oF: 'No miro atrás.',
  st_g1b8_rU: 'Con una basta. Los once no miraron.',
  st_g1b8_rQ: 'Si todavía lato.',
  st_g1b8_rF: 'Entonces ve a ser la duodécima.',

  st_g1b9_ask: '¿Qué dicen de mí por ahí?',
  st_g1b9_oU: 'Que sostuviste a todos. A mí también.',
  st_g1b9_oQ: 'Hablan. ¿Te molesta?',
  st_g1b9_oF: 'Que eres un portón.',
  st_g1b9_rU: 'Sostener era todo lo que sabía hacer.',
  st_g1b9_rQ: 'Me molesta. Aun así, late.',
  st_g1b9_rF: 'Portón. Es una palabra honesta.',

  st_g1b10_k: 'Guardián Pulsante',
  st_g1b10_1: '~El Guardián no ataca. Late, y los anillos laten con él.',
  st_g1b10_2: '~Es su forma de decir: quédate.',
  st_g1b10_3: 'Los sostuve a todos para que nadie se perdiera.',
  st_g1b10_4: 'Los perdí igual. Once.',
  st_g1b10_5: '@faisca No se perdieron. Se fueron.',
  st_g1b10_6: '¿Se fueron adónde?',
  st_g1b10_ask: 'Dime por qué debería abrir.',
  st_g1b10_oU: 'Porque sostener no es cuidar.',
  st_g1b10_oQ: 'Porque tú también quieres saber.',
  st_g1b10_oF: 'Porque paso con permiso o sin él.',
  st_g1b10_rU: 'Entonces ve. Si encuentras a alguno de los once, dile que esperé.',
  st_g1b10_rQ: 'Quiero. Hace mucho. Ve a preguntar por mí.',
  st_g1b10_rF: 'Pasa. Y mira cuánto pesa cargar eso sola.',

  st_g1c_who: 'vela', st_g1c_k: 'Una carta',
  st_g1c_1: '~A la salida de la Cuna, un anillo quedó girando solo.',
  st_g1c_2: '~Adentro, una nota.',
  st_g1c_3: 'Chispa: si estás leyendo esto, ya sabes volar.',
  st_g1c_4: 'No corras. El camino se hizo a tu medida.',
  st_g1c_5: 'Dejé este anillo girando. Es para cuando sientas falta.',
  st_g1c_6: '— V.',
  st_g1c_7: '@faisca Chispa. Entonces así me llaman.',
  st_g1c_8: '@faisca Y él sabe de la falta.'
});
