/* =====================================================================
   ORBO v7 — texto da história: Galáxia 2 (A Maré · Leviatã).
   Ver docs/HISTORIA_V7.md.

   O degrau: o Leviatã conta as marés desde a primeira — e ela é mais velha
   que a primeira maré. O mundo é mais novo que ela.
   A virtude: paciência. O gancho: Casco reconhece a letra das cartas.
   É a mesma dos anéis.
   ===================================================================== */
Object.assign(HR.I18N.pt, {
  /* ---------------- entrada ---------------- */
  st_g2_k: 'Capítulo 2 · A Maré', st_g2_who: 'casco',
  st_g2_1: '~Aqui os anéis sobem e descem como se respirassem.',
  st_g2_2: '~Lá no fundo, uma coisa enorme dorme e faz a maré de todo mundo.',
  st_g2_3: 'Não force. Eles não estão no caminho. Estão na hora deles.',
  st_g2_ask: 'O mar não atrasa, menina. Ele tem hora.',
  st_g2_oU: 'Então eu espero.',
  st_g2_oQ: 'E quem decidiu a hora?',
  st_g2_oF: 'Eu não tenho hora. Tenho pressa.',
  st_g2_rU: 'Então você já entendeu a Maré.',
  st_g2_rQ: 'Quem conta as marés. Ele, lá embaixo.',
  st_g2_rF: 'Pois é. Vamos ver quanto ela te rende.',

  /* ---------------- visitas ---------------- */
  st_g2v3_who: 'iris',
  st_g2v3_1: '~Um risco de luz passa por você, volta e para do seu lado.',
  st_g2v3_2: 'Íris. Cometa. Recordista de três rotas.',
  st_g2v3_3: 'Você voa bonito. Só devagar.',
  st_g2v3_4: '@faisca Eu nem sabia que era corrida.',
  st_g2v3_5: 'Tudo é corrida. Quem chega primeiro vê primeiro.',

  st_g2v6_who: 'casco',
  st_g2v6_1: 'Aquilo lá embaixo não é um bicho. É um relógio.',
  st_g2v6_2: 'Conta as marés desde a primeira.',
  st_g2v6_3: '@faisca Quantas foram?',
  st_g2v6_4: 'Pergunte a ele. Ele gosta que perguntem.',

  st_g2v9_who: 'iris',
  st_g2v9_1: 'Vou na frente. Te espero na Forja.',
  st_g2v9_2: 'Dizem que lá dá para ficar mais rápida.',
  st_g2v9_3: '~Ela some antes de você responder.',
  st_g2v9_4: '@casco Forja. Claro que ela ia querer a Forja.',

  /* ---------------- chefes dos sistemas ---------------- */
  st_g2b1_ask: 'Por que você corre?',
  st_g2b1_oU: 'Uma falta me puxa.',
  st_g2b1_oQ: 'Correr adianta alguma coisa aqui?',
  st_g2b1_oF: 'Porque devagar não chega.',
  st_g2b1_rU: 'Falta não anda. Você anda.',
  st_g2b1_rQ: 'Aqui, não. Aqui tudo tem hora.',
  st_g2b1_rF: 'A maré chega. Nunca correu.',

  st_g2b2_ask: 'Os anéis sobem quando você chega. Acha que é contra você?',
  st_g2b2_oU: 'Não. É a hora deles.',
  st_g2b2_oQ: 'Eles sabem que eu chego?',
  st_g2b2_oF: 'É. E eu passo assim mesmo.',
  st_g2b2_rU: 'Então você já sabe nadar.',
  st_g2b2_rQ: 'Tudo aqui sabe. A maré avisa.',
  st_g2b2_rF: 'Passa. E não vê a maré descer para você.',

  st_g2b3_1: '~Íris aparece do nada, girando em volta de você.',
  st_g2b3_ask: '@iris Aposta corrida até o próximo anel?',
  st_g2b3_oU: 'Aposto. Mas espero a maré.',
  st_g2b3_oQ: 'Apostar o quê?',
  st_g2b3_oF: 'Aposto. E ganho.',
  st_g2b3_rU: '@iris Esperar? Você é esquisita.',
  st_g2b3_rQ: '@iris Quem perde vai atrás. Sempre.',
  st_g2b3_rF: '@iris Veremos. Eu nunca perdi.',

  st_g2b4_ask: 'Uma luzinha vem na maré. Passa por você agora.',
  st_g2b4_oU: 'Eu paro e pego.',
  st_g2b4_oQ: 'Se eu parar, perco o quê?',
  st_g2b4_oF: 'A maré devolve.',
  st_g2b4_rU: 'Perdeu o embalo. Ganhou uma luz.',
  st_g2b4_rQ: 'O embalo. Só isso.',
  st_g2b4_rF: 'Às vezes devolve. Nem sempre inteira.',

  st_g2b5_ask: 'Quer saber o que eu sonho?',
  st_g2b5_oU: 'Quero.',
  st_g2b5_oQ: 'Você sonha?',
  st_g2b5_oF: 'Sonho não move ninguém.',
  st_g2b5_rU: 'Que alguém segura a maré por uma noite. E eu descanso.',
  st_g2b5_rQ: 'Durmo desde a primeira maré. Alguma coisa acontece aqui dentro.',
  st_g2b5_rF: 'Move a maré. Ela é o meu sonho vazando.',

  st_g2b6_ask: 'Se me acordarem, a maré fica reta. E a hora acaba.',
  st_g2b6_oU: 'Então continue dormindo.',
  st_g2b6_oQ: 'Acaba para você ou para todos?',
  st_g2b6_oF: 'Reta é melhor. Acorda.',
  st_g2b6_rU: 'Obrigado. Eu não sabia que dava para escolher.',
  st_g2b6_rQ: 'Para todos. Eu sou a hora de todo mundo.',
  st_g2b6_rF: 'Você não seria a primeira a tentar.',

  st_g2b7_1: '~Íris passou rasgando. A maré inteira desencontrou.',
  st_g2b7_ask: 'Viu o que uma pressa faz?',
  st_g2b7_oU: 'Vi. Eu ajudo a acertar.',
  st_g2b7_oQ: 'Quem vai consertar?',
  st_g2b7_oF: 'Foi acidente. Segue.',
  st_g2b7_rU: 'Ajuda. E fica para trás por isso.',
  st_g2b7_rQ: 'Quem tem tempo. Quase ninguém tem.',
  st_g2b7_rF: 'Segue. A maré leva uma volta para voltar.',

  st_g2b8_ask: 'Quer saber quantas marés eu já contei?',
  st_g2b8_oU: 'Quero. Se você quiser contar.',
  st_g2b8_oQ: 'Desde quando você conta?',
  st_g2b8_oF: 'Conta rápido.',
  st_g2b8_rU: 'Poucas. Muito menos do que parece.',
  st_g2b8_rQ: 'Desde a primeira. Antes dela, nada.',
  st_g2b8_rF: 'Não dá para contar rápido. Isso é a maré.',

  st_g2b9_1: '~O Leviatã abre um olho. É a primeira vez que alguém vê.',
  st_g2b9_ask: 'Você eu não vi entrar. Por onde veio?',
  st_g2b9_oU: 'Não sei. Acordei aqui dentro.',
  st_g2b9_oQ: 'Você dorme. Como veria?',
  st_g2b9_oF: 'Pela frente. Como todo mundo.',
  st_g2b9_rU: 'Acordar não é nascer. Você dormiu muito.',
  st_g2b9_rQ: 'Dormindo eu conto melhor. E não te contei.',
  st_g2b9_rF: 'Pela frente eu vejo todo mundo entrar. Você, não.',

  /* ---------------- chefe da galáxia ---------------- */
  st_g2b10_k: 'Leviatã',
  st_g2b10_1: '~A maré sobe inteira. Não dá para furar: dá para subir junto.',
  st_g2b10_2: 'Todo mundo que passa quer que eu fique quieto.',
  st_g2b10_3: 'Você é a primeira que eu não consigo contar.',
  st_g2b10_4: '@faisca Por quê?',
  st_g2b10_5: 'Porque você já estava aqui antes da primeira maré.',
  st_g2b10_ask: 'O que você quer de mim, faísca?',
  st_g2b10_oU: 'Que você descanse. Passo no seu ritmo.',
  st_g2b10_oQ: 'Saber quem te pôs para contar.',
  st_g2b10_oF: 'Passagem. Abaixa a maré.',
  st_g2b10_rU: 'Descansar. Eu nem sabia que dava para pedir. Vá com a maré.',
  st_g2b10_rQ: 'Quem me pôs, pôs a hora junto. Se achar, não me acorde.',
  st_g2b10_rF: 'Abaixo. E quando voltar, vai ser a nado.',

  /* ---------------- a carta ---------------- */
  st_g2c_who: 'vela', st_g2c_k: 'Uma carta',
  st_g2c_1: '~No alto da maré, preso num anel, um bilhete molhado.',
  st_g2c_2: 'Faísca: eu demorei muito para aprender a esperar.',
  st_g2c_3: 'Você não precisa demorar tanto. Mas espere.',
  st_g2c_4: '— V.',
  st_g2c_5: '@casco Essa letra, menina.',
  st_g2c_6: '@casco É a mesma dos riscos. A mesma dos anéis.'
});

Object.assign(HR.I18N.en, {
  st_g2_k: 'Chapter 2 · The Tide', st_g2_who: 'casco',
  st_g2_1: '~Here the rings rise and fall as if they were breathing.',
  st_g2_2: '~Far below, something huge sleeps and makes everyone’s tide.',
  st_g2_3: 'Do not force it. They are not in the way. They are on their own time.',
  st_g2_ask: 'The sea is never late, girl. It keeps its hour.',
  st_g2_oU: 'Then I wait.',
  st_g2_oQ: 'And who set the hour?',
  st_g2_oF: 'I have no hour. I have hurry.',
  st_g2_rU: 'Then you already understand the Tide.',
  st_g2_rQ: 'The one who counts the tides. Him, down there.',
  st_g2_rF: 'Right. Let us see how far it gets you.',

  st_g2v3_who: 'iris',
  st_g2v3_1: '~A streak of light shoots past you, comes back and stops beside you.',
  st_g2v3_2: 'Iris. Comet. Record holder on three routes.',
  st_g2v3_3: 'You fly beautifully. Just slowly.',
  st_g2v3_4: '@faisca I did not even know it was a race.',
  st_g2v3_5: 'Everything is a race. Whoever gets there first sees first.',

  st_g2v6_who: 'casco',
  st_g2v6_1: 'That thing down there is not an animal. It is a clock.',
  st_g2v6_2: 'It has counted the tides since the first one.',
  st_g2v6_3: '@faisca How many so far?',
  st_g2v6_4: 'Ask him. He likes being asked.',

  st_g2v9_who: 'iris',
  st_g2v9_1: 'I am going ahead. I will wait for you at the Forge.',
  st_g2v9_2: 'They say you can get faster there.',
  st_g2v9_3: '~She is gone before you can answer.',
  st_g2v9_4: '@casco The Forge. Of course she would want the Forge.',

  st_g2b1_ask: 'Why do you run?',
  st_g2b1_oU: 'An absence pulls me.',
  st_g2b1_oQ: 'Does running help here at all?',
  st_g2b1_oF: 'Because slow never arrives.',
  st_g2b1_rU: 'An absence does not move. You do.',
  st_g2b1_rQ: 'Not here. Here everything keeps its hour.',
  st_g2b1_rF: 'The tide arrives. It has never run.',

  st_g2b2_ask: 'The rings rise when you arrive. Do you think it is against you?',
  st_g2b2_oU: 'No. It is their hour.',
  st_g2b2_oQ: 'Do they know I am coming?',
  st_g2b2_oF: 'It is. And I get through anyway.',
  st_g2b2_rU: 'Then you already know how to swim.',
  st_g2b2_rQ: 'Everything here knows. The tide tells.',
  st_g2b2_rF: 'You do. And you never see the tide go down for you.',

  st_g2b3_1: '~Iris appears out of nowhere, circling you.',
  st_g2b3_ask: '@iris Race you to the next ring?',
  st_g2b3_oU: 'Deal. But I wait for the tide.',
  st_g2b3_oQ: 'Race for what?',
  st_g2b3_oF: 'Deal. And I win.',
  st_g2b3_rU: '@iris Wait? You are strange.',
  st_g2b3_rQ: '@iris Whoever loses follows. Always.',
  st_g2b3_rF: '@iris We will see. I have never lost.',

  st_g2b4_ask: 'A little light rides the tide. It is passing you now.',
  st_g2b4_oU: 'I stop and take it.',
  st_g2b4_oQ: 'If I stop, what do I lose?',
  st_g2b4_oF: 'The tide gives it back.',
  st_g2b4_rU: 'You lost your momentum. You gained a light.',
  st_g2b4_rQ: 'Your momentum. Only that.',
  st_g2b4_rF: 'Sometimes it gives back. Not always whole.',

  st_g2b5_ask: 'Want to know what I dream?',
  st_g2b5_oU: 'I do.',
  st_g2b5_oQ: 'You dream?',
  st_g2b5_oF: 'Dreams move no one.',
  st_g2b5_rU: 'That someone holds the tide for one night. And I rest.',
  st_g2b5_rQ: 'I have slept since the first tide. Something happens in here.',
  st_g2b5_rF: 'They move the tide. It is my dream leaking out.',

  st_g2b6_ask: 'If they wake me, the tide goes flat. And the hour ends.',
  st_g2b6_oU: 'Then keep sleeping.',
  st_g2b6_oQ: 'Ends for you or for everyone?',
  st_g2b6_oF: 'Flat is better. Wake up.',
  st_g2b6_rU: 'Thank you. I did not know it could be chosen.',
  st_g2b6_rQ: 'For everyone. I am everyone’s hour.',
  st_g2b6_rF: 'You would not be the first to try.',

  st_g2b7_1: '~Iris tore through. The whole tide fell out of step.',
  st_g2b7_ask: 'See what hurry does?',
  st_g2b7_oU: 'I see. I will help fix it.',
  st_g2b7_oQ: 'Who will fix it?',
  st_g2b7_oF: 'An accident. Move on.',
  st_g2b7_rU: 'Help. And fall behind for it.',
  st_g2b7_rQ: 'Whoever has time. Almost no one does.',
  st_g2b7_rF: 'Move on. The tide takes a full turn to come back.',

  st_g2b8_ask: 'Want to know how many tides I have counted?',
  st_g2b8_oU: 'I do. If you want to tell.',
  st_g2b8_oQ: 'Since when have you counted?',
  st_g2b8_oF: 'Count fast.',
  st_g2b8_rU: 'Few. Far fewer than it seems.',
  st_g2b8_rQ: 'Since the first. Before it, nothing.',
  st_g2b8_rF: 'You cannot count fast. That is the tide.',

  st_g2b9_1: '~The Leviathan opens one eye. No one has ever seen it.',
  st_g2b9_ask: 'You, I never saw come in. Which way did you come?',
  st_g2b9_oU: 'I do not know. I woke here.',
  st_g2b9_oQ: 'You sleep. How would you see?',
  st_g2b9_oF: 'Through the front. Like everyone.',
  st_g2b9_rU: 'Waking is not being born. You slept a long time.',
  st_g2b9_rQ: 'Asleep, I count better. And I did not count you.',
  st_g2b9_rF: 'I see everyone come in through the front. Not you.',

  st_g2b10_k: 'Leviathan',
  st_g2b10_1: '~The whole tide rises. You cannot pierce it: you can rise with it.',
  st_g2b10_2: 'Everyone who passes wants me to keep still.',
  st_g2b10_3: 'You are the first one I cannot count.',
  st_g2b10_4: '@faisca Why?',
  st_g2b10_5: 'Because you were already here before the first tide.',
  st_g2b10_ask: 'What do you want from me, spark?',
  st_g2b10_oU: 'That you rest. I match your pace.',
  st_g2b10_oQ: 'To know who set you counting.',
  st_g2b10_oF: 'Passage. Lower the tide.',
  st_g2b10_rU: 'Rest. I did not know one could ask for that. Go with the tide.',
  st_g2b10_rQ: 'Whoever set me set the hour too. If you find them, do not wake me.',
  st_g2b10_rF: 'I lower it. And when you come back, you will swim.',

  st_g2c_who: 'vela', st_g2c_k: 'A letter',
  st_g2c_1: '~At the top of the tide, caught in a ring, a wet note.',
  st_g2c_2: 'Spark: it took me a long time to learn to wait.',
  st_g2c_3: 'You do not need to take that long. But wait.',
  st_g2c_4: '— S.',
  st_g2c_5: '@casco That handwriting, girl.',
  st_g2c_6: '@casco It is the same as the scratches. The same as the rings.'
});

Object.assign(HR.I18N.es, {
  st_g2_k: 'Capítulo 2 · La Marea', st_g2_who: 'casco',
  st_g2_1: '~Aquí los anillos suben y bajan como si respiraran.',
  st_g2_2: '~Allá en el fondo, algo enorme duerme y hace la marea de todos.',
  st_g2_3: 'No fuerces. No están en el camino. Están en su hora.',
  st_g2_ask: 'El mar no se atrasa, niña. Tiene su hora.',
  st_g2_oU: 'Entonces espero.',
  st_g2_oQ: '¿Y quién decidió la hora?',
  st_g2_oF: 'No tengo hora. Tengo prisa.',
  st_g2_rU: 'Entonces ya entendiste la Marea.',
  st_g2_rQ: 'Quien cuenta las mareas. Él, allá abajo.',
  st_g2_rF: 'Pues sí. Veremos cuánto te rinde.',

  st_g2v3_who: 'iris',
  st_g2v3_1: '~Una raya de luz pasa junto a ti, vuelve y se detiene a tu lado.',
  st_g2v3_2: 'Iris. Cometa. Récord en tres rutas.',
  st_g2v3_3: 'Vuelas bonito. Solo despacio.',
  st_g2v3_4: '@faisca Ni sabía que era carrera.',
  st_g2v3_5: 'Todo es carrera. Quien llega primero ve primero.',

  st_g2v6_who: 'casco',
  st_g2v6_1: 'Eso de allá abajo no es un bicho. Es un reloj.',
  st_g2v6_2: 'Cuenta las mareas desde la primera.',
  st_g2v6_3: '@faisca ¿Cuántas van?',
  st_g2v6_4: 'Pregúntale. Le gusta que le pregunten.',

  st_g2v9_who: 'iris',
  st_g2v9_1: 'Me adelanto. Te espero en la Forja.',
  st_g2v9_2: 'Dicen que allí puedes volverte más rápida.',
  st_g2v9_3: '~Desaparece antes de que respondas.',
  st_g2v9_4: '@casco La Forja. Claro que iba a querer la Forja.',

  st_g2b1_ask: '¿Por qué corres?',
  st_g2b1_oU: 'Una falta me arrastra.',
  st_g2b1_oQ: '¿Correr sirve de algo aquí?',
  st_g2b1_oF: 'Porque despacio no se llega.',
  st_g2b1_rU: 'La falta no camina. Tú caminas.',
  st_g2b1_rQ: 'Aquí, no. Aquí todo tiene su hora.',
  st_g2b1_rF: 'La marea llega. Nunca corrió.',

  st_g2b2_ask: 'Los anillos suben cuando llegas. ¿Crees que es contra ti?',
  st_g2b2_oU: 'No. Es su hora.',
  st_g2b2_oQ: '¿Saben que llego?',
  st_g2b2_oF: 'Sí. Y paso igual.',
  st_g2b2_rU: 'Entonces ya sabes nadar.',
  st_g2b2_rQ: 'Todo aquí sabe. La marea avisa.',
  st_g2b2_rF: 'Pasas. Y no ves la marea bajar para ti.',

  st_g2b3_1: '~Iris aparece de la nada, girando a tu alrededor.',
  st_g2b3_ask: '@iris ¿Una carrera hasta el siguiente anillo?',
  st_g2b3_oU: 'Va. Pero espero la marea.',
  st_g2b3_oQ: '¿Apostando qué?',
  st_g2b3_oF: 'Va. Y gano.',
  st_g2b3_rU: '@iris ¿Esperar? Eres rara.',
  st_g2b3_rQ: '@iris Quien pierde va detrás. Siempre.',
  st_g2b3_rF: '@iris Ya veremos. Nunca perdí.',

  st_g2b4_ask: 'Una lucecita viene en la marea. Pasa junto a ti ahora.',
  st_g2b4_oU: 'Me detengo y la tomo.',
  st_g2b4_oQ: 'Si me detengo, ¿qué pierdo?',
  st_g2b4_oF: 'La marea la devuelve.',
  st_g2b4_rU: 'Perdiste el impulso. Ganaste una luz.',
  st_g2b4_rQ: 'El impulso. Nada más.',
  st_g2b4_rF: 'A veces la devuelve. No siempre entera.',

  st_g2b5_ask: '¿Quieres saber qué sueño?',
  st_g2b5_oU: 'Quiero.',
  st_g2b5_oQ: '¿Tú sueñas?',
  st_g2b5_oF: 'Los sueños no mueven a nadie.',
  st_g2b5_rU: 'Que alguien sostiene la marea una noche. Y yo descanso.',
  st_g2b5_rQ: 'Duermo desde la primera marea. Algo pasa aquí dentro.',
  st_g2b5_rF: 'Mueven la marea. Es mi sueño que se escapa.',

  st_g2b6_ask: 'Si me despiertan, la marea queda plana. Y la hora se acaba.',
  st_g2b6_oU: 'Entonces sigue durmiendo.',
  st_g2b6_oQ: '¿Se acaba para ti o para todos?',
  st_g2b6_oF: 'Plana es mejor. Despierta.',
  st_g2b6_rU: 'Gracias. No sabía que se podía elegir.',
  st_g2b6_rQ: 'Para todos. Soy la hora de todos.',
  st_g2b6_rF: 'No serías la primera en intentarlo.',

  st_g2b7_1: '~Iris pasó rasgando. Toda la marea se desacompasó.',
  st_g2b7_ask: '¿Viste lo que hace una prisa?',
  st_g2b7_oU: 'Lo vi. Ayudo a acomodarla.',
  st_g2b7_oQ: '¿Quién va a arreglarlo?',
  st_g2b7_oF: 'Fue un accidente. Sigue.',
  st_g2b7_rU: 'Ayuda. Y quédate atrás por eso.',
  st_g2b7_rQ: 'Quien tenga tiempo. Casi nadie tiene.',
  st_g2b7_rF: 'Sigue. La marea tarda una vuelta en volver.',

  st_g2b8_ask: '¿Quieres saber cuántas mareas he contado?',
  st_g2b8_oU: 'Quiero. Si quieres contarlo.',
  st_g2b8_oQ: '¿Desde cuándo cuentas?',
  st_g2b8_oF: 'Cuenta rápido.',
  st_g2b8_rU: 'Pocas. Muchas menos de lo que parece.',
  st_g2b8_rQ: 'Desde la primera. Antes de ella, nada.',
  st_g2b8_rF: 'No se puede contar rápido. Eso es la marea.',

  st_g2b9_1: '~El Leviatán abre un ojo. Nadie lo había visto nunca.',
  st_g2b9_ask: 'A ti no te vi entrar. ¿Por dónde viniste?',
  st_g2b9_oU: 'No sé. Desperté aquí dentro.',
  st_g2b9_oQ: 'Tú duermes. ¿Cómo verías?',
  st_g2b9_oF: 'Por el frente. Como todos.',
  st_g2b9_rU: 'Despertar no es nacer. Dormiste mucho.',
  st_g2b9_rQ: 'Dormido cuento mejor. Y a ti no te conté.',
  st_g2b9_rF: 'Por el frente veo entrar a todos. A ti, no.',

  st_g2b10_k: 'Leviatán',
  st_g2b10_1: '~Toda la marea sube. No se puede atravesar: se puede subir con ella.',
  st_g2b10_2: 'Todos los que pasan quieren que me quede quieto.',
  st_g2b10_3: 'Eres la primera a la que no puedo contar.',
  st_g2b10_4: '@faisca ¿Por qué?',
  st_g2b10_5: 'Porque ya estabas aquí antes de la primera marea.',
  st_g2b10_ask: '¿Qué quieres de mí, chispa?',
  st_g2b10_oU: 'Que descanses. Paso a tu ritmo.',
  st_g2b10_oQ: 'Saber quién te puso a contar.',
  st_g2b10_oF: 'Paso. Baja la marea.',
  st_g2b10_rU: 'Descansar. No sabía que se podía pedir. Ve con la marea.',
  st_g2b10_rQ: 'Quien me puso, puso la hora conmigo. Si los encuentras, no me despiertes.',
  st_g2b10_rF: 'La bajo. Y cuando vuelvas, será a nado.',

  st_g2c_who: 'vela', st_g2c_k: 'Una carta',
  st_g2c_1: '~En lo alto de la marea, atrapada en un anillo, una nota mojada.',
  st_g2c_2: 'Chispa: tardé mucho en aprender a esperar.',
  st_g2c_3: 'No necesitas tardar tanto. Pero espera.',
  st_g2c_4: '— V.',
  st_g2c_5: '@casco Esa letra, niña.',
  st_g2c_6: '@casco Es la misma de las rayas. La misma de los anillos.'
});
