/* =====================================================================
   ORBO v8 — texto da história: Galáxia 6 (A Via Láctea · Prisma).
   Ver docs/HISTORIA_V7.md e a crítica (secao 9.2).

   O topo do W: a calmaria. Nenhuma cena de pressão até o fim.
   O degrau: os pequenos do ponto azul chamam a linha de "o começo".
   O que acontece:
     - Íris e o Cardume continuam sumidos, e a ausência é a corrente
       que corre por baixo da galáxia mais bonita do jogo;
     - o Prisma separa tudo que atravessa e vê Faísca em duas cores:
       a premissa dita por um guardião, sem nunca explicar;
     - Casco nota que os anéis estão mais apertados que no Berço —
       o primeiro sintoma, e ele aprende a ler o segundo risco;
     - Faísca diz, pela primeira vez, o que quer: achar a Íris;
     - na carta, as duas letras aparecem juntos na mesma folha.
   ===================================================================== */
Object.assign(HR.I18N.pt, {
  /* ---------------- entrada ---------------- */
  st_g6_who: 'casco',
  st_g6_k: 'Capítulo 6 · A Via Láctea',
  st_g6_1: '~Depois da névoa, o céu abre inteiro. Uma espiral girando devagar, como quem já girou muito.',
  st_g6_2: '~Nada persegue você aqui. Pela primeira vez, sobra tempo.',
  st_g6_3: 'Menina. Olha para cima uma vez. Só uma.',
  st_g6_ask: 'Você sabe parar?',
  st_g6_oU: 'Sei. Nunca tive motivo.',
  st_g6_oQ: 'Parar para quê?',
  st_g6_oF: 'Parar é ficar para trás.',
  st_g6_rU: 'Aqui tem. Está em cima de você.',
  st_g6_rQ: 'Para ver o que passa quando você passa.',
  st_g6_rF: 'Íris dizia isso.',

  /* ---------------- visitas ---------------- */
  st_g6v3_who: 'poeira',
  st_g6v3_1: '~Longe, no fundo de um braço da espiral, um ponto azul. Não brilha: reflete.',
  st_g6v3_2: 'Aquele ali olha para cá.',
  st_g6v3_3: '@faisca Um ponto olha?',
  st_g6v3_4: 'Tem gente dentro. Muito pequena. Não voa. Só olha.',
  st_g6v3_5: '@faisca E o que eles veem?',
  st_g6v3_6: 'Tudo isto. De baixo.',

  st_g6v6_who: 'casco', st_g6v6_k: 'O primeiro sintoma',
  st_g6v6_1: 'Estes anéis estão mais apertados que os do Berço.',
  st_g6v6_2: '@faisca Aqui é só mais difícil.',
  st_g6v6_3: 'Não é o lugar. O risco está mais fundo. Alguém aperta mais.',
  st_g6v6_4: '@faisca Ou segura mais forte.',
  st_g6v6_5: '…Menina. Você está começando a ler.',

  st_g6v9_who: 'casco', st_g6v9_k: 'O que ela quer',
  st_g6v9_1: '@faisca Casco. Para onde o Eco leva quem ele leva?',
  st_g6v9_2: 'Para onde a pessoa já estava indo. Só mais rápido.',
  st_g6v9_3: '@faisca Ela estava indo para o fim. Sozinha.',
  st_g6v9_4: 'Então é lá que você acha. Se for atrás.',
  st_g6v9_5: '@faisca Eu vou atrás. Primeiro ela.',
  st_g6v9_6: 'Ela está no caminho de qualquer jeito. Todo mundo está.',

  /* ---------------- chefes de sistema ---------------- */
  st_g6b1_1: '~O Prisma gira. A luz que entra nele sai repartida.',
  st_g6b1_ask: 'Você entrou inteira. Saiu em duas cores. Sabia?',
  st_g6b1_oU: 'Sabia. Sempre fui duas.',
  st_g6b1_oQ: 'Duas? Quais?',
  st_g6b1_oF: 'Eu sou uma só.',
  st_g6b1_rU: 'Duas que não brigam. Isso é raro.',
  st_g6b1_rQ: 'Uma branca, acesa por dentro. Uma escura, acesa na beira.',
  st_g6b1_rF: 'Uma só não atravessa prisma. Você atravessou.',

  st_g6b2_ask: 'Se eu paro, a luz não separa. Por isso giro. Você para?',
  st_g6b2_oU: 'Paro. Às vezes é preciso.',
  st_g6b2_oQ: 'E se você parasse uma vez?',
  st_g6b2_oF: 'Girar é o que eu faço.',
  st_g6b2_rU: 'Então você vê o que eu nunca vi.',
  st_g6b2_rQ: 'Eu veria a luz inteira. Tenho medo dela.',
  st_g6b2_rF: 'Eu também. Por isso nunca vi nada.',

  st_g6b3_1: '~O Prisma vira devagar. Por um instante o eixo fica aberto para os dois lados.',
  st_g6b3_ask: 'Por que você olha para o ponto azul?',
  st_g6b3_oU: 'Porque ele olha de volta.',
  st_g6b3_oQ: 'Você também vê ele?',
  st_g6b3_oF: 'Não olho. Eu passo.',
  st_g6b3_rU: 'Olhar de volta. Eu nunca fui olhado. Só atravessado.',
  st_g6b3_rQ: 'Vejo em partes. Você vê inteiro. Me conta depois.',
  st_g6b3_rF: '@poeira Você olhou. Eu vi.',

  st_g6b4_1: '~Um trecho inteiro sem nada: poucos anéis, devagar. Só o ponto azul, ao fundo.',
  st_g6b4_ask: 'O que você fez com o silêncio?',
  st_g6b4_oU: 'Olhei. Eles olharam de volta.',
  st_g6b4_oQ: 'Era para fazer alguma coisa?',
  st_g6b4_oF: 'Passei. Rápido.',
  st_g6b4_rU: 'Então você foi vista. Isso muda uma luz.',
  st_g6b4_rQ: 'Não. Era para não fazer. É o mais difícil.',
  st_g6b4_rF: 'Eles não passam. Eles olham. Você ia gostar deles.',

  st_g6b5_k: 'Íris, de longe',
  st_g6b5_ask: 'Uma luz de cometa passou por mim faz pouco. Saiu numa cor só. Amiga sua?',
  st_g6b5_oU: 'Amiga. Ela era de várias.',
  st_g6b5_oQ: 'Uma cor só é ruim?',
  st_g6b5_oF: 'Ela é rápida. Não é minha.',
  st_g6b5_rU: 'Era. O fogo tirou as outras. Sobrou a fria.',
  st_g6b5_rQ: 'Não é ruim. É pouco. Uma cor não esquenta.',
  st_g6b5_rF: 'Ela disse o seu nome quando passou. Numa cor só.',

  st_g6b6_who: 'casco', st_g6b6_k: 'Os dois riscos',
  st_g6b6_1: 'Prisma. Você separa luz. Separa risco?',
  st_g6b6_2: '@guardiao Separo tudo. Este anel tem dois riscos. Um fundo, um leve.',
  st_g6b6_3: 'Dois. Eu só lia um.',
  st_g6b6_ask: '@guardiao Quer ver os dois separados?',
  st_g6b6_oU: 'Quero. Devagar.',
  st_g6b6_oQ: 'Separar não estraga?',
  st_g6b6_oF: 'Mostra logo.',
  st_g6b6_rU: '@guardiao Devagar é como eu faço tudo. Olhe.',
  st_g6b6_rQ: '@guardiao Estraga a pressa. O resto fica.',
  st_g6b6_rF: 'Logo, não. Isso se lê devagar.',

  st_g6b7_k: 'O começo',
  st_g6b7_1: '~Lá embaixo, o ponto azul. Lá em cima, a linha. Do ponto, dá para ver a linha.',
  st_g6b7_2: 'Os pequenos dão nome ao que veem. Aquela linha, eles chamam de começo.',
  st_g6b7_3: '@faisca Começo?',
  st_g6b7_4: 'De tudo isto. Eles contam a partir dela.',
  st_g6b7_ask: 'Se eles chamam de começo, o que foi antes?',
  st_g6b7_oU: 'Dois. Juntos.',
  st_g6b7_oQ: 'Antes existia "antes"?',
  st_g6b7_oF: 'Nada. Começo é começo.',
  st_g6b7_rU: 'Foi o que eles calcularam. De baixo. Sem nunca ter visto.',
  st_g6b7_rQ: 'Eles dizem que não. Eles erram pouco.',
  st_g6b7_rF: 'Eles também diziam isso. Depois olharam melhor.',

  st_g6b8_ask: 'A espiral gira há tanto tempo e ainda é nova. Como pode?',
  st_g6b8_oU: 'Girou muito num tempo curto.',
  st_g6b8_oQ: 'Nova comparada com o quê?',
  st_g6b8_oF: 'Não pode. Uma coisa ou outra.',
  st_g6b8_rU: 'Como você. Dormiu muito, acordou faz pouco.',
  st_g6b8_rQ: 'Com você. Tudo aqui é.',
  st_g6b8_rF: 'Pode. Giro desde o começo, e o começo foi ontem.',

  st_g6b9_who: 'poeira', st_g6b9_k: 'O grão quer ver',
  st_g6b9_1: 'Prisma. Me separa.',
  st_g6b9_2: '@guardiao Não dá. Você não é luz. É o que sobra quando a luz passa.',
  st_g6b9_3: 'Eu sei. Queria ver.',
  st_g6b9_ask: '@guardiao O grão quer ver o que é. Você deixa?',
  st_g6b9_oU: 'Deixo. Ela tem direito.',
  st_g6b9_oQ: 'O que sobra tem cor?',
  st_g6b9_oF: 'Não. Ela é Poeira. Chega.',
  st_g6b9_rU: 'Obrigada. Sou de fora.',
  st_g6b9_rQ: '@guardiao Tem. Escura. Acesa na beira. Não é daqui.',
  st_g6b9_rF: 'Chega. Eu já sabia.',

  /* ---------------- chefe da galáxia ---------------- */
  st_g6b10_k: 'Prisma',
  st_g6b10_1: '~O Prisma gira tão devagar que, pela primeira vez, dá para ver o eixo.',
  st_g6b10_2: 'Eu separei tudo que passou por mim. Nunca vi nada inteiro.',
  st_g6b10_3: 'Você eu separei em duas. As duas ficaram se olhando.',
  st_g6b10_4: '@faisca E depois?',
  st_g6b10_5: 'Voltaram. Eu nunca tinha visto luz voltar.',
  st_g6b10_ask: 'O que se vê quando se para?',
  st_g6b10_oU: 'O ponto azul. E quem olha.',
  st_g6b10_oQ: 'Você nunca parou?',
  st_g6b10_oF: 'Nada. Parar é perder.',
  st_g6b10_rU: 'Então você foi vista. Leve isso. Pesa pouco e dura.',
  st_g6b10_rQ: 'Uma vez. Agora. Para te ver inteira.',
  st_g6b10_rF: 'Você parou. Eu vi de cima. Você mente mal.',

  /* ---------------- carta ---------------- */
  st_g6c_who: 'vela', st_g6c_k: 'A carta do eixo',
  st_g6c_1: '~Preso no eixo do Prisma, um bilhete com duas letras.',
  st_g6c_2: 'Faísca: daqui de fora, essa é a que mais gira.',
  st_g6c_3: 'Ela quis assim. Eu só desenhei.',
  st_g6c_4: '— V.',
  st_g6c_5: '~Na margem, a outra letra, leve:',
  st_g6c_6: '@ancora olha para cima de vez em quando',
  st_g6c_7: '@poeira As duas. Na mesma folha.',
  st_g6c_8: '@casco Então eles ainda escrevem juntos.'
});

Object.assign(HR.I18N.en, {
  st_g6_who: 'casco',
  st_g6_k: 'Chapter 6 · The Milky Way',
  st_g6_1: '~After the mist, the sky opens wide. A spiral turning slowly, like something that has turned a long time.',
  st_g6_2: '~Nothing is chasing you here. For the first time, there is time to spare.',
  st_g6_3: 'Kid. Look up once. Just once.',
  st_g6_ask: 'Do you know how to stop?',
  st_g6_oU: 'I do. Never had a reason.',
  st_g6_oQ: 'Stop for what?',
  st_g6_oF: 'Stopping is falling behind.',
  st_g6_rU: 'Here you do. It is right above you.',
  st_g6_rQ: 'To see what goes by when you go by.',
  st_g6_rF: 'Iris used to say that.',

  st_g6v3_who: 'poeira',
  st_g6v3_1: '~Far off, deep in one arm of the spiral, a blue dot. It does not shine: it reflects.',
  st_g6v3_2: 'That one looks over here.',
  st_g6v3_3: '@faisca A dot looks?',
  st_g6v3_4: 'There are people inside. Very small. They do not fly. They only look.',
  st_g6v3_5: '@faisca And what do they see?',
  st_g6v3_6: 'All of this. From below.',

  st_g6v6_who: 'casco', st_g6v6_k: 'The first symptom',
  st_g6v6_1: 'These rings are tighter than the ones in the Cradle.',
  st_g6v6_2: '@faisca It is just harder here.',
  st_g6v6_3: 'It is not this place. The scratch is deeper. Someone is gripping harder.',
  st_g6v6_4: '@faisca Or holding on tighter.',
  st_g6v6_5: '…Kid. You are starting to read.',

  st_g6v9_who: 'casco', st_g6v9_k: 'What she wants',
  st_g6v9_1: '@faisca Hull. Where does the Echo take the ones it takes?',
  st_g6v9_2: 'Where they were already going. Only faster.',
  st_g6v9_3: '@faisca She was going to the end. Alone.',
  st_g6v9_4: 'Then that is where you find her. If you go.',
  st_g6v9_5: '@faisca I am going. Her first.',
  st_g6v9_6: 'She is on the way regardless. Everyone is.',

  st_g6b1_1: '~The Prism turns. Light that enters it comes out split.',
  st_g6b1_ask: 'You went in whole. You came out in two colors. Did you know?',
  st_g6b1_oU: 'I knew. I was always two.',
  st_g6b1_oQ: 'Two? Which ones?',
  st_g6b1_oF: 'I am only one.',
  st_g6b1_rU: 'Two that do not fight. That is rare.',
  st_g6b1_rQ: 'One white, lit from within. One dark, lit at the rim.',
  st_g6b1_rF: 'Only one does not cross a prism. You crossed.',

  st_g6b2_ask: 'If I stop, light does not split. So I turn. Do you stop?',
  st_g6b2_oU: 'I stop. Sometimes you must.',
  st_g6b2_oQ: 'What if you stopped once?',
  st_g6b2_oF: 'Turning is what I do.',
  st_g6b2_rU: 'Then you see what I never saw.',
  st_g6b2_rQ: 'I would see light whole. I am afraid of it.',
  st_g6b2_rF: 'So am I. That is why I never saw anything.',

  st_g6b3_1: '~The Prism turns slowly. For an instant the axis stands open to both sides.',
  st_g6b3_ask: 'Why do you look at the blue dot?',
  st_g6b3_oU: 'Because it looks back.',
  st_g6b3_oQ: 'Do you see it too?',
  st_g6b3_oF: 'I do not look. I pass.',
  st_g6b3_rU: 'Looking back. I was never looked at. Only crossed.',
  st_g6b3_rQ: 'I see it in parts. You see it whole. Tell me later.',
  st_g6b3_rF: '@poeira You looked. I saw.',

  st_g6b4_1: '~A whole stretch with nothing in it: few rings, slow. Only the blue dot, far behind.',
  st_g6b4_ask: 'What did you do with the silence?',
  st_g6b4_oU: 'I looked. They looked back.',
  st_g6b4_oQ: 'Was I supposed to do something?',
  st_g6b4_oF: 'I passed. Fast.',
  st_g6b4_rU: 'Then you were seen. That changes a light.',
  st_g6b4_rQ: 'No. You were supposed to not. That is the hard part.',
  st_g6b4_rF: 'They do not pass. They look. You would like them.',

  st_g6b5_k: 'Iris, from far away',
  st_g6b5_ask: 'A comet light crossed me a while back. Came out in one color. Friend of yours?',
  st_g6b5_oU: 'A friend. She was many.',
  st_g6b5_oQ: 'Is one color bad?',
  st_g6b5_oF: 'She is fast. She is not mine.',
  st_g6b5_rU: 'She was. The fire took the others. The cold one stayed.',
  st_g6b5_rQ: 'Not bad. Little. One color does not warm.',
  st_g6b5_rF: 'She said your name as she passed. In one color.',

  st_g6b6_who: 'casco', st_g6b6_k: 'The two scratches',
  st_g6b6_1: 'Prism. You split light. Do you split a scratch?',
  st_g6b6_2: '@guardiao I split everything. This ring has two scratches. One deep, one light.',
  st_g6b6_3: 'Two. I only ever read one.',
  st_g6b6_ask: '@guardiao Want to see them apart?',
  st_g6b6_oU: 'I do. Slowly.',
  st_g6b6_oQ: 'Does splitting ruin it?',
  st_g6b6_oF: 'Show me now.',
  st_g6b6_rU: '@guardiao Slowly is how I do everything. Look.',
  st_g6b6_rQ: '@guardiao It ruins the hurry. The rest stays.',
  st_g6b6_rF: 'Not now. This is read slowly.',

  st_g6b7_k: 'The beginning',
  st_g6b7_1: '~Down below, the blue dot. Up above, the line. From the dot, the line can be seen.',
  st_g6b7_2: 'The small ones name what they see. That line, they call the beginning.',
  st_g6b7_3: '@faisca Beginning?',
  st_g6b7_4: 'Of all of this. They count from it.',
  st_g6b7_ask: 'If they call it the beginning, what came before?',
  st_g6b7_oU: 'Two. Together.',
  st_g6b7_oQ: 'Was there a "before"?',
  st_g6b7_oF: 'Nothing. A beginning is a beginning.',
  st_g6b7_rU: 'That is what they worked out. From below. Never having seen.',
  st_g6b7_rQ: 'They say no. They are rarely wrong.',
  st_g6b7_rF: 'They used to say that too. Then they looked closer.',

  st_g6b8_ask: 'The spiral has turned so long and is still new. How?',
  st_g6b8_oU: 'It turned a lot in little time.',
  st_g6b8_oQ: 'New compared to what?',
  st_g6b8_oF: 'It cannot be. One or the other.',
  st_g6b8_rU: 'Like you. Slept a long time, woke up recently.',
  st_g6b8_rQ: 'To you. Everything here is.',
  st_g6b8_rF: 'It can. I have turned since the beginning, and the beginning was yesterday.',

  st_g6b9_who: 'poeira', st_g6b9_k: 'The speck wants to see',
  st_g6b9_1: 'Prism. Split me.',
  st_g6b9_2: '@guardiao I cannot. You are not light. You are what is left when light passes.',
  st_g6b9_3: 'I know. I wanted to see.',
  st_g6b9_ask: '@guardiao The speck wants to see what it is. Do you allow it?',
  st_g6b9_oU: 'I do. She has the right.',
  st_g6b9_oQ: 'Does what is left have a color?',
  st_g6b9_oF: 'No. She is Dust. Enough.',
  st_g6b9_rU: 'Thank you. I am from outside.',
  st_g6b9_rQ: '@guardiao It does. Dark. Lit at the rim. Not from here.',
  st_g6b9_rF: 'Enough. I already knew.',

  st_g6b10_k: 'Prism',
  st_g6b10_1: '~The Prism turns so slowly that, for the first time, the axis can be seen.',
  st_g6b10_2: 'I have split everything that passed through me. I never saw anything whole.',
  st_g6b10_3: 'You I split in two. The two stood looking at each other.',
  st_g6b10_4: '@faisca And then?',
  st_g6b10_5: 'They came back. I had never seen light come back.',
  st_g6b10_ask: 'What do you see when you stop?',
  st_g6b10_oU: 'The blue dot. And who looks.',
  st_g6b10_oQ: 'You never stopped?',
  st_g6b10_oF: 'Nothing. Stopping is losing.',
  st_g6b10_rU: 'Then you were seen. Take that. It weighs little and lasts.',
  st_g6b10_rQ: 'Once. Now. To see you whole.',
  st_g6b10_rF: 'You stopped. I saw from above. You lie badly.',

  st_g6c_who: 'vela', st_g6c_k: 'The letter on the axis',
  st_g6c_1: '~Caught in the axis of the Prism, a note in two hands.',
  st_g6c_2: 'Spark: from out here, that is the one that turns most.',
  st_g6c_3: 'She wanted it that way. I only drew it.',
  st_g6c_4: '— S.',
  st_g6c_5: '~In the margin, the other hand, light:',
  st_g6c_6: '@ancora look up once in a while',
  st_g6c_7: '@poeira Both. On the same page.',
  st_g6c_8: '@casco So they still write together.'
});

Object.assign(HR.I18N.es, {
  st_g6_who: 'casco',
  st_g6_k: 'Capítulo 6 · La Vía Láctea',
  st_g6_1: '~Tras la niebla, el cielo se abre entero. Una espiral girando despacio, como quien ya giró mucho.',
  st_g6_2: '~Nada te persigue aquí. Por primera vez, sobra tiempo.',
  st_g6_3: 'Niña. Mira hacia arriba una vez. Solo una.',
  st_g6_ask: '¿Sabes parar?',
  st_g6_oU: 'Sé. Nunca tuve motivo.',
  st_g6_oQ: '¿Parar para qué?',
  st_g6_oF: 'Parar es quedarse atrás.',
  st_g6_rU: 'Aquí lo hay. Está encima de ti.',
  st_g6_rQ: 'Para ver lo que pasa cuando tú pasas.',
  st_g6_rF: 'Iris decía eso.',

  st_g6v3_who: 'poeira',
  st_g6v3_1: '~Lejos, al fondo de un brazo de la espiral, un punto azul. No brilla: refleja.',
  st_g6v3_2: 'Ese de ahí mira hacia acá.',
  st_g6v3_3: '@faisca ¿Un punto mira?',
  st_g6v3_4: 'Hay gente dentro. Muy pequeña. No vuela. Solo mira.',
  st_g6v3_5: '@faisca ¿Y qué ven?',
  st_g6v3_6: 'Todo esto. Desde abajo.',

  st_g6v6_who: 'casco', st_g6v6_k: 'El primer síntoma',
  st_g6v6_1: 'Estos aros están más apretados que los de la Cuna.',
  st_g6v6_2: '@faisca Aquí solo es más difícil.',
  st_g6v6_3: 'No es el lugar. La raya está más honda. Alguien aprieta más.',
  st_g6v6_4: '@faisca O sujeta más fuerte.',
  st_g6v6_5: '…Niña. Estás empezando a leer.',

  st_g6v9_who: 'casco', st_g6v9_k: 'Lo que ella quiere',
  st_g6v9_1: '@faisca Casco. ¿Adónde lleva el Eco a quien se lleva?',
  st_g6v9_2: 'Adonde ya iba. Solo que más rápido.',
  st_g6v9_3: '@faisca Ella iba hacia el final. Sola.',
  st_g6v9_4: 'Entonces ahí la encuentras. Si vas.',
  st_g6v9_5: '@faisca Voy. Ella primero.',
  st_g6v9_6: 'Está en el camino igual. Todos lo estamos.',

  st_g6b1_1: '~El Prisma gira. La luz que entra en él sale repartida.',
  st_g6b1_ask: 'Entraste entera. Saliste en dos colores. ¿Lo sabías?',
  st_g6b1_oU: 'Lo sabía. Siempre fui dos.',
  st_g6b1_oQ: '¿Dos? ¿Cuáles?',
  st_g6b1_oF: 'Soy una sola.',
  st_g6b1_rU: 'Dos que no pelean. Eso es raro.',
  st_g6b1_rQ: 'Una blanca, encendida por dentro. Una oscura, encendida en el borde.',
  st_g6b1_rF: 'Una sola no atraviesa un prisma. Tú atravesaste.',

  st_g6b2_ask: 'Si paro, la luz no se separa. Por eso giro. ¿Tú paras?',
  st_g6b2_oU: 'Paro. A veces hace falta.',
  st_g6b2_oQ: '¿Y si pararas una vez?',
  st_g6b2_oF: 'Girar es lo que hago.',
  st_g6b2_rU: 'Entonces ves lo que yo nunca vi.',
  st_g6b2_rQ: 'Vería la luz entera. Le tengo miedo.',
  st_g6b2_rF: 'Yo también. Por eso nunca vi nada.',

  st_g6b3_1: '~El Prisma gira despacio. Por un instante el eje queda abierto a los dos lados.',
  st_g6b3_ask: '¿Por qué miras el punto azul?',
  st_g6b3_oU: 'Porque él mira de vuelta.',
  st_g6b3_oQ: '¿Tú también lo ves?',
  st_g6b3_oF: 'No miro. Yo paso.',
  st_g6b3_rU: 'Mirar de vuelta. A mí nunca me miraron. Solo me atravesaron.',
  st_g6b3_rQ: 'Lo veo en partes. Tú lo ves entero. Cuéntame después.',
  st_g6b3_rF: '@poeira Miraste. Yo lo vi.',

  st_g6b4_1: '~Un tramo entero sin nada: pocos aros, despacio. Solo el punto azul, al fondo.',
  st_g6b4_ask: '¿Qué hiciste con el silencio?',
  st_g6b4_oU: 'Miré. Ellos miraron de vuelta.',
  st_g6b4_oQ: '¿Había que hacer algo?',
  st_g6b4_oF: 'Pasé. Rápido.',
  st_g6b4_rU: 'Entonces te vieron. Eso cambia una luz.',
  st_g6b4_rQ: 'No. Había que no hacer. Es lo más difícil.',
  st_g6b4_rF: 'Ellos no pasan. Miran. Te caerían bien.',

  st_g6b5_k: 'Iris, de lejos',
  st_g6b5_ask: 'Una luz de cometa me cruzó hace poco. Salió en un solo color. ¿Amiga tuya?',
  st_g6b5_oU: 'Amiga. Ella era de varios.',
  st_g6b5_oQ: '¿Un solo color es malo?',
  st_g6b5_oF: 'Es rápida. No es mía.',
  st_g6b5_rU: 'Lo era. El fuego se llevó los otros. Quedó el frío.',
  st_g6b5_rQ: 'Malo no. Poco. Un color no calienta.',
  st_g6b5_rF: 'Dijo tu nombre al pasar. En un solo color.',

  st_g6b6_who: 'casco', st_g6b6_k: 'Las dos rayas',
  st_g6b6_1: 'Prisma. Separas luz. ¿Separas una raya?',
  st_g6b6_2: '@guardiao Separo todo. Este aro tiene dos rayas. Una honda, una leve.',
  st_g6b6_3: 'Dos. Yo solo leía una.',
  st_g6b6_ask: '@guardiao ¿Quieres verlas separadas?',
  st_g6b6_oU: 'Quiero. Despacio.',
  st_g6b6_oQ: '¿Separar no lo estropea?',
  st_g6b6_oF: 'Muéstralo ya.',
  st_g6b6_rU: '@guardiao Despacio es como hago todo. Mira.',
  st_g6b6_rQ: '@guardiao Estropea la prisa. Lo demás queda.',
  st_g6b6_rF: 'Ya, no. Esto se lee despacio.',

  st_g6b7_k: 'El comienzo',
  st_g6b7_1: '~Allá abajo, el punto azul. Allá arriba, la línea. Desde el punto se ve la línea.',
  st_g6b7_2: 'Los pequeños nombran lo que ven. A esa línea la llaman comienzo.',
  st_g6b7_3: '@faisca ¿Comienzo?',
  st_g6b7_4: 'De todo esto. Cuentan a partir de ella.',
  st_g6b7_ask: 'Si lo llaman comienzo, ¿qué hubo antes?',
  st_g6b7_oU: 'Dos. Juntos.',
  st_g6b7_oQ: '¿Existía un "antes"?',
  st_g6b7_oF: 'Nada. Comienzo es comienzo.',
  st_g6b7_rU: 'Eso calcularon. Desde abajo. Sin haberlo visto nunca.',
  st_g6b7_rQ: 'Dicen que no. Se equivocan poco.',
  st_g6b7_rF: 'Ellos también lo decían. Luego miraron mejor.',

  st_g6b8_ask: 'La espiral gira hace tanto y sigue siendo nueva. ¿Cómo puede ser?',
  st_g6b8_oU: 'Giró mucho en poco tiempo.',
  st_g6b8_oQ: '¿Nueva comparada con qué?',
  st_g6b8_oF: 'No puede. Una cosa u otra.',
  st_g6b8_rU: 'Como tú. Dormiste mucho, despertaste hace poco.',
  st_g6b8_rQ: 'Contigo. Todo aquí lo es.',
  st_g6b8_rF: 'Puede. Giro desde el comienzo, y el comienzo fue ayer.',

  st_g6b9_who: 'poeira', st_g6b9_k: 'El grano quiere ver',
  st_g6b9_1: 'Prisma. Sepárame.',
  st_g6b9_2: '@guardiao No puedo. No eres luz. Eres lo que queda cuando la luz pasa.',
  st_g6b9_3: 'Lo sé. Quería ver.',
  st_g6b9_ask: '@guardiao El grano quiere ver lo que es. ¿Lo permites?',
  st_g6b9_oU: 'Lo permito. Tiene derecho.',
  st_g6b9_oQ: '¿Lo que queda tiene color?',
  st_g6b9_oF: 'No. Ella es Polvo. Basta.',
  st_g6b9_rU: 'Gracias. Soy de fuera.',
  st_g6b9_rQ: '@guardiao Lo tiene. Oscuro. Encendido en el borde. No es de aquí.',
  st_g6b9_rF: 'Basta. Ya lo sabía.',

  st_g6b10_k: 'Prisma',
  st_g6b10_1: '~El Prisma gira tan despacio que, por primera vez, se ve el eje.',
  st_g6b10_2: 'Separé todo lo que pasó por mí. Nunca vi nada entero.',
  st_g6b10_3: 'A ti te separé en dos. Las dos se quedaron mirándose.',
  st_g6b10_4: '@faisca ¿Y después?',
  st_g6b10_5: 'Volvieron. Nunca había visto volver a la luz.',
  st_g6b10_ask: '¿Qué se ve cuando uno para?',
  st_g6b10_oU: 'El punto azul. Y quien mira.',
  st_g6b10_oQ: '¿Tú nunca paraste?',
  st_g6b10_oF: 'Nada. Parar es perder.',
  st_g6b10_rU: 'Entonces te vieron. Llévate eso. Pesa poco y dura.',
  st_g6b10_rQ: 'Una vez. Ahora. Para verte entera.',
  st_g6b10_rF: 'Paraste. Lo vi desde arriba. Mientes mal.',

  st_g6c_who: 'vela', st_g6c_k: 'La carta del eje',
  st_g6c_1: '~Atrapada en el eje del Prisma, una nota con dos letras.',
  st_g6c_2: 'Chispa: desde aquí fuera, esa es la que más gira.',
  st_g6c_3: 'Ella la quiso así. Yo solo la dibujé.',
  st_g6c_4: '— V.',
  st_g6c_5: '~En el margen, la otra letra, leve:',
  st_g6c_6: '@ancora mira hacia arriba de vez en cuando',
  st_g6c_7: '@poeira Las dos. En la misma hoja.',
  st_g6c_8: '@casco Entonces todavía escriben juntos.'
});
