/* =====================================================================
   ORBO v7 — texto da história: Galáxia 4 (A Forja · Fornalha).
   Ver docs/HISTORIA_V7.md.

   O degrau: o instante tinha um NOME PEQUENO. Igual ao dela.
   A virtude: o preço (esforço honesto contra atalho).
   O que acontece: Íris aceita o fogo e volta rápida e gelada. A Fornalha é
   Brasa — a companheira que Casco deixou entrar e esperou do lado de fora.
   Ela reconhece o nome dele. E reconhece faísca, porque viu a primeira.
   ===================================================================== */
Object.assign(HR.I18N.pt, {
  /* ---------------- entrada ---------------- */
  st_g4_k: 'Capítulo 4 · A Forja',
  st_g4_1: '~A Forja é quente, barulhenta e honesta: aqui tudo custa.',
  st_g4_2: '~Os anéis encolhem quando você chega perto. Quem decide cedo, passa.',
  st_g4_3: '~No meio, uma boca acesa mede a sua luz e dá um preço.',
  st_g4_ask: 'Você chega lá em dez voltas. Comigo, em uma. Quer?',
  st_g4_oU: 'Quero chegar inteira. Mesmo devagar.',
  st_g4_oQ: 'Uma volta custa o quê?',
  st_g4_oF: 'Quero. Acende.',
  st_g4_rU: 'Inteira. Todas dizem isso antes da pressa.',
  st_g4_rQ: 'Calor. O seu.',
  st_g4_rF: 'Boa menina. Chega mais perto.',

  /* ---------------- visitas ---------------- */
  st_g4v3_who: 'iris',
  st_g4v3_1: '~Íris passa rasgando. Brilha o dobro. E nada esquenta perto dela.',
  st_g4v3_2: 'Eu passei pelo fogo. Olha só.',
  st_g4v3_3: '@faisca Você está gelada.',
  st_g4v3_4: 'Estou rápida. É diferente.',

  st_g4v6_who: 'casco',
  st_g4v6_1: 'Eu vim aqui uma vez. Com alguém.',
  st_g4v6_2: 'Ela quis o fogo. Eu quis esperar do lado de fora.',
  st_g4v6_3: '~Ele não termina a frase.',

  st_g4v9_who: 'poeira',
  st_g4v9_1: 'Aqui ninguém me vê. É bom.',
  st_g4v9_2: 'Poeira não queima. Poeira já queimou.',
  st_g4v9_3: '@faisca Queimou quando?',
  st_g4v9_4: 'Antes. Bem antes de tudo.',

  /* ---------------- chefes dos sistemas ---------------- */
  st_g4b1_ask: 'Tudo aqui tem preço. O que você tem?',
  st_g4b1_oU: 'Tempo.',
  st_g4b1_oQ: 'Você cobra em quê?',
  st_g4b1_oF: 'Vontade.',
  st_g4b1_rU: 'Tempo é a moeda mais cara. E você gasta sem ver.',
  st_g4b1_rQ: 'Em calor. Em tempo. No que você tiver.',
  st_g4b1_rF: 'Vontade eu aceito. Dá liga com fogo.',

  st_g4b2_ask: 'A primeira têmpera dói um pouco. Continua?',
  st_g4b2_oU: 'Continuo, se a dor for minha.',
  st_g4b2_oQ: 'Essa dor melhora o quê?',
  st_g4b2_oF: 'Continuo. Mais forte.',
  st_g4b2_rU: 'Aí é outra coisa. Aí é trabalho.',
  st_g4b2_rQ: 'O que você quiser. Ela não escolhe.',
  st_g4b2_rF: 'Mais forte é a palavra que mais se ouve aqui.',

  st_g4b3_1: '~Íris dá uma volta inteira na Forja enquanto você passa um anel.',
  st_g4b3_ask: 'Repare na cometa agora.',
  st_g4b3_oU: 'Ela está linda. E longe.',
  st_g4b3_oQ: 'Ela ainda é ela?',
  st_g4b3_oF: 'Ela está na frente.',
  st_g4b3_rU: 'Longe é o preço. Ninguém lê isso na placa.',
  st_g4b3_rQ: 'É. Com menos de alguma coisa.',
  st_g4b3_rF: '@iris Estou. E você devia vir também.',

  st_g4b4_ask: 'Notou que ela não esquenta mais ninguém?',
  st_g4b4_oU: 'Notei. Isso me assusta.',
  st_g4b4_oQ: 'Dá para voltar atrás?',
  st_g4b4_oF: 'Calor não ganha corrida.',
  st_g4b4_rU: 'Bom susto. Guarde.',
  st_g4b4_rQ: 'Devagar, dá. Ninguém tem paciência.',
  st_g4b4_rF: 'Não ganha. Só serve para ficar.',

  st_g4b5_ask: 'Uma luz se apagou trabalhando. Segue o trabalho?',
  st_g4b5_oU: 'Não. Vamos parar um instante.',
  st_g4b5_oQ: 'Isso acontece sempre?',
  st_g4b5_oF: 'Uma a menos.',
  st_g4b5_rU: 'Um instante. Só um.',
  st_g4b5_rQ: 'Toda semana. A gente parou de contar.',
  st_g4b5_rF: 'Foi o que eu disse da primeira vez.',

  st_g4b6_1: '@iris Anda, Faísca. Você está atrasando a gente.',
  st_g4b6_ask: 'Você está lenta hoje.',
  st_g4b6_oU: 'Estou. Carreguei alguém ontem.',
  st_g4b6_oQ: 'Lenta comparada com quem?',
  st_g4b6_oF: 'Aumenta o fogo.',
  st_g4b6_rU: 'Carregar pesa. E não aparece no número.',
  st_g4b6_rQ: 'Com a de ontem. Sempre com a de ontem.',
  st_g4b6_rF: 'Aumentado.',

  st_g4b7_ask: 'Última oferta: metade do preço.',
  st_g4b7_oU: 'Não. Obrigada.',
  st_g4b7_oQ: 'Por que insistir tanto comigo?',
  st_g4b7_oF: 'Aceito.',
  st_g4b7_rU: 'Ninguém agradece uma recusa. Você agradeceu.',
  st_g4b7_rQ: 'Porque quem recusa duas vezes nunca mais volta.',
  st_g4b7_rF: 'Então segure firme.',

  st_g4b8_ask: 'Quem recusa sai daqui de mãos vazias.',
  st_g4b8_oU: 'Saio com as minhas mãos.',
  st_g4b8_oQ: 'Vazias, ou só sem as suas coisas?',
  st_g4b8_oF: 'Eu levo o que vim buscar.',
  st_g4b8_rU: 'Isso não estava na conta.',
  st_g4b8_rQ: 'Bem observado. Você me deve essa.',
  st_g4b8_rF: 'Leva. E paga depois, como todo mundo.',

  st_g4b9_ask: 'O velho está falando demais sobre mim.',
  st_g4b9_oU: 'Deixa ele falar. Ele viu coisas.',
  st_g4b9_oQ: 'Por que isso te incomoda?',
  st_g4b9_oF: 'Ele fala demais mesmo.',
  st_g4b9_rU: 'Viu. Foi ele que esperou do lado de fora.',
  st_g4b9_rQ: 'Porque ele lembra de mim antes do fogo.',
  st_g4b9_rF: 'Fala. E está certo.',

  /* ---------------- chefe da galáxia ---------------- */
  st_g4b10_k: 'Fornalha',
  st_g4b10_1: '~A boca abre inteira. Dentro dela cabe uma vida acelerada.',
  st_g4b10_2: 'Eu me acendi primeiro. Olha o que eu virei.',
  st_g4b10_3: 'Forte. Rápida. E sozinha desde então.',
  st_g4b10_4: '@casco Brasa.',
  st_g4b10_5: 'Faz tempo que ninguém diz o meu nome.',
  st_g4b10_6: 'E você, menina. Eu conheço faísca. Eu vi a primeira.',
  st_g4b10_7: 'O instante tinha um nome pequeno. Igual ao seu.',
  st_g4b10_ask: 'Me diga: para que serve ficar inteira?',
  st_g4b10_oU: 'Para ainda aquecer quando eu chegar.',
  st_g4b10_oQ: 'Ninguém aqui pergunta isso, né?',
  st_g4b10_oF: 'Não serve. Serve chegar primeiro.',
  st_g4b10_rU: 'Sai daqui antes que eu mude de ideia sobre mim.',
  st_g4b10_rQ: 'Ninguém. Eu já tinha esquecido a pergunta.',
  st_g4b10_rF: 'Então você já é minha. Pode ir.',

  /* ---------------- a carta ---------------- */
  st_g4c_who: 'vela', st_g4c_k: 'Uma carta',
  st_g4c_1: '~Preso na brasa de um anel, um bilhete que não queimou.',
  st_g4c_2: 'Faísca: não aceite o fogo de ninguém.',
  st_g4c_3: 'Você já nasceu acesa.',
  st_g4c_4: '— V.',
  st_g4c_5: '@casco Nasceu. Ele disse nasceu.'
});

Object.assign(HR.I18N.en, {
  st_g4_k: 'Chapter 4 · The Forge',
  st_g4_1: '~The Forge is hot, loud and honest: everything here costs.',
  st_g4_2: '~The rings shrink as you get close. Whoever decides early gets through.',
  st_g4_3: '~In the middle, a burning mouth measures your light and names a price.',
  st_g4_ask: 'You get there in ten turns. With me, in one. Want it?',
  st_g4_oU: 'I want to arrive whole. Even slowly.',
  st_g4_oQ: 'What does one turn cost?',
  st_g4_oF: 'I want it. Light me.',
  st_g4_rU: 'Whole. They all say that before the hurry.',
  st_g4_rQ: 'Heat. Yours.',
  st_g4_rF: 'Good girl. Come closer.',

  st_g4v3_who: 'iris',
  st_g4v3_1: '~Iris tears past. Twice as bright. And nothing near her is warm.',
  st_g4v3_2: 'I went through the fire. Look at me.',
  st_g4v3_3: '@faisca You are cold.',
  st_g4v3_4: 'I am fast. It is different.',

  st_g4v6_who: 'casco',
  st_g4v6_1: 'I came here once. With someone.',
  st_g4v6_2: 'She wanted the fire. I wanted to wait outside.',
  st_g4v6_3: '~He does not finish the sentence.',

  st_g4v9_who: 'poeira',
  st_g4v9_1: 'No one sees me here. It is good.',
  st_g4v9_2: 'Dust does not burn. Dust already burned.',
  st_g4v9_3: '@faisca Burned when?',
  st_g4v9_4: 'Before. Long before everything.',

  st_g4b1_ask: 'Everything here has a price. What do you have?',
  st_g4b1_oU: 'Time.',
  st_g4b1_oQ: 'What do you charge in?',
  st_g4b1_oF: 'Will.',
  st_g4b1_rU: 'Time is the dearest coin. And you spend it without seeing.',
  st_g4b1_rQ: 'In heat. In time. In whatever you have.',
  st_g4b1_rF: 'Will I accept. It binds with fire.',

  st_g4b2_ask: 'The first tempering hurts a little. Go on?',
  st_g4b2_oU: 'I go on, if the pain is mine.',
  st_g4b2_oQ: 'What does that pain improve?',
  st_g4b2_oF: 'I go on. Harder.',
  st_g4b2_rU: 'Then it is something else. Then it is work.',
  st_g4b2_rQ: 'Whatever you want. It does not choose.',
  st_g4b2_rF: 'Harder is the word heard most in here.',

  st_g4b3_1: '~Iris laps the whole Forge while you pass one ring.',
  st_g4b3_ask: 'Look at the comet now.',
  st_g4b3_oU: 'She is beautiful. And far.',
  st_g4b3_oQ: 'Is she still herself?',
  st_g4b3_oF: 'She is ahead.',
  st_g4b3_rU: 'Far is the price. Nobody reads that on the sign.',
  st_g4b3_rQ: 'She is. With less of something.',
  st_g4b3_rF: '@iris I am. And you should come too.',

  st_g4b4_ask: 'Noticed she warms no one anymore?',
  st_g4b4_oU: 'I noticed. It scares me.',
  st_g4b4_oQ: 'Can it be undone?',
  st_g4b4_oF: 'Warmth does not win races.',
  st_g4b4_rU: 'A good scare. Keep it.',
  st_g4b4_rQ: 'Slowly, it can. No one has the patience.',
  st_g4b4_rF: 'It does not. It is only for staying.',

  st_g4b5_ask: 'A light went out working. Does the work go on?',
  st_g4b5_oU: 'No. Let us stop a moment.',
  st_g4b5_oQ: 'Does this always happen?',
  st_g4b5_oF: 'One fewer.',
  st_g4b5_rU: 'A moment. Just one.',
  st_g4b5_rQ: 'Every week. We stopped counting.',
  st_g4b5_rF: 'That is what I said the first time.',

  st_g4b6_1: '@iris Come on, Spark. You are holding us up.',
  st_g4b6_ask: 'You are slow today.',
  st_g4b6_oU: 'I am. I carried someone yesterday.',
  st_g4b6_oQ: 'Slow compared to whom?',
  st_g4b6_oF: 'Turn up the fire.',
  st_g4b6_rU: 'Carrying weighs. And it does not show in the number.',
  st_g4b6_rQ: 'To yesterday’s you. Always to yesterday’s.',
  st_g4b6_rF: 'Turned up.',

  st_g4b7_ask: 'Last offer: half price.',
  st_g4b7_oU: 'No. Thank you.',
  st_g4b7_oQ: 'Why push me so hard?',
  st_g4b7_oF: 'I accept.',
  st_g4b7_rU: 'No one thanks a refusal. You did.',
  st_g4b7_rQ: 'Because whoever refuses twice never comes back.',
  st_g4b7_rF: 'Then hold on tight.',

  st_g4b8_ask: 'Whoever refuses leaves here empty-handed.',
  st_g4b8_oU: 'I leave with my own hands.',
  st_g4b8_oQ: 'Empty, or just without your things?',
  st_g4b8_oF: 'I take what I came for.',
  st_g4b8_rU: 'That was not in the count.',
  st_g4b8_rQ: 'Well spotted. You owe me that one.',
  st_g4b8_rF: 'Take it. And pay later, like everyone.',

  st_g4b9_ask: 'The old one is talking too much about me.',
  st_g4b9_oU: 'Let him talk. He has seen things.',
  st_g4b9_oQ: 'Why does it bother you?',
  st_g4b9_oF: 'He does talk too much.',
  st_g4b9_rU: 'He has. He is the one who waited outside.',
  st_g4b9_rQ: 'Because he remembers me before the fire.',
  st_g4b9_rF: 'He does. And he is right.',

  st_g4b10_k: 'Furnace',
  st_g4b10_1: '~The mouth opens wide. Inside it fits a life in a hurry.',
  st_g4b10_2: 'I lit myself first. Look what I became.',
  st_g4b10_3: 'Strong. Fast. And alone ever since.',
  st_g4b10_4: '@casco Ember.',
  st_g4b10_5: 'It has been a long time since anyone said my name.',
  st_g4b10_6: 'And you, girl. I know a spark. I saw the first one.',
  st_g4b10_7: 'The instant had a small name. The same as yours.',
  st_g4b10_ask: 'Tell me: what is staying whole for?',
  st_g4b10_oU: 'To still warm someone when I arrive.',
  st_g4b10_oQ: 'Nobody here asks that, right?',
  st_g4b10_oF: 'Nothing. Arriving first is.',
  st_g4b10_rU: 'Get out before I change my mind about myself.',
  st_g4b10_rQ: 'Nobody. I had forgotten the question.',
  st_g4b10_rF: 'Then you are already mine. You may go.',

  st_g4c_who: 'vela', st_g4c_k: 'A letter',
  st_g4c_1: '~Caught in the embers of a ring, a note that did not burn.',
  st_g4c_2: 'Spark: do not accept anyone’s fire.',
  st_g4c_3: 'You were born already lit.',
  st_g4c_4: '— S.',
  st_g4c_5: '@casco Born. He said born.'
});

Object.assign(HR.I18N.es, {
  st_g4_k: 'Capítulo 4 · La Forja',
  st_g4_1: '~La Forja es caliente, ruidosa y honesta: aquí todo cuesta.',
  st_g4_2: '~Los anillos se encogen cuando te acercas. Quien decide temprano, pasa.',
  st_g4_3: '~En el medio, una boca encendida mide tu luz y pone un precio.',
  st_g4_ask: 'Llegas en diez vueltas. Conmigo, en una. ¿Quieres?',
  st_g4_oU: 'Quiero llegar entera. Aunque tarde.',
  st_g4_oQ: '¿Qué cuesta una vuelta?',
  st_g4_oF: 'Quiero. Enciéndeme.',
  st_g4_rU: 'Entera. Todas dicen eso antes de la prisa.',
  st_g4_rQ: 'Calor. El tuyo.',
  st_g4_rF: 'Buena chica. Acércate.',

  st_g4v3_who: 'iris',
  st_g4v3_1: '~Iris pasa rasgando. Brilla el doble. Y nada se calienta cerca de ella.',
  st_g4v3_2: 'Pasé por el fuego. Mírame.',
  st_g4v3_3: '@faisca Estás helada.',
  st_g4v3_4: 'Estoy rápida. Es distinto.',

  st_g4v6_who: 'casco',
  st_g4v6_1: 'Vine aquí una vez. Con alguien.',
  st_g4v6_2: 'Ella quiso el fuego. Yo quise esperar afuera.',
  st_g4v6_3: '~No termina la frase.',

  st_g4v9_who: 'poeira',
  st_g4v9_1: 'Aquí nadie me ve. Está bien.',
  st_g4v9_2: 'El polvo no se quema. El polvo ya se quemó.',
  st_g4v9_3: '@faisca ¿Se quemó cuándo?',
  st_g4v9_4: 'Antes. Mucho antes de todo.',

  st_g4b1_ask: 'Aquí todo tiene precio. ¿Qué tienes?',
  st_g4b1_oU: 'Tiempo.',
  st_g4b1_oQ: '¿En qué cobras?',
  st_g4b1_oF: 'Voluntad.',
  st_g4b1_rU: 'El tiempo es la moneda más cara. Y la gastas sin ver.',
  st_g4b1_rQ: 'En calor. En tiempo. En lo que tengas.',
  st_g4b1_rF: 'Voluntad acepto. Liga con el fuego.',

  st_g4b2_ask: 'El primer templado duele un poco. ¿Sigues?',
  st_g4b2_oU: 'Sigo, si el dolor es mío.',
  st_g4b2_oQ: '¿Qué mejora ese dolor?',
  st_g4b2_oF: 'Sigo. Más fuerte.',
  st_g4b2_rU: 'Entonces es otra cosa. Entonces es trabajo.',
  st_g4b2_rQ: 'Lo que quieras. Él no elige.',
  st_g4b2_rF: 'Más fuerte es lo que más se oye aquí.',

  st_g4b3_1: '~Iris da una vuelta entera a la Forja mientras pasas un anillo.',
  st_g4b3_ask: 'Mira a la cometa ahora.',
  st_g4b3_oU: 'Está preciosa. Y lejos.',
  st_g4b3_oQ: '¿Sigue siendo ella?',
  st_g4b3_oF: 'Va adelante.',
  st_g4b3_rU: 'Lejos es el precio. Nadie lo lee en el cartel.',
  st_g4b3_rQ: 'Lo es. Con menos de algo.',
  st_g4b3_rF: '@iris Voy. Y tú deberías venir.',

  st_g4b4_ask: '¿Notaste que ya no calienta a nadie?',
  st_g4b4_oU: 'Lo noté. Me asusta.',
  st_g4b4_oQ: '¿Se puede deshacer?',
  st_g4b4_oF: 'El calor no gana carreras.',
  st_g4b4_rU: 'Buen susto. Guárdalo.',
  st_g4b4_rQ: 'Despacio, se puede. Nadie tiene paciencia.',
  st_g4b4_rF: 'No gana. Solo sirve para quedarse.',

  st_g4b5_ask: 'Una luz se apagó trabajando. ¿Sigue el trabajo?',
  st_g4b5_oU: 'No. Paremos un instante.',
  st_g4b5_oQ: '¿Esto pasa siempre?',
  st_g4b5_oF: 'Una menos.',
  st_g4b5_rU: 'Un instante. Solo uno.',
  st_g4b5_rQ: 'Cada semana. Dejamos de contar.',
  st_g4b5_rF: 'Eso dije la primera vez.',

  st_g4b6_1: '@iris Vamos, Chispa. Nos estás atrasando.',
  st_g4b6_ask: 'Estás lenta hoy.',
  st_g4b6_oU: 'Lo estoy. Ayer cargué a alguien.',
  st_g4b6_oQ: '¿Lenta comparada con quién?',
  st_g4b6_oF: 'Sube el fuego.',
  st_g4b6_rU: 'Cargar pesa. Y no aparece en el número.',
  st_g4b6_rQ: 'Con la de ayer. Siempre con la de ayer.',
  st_g4b6_rF: 'Subido.',

  st_g4b7_ask: 'Última oferta: mitad de precio.',
  st_g4b7_oU: 'No. Gracias.',
  st_g4b7_oQ: '¿Por qué insistes tanto conmigo?',
  st_g4b7_oF: 'Acepto.',
  st_g4b7_rU: 'Nadie agradece un rechazo. Tú agradeciste.',
  st_g4b7_rQ: 'Porque quien rechaza dos veces no vuelve nunca.',
  st_g4b7_rF: 'Entonces agárrate fuerte.',

  st_g4b8_ask: 'Quien rechaza sale de aquí con las manos vacías.',
  st_g4b8_oU: 'Salgo con mis manos.',
  st_g4b8_oQ: '¿Vacías, o solo sin tus cosas?',
  st_g4b8_oF: 'Me llevo lo que vine a buscar.',
  st_g4b8_rU: 'Eso no estaba en la cuenta.',
  st_g4b8_rQ: 'Bien visto. Me debes esa.',
  st_g4b8_rF: 'Llévalo. Y paga después, como todos.',

  st_g4b9_ask: 'El viejo habla demasiado de mí.',
  st_g4b9_oU: 'Déjalo hablar. Ha visto cosas.',
  st_g4b9_oQ: '¿Por qué te molesta?',
  st_g4b9_oF: 'Sí que habla demasiado.',
  st_g4b9_rU: 'Las vio. Él fue quien esperó afuera.',
  st_g4b9_rQ: 'Porque me recuerda de antes del fuego.',
  st_g4b9_rF: 'Habla. Y tiene razón.',

  st_g4b10_k: 'Horno',
  st_g4b10_1: '~La boca se abre entera. Dentro cabe una vida acelerada.',
  st_g4b10_2: 'Me encendí primero. Mira en qué me convertí.',
  st_g4b10_3: 'Fuerte. Rápida. Y sola desde entonces.',
  st_g4b10_4: '@casco Brasa.',
  st_g4b10_5: 'Hace mucho que nadie dice mi nombre.',
  st_g4b10_6: 'Y tú, niña. Conozco una chispa. Vi la primera.',
  st_g4b10_7: 'El instante tenía un nombre pequeño. Igual al tuyo.',
  st_g4b10_ask: 'Dime: ¿para qué sirve quedarse entera?',
  st_g4b10_oU: 'Para calentar todavía al llegar.',
  st_g4b10_oQ: 'Nadie aquí pregunta eso, ¿no?',
  st_g4b10_oF: 'Para nada. Sirve llegar primero.',
  st_g4b10_rU: 'Vete antes de que cambie de idea sobre mí.',
  st_g4b10_rQ: 'Nadie. Ya había olvidado la pregunta.',
  st_g4b10_rF: 'Entonces ya eres mía. Puedes irte.',

  st_g4c_who: 'vela', st_g4c_k: 'Una carta',
  st_g4c_1: '~Atrapada en la brasa de un anillo, una nota que no se quemó.',
  st_g4c_2: 'Chispa: no aceptes el fuego de nadie.',
  st_g4c_3: 'Ya naciste encendida.',
  st_g4c_4: '— V.',
  st_g4c_5: '@casco Naciste. Dijo naciste.'
});
