/* =====================================================================
   ORBO v5.9 — texto da história: Galáxia 2 (Maré · Leviatã · Paciência).
   Ver docs/HISTORIA.md §11.
   ===================================================================== */
Object.assign(HR.I18N.pt, {
  st_g2_1: '~Aqui os anéis sobem e descem como se respirassem.',
  st_g2_2: '~Não adianta forçar: eles não estão no caminho, estão na hora deles.',
  st_g2_3: '~Lá no fundo, uma coisa enorme dorme e faz a maré de todo mundo.',
  st_g2_who: 'casco',
  st_g2_ask: 'Guarde isto: o mar não atrasa. Ele tem hora.',
  st_g2_oU: 'Então eu espero.',
  st_g2_oQ: 'E quem decidiu a hora?',
  st_g2_oF: 'Eu não tenho hora. Tenho pressa.',
  st_g2_rU: 'Boa menina.',
  st_g2_rQ: 'Ninguém sabe. Faz tempo demais.',
  st_g2_rF: 'Pois é. Vamos ver quanto ela te rende.',

  st_g2v3_who: 'iris',
  st_g2v3_1: 'Íris. Cometa. Recordista de três rotas.',
  st_g2v3_2: 'Você voa bonito. Só devagar.',
  st_g2v6_who: 'casco',
  st_g2v6_1: 'Aquilo lá embaixo não é um bicho. É um horário.',
  st_g2v6_2: 'Se ele parar, metade do céu perde a hora.',
  st_g2v9_who: 'iris',
  st_g2v9_1: 'Eu vou na frente. Te espero na Forja.',
  st_g2v9_2: '~Ela some antes de você responder.',

  st_g2b1_ask: 'Por que você corre?',
  st_g2b1_oU: 'Porque eles estão longe.',
  st_g2b1_oQ: 'Correr adianta alguma coisa aqui?',
  st_g2b1_oF: 'Porque o tempo não é meu amigo.',
  st_g2b1_rU: 'Longe não anda. Você anda.',
  st_g2b1_rQ: 'Aqui, não. Em outro lugar, talvez.',
  st_g2b1_rF: 'O tempo não é amigo de ninguém. É só tempo.',

  st_g2b2_ask: 'Quanto tempo você aguenta parada?',
  st_g2b2_oU: 'O quanto for preciso.',
  st_g2b2_oQ: 'Parar é perder tempo ou ganhar?',
  st_g2b2_oF: 'Nem um instante.',
  st_g2b2_rU: 'Então você já sabe nadar.',
  st_g2b2_rQ: 'Depende do que você faz enquanto para.',
  st_g2b2_rF: 'A maré também não para. E ela cansa.',

  st_g2b3_ask: 'Aquela que brilha rápido quer te ensinar. Vai ouvir?',
  st_g2b3_oU: 'Vou. Todo mundo sabe alguma coisa.',
  st_g2b3_oQ: 'O que ela quer em troca?',
  st_g2b3_oF: 'Eu é que vou ensinar ela.',
  st_g2b3_rU: 'Ela sabe. Só não sabe o que não sabe.',
  st_g2b3_rQ: 'Plateia. E nem percebe que quer.',
  st_g2b3_rF: 'Vocês duas correndo. Que barulho.',

  st_g2b4_ask: 'Uma luzinha vem na maré. Ela passa por você agora.',
  st_g2b4_oU: 'Eu paro e pego.',
  st_g2b4_oQ: 'Se eu parar, eu perco o quê?',
  st_g2b4_oF: 'A maré devolve. Sempre devolve.',
  st_g2b4_rU: 'Você perdeu o embalo. E ganhou uma luz.',
  st_g2b4_rQ: 'O embalo. Só isso.',
  st_g2b4_rF: 'Às vezes devolve. Nem sempre inteira.',

  st_g2b5_ask: 'Quer saber o que eu sonho?',
  st_g2b5_oU: 'Quero.',
  st_g2b5_oQ: 'Você sonha?',
  st_g2b5_oF: 'Sonho não move ninguém.',
  st_g2b5_rU: 'Sonho que alguém segura a maré por uma noite.',
  st_g2b5_rQ: 'Durmo desde sempre. Alguma coisa tem que acontecer aqui dentro.',
  st_g2b5_rF: 'Move a maré. Ela é o meu sonho vazando.',

  st_g2b6_ask: 'Se me acordarem, a maré fica reta. E acaba.',
  st_g2b6_oU: 'Então continue dormindo.',
  st_g2b6_oQ: 'Acaba para você ou para todos?',
  st_g2b6_oF: 'Reta é melhor. Acorda.',
  st_g2b6_rU: 'Obrigado. Ninguém escolhe isso.',
  st_g2b6_rQ: 'Para todos. Eu só paro de sonhar.',
  st_g2b6_rF: 'Você não seria a primeira a tentar.',

  st_g2b7_ask: 'Viu o que uma pressa faz?',
  st_g2b7_oU: 'Vi. E foi por minha causa também.',
  st_g2b7_oQ: 'Foi culpa de quem?',
  st_g2b7_oF: 'Foi um acidente. Segue.',
  st_g2b7_rU: 'Foi. E você ficou para consertar.',
  st_g2b7_rQ: 'De quem tinha pressa. Isso somos quase todos.',
  st_g2b7_rF: 'Segue. A maré leva um ciclo para voltar.',

  st_g2b8_ask: 'Para consertar, alguém espera um ciclo inteiro.',
  st_g2b8_oU: 'Eu espero.',
  st_g2b8_oQ: 'Um ciclo é quanto?',
  st_g2b8_oF: 'Que espere outro.',
  st_g2b8_rU: 'Então durma um pouco. Eu acordo você.',
  st_g2b8_rQ: 'O suficiente para você sentir. Não mais que isso.',
  st_g2b8_rF: 'Sempre tem outro. Foi assim que eu vim parar aqui.',

  st_g2b9_ask: 'Você sabe há quanto tempo eu faço isto?',
  st_g2b9_oU: 'Não. Mas obrigada por fazer.',
  st_g2b9_oQ: 'Alguém já te rendeu?',
  st_g2b9_oF: 'Não interessa. Faz.',
  st_g2b9_rU: '…Ninguém agradece a maré. Ela só está aí.',
  st_g2b9_rQ: 'Nunca. Nunca fizeram turno comigo.',
  st_g2b9_rF: 'Eu faço. É o que eu sei.',

  st_g2b10_1: '~A maré sobe inteira. Não dá para furar: dá para subir junto.',
  st_g2b10_2: 'Todo mundo que passa aqui quer a mesma coisa.',
  st_g2b10_3: 'Que eu fique quieto até eles atravessarem.',
  st_g2b10_ask: 'E você, faísca. O que você quer de mim?',
  st_g2b10_oU: 'Quero que você descanse. Eu passo no seu ritmo.',
  st_g2b10_oQ: 'Quero saber quem te pôs para marcar a hora dos outros.',
  st_g2b10_oF: 'Quero passagem. Abaixa a maré.',
  st_g2b10_rU: '…Ninguém nunca disse isso. Vá. A maré te acompanha.',
  st_g2b10_rQ: '…Eu também queria saber. Se descobrir, volte e conte.',
  st_g2b10_rF: '…Abaixo. E quando você voltar, vai ser a nado.',

  st_g2c_who: 'vela', st_g2c_k: 'Carta de Vela',
  st_g2c_1: '~No alto da maré, preso num anel, um bilhete molhado.',
  st_g2c_2: 'Faísca: teu pai levou onze anos para aprender a esperar.',
  st_g2c_3: 'Eu levei mais. Não tenha vergonha de ser devagar.',
  st_g2c_4: '— V.'
});

Object.assign(HR.I18N.en, {
  st_g2_1: '~Here the rings rise and fall as if they were breathing.',
  st_g2_2: '~Forcing gets you nowhere: they are not in your way, they are on their hour.',
  st_g2_3: '~Deep down, something enormous sleeps and makes everyone\'s tide.',
  st_g2_who: 'casco',
  st_g2_ask: 'Remember this: the sea is never late. It has an hour.',
  st_g2_oU: 'Then I wait.',
  st_g2_oQ: 'And who decided the hour?',
  st_g2_oF: 'I do not have an hour. I have a hurry.',
  st_g2_rU: 'Good girl.',
  st_g2_rQ: 'Nobody knows. It has been too long.',
  st_g2_rF: 'Right. Let us see what that gets you.',

  st_g2v3_who: 'iris',
  st_g2v3_1: 'Iris. Comet. Record holder on three routes.',
  st_g2v3_2: 'You fly nicely. Just slowly.',
  st_g2v6_who: 'casco',
  st_g2v6_1: 'That thing down there is not a beast. It is a timetable.',
  st_g2v6_2: 'If it stops, half the sky loses track of the hour.',
  st_g2v9_who: 'iris',
  st_g2v9_1: 'I am going ahead. See you at the Forge.',
  st_g2v9_2: '~She is gone before you can answer.',

  st_g2b1_ask: 'Why do you run?',
  st_g2b1_oU: 'Because they are far away.',
  st_g2b1_oQ: 'Does running help at all here?',
  st_g2b1_oF: 'Because time is not my friend.',
  st_g2b1_rU: 'Far does not move. You move.',
  st_g2b1_rQ: 'Here, no. Somewhere else, maybe.',
  st_g2b1_rF: 'Time is nobody\'s friend. It is only time.',

  st_g2b2_ask: 'How long can you stay still?',
  st_g2b2_oU: 'As long as it takes.',
  st_g2b2_oQ: 'Is stopping losing time or gaining it?',
  st_g2b2_oF: 'Not one moment.',
  st_g2b2_rU: 'Then you already know how to swim.',
  st_g2b2_rQ: 'Depends what you do while you stop.',
  st_g2b2_rF: 'The tide never stops either. And it gets tired.',

  st_g2b3_ask: 'That fast bright one wants to teach you. Will you listen?',
  st_g2b3_oU: 'I will. Everyone knows something.',
  st_g2b3_oQ: 'What does she want in return?',
  st_g2b3_oF: 'I am the one who will teach her.',
  st_g2b3_rU: 'She does know. She just does not know what she does not know.',
  st_g2b3_rQ: 'An audience. She does not even notice she wants it.',
  st_g2b3_rF: 'The two of you, running. What a racket.',

  st_g2b4_ask: 'A small light is coming in on the tide. It passes you now.',
  st_g2b4_oU: 'I stop and catch it.',
  st_g2b4_oQ: 'If I stop, what do I lose?',
  st_g2b4_oF: 'The tide brings things back. It always does.',
  st_g2b4_rU: 'You lost your momentum. And gained a light.',
  st_g2b4_rQ: 'Momentum. That is all.',
  st_g2b4_rF: 'Sometimes it does. Not always whole.',

  st_g2b5_ask: 'Do you want to know what I dream?',
  st_g2b5_oU: 'I do.',
  st_g2b5_oQ: 'You dream?',
  st_g2b5_oF: 'Dreams move nobody.',
  st_g2b5_rU: 'I dream that someone holds the tide for one night.',
  st_g2b5_rQ: 'I have slept forever. Something has to happen in here.',
  st_g2b5_rF: 'They move the tide. It is my dream leaking out.',

  st_g2b6_ask: 'If they wake me, the tide goes flat. And it ends.',
  st_g2b6_oU: 'Then keep sleeping.',
  st_g2b6_oQ: 'Ends for you or for everyone?',
  st_g2b6_oF: 'Flat is better. Wake up.',
  st_g2b6_rU: 'Thank you. Nobody chooses that.',
  st_g2b6_rQ: 'For everyone. I only stop dreaming.',
  st_g2b6_rF: 'You would not be the first to try.',

  st_g2b7_ask: 'See what one hurry does?',
  st_g2b7_oU: 'I do. And part of it was me.',
  st_g2b7_oQ: 'Whose fault was it?',
  st_g2b7_oF: 'It was an accident. Move on.',
  st_g2b7_rU: 'It was. And you stayed to fix it.',
  st_g2b7_rQ: 'Whoever was in a hurry. That is almost all of us.',
  st_g2b7_rF: 'Move on. The tide takes a cycle to come back.',

  st_g2b8_ask: 'To fix it, someone waits a whole cycle.',
  st_g2b8_oU: 'I will wait.',
  st_g2b8_oQ: 'How long is a cycle?',
  st_g2b8_oF: 'Let someone else wait.',
  st_g2b8_rU: 'Then sleep a little. I will wake you.',
  st_g2b8_rQ: 'Long enough for you to feel it. No longer.',
  st_g2b8_rF: 'There is always someone else. That is how I ended up here.',

  st_g2b9_ask: 'Do you know how long I have been doing this?',
  st_g2b9_oU: 'No. But thank you for doing it.',
  st_g2b9_oQ: 'Has anyone ever taken over for you?',
  st_g2b9_oF: 'Does not matter. Keep doing it.',
  st_g2b9_rU: '…Nobody thanks the tide. It is just there.',
  st_g2b9_rQ: 'Never. Nobody ever took a shift with me.',
  st_g2b9_rF: 'I do it. It is what I know.',

  st_g2b10_1: '~The whole tide rises. You cannot cut through: you can rise with it.',
  st_g2b10_2: 'Everyone who comes through here wants the same thing.',
  st_g2b10_3: 'For me to stay quiet until they are across.',
  st_g2b10_ask: 'And you, spark. What do you want from me?',
  st_g2b10_oU: 'I want you to rest. I will go at your pace.',
  st_g2b10_oQ: 'I want to know who put you in charge of everyone\'s hour.',
  st_g2b10_oF: 'I want passage. Lower the tide.',
  st_g2b10_rU: '…No one has ever said that. Go. The tide goes with you.',
  st_g2b10_rQ: '…I would like to know too. If you find out, come back and tell me.',
  st_g2b10_rF: '…Lowered. And when you come back, you swim.',

  st_g2c_who: 'vela', st_g2c_k: 'A letter from Sail',
  st_g2c_1: '~High on the tide, caught in a ring, a soaked note.',
  st_g2c_2: 'Spark: your father took eleven years to learn how to wait.',
  st_g2c_3: 'I took longer. Never be ashamed of being slow.',
  st_g2c_4: '— S.'
});

Object.assign(HR.I18N.es, {
  st_g2_1: '~Aquí los anillos suben y bajan como si respiraran.',
  st_g2_2: '~No sirve forzar: no están en el camino, están en su hora.',
  st_g2_3: '~En el fondo, algo enorme duerme y hace la marea de todos.',
  st_g2_who: 'casco',
  st_g2_ask: 'Guarda esto: el mar no llega tarde. Tiene hora.',
  st_g2_oU: 'Entonces espero.',
  st_g2_oQ: '¿Y quién decidió la hora?',
  st_g2_oF: 'No tengo hora. Tengo prisa.',
  st_g2_rU: 'Buena chica.',
  st_g2_rQ: 'Nadie sabe. Hace demasiado tiempo.',
  st_g2_rF: 'Ya. Veamos cuánto te rinde.',

  st_g2v3_who: 'iris',
  st_g2v3_1: 'Iris. Cometa. Récord en tres rutas.',
  st_g2v3_2: 'Vuelas bonito. Solo que despacio.',
  st_g2v6_who: 'casco',
  st_g2v6_1: 'Eso de ahí abajo no es un bicho. Es un horario.',
  st_g2v6_2: 'Si se detiene, medio cielo pierde la hora.',
  st_g2v9_who: 'iris',
  st_g2v9_1: 'Me adelanto. Te espero en la Forja.',
  st_g2v9_2: '~Desaparece antes de que puedas responder.',

  st_g2b1_ask: '¿Por qué corres?',
  st_g2b1_oU: 'Porque ellos están lejos.',
  st_g2b1_oQ: '¿Correr sirve de algo aquí?',
  st_g2b1_oF: 'Porque el tiempo no es mi amigo.',
  st_g2b1_rU: 'Lejos no camina. Tú caminas.',
  st_g2b1_rQ: 'Aquí, no. En otra parte, quizá.',
  st_g2b1_rF: 'El tiempo no es amigo de nadie. Solo es tiempo.',

  st_g2b2_ask: '¿Cuánto aguantas quieta?',
  st_g2b2_oU: 'Lo que haga falta.',
  st_g2b2_oQ: '¿Parar es perder tiempo o ganarlo?',
  st_g2b2_oF: 'Ni un instante.',
  st_g2b2_rU: 'Entonces ya sabes nadar.',
  st_g2b2_rQ: 'Depende de lo que hagas mientras paras.',
  st_g2b2_rF: 'La marea tampoco para. Y se cansa.',

  st_g2b3_ask: 'Esa que brilla rápido quiere enseñarte. ¿La escuchas?',
  st_g2b3_oU: 'Sí. Todos saben algo.',
  st_g2b3_oQ: '¿Qué quiere a cambio?',
  st_g2b3_oF: 'Yo le voy a enseñar a ella.',
  st_g2b3_rU: 'Sabe. Solo no sabe lo que no sabe.',
  st_g2b3_rQ: 'Público. Ni se da cuenta de que lo quiere.',
  st_g2b3_rF: 'Las dos corriendo. Qué ruido.',

  st_g2b4_ask: 'Una lucecita viene en la marea. Te pasa ahora.',
  st_g2b4_oU: 'Paro y la recojo.',
  st_g2b4_oQ: 'Si paro, ¿qué pierdo?',
  st_g2b4_oF: 'La marea devuelve. Siempre devuelve.',
  st_g2b4_rU: 'Perdiste el impulso. Y ganaste una luz.',
  st_g2b4_rQ: 'El impulso. Nada más.',
  st_g2b4_rF: 'A veces devuelve. No siempre entera.',

  st_g2b5_ask: '¿Quieres saber qué sueño?',
  st_g2b5_oU: 'Quiero.',
  st_g2b5_oQ: '¿Tú sueñas?',
  st_g2b5_oF: 'Los sueños no mueven a nadie.',
  st_g2b5_rU: 'Sueño que alguien sostiene la marea una noche.',
  st_g2b5_rQ: 'Duermo desde siempre. Algo tiene que pasar aquí dentro.',
  st_g2b5_rF: 'Mueven la marea. Ella es mi sueño saliéndose.',

  st_g2b6_ask: 'Si me despiertan, la marea se queda recta. Y se acaba.',
  st_g2b6_oU: 'Entonces sigue durmiendo.',
  st_g2b6_oQ: '¿Se acaba para ti o para todos?',
  st_g2b6_oF: 'Recta es mejor. Despierta.',
  st_g2b6_rU: 'Gracias. Nadie elige eso.',
  st_g2b6_rQ: 'Para todos. Yo solo dejo de soñar.',
  st_g2b6_rF: 'No serías la primera en intentarlo.',

  st_g2b7_ask: '¿Viste lo que hace una prisa?',
  st_g2b7_oU: 'Lo vi. Y en parte fue por mí.',
  st_g2b7_oQ: '¿De quién fue la culpa?',
  st_g2b7_oF: 'Fue un accidente. Sigue.',
  st_g2b7_rU: 'Lo fue. Y te quedaste a arreglarlo.',
  st_g2b7_rQ: 'De quien tenía prisa. Eso somos casi todos.',
  st_g2b7_rF: 'Sigue. La marea tarda un ciclo en volver.',

  st_g2b8_ask: 'Para arreglarlo, alguien espera un ciclo entero.',
  st_g2b8_oU: 'Yo espero.',
  st_g2b8_oQ: '¿Cuánto es un ciclo?',
  st_g2b8_oF: 'Que espere otro.',
  st_g2b8_rU: 'Entonces duerme un poco. Yo te despierto.',
  st_g2b8_rQ: 'Lo justo para que lo sientas. Nada más.',
  st_g2b8_rF: 'Siempre hay otro. Así terminé yo aquí.',

  st_g2b9_ask: '¿Sabes hace cuánto hago esto?',
  st_g2b9_oU: 'No. Pero gracias por hacerlo.',
  st_g2b9_oQ: '¿Alguien te relevó alguna vez?',
  st_g2b9_oF: 'Da igual. Hazlo.',
  st_g2b9_rU: '…Nadie le da las gracias a la marea. Solo está ahí.',
  st_g2b9_rQ: 'Nunca. Nunca hicieron turno conmigo.',
  st_g2b9_rF: 'Lo hago. Es lo que sé.',

  st_g2b10_1: '~La marea sube entera. No se puede cortar: se puede subir con ella.',
  st_g2b10_2: 'Todos los que pasan quieren lo mismo.',
  st_g2b10_3: 'Que me quede quieto hasta que crucen.',
  st_g2b10_ask: 'Y tú, chispa. ¿Qué quieres de mí?',
  st_g2b10_oU: 'Quiero que descanses. Paso a tu ritmo.',
  st_g2b10_oQ: 'Quiero saber quién te puso a marcar la hora de los demás.',
  st_g2b10_oF: 'Quiero paso. Baja la marea.',
  st_g2b10_rU: '…Nadie dijo eso nunca. Ve. La marea te acompaña.',
  st_g2b10_rQ: '…Yo también querría saberlo. Si lo averiguas, vuelve y cuéntame.',
  st_g2b10_rF: '…La bajo. Y cuando vuelvas, será a nado.',

  st_g2c_who: 'vela', st_g2c_k: 'Carta de Vela',
  st_g2c_1: '~En lo alto de la marea, atrapada en un anillo, una nota mojada.',
  st_g2c_2: 'Chispa: tu padre tardó once años en aprender a esperar.',
  st_g2c_3: 'Yo tardé más. No te avergüences de ser lenta.',
  st_g2c_4: '— V.'
});
