/* =====================================================================
   ORBO v7 — texto da história: Galáxia 5 (A Névoa · Espectro).
   Ver docs/HISTORIA_V7.md.

   O primeiro fundo do poço.
   O degrau: ela vê o rasgo pela primeira vez, de longe, e não entende.
   O que acontece:
     - nasce o ECO, feito do que ninguém disse. Ele imita a voz de quem ela
       ama e diz a mentira: foi você. É ele quem traz a palavra "culpa";
     - Poeira desmente o Eco e, sem querer, diz "mãe" — a primeira vez;
     - o Eco leva Íris; o Cardume vai embora quando ela apaga;
     - Casco conta o que não contou: deixou Brasa entrar no fogo e esperou;
     - na carta, embaixo da letra do pai, uma segunda letra, leve: "nunca foi".
   ===================================================================== */
Object.assign(HR.I18N.pt, {
  /* ---------------- entrada ---------------- */
  st_g5_k: 'Capítulo 5 · A Névoa',
  st_g5_1: '~A Névoa esconde os anéis até eles estarem quase em cima de você.',
  st_g5_2: '~Aqui não dá para planejar. Dá para confiar no ritmo.',
  st_g5_3: '~E tem alguma coisa que fala com a voz de quem falta.',
  st_g5_4: '@eco Faísca? Por que você demorou tanto?',
  st_g5_ask: '@eco Você nem lembra de mim. Lembra?',
  st_g5_oU: 'Não lembro. Mas eu sinto.',
  st_g5_oQ: 'Quem está falando de verdade?',
  st_g5_oF: 'Você não é ninguém.',
  st_g5_rU: '@eco Sente. É só disso que eu preciso.',
  st_g5_rQ: '@eco Você. Sempre você. Eu só repito.',
  st_g5_rF: '@eco Grite mais. Eu fico maior.',

  /* ---------------- visitas ---------------- */
  st_g5v2_who: 'casco',
  st_g5v2_1: 'Não confie no que enxerga aqui.',
  st_g5v2_2: 'Confie no que você sabe de antes da névoa.',
  st_g5v2_3: '@faisca Eu não sei nada de antes.',
  st_g5v2_4: 'Sabe. Só não lembra que sabe.',

  st_g5v5_who: 'casco', st_g5v5_k: 'O que Casco não contou',
  st_g5v5_1: 'Brasa entrou na Forja. Eu fiquei do lado de fora.',
  st_g5v5_2: 'Esperei. Ela voltou rápida demais para mim.',
  st_g5v5_3: 'Eu não fui atrás. Achei que ela voltaria.',
  st_g5v5_4: '~Ele olha para a névoa.',
  st_g5v5_5: 'Por isso eu vim com você. Dessa vez eu vou junto.',

  st_g5v8_who: 'poeira',
  st_g5v8_1: 'A voz imita mal.',
  st_g5v8_2: 'Sua mãe nunca perguntaria isso.',
  st_g5v8_3: '@faisca Minha… mãe?',
  st_g5v8_4: '~Pela primeira vez, a palavra tem formato. O mesmo formato da falta.',
  st_g5v8_5: '@faisca Como você sabe como ela fala?',
  st_g5v8_6: 'Não sei. Só sei.',

  /* ---------------- chefes dos sistemas ---------------- */
  st_g5b1_ask: '@eco Reconhece esta voz?',
  st_g5b1_oU: 'Não. Mas dói.',
  st_g5b1_oQ: 'De onde você tirou ela?',
  st_g5b1_oF: 'Imitação barata.',
  st_g5b1_rU: '@eco Dói porque é sua. Eu só devolvo.',
  st_g5b1_rQ: '@eco De você. Eu não invento nada.',
  st_g5b1_rF: '@eco Barata. E você parou para ouvir.',

  st_g5b2_ask: '@eco Alguém foi embora por sua causa.',
  st_g5b2_oU: 'Eu não sei. Não lembro.',
  st_g5b2_oQ: 'Quem? Diga quem.',
  st_g5b2_oF: 'Mentira.',
  st_g5b2_rU: '@eco Não lembrar é o pior jeito de saber.',
  st_g5b2_rQ: '@eco Você vai descobrir. E vai querer não ter.',
  st_g5b2_rF: '@eco Então por que tremeu?',

  st_g5b3_k: 'A linha',
  st_g5b3_1: '~A névoa abre um buraco. Lá longe, atravessando o céu, uma linha.',
  st_g5b3_2: '~Não é estrela. É mais antiga que as estrelas. Dói olhar.',
  st_g5b3_3: '@faisca O que é aquilo?',
  st_g5b3_ask: '@eco Você sabe o que é. Você abriu.',
  st_g5b3_oU: 'Não sei do que você fala.',
  st_g5b3_oQ: 'Abri como?',
  st_g5b3_oF: 'Eu não abri nada.',
  st_g5b3_rU: '@eco Sabe. Só não lembra que sabe.',
  st_g5b3_rQ: '@eco Pergunte a ela. Ela tem o seu formato.',
  st_g5b3_rF: '@eco Então por que ela se parece com você?',

  st_g5b4_ask: '@eco O velho também perdeu alguém. Ele contou?',
  st_g5b4_oU: 'Contou. Eu ouvi inteiro.',
  st_g5b4_oQ: 'Por que ele demorou tanto?',
  st_g5b4_oF: 'Todo mundo perdeu alguém.',
  st_g5b4_rU: '@eco Ouvir inteiro. Isso eu não sei fazer.',
  st_g5b4_rQ: '@eco Porque contar torna verdade.',
  st_g5b4_rF: '@eco Todo mundo. E cada um acha que é só ele.',

  st_g5b5_ask: '@eco Ele te acha um peso. Eu ouvi.',
  st_g5b5_oU: 'Ele disse o contrário. Acredito.',
  st_g5b5_oQ: 'Isso é ele ou é você?',
  st_g5b5_oF: 'Que ache.',
  st_g5b5_rU: '@eco Acreditar em alguém me deixa pequeno.',
  st_g5b5_rQ: '@eco Sou eu. Quase sempre sou eu.',
  st_g5b5_rF: '@eco Então vocês dois vão andar calados.',

  st_g5b6_1: '~Na névoa, um risco de luz gira em círculos.',
  st_g5b6_2: '@iris Faísca. Ele diz que eu cheguei primeiro. E que não tem ninguém lá.',
  st_g5b6_ask: '@iris Diz que é mentira.',
  st_g5b6_oU: 'Eu estou aqui. Isso é verdade.',
  st_g5b6_oQ: 'Chegou primeiro aonde?',
  st_g5b6_oF: 'Ignora. Voa comigo.',
  st_g5b6_rU: '@iris Você parou. Por mim. Ninguém para.',
  st_g5b6_rQ: '@iris No fim. E o fim estava vazio.',
  st_g5b6_rF: '@iris Eu voo. Eu sempre voo…',

  st_g5b7_1: '~Íris sumiu na névoa.',
  st_g5b7_2: '@cardume Ela está apagando! A gente vai procurar outra luz!',
  st_g5b7_3: '~O Cardume vai embora, todo de uma vez.',
  st_g5b7_ask: '@eco Viu? Todo mundo vai embora de você.',
  st_g5b7_oU: 'O Casco ficou. Poeira ficou.',
  st_g5b7_oQ: 'Por que você quer que eu acredite?',
  st_g5b7_oF: 'Então eu vou sozinha.',
  st_g5b7_rU: '@eco Por enquanto.',
  st_g5b7_rQ: '@eco Porque eu sou feito do que você teme.',
  st_g5b7_rF: '@eco Isso. Assim fica mais fácil te achar.',

  st_g5b8_ask: '@eco Diga em voz alta o que você mais teme.',
  st_g5b8_oU: 'Chegar e não ser reconhecida.',
  st_g5b8_oQ: 'Falar em voz alta muda algo?',
  st_g5b8_oF: 'Não tenho medo.',
  st_g5b8_rU: '@eco Agora eu tenho menos de você.',
  st_g5b8_rQ: '@eco Muda. É a única coisa que me machuca.',
  st_g5b8_rF: '@eco Tem. E ele cresce calado.',

  st_g5b9_ask: '@eco Eu sou feito do que não foi dito. Me diga algo.',
  st_g5b9_oU: 'Eu sinto falta. De alguém.',
  st_g5b9_oQ: 'Não foi dito por quem?',
  st_g5b9_oF: 'Não tenho nada para você.',
  st_g5b9_rU: '~Um pedaço da névoa se desfaz.',
  st_g5b9_rQ: '@eco Por todos. Cada silêncio vira um pedaço de mim.',
  st_g5b9_rF: '@eco Então eu fico com o seu silêncio.',

  /* ---------------- chefe da galáxia ---------------- */
  st_g5b10_k: 'Espectro',
  st_g5b10_1: '~O Espectro perde as caras, uma por uma, até não sobrar nenhuma.',
  st_g5b10_2: 'Sem a sua voz eu não existo.',
  st_g5b10_3: 'Então responda uma última vez.',
  st_g5b10_ask: '@eco De quem é a culpa?',
  st_g5b10_oU: 'De ninguém. E eu estou aqui.',
  st_g5b10_oQ: 'Ainda não sei. Vou descobrir.',
  st_g5b10_oF: 'Do escuro. E ele vai pagar.',
  st_g5b10_rU: '@eco Então não sobrou nada de mim. Por agora.',
  st_g5b10_rQ: '@eco Leve a pergunta. Ela é mais honesta que eu.',
  st_g5b10_rF: '@eco Ótimo. Raiva me alimenta. Até a próxima névoa.',

  /* ---------------- a carta ---------------- */
  st_g5c_who: 'vela', st_g5c_k: 'Uma carta',
  st_g5c_1: '~A névoa se abre num ponto só, do tamanho de um bilhete.',
  st_g5c_2: 'Faísca: se alguém aí dentro disser que a culpa é sua, não responda.',
  st_g5c_3: 'Só passe. A névoa odeia quem passa sem discutir.',
  st_g5c_4: '— V.',
  st_g5c_5: '~Embaixo, com outra letra, leve, sem terminar:',
  st_g5c_6: '@ancora nunca foi',
  st_g5c_7: '@poeira É ela.'
});

Object.assign(HR.I18N.en, {
  st_g5_k: 'Chapter 5 · The Mist',
  st_g5_1: '~The Mist hides the rings until they are almost on top of you.',
  st_g5_2: '~Here you cannot plan. You can trust the rhythm.',
  st_g5_3: '~And something here speaks with the voice of whoever is missing.',
  st_g5_4: '@eco Spark? Why did you take so long?',
  st_g5_ask: '@eco You do not even remember me. Do you?',
  st_g5_oU: 'I do not. But I feel it.',
  st_g5_oQ: 'Who is really speaking?',
  st_g5_oF: 'You are no one.',
  st_g5_rU: '@eco You feel it. That is all I need.',
  st_g5_rQ: '@eco You. Always you. I only repeat.',
  st_g5_rF: '@eco Shout louder. I grow bigger.',

  st_g5v2_who: 'casco',
  st_g5v2_1: 'Do not trust what you see here.',
  st_g5v2_2: 'Trust what you know from before the mist.',
  st_g5v2_3: '@faisca I know nothing from before.',
  st_g5v2_4: 'You do. You just do not remember knowing.',

  st_g5v5_who: 'casco', st_g5v5_k: 'What Hull never told',
  st_g5v5_1: 'Ember went into the Forge. I stayed outside.',
  st_g5v5_2: 'I waited. She came back too fast for me.',
  st_g5v5_3: 'I did not go after her. I thought she would come back.',
  st_g5v5_4: '~He looks into the mist.',
  st_g5v5_5: 'That is why I came with you. This time I go along.',

  st_g5v8_who: 'poeira',
  st_g5v8_1: 'The voice is a poor copy.',
  st_g5v8_2: 'Your mother would never ask that.',
  st_g5v8_3: '@faisca My… mother?',
  st_g5v8_4: '~For the first time, the word has a shape. The same shape as the absence.',
  st_g5v8_5: '@faisca How do you know how she speaks?',
  st_g5v8_6: 'I do not. I just know.',

  st_g5b1_ask: '@eco Do you recognise this voice?',
  st_g5b1_oU: 'No. But it hurts.',
  st_g5b1_oQ: 'Where did you get it?',
  st_g5b1_oF: 'A cheap copy.',
  st_g5b1_rU: '@eco It hurts because it is yours. I only give it back.',
  st_g5b1_rQ: '@eco From you. I invent nothing.',
  st_g5b1_rF: '@eco Cheap. And you stopped to listen.',

  st_g5b2_ask: '@eco Someone left because of you.',
  st_g5b2_oU: 'I do not know. I do not remember.',
  st_g5b2_oQ: 'Who? Say who.',
  st_g5b2_oF: 'A lie.',
  st_g5b2_rU: '@eco Not remembering is the worst way of knowing.',
  st_g5b2_rQ: '@eco You will find out. And wish you had not.',
  st_g5b2_rF: '@eco Then why did you tremble?',

  st_g5b3_k: 'The line',
  st_g5b3_1: '~The mist opens a hole. Far away, across the sky, a line.',
  st_g5b3_2: '~It is no star. It is older than the stars. It hurts to look.',
  st_g5b3_3: '@faisca What is that?',
  st_g5b3_ask: '@eco You know what it is. You opened it.',
  st_g5b3_oU: 'I do not know what you mean.',
  st_g5b3_oQ: 'Opened it how?',
  st_g5b3_oF: 'I opened nothing.',
  st_g5b3_rU: '@eco You know. You just do not remember knowing.',
  st_g5b3_rQ: '@eco Ask it. It has your shape.',
  st_g5b3_rF: '@eco Then why does it look like you?',

  st_g5b4_ask: '@eco The old one lost someone too. Did he tell you?',
  st_g5b4_oU: 'He did. I heard all of it.',
  st_g5b4_oQ: 'Why did he wait so long?',
  st_g5b4_oF: 'Everyone lost someone.',
  st_g5b4_rU: '@eco Hearing all of it. That I cannot do.',
  st_g5b4_rQ: '@eco Because telling makes it true.',
  st_g5b4_rF: '@eco Everyone. And each thinks it is only them.',

  st_g5b5_ask: '@eco He thinks you are a burden. I heard.',
  st_g5b5_oU: 'He said the opposite. I believe him.',
  st_g5b5_oQ: 'Is that him or you?',
  st_g5b5_oF: 'Let him think it.',
  st_g5b5_rU: '@eco Believing someone makes me small.',
  st_g5b5_rQ: '@eco It is me. It is almost always me.',
  st_g5b5_rF: '@eco Then the two of you will walk in silence.',

  st_g5b6_1: '~In the mist, a streak of light spins in circles.',
  st_g5b6_2: '@iris Spark. He says I got there first. And that no one is there.',
  st_g5b6_ask: '@iris Tell me it is a lie.',
  st_g5b6_oU: 'I am here. That is true.',
  st_g5b6_oQ: 'Got first where?',
  st_g5b6_oF: 'Ignore it. Fly with me.',
  st_g5b6_rU: '@iris You stopped. For me. Nobody stops.',
  st_g5b6_rQ: '@iris At the end. And the end was empty.',
  st_g5b6_rF: '@iris I fly. I always fly…',

  st_g5b7_1: '~Iris vanished into the mist.',
  st_g5b7_2: '@cardume She is going dim! We will look for another light!',
  st_g5b7_3: '~The Shoal leaves, all at once.',
  st_g5b7_ask: '@eco See? Everyone leaves you.',
  st_g5b7_oU: 'Hull stayed. Dust stayed.',
  st_g5b7_oQ: 'Why do you want me to believe it?',
  st_g5b7_oF: 'Then I go alone.',
  st_g5b7_rU: '@eco For now.',
  st_g5b7_rQ: '@eco Because I am made of what you fear.',
  st_g5b7_rF: '@eco Good. That makes you easier to find.',

  st_g5b8_ask: '@eco Say out loud what you fear most.',
  st_g5b8_oU: 'Arriving and not being known.',
  st_g5b8_oQ: 'Does saying it change anything?',
  st_g5b8_oF: 'I am not afraid.',
  st_g5b8_rU: '@eco Now I have less of you.',
  st_g5b8_rQ: '@eco It does. It is the only thing that hurts me.',
  st_g5b8_rF: '@eco You are. And it grows in silence.',

  st_g5b9_ask: '@eco I am made of what was never said. Tell me something.',
  st_g5b9_oU: 'I miss someone.',
  st_g5b9_oQ: 'Never said by whom?',
  st_g5b9_oF: 'I have nothing for you.',
  st_g5b9_rU: '~A piece of the mist comes apart.',
  st_g5b9_rQ: '@eco By everyone. Every silence becomes a piece of me.',
  st_g5b9_rF: '@eco Then I keep your silence.',

  st_g5b10_k: 'Specter',
  st_g5b10_1: '~The Specter loses its faces, one by one, until none are left.',
  st_g5b10_2: 'Without your voice I do not exist.',
  st_g5b10_3: 'So answer one last time.',
  st_g5b10_ask: '@eco Whose fault is it?',
  st_g5b10_oU: 'No one’s. And I am here.',
  st_g5b10_oQ: 'I do not know yet. I will.',
  st_g5b10_oF: 'The dark’s. And it will pay.',
  st_g5b10_rU: '@eco Then nothing is left of me. For now.',
  st_g5b10_rQ: '@eco Take the question. It is more honest than I am.',
  st_g5b10_rF: '@eco Good. Anger feeds me. Until the next mist.',

  st_g5c_who: 'vela', st_g5c_k: 'A letter',
  st_g5c_1: '~The mist opens in a single spot, the size of a note.',
  st_g5c_2: 'Spark: if anyone in there says it is your fault, do not answer.',
  st_g5c_3: 'Just pass. The mist hates those who pass without arguing.',
  st_g5c_4: '— S.',
  st_g5c_5: '~Below it, in another hand, light, unfinished:',
  st_g5c_6: '@ancora it never was',
  st_g5c_7: '@poeira It is her.'
});

Object.assign(HR.I18N.es, {
  st_g5_k: 'Capítulo 5 · La Niebla',
  st_g5_1: '~La Niebla esconde los anillos hasta que están casi encima de ti.',
  st_g5_2: '~Aquí no se puede planear. Se puede confiar en el ritmo.',
  st_g5_3: '~Y hay algo que habla con la voz de quien falta.',
  st_g5_4: '@eco ¿Chispa? ¿Por qué tardaste tanto?',
  st_g5_ask: '@eco Ni siquiera me recuerdas. ¿O sí?',
  st_g5_oU: 'No te recuerdo. Pero lo siento.',
  st_g5_oQ: '¿Quién habla de verdad?',
  st_g5_oF: 'No eres nadie.',
  st_g5_rU: '@eco Lo sientes. Es todo lo que necesito.',
  st_g5_rQ: '@eco Tú. Siempre tú. Yo solo repito.',
  st_g5_rF: '@eco Grita más. Crezco.',

  st_g5v2_who: 'casco',
  st_g5v2_1: 'No confíes en lo que ves aquí.',
  st_g5v2_2: 'Confía en lo que sabes de antes de la niebla.',
  st_g5v2_3: '@faisca No sé nada de antes.',
  st_g5v2_4: 'Sabes. Solo no recuerdas que sabes.',

  st_g5v5_who: 'casco', st_g5v5_k: 'Lo que Casco no contó',
  st_g5v5_1: 'Brasa entró en la Forja. Yo me quedé afuera.',
  st_g5v5_2: 'Esperé. Volvió demasiado rápida para mí.',
  st_g5v5_3: 'No fui tras ella. Creí que volvería.',
  st_g5v5_4: '~Mira la niebla.',
  st_g5v5_5: 'Por eso vine contigo. Esta vez voy también.',

  st_g5v8_who: 'poeira',
  st_g5v8_1: 'La voz imita mal.',
  st_g5v8_2: 'Tu madre nunca preguntaría eso.',
  st_g5v8_3: '@faisca ¿Mi… madre?',
  st_g5v8_4: '~Por primera vez, la palabra tiene forma. La misma forma de la falta.',
  st_g5v8_5: '@faisca ¿Cómo sabes cómo habla?',
  st_g5v8_6: 'No sé. Solo sé.',

  st_g5b1_ask: '@eco ¿Reconoces esta voz?',
  st_g5b1_oU: 'No. Pero duele.',
  st_g5b1_oQ: '¿De dónde la sacaste?',
  st_g5b1_oF: 'Imitación barata.',
  st_g5b1_rU: '@eco Duele porque es tuya. Yo solo la devuelvo.',
  st_g5b1_rQ: '@eco De ti. No invento nada.',
  st_g5b1_rF: '@eco Barata. Y te detuviste a escuchar.',

  st_g5b2_ask: '@eco Alguien se fue por tu causa.',
  st_g5b2_oU: 'No sé. No recuerdo.',
  st_g5b2_oQ: '¿Quién? Di quién.',
  st_g5b2_oF: 'Mentira.',
  st_g5b2_rU: '@eco No recordar es la peor forma de saber.',
  st_g5b2_rQ: '@eco Lo descubrirás. Y querrás no haberlo hecho.',
  st_g5b2_rF: '@eco ¿Entonces por qué temblaste?',

  st_g5b3_k: 'La línea',
  st_g5b3_1: '~La niebla abre un hueco. A lo lejos, cruzando el cielo, una línea.',
  st_g5b3_2: '~No es estrella. Es más vieja que las estrellas. Duele mirarla.',
  st_g5b3_3: '@faisca ¿Qué es eso?',
  st_g5b3_ask: '@eco Sabes lo que es. Tú la abriste.',
  st_g5b3_oU: 'No sé de qué hablas.',
  st_g5b3_oQ: '¿La abrí cómo?',
  st_g5b3_oF: 'No abrí nada.',
  st_g5b3_rU: '@eco Sabes. Solo no recuerdas que sabes.',
  st_g5b3_rQ: '@eco Pregúntale a ella. Tiene tu forma.',
  st_g5b3_rF: '@eco ¿Entonces por qué se parece a ti?',

  st_g5b4_ask: '@eco El viejo también perdió a alguien. ¿Te lo contó?',
  st_g5b4_oU: 'Me lo contó. Lo oí entero.',
  st_g5b4_oQ: '¿Por qué tardó tanto?',
  st_g5b4_oF: 'Todos perdieron a alguien.',
  st_g5b4_rU: '@eco Oír entero. Eso no sé hacerlo.',
  st_g5b4_rQ: '@eco Porque contarlo lo vuelve verdad.',
  st_g5b4_rF: '@eco Todos. Y cada uno cree que es el único.',

  st_g5b5_ask: '@eco Él cree que eres un peso. Lo oí.',
  st_g5b5_oU: 'Dijo lo contrario. Le creo.',
  st_g5b5_oQ: '¿Eso es él o eres tú?',
  st_g5b5_oF: 'Que lo crea.',
  st_g5b5_rU: '@eco Creer en alguien me hace pequeño.',
  st_g5b5_rQ: '@eco Soy yo. Casi siempre soy yo.',
  st_g5b5_rF: '@eco Entonces van a caminar callados.',

  st_g5b6_1: '~En la niebla, una raya de luz gira en círculos.',
  st_g5b6_2: '@iris Chispa. Dice que llegué primero. Y que no hay nadie allí.',
  st_g5b6_ask: '@iris Dime que es mentira.',
  st_g5b6_oU: 'Estoy aquí. Eso es verdad.',
  st_g5b6_oQ: '¿Llegaste primero adónde?',
  st_g5b6_oF: 'Ignóralo. Vuela conmigo.',
  st_g5b6_rU: '@iris Te detuviste. Por mí. Nadie se detiene.',
  st_g5b6_rQ: '@iris Al final. Y el final estaba vacío.',
  st_g5b6_rF: '@iris Vuelo. Siempre vuelo…',

  st_g5b7_1: '~Iris desapareció en la niebla.',
  st_g5b7_2: '@cardume ¡Se está apagando! ¡Vamos a buscar otra luz!',
  st_g5b7_3: '~El Cardumen se va, todo de una vez.',
  st_g5b7_ask: '@eco ¿Ves? Todos se van de ti.',
  st_g5b7_oU: 'Casco se quedó. Polvo se quedó.',
  st_g5b7_oQ: '¿Por qué quieres que lo crea?',
  st_g5b7_oF: 'Entonces voy sola.',
  st_g5b7_rU: '@eco Por ahora.',
  st_g5b7_rQ: '@eco Porque estoy hecho de lo que temes.',
  st_g5b7_rF: '@eco Eso. Así es más fácil encontrarte.',

  st_g5b8_ask: '@eco Di en voz alta lo que más temes.',
  st_g5b8_oU: 'Llegar y que no me reconozcan.',
  st_g5b8_oQ: '¿Decirlo en voz alta cambia algo?',
  st_g5b8_oF: 'No tengo miedo.',
  st_g5b8_rU: '@eco Ahora tengo menos de ti.',
  st_g5b8_rQ: '@eco Cambia. Es lo único que me duele.',
  st_g5b8_rF: '@eco Lo tienes. Y crece callado.',

  st_g5b9_ask: '@eco Estoy hecho de lo que no se dijo. Dime algo.',
  st_g5b9_oU: 'Extraño a alguien.',
  st_g5b9_oQ: '¿No lo dijo quién?',
  st_g5b9_oF: 'No tengo nada para ti.',
  st_g5b9_rU: '~Un pedazo de la niebla se deshace.',
  st_g5b9_rQ: '@eco Nadie. Cada silencio se vuelve un pedazo de mí.',
  st_g5b9_rF: '@eco Entonces me quedo con tu silencio.',

  st_g5b10_k: 'Espectro',
  st_g5b10_1: '~El Espectro pierde sus caras, una por una, hasta que no queda ninguna.',
  st_g5b10_2: 'Sin tu voz no existo.',
  st_g5b10_3: 'Así que responde una última vez.',
  st_g5b10_ask: '@eco ¿De quién es la culpa?',
  st_g5b10_oU: 'De nadie. Y estoy aquí.',
  st_g5b10_oQ: 'Todavía no sé. Lo sabré.',
  st_g5b10_oF: 'De lo oscuro. Y pagará.',
  st_g5b10_rU: '@eco Entonces no queda nada de mí. Por ahora.',
  st_g5b10_rQ: '@eco Llévate la pregunta. Es más honesta que yo.',
  st_g5b10_rF: '@eco Bien. La rabia me alimenta. Hasta la próxima niebla.',

  st_g5c_who: 'vela', st_g5c_k: 'Una carta',
  st_g5c_1: '~La niebla se abre en un solo punto, del tamaño de una nota.',
  st_g5c_2: 'Chispa: si alguien ahí dentro dice que la culpa es tuya, no respondas.',
  st_g5c_3: 'Solo pasa. La niebla odia a quien pasa sin discutir.',
  st_g5c_4: '— V.',
  st_g5c_5: '~Debajo, con otra letra, leve, sin terminar:',
  st_g5c_6: '@ancora nunca lo fue',
  st_g5c_7: '@poeira Es ella.'
});
