/* =====================================================================
   ORBO v5.9 — texto da história: Galáxia 5 (Névoa · Espectro · Verdade).
   Ver docs/HISTORIA.md §14.
   ===================================================================== */
Object.assign(HR.I18N.pt, {
  st_g5_1: '~A Névoa esconde os anéis até eles estarem quase em cima de você.',
  st_g5_2: '~Aqui não dá para planejar. Dá para confiar no ritmo.',
  st_g5_3: '~E tem algo que fala com a voz de quem você ama.',
  st_g5_ask: 'Faísca? Por que você não veio antes?',
  st_g5_oU: 'Você não é ela. Mas eu ouvi.',
  st_g5_oQ: 'Quem está falando de verdade?',
  st_g5_oF: 'Cala a boca.',
  st_g5_rU: 'Ouviu. É só disso que eu preciso.',
  st_g5_rQ: 'Você. Sempre você. Eu só repito.',
  st_g5_rF: 'Grite mais. Eu fico maior.',

  st_g5v2_who: 'casco',
  st_g5v2_1: 'Não confie no que enxerga aqui.',
  st_g5v2_2: 'Confie no que você sabe de antes da névoa.',
  st_g5v5_who: 'casco', st_g5v5_k: 'O que Casco não contou',
  st_g5v5_1: 'Eu tinha alguém. Uma luz.',
  st_g5v5_2: 'Ela foi para a Forja e voltou rápida demais para mim.',
  st_g5v5_3: 'Eu não fui atrás. Achei que ela voltaria.',
  st_g5v5_4: '~Ele olha para a névoa.',
  st_g5v5_5: 'Por isso eu vim com você. Dessa vez eu vou atrás.',
  st_g5v8_who: 'poeira',
  st_g5v8_1: 'A voz dele imita mal.',
  st_g5v8_2: 'Sua mãe nunca perguntaria isso.',

  st_g5b1_ask: 'Reconhece esta voz?',
  st_g5b1_oU: 'Reconheço. E dói.',
  st_g5b1_oQ: 'De onde você tirou ela?',
  st_g5b1_oF: 'É imitação barata.',
  st_g5b1_rU: 'Dói porque é sua. Eu só devolvo.',
  st_g5b1_rQ: 'De você. Eu não invento nada.',
  st_g5b1_rF: 'Barata, e ainda assim você parou para ouvir.',

  st_g5b2_ask: 'Eles teriam ficado se você chamasse.',
  st_g5b2_oU: 'Não. Eles já tinham decidido.',
  st_g5b2_oQ: 'Como você sabe disso?',
  st_g5b2_oF: 'Eu teria segurado os dois.',
  st_g5b2_rU: '…Você está firme hoje.',
  st_g5b2_rQ: 'Não sei. Eu digo o que você teme.',
  st_g5b2_rF: 'Com que força? Você era do tamanho de um anel.',

  st_g5b3_ask: 'Por que o céu abriu bem naquela noite?',
  st_g5b3_oU: 'Eu não sei. E não é minha culpa.',
  st_g5b3_oQ: 'Por quê, afinal?',
  st_g5b3_oF: 'Porque alguém deixou.',
  st_g5b3_rU: 'Essa frase me tira um pedaço.',
  st_g5b3_rQ: 'Ninguém aqui sabe. Nem eu.',
  st_g5b3_rF: 'Alguém. Você vai passar a vida procurando esse alguém.',

  st_g5b4_ask: 'O velho também perdeu alguém. Ele contou?',
  st_g5b4_oU: 'Contou agora. Eu ouvi inteiro.',
  st_g5b4_oQ: 'Por que ele demorou tanto?',
  st_g5b4_oF: 'Todo mundo perdeu alguém.',
  st_g5b4_rU: 'Ouvir inteiro é raro. Eu não sei fazer isso.',
  st_g5b4_rQ: 'Porque contar torna verdade.',
  st_g5b4_rF: 'Todo mundo. E cada um acha que é só ele.',

  st_g5b5_ask: 'Ele te acha um peso. Eu ouvi.',
  st_g5b5_oU: 'Ele já disse o contrário. Acredito nele.',
  st_g5b5_oQ: 'Isso é ele falando ou é você?',
  st_g5b5_oF: 'Que ache.',
  st_g5b5_rU: 'Acreditar em alguém me deixa pequeno.',
  st_g5b5_rQ: '…Sou eu. Quase sempre sou eu.',
  st_g5b5_rF: 'Então vocês dois vão andar calados.',

  st_g5b6_ask: 'Você chora pelos dois ou por você?',
  st_g5b6_oU: 'Pelos três.',
  st_g5b6_oQ: 'Tem diferença?',
  st_g5b6_oF: 'Eu não choro.',
  st_g5b6_rU: 'Pelos três. Essa resposta não me serve.',
  st_g5b6_rQ: 'Nenhuma. Eu só queria te ver escolher.',
  st_g5b6_rF: 'Todo mundo chora na névoa. Ninguém vê.',

  st_g5b7_ask: 'Quer a verdade? Ela é pequena.',
  st_g5b7_oU: 'Quero mesmo assim.',
  st_g5b7_oQ: 'Pequena como?',
  st_g5b7_oF: 'Quero a grande.',
  st_g5b7_rU: 'Aconteceu. Você era criança. Ponto.',
  st_g5b7_rQ: 'Cabe numa frase. E ninguém aceita.',
  st_g5b7_rF: 'Não existe grande. Existe verdade e história.',

  st_g5b8_ask: 'Diga em voz alta o que você mais teme.',
  st_g5b8_oU: 'Que eu chegue lá e eles não me reconheçam.',
  st_g5b8_oQ: 'Falar em voz alta muda alguma coisa?',
  st_g5b8_oF: 'Não tenho medo.',
  st_g5b8_rU: '…Agora eu tenho menos de você.',
  st_g5b8_rQ: 'Muda. É a única coisa que me machuca.',
  st_g5b8_rF: 'Tem. E ele fica maior calado.',

  st_g5b9_ask: 'Eu sou feito do que não foi dito. Me diga algo.',
  st_g5b9_oU: 'Eu sinto falta deles. Todo dia.',
  st_g5b9_oQ: 'Não foi dito por quem?',
  st_g5b9_oF: 'Não tenho nada para você.',
  st_g5b9_rU: '~Um pedaço da névoa se desfaz.',
  st_g5b9_rQ: 'Por todos. Cada silêncio virou um pedaço de mim.',
  st_g5b9_rF: 'Então eu fico com o seu silêncio.',

  st_g5b10_1: '~O Espectro perde as caras, uma por uma, até não sobrar nenhuma.',
  st_g5b10_2: 'Sem a sua voz eu não existo.',
  st_g5b10_3: 'Então responda uma última vez.',
  st_g5b10_ask: 'De quem é a culpa?',
  st_g5b10_oU: 'De ninguém. Aconteceu, e eu sobrevivi.',
  st_g5b10_oQ: 'Ainda não sei. Vou descobrir lá dentro.',
  st_g5b10_oF: 'Do escuro. E ele vai me pagar.',
  st_g5b10_rU: '…Então não sobrou nada de mim. Obrigado.',
  st_g5b10_rQ: '…Leve a pergunta. Ela é mais honesta que eu.',
  st_g5b10_rF: '…Ótimo. Raiva me alimenta. Até a próxima névoa.',

  st_g5c_who: 'vela', st_g5c_k: 'Carta de Vela',
  st_g5c_1: '~A névoa se abre num ponto só, do tamanho de um bilhete.',
  st_g5c_2: 'Faísca: se alguém aí dentro disser que a culpa é sua, não responda.',
  st_g5c_3: 'Só passe. A névoa odeia quem passa sem discutir.',
  st_g5c_4: '— V.'
});

Object.assign(HR.I18N.en, {
  st_g5_1: '~The Mist hides the rings until they are almost on top of you.',
  st_g5_2: '~You cannot plan here. You can trust the rhythm.',
  st_g5_3: '~And there is something that speaks with the voice of someone you love.',
  st_g5_ask: 'Spark? Why did you not come sooner?',
  st_g5_oU: 'You are not her. But I heard you.',
  st_g5_oQ: 'Who is really speaking?',
  st_g5_oF: 'Shut up.',
  st_g5_rU: 'You heard. That is all I need.',
  st_g5_rQ: 'You. Always you. I only repeat.',
  st_g5_rF: 'Shout louder. I get bigger.',

  st_g5v2_who: 'casco',
  st_g5v2_1: 'Do not trust what you see in here.',
  st_g5v2_2: 'Trust what you knew before the mist.',
  st_g5v5_who: 'casco', st_g5v5_k: 'What Hull never said',
  st_g5v5_1: 'I had someone. A light.',
  st_g5v5_2: 'She went to the Forge and came back too fast for me.',
  st_g5v5_3: 'I did not go after her. I thought she would come back.',
  st_g5v5_4: '~He looks into the mist.',
  st_g5v5_5: 'That is why I came with you. This time I go after.',
  st_g5v8_who: 'poeira',
  st_g5v8_1: 'His voice does a bad impression.',
  st_g5v8_2: 'Your mother would never ask that.',

  st_g5b1_ask: 'Do you recognise this voice?',
  st_g5b1_oU: 'I do. And it hurts.',
  st_g5b1_oQ: 'Where did you get it?',
  st_g5b1_oF: 'It is a cheap impression.',
  st_g5b1_rU: 'It hurts because it is yours. I only give it back.',
  st_g5b1_rQ: 'From you. I invent nothing.',
  st_g5b1_rF: 'Cheap, and you still stopped to listen.',

  st_g5b2_ask: 'They would have stayed if you had called them.',
  st_g5b2_oU: 'No. They had already decided.',
  st_g5b2_oQ: 'How would you know that?',
  st_g5b2_oF: 'I would have held them both.',
  st_g5b2_rU: '…You are steady today.',
  st_g5b2_rQ: 'I do not know. I say what you fear.',
  st_g5b2_rF: 'With what strength? You were the size of a ring.',

  st_g5b3_ask: 'Why did the sky open on that exact night?',
  st_g5b3_oU: 'I do not know. And it is not my fault.',
  st_g5b3_oQ: 'Why, then?',
  st_g5b3_oF: 'Because someone let it.',
  st_g5b3_rU: 'That sentence takes a piece out of me.',
  st_g5b3_rQ: 'Nobody here knows. Not even me.',
  st_g5b3_rF: 'Someone. You will spend your life looking for that someone.',

  st_g5b4_ask: 'The old one lost somebody too. Did he tell you?',
  st_g5b4_oU: 'He told me just now. I listened to all of it.',
  st_g5b4_oQ: 'Why did he take so long?',
  st_g5b4_oF: 'Everyone has lost somebody.',
  st_g5b4_rU: 'Listening to all of it is rare. I cannot do that.',
  st_g5b4_rQ: 'Because telling makes it true.',
  st_g5b4_rF: 'Everyone. And each one thinks they are the only one.',

  st_g5b5_ask: 'He thinks you are a burden. I heard him.',
  st_g5b5_oU: 'He has said the opposite. I believe him.',
  st_g5b5_oQ: 'Is that him talking, or you?',
  st_g5b5_oF: 'Let him think it.',
  st_g5b5_rU: 'Believing someone makes me small.',
  st_g5b5_rQ: '…It is me. It is almost always me.',
  st_g5b5_rF: 'Then the two of you will travel in silence.',

  st_g5b6_ask: 'Do you cry for them or for yourself?',
  st_g5b6_oU: 'For all three of us.',
  st_g5b6_oQ: 'Is there a difference?',
  st_g5b6_oF: 'I do not cry.',
  st_g5b6_rU: 'All three. That answer is no use to me.',
  st_g5b6_rQ: 'None. I only wanted to watch you choose.',
  st_g5b6_rF: 'Everyone cries in the mist. Nobody sees.',

  st_g5b7_ask: 'Want the truth? It is small.',
  st_g5b7_oU: 'I want it anyway.',
  st_g5b7_oQ: 'Small how?',
  st_g5b7_oF: 'I want the big one.',
  st_g5b7_rU: 'It happened. You were a child. That is all.',
  st_g5b7_rQ: 'It fits in one sentence. And nobody accepts it.',
  st_g5b7_rF: 'There is no big one. There is truth, and there are stories.',

  st_g5b8_ask: 'Say out loud what you fear most.',
  st_g5b8_oU: 'That I get there and they do not recognise me.',
  st_g5b8_oQ: 'Does saying it out loud change anything?',
  st_g5b8_oF: 'I am not afraid.',
  st_g5b8_rU: '…Now I have less of you.',
  st_g5b8_rQ: 'It does. It is the only thing that hurts me.',
  st_g5b8_rF: 'You are. And it grows in silence.',

  st_g5b9_ask: 'I am made of what was never said. Say something.',
  st_g5b9_oU: 'I miss them. Every day.',
  st_g5b9_oQ: 'Never said by whom?',
  st_g5b9_oF: 'I have nothing for you.',
  st_g5b9_rU: '~A piece of the mist comes undone.',
  st_g5b9_rQ: 'By everyone. Every silence became a piece of me.',
  st_g5b9_rF: 'Then I will keep your silence.',

  st_g5b10_1: '~The Specter loses its faces, one by one, until none are left.',
  st_g5b10_2: 'Without your voice I do not exist.',
  st_g5b10_3: 'So answer me one last time.',
  st_g5b10_ask: 'Whose fault is it?',
  st_g5b10_oU: 'Nobody\'s. It happened, and I survived it.',
  st_g5b10_oQ: 'I still do not know. I will find out in there.',
  st_g5b10_oF: 'The dark\'s. And it is going to pay.',
  st_g5b10_rU: '…Then there is nothing left of me. Thank you.',
  st_g5b10_rQ: '…Take the question. It is more honest than I am.',
  st_g5b10_rF: '…Good. Anger feeds me. See you at the next mist.',

  st_g5c_who: 'vela', st_g5c_k: 'A letter from Sail',
  st_g5c_1: '~The mist opens in one spot, the size of a note.',
  st_g5c_2: 'Spark: if something in there says it is your fault, do not answer.',
  st_g5c_3: 'Just go through. The mist hates whoever passes without arguing.',
  st_g5c_4: '— S.'
});

Object.assign(HR.I18N.es, {
  st_g5_1: '~La Niebla esconde los anillos hasta que están casi encima de ti.',
  st_g5_2: '~Aquí no se puede planear. Se puede confiar en el ritmo.',
  st_g5_3: '~Y hay algo que habla con la voz de quien tú quieres.',
  st_g5_ask: '¿Chispa? ¿Por qué no viniste antes?',
  st_g5_oU: 'Tú no eres ella. Pero te escuché.',
  st_g5_oQ: '¿Quién habla de verdad?',
  st_g5_oF: 'Cállate.',
  st_g5_rU: 'Escuchaste. Solo necesito eso.',
  st_g5_rQ: 'Tú. Siempre tú. Yo solo repito.',
  st_g5_rF: 'Grita más. Yo me hago más grande.',

  st_g5v2_who: 'casco',
  st_g5v2_1: 'No confíes en lo que ves aquí.',
  st_g5v2_2: 'Confía en lo que sabías antes de la niebla.',
  st_g5v5_who: 'casco', st_g5v5_k: 'Lo que Casco no contó',
  st_g5v5_1: 'Yo tenía a alguien. Una luz.',
  st_g5v5_2: 'Fue a la Forja y volvió demasiado rápida para mí.',
  st_g5v5_3: 'No fui tras ella. Pensé que volvería.',
  st_g5v5_4: '~Mira hacia la niebla.',
  st_g5v5_5: 'Por eso vine contigo. Esta vez voy detrás.',
  st_g5v8_who: 'poeira',
  st_g5v8_1: 'Su voz imita mal.',
  st_g5v8_2: 'Tu madre nunca preguntaría eso.',

  st_g5b1_ask: '¿Reconoces esta voz?',
  st_g5b1_oU: 'La reconozco. Y duele.',
  st_g5b1_oQ: '¿De dónde la sacaste?',
  st_g5b1_oF: 'Es una imitación barata.',
  st_g5b1_rU: 'Duele porque es tuya. Yo solo la devuelvo.',
  st_g5b1_rQ: 'De ti. Yo no invento nada.',
  st_g5b1_rF: 'Barata, y aun así te detuviste a escuchar.',

  st_g5b2_ask: 'Se habrían quedado si los hubieras llamado.',
  st_g5b2_oU: 'No. Ya lo habían decidido.',
  st_g5b2_oQ: '¿Cómo sabes eso?',
  st_g5b2_oF: 'Yo habría sostenido a los dos.',
  st_g5b2_rU: '…Hoy estás firme.',
  st_g5b2_rQ: 'No lo sé. Digo lo que temes.',
  st_g5b2_rF: '¿Con qué fuerza? Eras del tamaño de un anillo.',

  st_g5b3_ask: '¿Por qué se abrió el cielo justo esa noche?',
  st_g5b3_oU: 'No lo sé. Y no es culpa mía.',
  st_g5b3_oQ: '¿Por qué, entonces?',
  st_g5b3_oF: 'Porque alguien lo permitió.',
  st_g5b3_rU: 'Esa frase me arranca un pedazo.',
  st_g5b3_rQ: 'Nadie aquí lo sabe. Ni yo.',
  st_g5b3_rF: 'Alguien. Vas a pasar la vida buscando a ese alguien.',

  st_g5b4_ask: 'El viejo también perdió a alguien. ¿Te lo contó?',
  st_g5b4_oU: 'Me lo contó ahora. Lo escuché entero.',
  st_g5b4_oQ: '¿Por qué tardó tanto?',
  st_g5b4_oF: 'Todos perdieron a alguien.',
  st_g5b4_rU: 'Escuchar entero es raro. Yo no sé hacerlo.',
  st_g5b4_rQ: 'Porque contarlo lo vuelve verdad.',
  st_g5b4_rF: 'Todos. Y cada uno cree que es el único.',

  st_g5b5_ask: 'Él cree que eres un peso. Lo oí.',
  st_g5b5_oU: 'Él dijo lo contrario. Le creo.',
  st_g5b5_oQ: '¿Eso lo dice él o lo dices tú?',
  st_g5b5_oF: 'Que lo crea.',
  st_g5b5_rU: 'Creerle a alguien me deja pequeño.',
  st_g5b5_rQ: '…Soy yo. Casi siempre soy yo.',
  st_g5b5_rF: 'Entonces los dos van a viajar callados.',

  st_g5b6_ask: '¿Lloras por ellos o por ti?',
  st_g5b6_oU: 'Por los tres.',
  st_g5b6_oQ: '¿Hay diferencia?',
  st_g5b6_oF: 'Yo no lloro.',
  st_g5b6_rU: 'Por los tres. Esa respuesta no me sirve.',
  st_g5b6_rQ: 'Ninguna. Solo quería verte elegir.',
  st_g5b6_rF: 'Todos lloran en la niebla. Nadie lo ve.',

  st_g5b7_ask: '¿Quieres la verdad? Es pequeña.',
  st_g5b7_oU: 'La quiero igual.',
  st_g5b7_oQ: '¿Pequeña cómo?',
  st_g5b7_oF: 'Quiero la grande.',
  st_g5b7_rU: 'Pasó. Eras una niña. Punto.',
  st_g5b7_rQ: 'Cabe en una frase. Y nadie la acepta.',
  st_g5b7_rF: 'No existe la grande. Existe la verdad, y existen las historias.',

  st_g5b8_ask: 'Di en voz alta lo que más temes.',
  st_g5b8_oU: 'Que llegue allá y no me reconozcan.',
  st_g5b8_oQ: '¿Decirlo en voz alta cambia algo?',
  st_g5b8_oF: 'No tengo miedo.',
  st_g5b8_rU: '…Ahora tengo menos de ti.',
  st_g5b8_rQ: 'Cambia. Es lo único que me hace daño.',
  st_g5b8_rF: 'Lo tienes. Y callado se hace más grande.',

  st_g5b9_ask: 'Estoy hecho de lo que no se dijo. Dime algo.',
  st_g5b9_oU: 'Los extraño. Todos los días.',
  st_g5b9_oQ: '¿No lo dijo quién?',
  st_g5b9_oF: 'No tengo nada para ti.',
  st_g5b9_rU: '~Un pedazo de la niebla se deshace.',
  st_g5b9_rQ: 'Todos. Cada silencio se volvió un pedazo de mí.',
  st_g5b9_rF: 'Entonces me quedo con tu silencio.',

  st_g5b10_1: '~El Espectro pierde las caras, una por una, hasta no quedar ninguna.',
  st_g5b10_2: 'Sin tu voz yo no existo.',
  st_g5b10_3: 'Así que responde una última vez.',
  st_g5b10_ask: '¿De quién es la culpa?',
  st_g5b10_oU: 'De nadie. Pasó, y yo sobreviví.',
  st_g5b10_oQ: 'Todavía no lo sé. Voy a averiguarlo allá dentro.',
  st_g5b10_oF: 'De lo oscuro. Y me lo va a pagar.',
  st_g5b10_rU: '…Entonces no quedó nada de mí. Gracias.',
  st_g5b10_rQ: '…Llévate la pregunta. Es más honesta que yo.',
  st_g5b10_rF: '…Bien. La rabia me alimenta. Hasta la próxima niebla.',

  st_g5c_who: 'vela', st_g5c_k: 'Carta de Vela',
  st_g5c_1: '~La niebla se abre en un solo punto, del tamaño de una nota.',
  st_g5c_2: 'Chispa: si algo ahí dentro dice que la culpa es tuya, no respondas.',
  st_g5c_3: 'Solo pasa. La niebla odia a quien pasa sin discutir.',
  st_g5c_4: '— V.'
});
