/* =====================================================================
   ORBO v8 — texto da história: Galáxia 7 (A Tempestade · Tempestade).
   Ver docs/HISTORIA_V7.md e a crítica (secao 9.3).

   Começa a queda.
   O degrau: o rasgo está se fechando — e dá para medir. Na Névoa cabiam
   nove anéis na linha; aqui cabem sete, depois seis.
   O que acontece:
     - o Eco volta e torce o degrau da Forja: "o instante era você".
       Poeira desmonta em quatro palavras: "Abriu. Não quebrou.";
     - Íris é achada apagada e fria, e Faísca para para carregá-la —
       a primeira coisa que ela escolhe perder tempo fazendo;
     - a Tempestade não acusa ninguém: ela é espaço apertado gritando,
       e nasceu quando quem segura começou a cansar;
     - a carta é a mais curta até aqui, e a margem tem uma palavra só.
   ===================================================================== */
Object.assign(HR.I18N.pt, {
  /* ---------------- entrada ---------------- */
  st_g7_who: 'casco',
  st_g7_k: 'Capítulo 7 · A Tempestade',
  st_g7_1: '~O céu muda de direção sem avisar. Nada fica onde estava.',
  st_g7_2: '~Lá em cima, a linha. Está mais curta do que na Névoa.',
  st_g7_3: 'Menina. A linha. Ela era maior.',
  st_g7_ask: 'Você reparou?',
  st_g7_oU: 'Reparei. Não quis dizer.',
  st_g7_oQ: 'Linha fecha?',
  st_g7_oF: 'É a tempestade. Está longe.',
  st_g7_rU: 'Eu também não. Agora está dito.',
  st_g7_rQ: 'Fecha. Pelos riscos, alguém segura para não fechar.',
  st_g7_rF: 'Eu li anéis a vida inteira. Não é a tempestade.',

  /* ---------------- visitas ---------------- */
  st_g7v2_k: 'A voz volta',
  st_g7v2_1: '~A tempestade abre um corredor. Dentro dele, uma voz que você conhece.',
  st_g7v2_2: '@eco Faísca. Está fechando. Você viu.',
  st_g7v2_3: '@eco Está fechando porque você está aqui.',
  st_g7v2_4: '@faisca Aqui onde?',
  st_g7v2_5: '@eco Aqui dentro. Ocupando.',
  st_g7v2_ask: '@eco Você sabe o que abriu tudo isto. Diz.',
  st_g7v2_oU: 'Não sei. Mas fico.',
  st_g7v2_oQ: 'Se eu sair, para?',
  st_g7v2_oF: 'Eu não abri. Eu nasci.',
  st_g7v2_rU: '@eco Ficar é o que aperta.',
  st_g7v2_rQ: '@eco Experimenta.',
  st_g7v2_rF: '@eco Nascer. Foi isso que abriu.',

  st_g7v5_who: 'iris', st_g7v5_k: 'Achada',
  st_g7v5_1: '~No meio das rajadas, uma coisa parada. Não brilha. Está fria.',
  st_g7v5_2: '@faisca Íris.',
  st_g7v5_3: 'Não vem. Eu não esquento.',
  st_g7v5_4: '@faisca Eu não vim pelo calor.',
  st_g7v5_5: '~Você para. A tempestade passa por cima. Você não solta.',
  st_g7v5_6: '@faisca Sobe. Eu carrego.',
  st_g7v5_7: 'Você vai ficar lenta.',
  st_g7v5_8: '@faisca Eu já sou.',

  st_g7v8_who: 'poeira', st_g7v8_k: 'A torção',
  st_g7v8_1: '@eco O instante tinha um nome pequeno. Brasa disse. Ela não disse tudo.',
  st_g7v8_2: '@eco O instante não tinha o seu nome. O instante era você.',
  st_g7v8_3: '@faisca …Era eu.',
  st_g7v8_4: 'Ele não mente. Ele torce.',
  st_g7v8_5: '@faisca Torce o quê? Se o instante era eu, isto tudo é o que eu abri.',
  st_g7v8_6: 'Abriu. Não quebrou.',

  /* ---------------- chefes de sistema ---------------- */
  st_g7b1_ask: 'A direção muda a cada quatro anéis. Você escolhe ou obedece?',
  st_g7b1_oU: 'Obedeço. E escolho como.',
  st_g7b1_oQ: 'Quem muda a direção?',
  st_g7b1_oF: 'Escolho. Sempre.',
  st_g7b1_rU: 'Isso é escolher. O resto é vento.',
  st_g7b1_rQ: 'O aperto. Eu só sou o barulho dele.',
  st_g7b1_rF: 'Escolheu quatro vezes contra mim. Vamos ver a quinta.',

  st_g7b2_ask: 'Você está carregando uma coisa fria. Solta.',
  st_g7b2_oU: 'Não. Ela vem comigo.',
  st_g7b2_oQ: 'Fria esquenta de novo?',
  st_g7b2_oF: 'Solto quando eu quiser.',
  st_g7b2_rU: 'Então chega mais tarde. Mas chega.',
  st_g7b2_rQ: 'Devagar. Perto de alguém. Você é alguém?',
  st_g7b2_rF: 'A tempestade solta por você. Segura firme.',

  st_g7b3_1: '~Uma rajada tira Íris das suas costas. Você volta. Pega de novo.',
  st_g7b3_ask: 'Segunda vez. Vai ter uma terceira?',
  st_g7b3_oU: 'Quantas forem.',
  st_g7b3_oQ: 'Você faz de propósito?',
  st_g7b3_oF: 'Tenta de novo.',
  st_g7b3_rU: 'Vai ter. Eu sou rajada. Não sei fazer outra coisa.',
  st_g7b3_rQ: 'Não. Eu não escolho. Você escolhe.',
  st_g7b3_rF: '@iris Faísca. Me deixa. Eu não valho a volta.',

  st_g7b4_ask: 'Ele diz que eu sou por sua causa. Eu digo: pelo aperto. Em quem acredita?',
  st_g7b4_oU: 'Em você. Você não me odeia.',
  st_g7b4_oQ: 'Aperto de quê?',
  st_g7b4_oF: 'Em nenhum. Eu passo.',
  st_g7b4_rU: 'Não odeio. Sou só o que sobra quando o espaço aperta.',
  st_g7b4_rQ: 'De dois lados chegando perto. Eu sou o que sobra no meio.',
  st_g7b4_rF: 'Passa. Eu grito do mesmo jeito.',

  st_g7b5_who: 'casco', st_g7b5_k: 'Desde quando',
  st_g7b5_1: 'Tempestade. Você não existia quando eu passei aqui.',
  st_g7b5_2: '@guardiao Não existia aperto. Agora existe.',
  st_g7b5_3: 'Desde quando?',
  st_g7b5_4: '@guardiao Desde que quem segura começou a cansar.',
  st_g7b5_ask: '@guardiao Você sabia que alguém segurava?',
  st_g7b5_oU: 'Sabia. Casco leu nos anéis.',
  st_g7b5_oQ: 'Segura o quê, exatamente?',
  st_g7b5_oF: 'Segurar foi escolha deles.',
  st_g7b5_rU: '@guardiao Então sabe que cansa. Eu sou o cansaço, soprando.',
  st_g7b5_rQ: '@guardiao A beirada. Não sei por quê. Sei que aperta quando afrouxa.',
  st_g7b5_rF: '@guardiao Foi. Cansar não é.',

  st_g7b6_k: 'A medida',
  st_g7b6_1: '~A linha, lá em cima. Casco mede com o dedo.',
  st_g7b6_2: '@casco Na Névoa cabiam nove anéis nela. Hoje cabem sete.',
  st_g7b6_ask: 'Sete. Quantos cabem antes de não caber nenhum?',
  st_g7b6_oU: 'Não sei. Chego antes.',
  st_g7b6_oQ: 'Isso dá para calcular?',
  st_g7b6_oF: 'Os que eu precisar.',
  st_g7b6_rU: 'Vai. Para lá a rajada empurra. Eu nunca empurrei a favor.',
  st_g7b6_rQ: '@casco Dá. Eu não quero.',
  st_g7b6_rF: 'Não é você que decide quantos. É quem segura.',

  st_g7b7_k: 'Um grau',
  st_g7b7_1: '@iris Você parou de novo. Por mim.',
  st_g7b7_2: '@faisca Eu paro quantas vezes for.',
  st_g7b7_3: '@iris …Você é esquisita.',
  st_g7b7_4: '@faisca Eu sei.',
  st_g7b7_ask: 'Ela esquentou um grau. Você sentiu?',
  st_g7b7_oU: 'Senti. Nas costas.',
  st_g7b7_oQ: 'Frio volta a ser quente?',
  st_g7b7_oF: 'Não importa. Ela vem.',
  st_g7b7_rU: 'Nas costas é onde se sente. Nunca na frente.',
  st_g7b7_rQ: 'Volta devagar. Você é o devagar dela.',
  st_g7b7_rF: 'Importa para ela. Ela ouviu.',

  st_g7b8_k: 'Seis',
  st_g7b8_1: '@eco Faísca. Sete anéis. Seis, agora.',
  st_g7b8_2: '@eco Cada um que você passa, aperta.',
  st_g7b8_ask: '@eco Você quer que eles cansem?',
  st_g7b8_oU: 'Não. Quero chegar antes.',
  st_g7b8_oQ: 'Eles cansam por minha causa?',
  st_g7b8_oF: 'Eles aguentam. Eu conheço.',
  st_g7b8_rU: '@eco Chegar é apertar mais.',
  st_g7b8_rQ: '@eco Você perguntou. Então acha que sim.',
  st_g7b8_rF: '@eco Você nunca viu os dois. Como conhece?',

  st_g7b9_k: 'Beirada',
  st_g7b9_1: '@poeira A tempestade não é contra. É barulho de aperto.',
  st_g7b9_2: '@faisca Você entende ela?',
  st_g7b9_3: '@poeira Eu sou de beirada. Beirada faz barulho quando aperta.',
  st_g7b9_ask: 'O grão me entende. Você me entende?',
  st_g7b9_oU: 'Entendo. Você dói e não quer.',
  st_g7b9_oQ: 'Você quer parar?',
  st_g7b9_oF: 'Não preciso entender. Preciso passar.',
  st_g7b9_rU: 'É isso. Guarde para quando for você.',
  st_g7b9_rQ: 'Quero. Paro quando afrouxar. Ou quando fechar.',
  st_g7b9_rF: 'Passa. Passar também é resposta. Ruim, mas é.',

  /* ---------------- chefe da galáxia ---------------- */
  st_g7b10_k: 'Tempestade',
  st_g7b10_1: '~A tempestade fala em rajadas. Cada frase vem de um lado diferente.',
  st_g7b10_2: 'Eu não sou vento. Eu sou espaço apertado gritando.',
  st_g7b10_3: 'Alguém está fechando. Não sou eu. Não é você.',
  st_g7b10_4: '@eco Está fechando porque ela está aqui.',
  st_g7b10_5: '@faisca Se eu sair, para?',
  st_g7b10_6: '@eco Experimenta.',
  st_g7b10_ask: 'Ele diz que é você. Você acredita?',
  st_g7b10_oU: 'Não sei. Mas eu fico.',
  st_g7b10_oQ: 'Quem está fechando, então?',
  st_g7b10_oF: 'Se fui eu, eu abro de novo.',
  st_g7b10_rU: 'Ficar é a única resposta que o vento não leva.',
  st_g7b10_rQ: 'Quem segura. E quem segura cansa. Só isso.',
  st_g7b10_rF: 'Abrir se faz uma vez. Segurar é todo dia.',

  /* ---------------- carta ---------------- */
  st_g7c_who: 'vela', st_g7c_k: 'A carta curta',
  st_g7c_1: '~Colado num anel torto pelo vento, um bilhete curto.',
  st_g7c_2: 'Faísca: está pesado.',
  st_g7c_3: 'Não é por sua causa.',
  st_g7c_4: '— V.',
  st_g7c_5: '~Na margem, quase apagada:',
  st_g7c_6: '@ancora vale',
  st_g7c_7: '@poeira Ele está cansado.',
  st_g7c_8: '@faisca Então eu tenho que chegar.',
  st_g7c_9: '@casco Carregando.',
  st_g7c_10: '@faisca Carregando.'
});

Object.assign(HR.I18N.en, {
  st_g7_who: 'casco',
  st_g7_k: 'Chapter 7 · The Storm',
  st_g7_1: '~The sky changes direction without warning. Nothing stays where it was.',
  st_g7_2: '~Up above, the line. It is shorter than it was in the Mist.',
  st_g7_3: 'Kid. The line. It used to be longer.',
  st_g7_ask: 'Did you notice?',
  st_g7_oU: 'I did. I said nothing.',
  st_g7_oQ: 'Can a line close?',
  st_g7_oF: 'It is the storm. It is far.',
  st_g7_rU: 'Neither did I. Now it is said.',
  st_g7_rQ: 'It closes. By the scratches, someone holds it so it won’t.',
  st_g7_rF: 'I read rings my whole life. It is not the storm.',

  st_g7v2_k: 'The voice returns',
  st_g7v2_1: '~The storm opens a corridor. Inside it, a voice you know.',
  st_g7v2_2: '@eco Spark. It is closing. You saw.',
  st_g7v2_3: '@eco It is closing because you are here.',
  st_g7v2_4: '@faisca Here where?',
  st_g7v2_5: '@eco In here. Taking up room.',
  st_g7v2_ask: '@eco You know what opened all this. Say it.',
  st_g7v2_oU: 'I do not know. But I stay.',
  st_g7v2_oQ: 'If I leave, does it stop?',
  st_g7v2_oF: 'I opened nothing. I was born.',
  st_g7v2_rU: '@eco Staying is what tightens it.',
  st_g7v2_rQ: '@eco Try it.',
  st_g7v2_rF: '@eco Born. That is what opened it.',

  st_g7v5_who: 'iris', st_g7v5_k: 'Found',
  st_g7v5_1: '~In the middle of the gusts, something still. It does not shine. It is cold.',
  st_g7v5_2: '@faisca Iris.',
  st_g7v5_3: 'Do not come. I do not warm anything.',
  st_g7v5_4: '@faisca I did not come for the warmth.',
  st_g7v5_5: '~You stop. The storm runs over you. You do not let go.',
  st_g7v5_6: '@faisca Climb on. I will carry you.',
  st_g7v5_7: 'You will be slow.',
  st_g7v5_8: '@faisca I already am.',

  st_g7v8_who: 'poeira', st_g7v8_k: 'The twist',
  st_g7v8_1: '@eco The instant had a small name. Ember said so. She did not say all of it.',
  st_g7v8_2: '@eco The instant did not have your name. The instant was you.',
  st_g7v8_3: '@faisca …It was me.',
  st_g7v8_4: 'He does not lie. He twists.',
  st_g7v8_5: '@faisca Twists what? If the instant was me, all this is what I opened.',
  st_g7v8_6: 'Opened. Did not break.',

  st_g7b1_ask: 'Direction changes every four rings. Do you choose, or obey?',
  st_g7b1_oU: 'I obey. And I choose how.',
  st_g7b1_oQ: 'Who changes the direction?',
  st_g7b1_oF: 'I choose. Always.',
  st_g7b1_rU: 'That is choosing. The rest is wind.',
  st_g7b1_rQ: 'The squeeze. I am only the noise of it.',
  st_g7b1_rF: 'You chose four times against me. Let us see the fifth.',

  st_g7b2_ask: 'You are carrying something cold. Drop it.',
  st_g7b2_oU: 'No. She comes with me.',
  st_g7b2_oQ: 'Does cold warm up again?',
  st_g7b2_oF: 'I drop her when I want.',
  st_g7b2_rU: 'Then you arrive later. But you arrive.',
  st_g7b2_rQ: 'Slowly. Near someone. Are you someone?',
  st_g7b2_rF: 'The storm drops her for you. Hold tight.',

  st_g7b3_1: '~A gust tears Iris off your back. You turn around. You pick her up again.',
  st_g7b3_ask: 'Second time. Will there be a third?',
  st_g7b3_oU: 'As many as it takes.',
  st_g7b3_oQ: 'Do you do it on purpose?',
  st_g7b3_oF: 'Try it again.',
  st_g7b3_rU: 'There will be. I am a gust. I know nothing else.',
  st_g7b3_rQ: 'No. I do not choose. You choose.',
  st_g7b3_rF: '@iris Spark. Leave me. I am not worth the trip back.',

  st_g7b4_ask: 'He says I am your doing. I say it is the squeeze. Who do you believe?',
  st_g7b4_oU: 'You. You do not hate me.',
  st_g7b4_oQ: 'A squeeze of what?',
  st_g7b4_oF: 'Neither. I pass.',
  st_g7b4_rU: 'I do not. I am only what is left when space tightens.',
  st_g7b4_rQ: 'Two sides coming closer. I am what is left in between.',
  st_g7b4_rF: 'Pass. I scream all the same.',

  st_g7b5_who: 'casco', st_g7b5_k: 'Since when',
  st_g7b5_1: 'Storm. You did not exist when I came through here.',
  st_g7b5_2: '@guardiao There was no squeeze. Now there is.',
  st_g7b5_3: 'Since when?',
  st_g7b5_4: '@guardiao Since the ones holding started to tire.',
  st_g7b5_ask: '@guardiao Did you know someone was holding?',
  st_g7b5_oU: 'Hull read it in the rings.',
  st_g7b5_oQ: 'Holding what, exactly?',
  st_g7b5_oF: 'Holding was their choice.',
  st_g7b5_rU: '@guardiao Then you know it tires. I am the tiredness, blowing.',
  st_g7b5_rQ: '@guardiao The rim. I do not know why. It tightens when they slip.',
  st_g7b5_rF: '@guardiao It was. Tiring is not.',

  st_g7b6_k: 'The measure',
  st_g7b6_1: '~The line, up above. Hull measures it with his finger.',
  st_g7b6_2: '@casco In the Mist, nine rings fit along it. Today seven do.',
  st_g7b6_ask: 'Seven. How many fit before none do?',
  st_g7b6_oU: 'I do not know. I arrive first.',
  st_g7b6_oQ: 'Can that be worked out?',
  st_g7b6_oF: 'As many as I need.',
  st_g7b6_rU: 'Go. That way the gust pushes. I never pushed in anyone favor.',
  st_g7b6_rQ: '@casco It can. I do not want to.',
  st_g7b6_rF: 'You do not decide how many. The ones holding do.',

  st_g7b7_k: 'One degree',
  st_g7b7_1: '@iris You stopped again. For me.',
  st_g7b7_2: '@faisca I will stop as many times as it takes.',
  st_g7b7_3: '@iris …You are strange.',
  st_g7b7_4: '@faisca I know.',
  st_g7b7_ask: 'She warmed by one degree. Did you feel it?',
  st_g7b7_oU: 'I felt it. On my back.',
  st_g7b7_oQ: 'Does cold turn warm again?',
  st_g7b7_oF: 'It does not matter. She is coming.',
  st_g7b7_rU: 'The back is where it is felt. Never the front.',
  st_g7b7_rQ: 'Slowly. You are her slowly.',
  st_g7b7_rF: 'It matters to her. She heard you.',

  st_g7b8_k: 'Six',
  st_g7b8_1: '@eco Spark. Seven rings. Six, now.',
  st_g7b8_2: '@eco Every one you pass tightens it.',
  st_g7b8_ask: '@eco Do you want them to tire?',
  st_g7b8_oU: 'No. I want to arrive first.',
  st_g7b8_oQ: 'Do they tire because of me?',
  st_g7b8_oF: 'They can take it. I know them.',
  st_g7b8_rU: '@eco Arriving tightens it more.',
  st_g7b8_rQ: '@eco You asked. So you think so.',
  st_g7b8_rF: '@eco You never saw the two of them. How do you know them?',

  st_g7b9_k: 'Rim',
  st_g7b9_1: '@poeira The storm is not against you. It is the noise of tightening.',
  st_g7b9_2: '@faisca Do you understand her?',
  st_g7b9_3: '@poeira I am from the rim. A rim makes noise when it tightens.',
  st_g7b9_ask: 'The speck understands me. Do you?',
  st_g7b9_oU: 'You hurt. You did not want to.',
  st_g7b9_oQ: 'Do you want to stop?',
  st_g7b9_oF: 'No need. I need to pass.',
  st_g7b9_rU: 'That is it. Keep that for when it is you.',
  st_g7b9_rQ: 'I do. I stop when it slackens. Or when it closes.',
  st_g7b9_rF: 'Pass. Passing is an answer too. A poor one.',

  st_g7b10_k: 'Storm',
  st_g7b10_1: '~The storm speaks in gusts. Each sentence comes from a different side.',
  st_g7b10_2: 'I am not wind. I am tight space, screaming.',
  st_g7b10_3: 'Someone is closing it. Not me. Not you.',
  st_g7b10_4: '@eco It is closing because she is here.',
  st_g7b10_5: '@faisca If I leave, does it stop?',
  st_g7b10_6: '@eco Try it.',
  st_g7b10_ask: 'He says it is you. Do you believe him?',
  st_g7b10_oU: 'I do not know. But I stay.',
  st_g7b10_oQ: 'Who is closing it, then?',
  st_g7b10_oF: 'Then I open it again.',
  st_g7b10_rU: 'Staying is the one answer the wind cannot carry off.',
  st_g7b10_rQ: 'The ones holding. And holding tires. That is all.',
  st_g7b10_rF: 'Opening is done once. Holding is every day.',

  st_g7c_who: 'vela', st_g7c_k: 'The short letter',
  st_g7c_1: '~Stuck to a ring bent by the wind, a short note.',
  st_g7c_2: 'Spark: it is heavy.',
  st_g7c_3: 'It is not because of you.',
  st_g7c_4: '— S.',
  st_g7c_5: '~In the margin, almost faded:',
  st_g7c_6: '@ancora worth it',
  st_g7c_7: '@poeira He is tired.',
  st_g7c_8: '@faisca Then I have to get there.',
  st_g7c_9: '@casco Carrying her.',
  st_g7c_10: '@faisca Carrying her.'
});

Object.assign(HR.I18N.es, {
  st_g7_who: 'casco',
  st_g7_k: 'Capítulo 7 · La Tormenta',
  st_g7_1: '~El cielo cambia de dirección sin avisar. Nada se queda donde estaba.',
  st_g7_2: '~Allá arriba, la línea. Está más corta que en la Niebla.',
  st_g7_3: 'Niña. La línea. Era más grande.',
  st_g7_ask: '¿Te diste cuenta?',
  st_g7_oU: 'Sí. No quise decirlo.',
  st_g7_oQ: '¿Una línea se cierra?',
  st_g7_oF: 'Es la tormenta. Está lejos.',
  st_g7_rU: 'Yo tampoco. Ya está dicho.',
  st_g7_rQ: 'Se cierra. Por las rayas, alguien la sujeta para que no.',
  st_g7_rF: 'Leí aros toda mi vida. No es la tormenta.',

  st_g7v2_k: 'La voz vuelve',
  st_g7v2_1: '~La tormenta abre un pasillo. Dentro, una voz que conoces.',
  st_g7v2_2: '@eco Chispa. Se está cerrando. Lo viste.',
  st_g7v2_3: '@eco Se cierra porque tú estás aquí.',
  st_g7v2_4: '@faisca ¿Aquí dónde?',
  st_g7v2_5: '@eco Aquí dentro. Ocupando.',
  st_g7v2_ask: '@eco Sabes qué abrió todo esto. Dilo.',
  st_g7v2_oU: 'No sé. Pero me quedo.',
  st_g7v2_oQ: 'Si me voy, ¿para?',
  st_g7v2_oF: 'Yo no abrí. Yo nací.',
  st_g7v2_rU: '@eco Quedarse es lo que aprieta.',
  st_g7v2_rQ: '@eco Pruébalo.',
  st_g7v2_rF: '@eco Nacer. Eso fue lo que abrió.',

  st_g7v5_who: 'iris', st_g7v5_k: 'Encontrada',
  st_g7v5_1: '~Entre las ráfagas, algo quieto. No brilla. Está frío.',
  st_g7v5_2: '@faisca Iris.',
  st_g7v5_3: 'No vengas. Yo no caliento.',
  st_g7v5_4: '@faisca No vine por el calor.',
  st_g7v5_5: '~Te detienes. La tormenta te pasa por encima. No la sueltas.',
  st_g7v5_6: '@faisca Sube. Yo te llevo.',
  st_g7v5_7: 'Vas a ir lenta.',
  st_g7v5_8: '@faisca Ya lo soy.',

  st_g7v8_who: 'poeira', st_g7v8_k: 'La torcedura',
  st_g7v8_1: '@eco El instante tenía un nombre pequeño. Brasa lo dijo. No lo dijo todo.',
  st_g7v8_2: '@eco El instante no tenía tu nombre. El instante eras tú.',
  st_g7v8_3: '@faisca …Era yo.',
  st_g7v8_4: 'Él no miente. Él tuerce.',
  st_g7v8_5: '@faisca ¿Tuerce qué? Si el instante era yo, todo esto lo abrí yo.',
  st_g7v8_6: 'Abrió. No rompió.',

  st_g7b1_ask: 'La dirección cambia cada cuatro aros. ¿Eliges u obedeces?',
  st_g7b1_oU: 'Obedezco. Y elijo cómo.',
  st_g7b1_oQ: '¿Quién cambia la dirección?',
  st_g7b1_oF: 'Elijo. Siempre.',
  st_g7b1_rU: 'Eso es elegir. Lo demás es viento.',
  st_g7b1_rQ: 'El apretón. Yo solo soy su ruido.',
  st_g7b1_rF: 'Elegiste cuatro veces contra mí. Veamos la quinta.',

  st_g7b2_ask: 'Llevas algo frío encima. Suéltalo.',
  st_g7b2_oU: 'No. Ella viene conmigo.',
  st_g7b2_oQ: '¿Lo frío vuelve a calentar?',
  st_g7b2_oF: 'La suelto cuando quiera.',
  st_g7b2_rU: 'Entonces llegas más tarde. Pero llegas.',
  st_g7b2_rQ: 'Despacio. Cerca de alguien. ¿Tú eres alguien?',
  st_g7b2_rF: 'La tormenta la suelta por ti. Agárrala fuerte.',

  st_g7b3_1: '~Una ráfaga arranca a Iris de tu espalda. Vuelves. La recoges otra vez.',
  st_g7b3_ask: 'Segunda vez. ¿Habrá una tercera?',
  st_g7b3_oU: 'Las que hagan falta.',
  st_g7b3_oQ: '¿Lo haces a propósito?',
  st_g7b3_oF: 'Inténtalo otra vez.',
  st_g7b3_rU: 'La habrá. Soy ráfaga. No sé hacer otra cosa.',
  st_g7b3_rQ: 'No. Yo no elijo. Tú eliges.',
  st_g7b3_rF: '@iris Chispa. Déjame. No valgo la vuelta.',

  st_g7b4_ask: 'Él dice que soy cosa tuya. Yo digo que del apretón. ¿A quién crees?',
  st_g7b4_oU: 'A ti. Tú no me odias.',
  st_g7b4_oQ: '¿Apretón de qué?',
  st_g7b4_oF: 'A ninguno. Yo paso.',
  st_g7b4_rU: 'No te odio. Soy lo que queda cuando el espacio aprieta.',
  st_g7b4_rQ: 'Dos lados acercándose. Yo soy lo que queda en medio.',
  st_g7b4_rF: 'Pasa. Grito igual.',

  st_g7b5_who: 'casco', st_g7b5_k: 'Desde cuándo',
  st_g7b5_1: 'Tormenta. Tú no existías cuando pasé por aquí.',
  st_g7b5_2: '@guardiao No había apretón. Ahora lo hay.',
  st_g7b5_3: '¿Desde cuándo?',
  st_g7b5_4: '@guardiao Desde que quien sujeta empezó a cansarse.',
  st_g7b5_ask: '@guardiao ¿Sabías que alguien sujetaba?',
  st_g7b5_oU: 'Sí. Casco lo leyó en los aros.',
  st_g7b5_oQ: '¿Sujeta qué, exactamente?',
  st_g7b5_oF: 'Sujetar fue elección suya.',
  st_g7b5_rU: '@guardiao Entonces sabes que cansa. Yo soy el cansancio soplando.',
  st_g7b5_rQ: '@guardiao El borde. No sé por qué. Aprieta cuando aflojan.',
  st_g7b5_rF: '@guardiao Lo fue. Cansarse no.',

  st_g7b6_k: 'La medida',
  st_g7b6_1: '~La línea, allá arriba. Casco la mide con el dedo.',
  st_g7b6_2: '@casco En la Niebla cabían nueve aros en ella. Hoy caben siete.',
  st_g7b6_ask: 'Siete. ¿Cuántos caben antes de que no quepa ninguno?',
  st_g7b6_oU: 'No sé. Llego antes.',
  st_g7b6_oQ: '¿Eso se puede calcular?',
  st_g7b6_oF: 'Los que me hagan falta.',
  st_g7b6_rU: 'Ve. Para allá la ráfaga empuja. Nunca empujé a favor.',
  st_g7b6_rQ: '@casco Se puede. No quiero.',
  st_g7b6_rF: 'No decides tú cuántos. Decide quien sujeta.',

  st_g7b7_k: 'Un grado',
  st_g7b7_1: '@iris Paraste otra vez. Por mí.',
  st_g7b7_2: '@faisca Paro las veces que haga falta.',
  st_g7b7_3: '@iris …Eres rara.',
  st_g7b7_4: '@faisca Lo sé.',
  st_g7b7_ask: 'Ella calentó un grado. ¿Lo sentiste?',
  st_g7b7_oU: 'Lo sentí. En la espalda.',
  st_g7b7_oQ: '¿Lo frío vuelve a ser caliente?',
  st_g7b7_oF: 'Da igual. Ella viene.',
  st_g7b7_rU: 'En la espalda es donde se siente. Nunca de frente.',
  st_g7b7_rQ: 'Vuelve despacio. Tú eres su despacio.',
  st_g7b7_rF: 'A ella le importa. Te oyó.',

  st_g7b8_k: 'Seis',
  st_g7b8_1: '@eco Chispa. Siete aros. Seis, ahora.',
  st_g7b8_2: '@eco Cada uno que pasas, aprieta.',
  st_g7b8_ask: '@eco ¿Quieres que se cansen?',
  st_g7b8_oU: 'No. Quiero llegar antes.',
  st_g7b8_oQ: '¿Se cansan por mí?',
  st_g7b8_oF: 'Aguantan. Yo los conozco.',
  st_g7b8_rU: '@eco Llegar aprieta más.',
  st_g7b8_rQ: '@eco Preguntaste. Entonces crees que sí.',
  st_g7b8_rF: '@eco Nunca viste a los dos. ¿Cómo los conoces?',

  st_g7b9_k: 'Borde',
  st_g7b9_1: '@poeira La tormenta no está en contra. Es ruido de apretón.',
  st_g7b9_2: '@faisca ¿Tú la entiendes?',
  st_g7b9_3: '@poeira Soy de borde. El borde hace ruido cuando aprieta.',
  st_g7b9_ask: 'El grano me entiende. ¿Tú me entiendes?',
  st_g7b9_oU: 'Sí. Te duele y no querías.',
  st_g7b9_oQ: '¿Quieres parar?',
  st_g7b9_oF: 'No necesito entender. Necesito pasar.',
  st_g7b9_rU: 'Eso es. Guárdalo para cuando te toque.',
  st_g7b9_rQ: 'Quiero. Paro cuando afloje. O cuando cierre.',
  st_g7b9_rF: 'Pasa. Pasar también es respuesta. Mala, pero lo es.',

  st_g7b10_k: 'Tormenta',
  st_g7b10_1: '~La tormenta habla en ráfagas. Cada frase viene de un lado distinto.',
  st_g7b10_2: 'No soy viento. Soy espacio apretado gritando.',
  st_g7b10_3: 'Alguien está cerrando. No soy yo. No eres tú.',
  st_g7b10_4: '@eco Se cierra porque ella está aquí.',
  st_g7b10_5: '@faisca Si me voy, ¿para?',
  st_g7b10_6: '@eco Pruébalo.',
  st_g7b10_ask: 'Él dice que eres tú. ¿Le crees?',
  st_g7b10_oU: 'No sé. Pero me quedo.',
  st_g7b10_oQ: '¿Quién cierra, entonces?',
  st_g7b10_oF: 'Si fui yo, abro otra vez.',
  st_g7b10_rU: 'Quedarse es la única respuesta que el viento no se lleva.',
  st_g7b10_rQ: 'Quien sujeta. Y quien sujeta se cansa. Nada más.',
  st_g7b10_rF: 'Abrir se hace una vez. Sujetar es todos los días.',

  st_g7c_who: 'vela', st_g7c_k: 'La carta corta',
  st_g7c_1: '~Pegada a un aro torcido por el viento, una nota corta.',
  st_g7c_2: 'Chispa: pesa.',
  st_g7c_3: 'No es por ti.',
  st_g7c_4: '— V.',
  st_g7c_5: '~En el margen, casi borrada:',
  st_g7c_6: '@ancora vale',
  st_g7c_7: '@poeira Está cansado.',
  st_g7c_8: '@faisca Entonces tengo que llegar.',
  st_g7c_9: '@casco Cargándola.',
  st_g7c_10: '@faisca Cargándola.'
});
