/* =====================================================================
   ORBO v8 — texto da história: Galáxia 9 (O Ciclone · Ciclone).
   Ver docs/HISTORIA_V7.md e a crítica (secao 9.5).

   O fundo do poço.
   O degrau: fechar o rasgo apaga tudo, inclusive ela. Dentro só existe
   enquanto houver beira.
   O que acontece:
     - Poeira encosta na beirada e não apaga: ela é um farelo da mãe que
       caiu para dentro. E diz o que ninguém disse ainda: alguém quis;
     - Casco entra num anel que fecha e segura para ela passar. Dessa vez
       ele segura — é o avesso exato do que ele nao fez com Brasa;
     - o Eco perde as vozes emprestadas e usa a dela. Poeira desmascara
       com uma regra: você não pede para sumir;
     - Íris volta a voar, devagar, do lado dela;
     - as onze luzes paradas à frente são os onze que o Guardião perdeu;
     - não há carta. Só uma palavra na beirada, com a letra leve: "vem".
   ===================================================================== */
Object.assign(HR.I18N.pt, {
  /* ---------------- entrada ---------------- */
  st_g9_who: 'casco',
  st_g9_k: 'Capítulo 9 · O Ciclone',
  st_g9_1: '~Tudo ao mesmo tempo: sobe, gira, troca de lado. É o espaço apertando.',
  st_g9_2: '~A linha lá em cima virou uma fresta. Dá para ver a beirada dos dois lados.',
  st_g9_3: 'É aqui que fecha, menina. Dá para ver a beira.',
  st_g9_ask: 'Se fechar, o que fica do lado de dentro?',
  st_g9_oU: 'Nada. Nem eu.',
  st_g9_oQ: 'E do lado de fora?',
  st_g9_oF: 'Eu abro de novo.',
  st_g9_rU: 'Nem você. Foi o que eu li. Não quis ler.',
  st_g9_rQ: 'Os dois. Encostados. Como antes de você.',
  st_g9_rF: 'Você nunca abriu nada, menina. Você nasceu.',

  /* ---------------- visitas ---------------- */
  st_g9v6_who: 'poeira', st_g9v6_k: 'A beirada',
  st_g9v6_1: '~Poeira vai até a beirada do Vórtice. Encosta. Não apaga.',
  st_g9v6_2: 'Eu encostei. Ela é morna.',
  st_g9v6_3: '@faisca Como você não apagou?',
  st_g9v6_4: 'Eu sou dela. Um farelo que caiu para dentro.',
  st_g9v6_5: '@faisca Desde quando você sabe?',
  st_g9v6_6: 'Desde "mãe".',
  st_g9v6_7: '~E depois, mais baixo:',
  st_g9v6_8: 'Um não vira dois sozinho. Alguém quis.',

  st_g9v3_who: 'casco', st_g9v3_k: 'Dessa vez ele segura',
  st_g9v3_1: '~Um anel começa a fechar antes de você chegar. Casco entra nele e segura.',
  st_g9v3_2: 'Passa.',
  st_g9v3_3: '@faisca Casco, vem.',
  st_g9v3_4: 'Dessa vez eu seguro. Passa, menina.',
  st_g9v3_5: '@faisca Você disse que ia junto!',
  st_g9v3_6: 'Eu fui. Até aqui.',
  st_g9v3_7: '~Você passa. Atrás, o anel fica aberto. Ele não.',

  st_g9v9_who: 'poeira', st_g9v9_k: 'A voz dela',
  st_g9v9_1: '~Nenhuma cara. Nenhuma voz emprestada. A voz é a sua.',
  st_g9v9_2: '@eco Sou eu. Você.',
  st_g9v9_3: '@eco Se eu sumir, fecha devagar. Eles descansam.',
  st_g9v9_4: 'Não é ela.',
  st_g9v9_5: '@faisca Como sabe?',
  st_g9v9_6: 'Você não pede para sumir.',
  st_g9v9_ask: '@eco Você quer que eles descansem?',
  st_g9v9_oU: 'Quero. Mais que tudo.',
  st_g9v9_oQ: 'Descansar é se encostar?',
  st_g9v9_oF: 'Quero que eles me vejam.',
  st_g9v9_rU: '@eco Então some.',
  st_g9v9_rQ: '@eco E você no meio atrapalha.',
  st_g9v9_rF: '@eco Eles nunca te viram. Só o buraco.',

  /* ---------------- chefes de sistema ---------------- */
  st_g9b1_ask: 'Eu puxo para o meio. Você sente?',
  st_g9b1_oU: 'Sinto. Não vou.',
  st_g9b1_oQ: 'Puxa para quem?',
  st_g9b1_oF: 'Puxa. Eu passo.',
  st_g9b1_rU: 'Todos sentem. Poucos dizem "não vou".',
  st_g9b1_rQ: 'Para os dois. Eles puxam. Eu giro.',
  st_g9b1_rF: 'Passa. Eu não sou parede. Sou vontade.',

  st_g9b2_ask: 'Aqui todo mundo fica por alguém. Você ficaria?',
  st_g9b2_oU: 'Já parei por alguém. Duas vezes.',
  st_g9b2_oQ: 'Ficar é o mesmo que segurar?',
  st_g9b2_oF: 'Não. Eu passo por todo mundo.',
  st_g9b2_rU: 'Então você sabe o que é. Cansaço com direção.',
  st_g9b2_rQ: 'É. Ficar é segurar sem mãos.',
  st_g9b2_rF: 'Passar por todos é chegar sozinha. Você quer isso?',

  st_g9b3_1: '@poeira Ciclone. Você puxa a beira. Eu sou da beira.',
  st_g9b3_2: 'Então eu te puxo para casa.',
  st_g9b3_3: '@poeira Casa é aqui dentro.',
  st_g9b3_ask: 'O grão escolheu dentro. Você escolheria fora?',
  st_g9b3_oU: 'Não. Eu escolho os dois.',
  st_g9b3_oQ: 'Dá para escolher os dois?',
  st_g9b3_oF: 'Fora. Sempre quis sair.',
  st_g9b3_rU: 'Dois não se escolhe. Se segura. Como eles.',
  st_g9b3_rQ: 'Dá para tentar. Custa o que eles pagam.',
  st_g9b3_rF: 'Sair é fechar. Você sabe disso agora.',

  st_g9b4_k: 'Fechou, não tem dentro',
  st_g9b4_1: '~Casco não está. O lugar dele no caminho fica vazio de um jeito específico.',
  st_g9b4_ask: 'Se as duas beiradas se encostam, o que fica?',
  st_g9b4_oU: 'Eles. Só eles.',
  st_g9b4_oQ: 'E o que está dentro?',
  st_g9b4_oF: 'Eu. Eu sempre fico.',
  st_g9b4_rU: 'Eles. Sem espaço. Sem tudo isto.',
  st_g9b4_rQ: 'Dentro só existe enquanto tem beira. Fechou, não tem dentro.',
  st_g9b4_rF: 'Você fica onde? Não sobra onde.',

  st_g9b5_k: 'Devagar',
  st_g9b5_1: '@iris Me solta aqui. Eu consigo voar um pouco.',
  st_g9b5_2: '@faisca Você está fria.',
  st_g9b5_3: '@iris Estou morna. Aprendi com uma lenta.',
  st_g9b5_4: '~Ela voa ao seu lado. Devagar. É a primeira vez que ela voa devagar.',
  st_g9b5_ask: 'Íris voa no seu ritmo. Você a puxou para baixo?',
  st_g9b5_oU: 'Não. Ela veio.',
  st_g9b5_oQ: 'Ritmo é para baixo?',
  st_g9b5_oF: 'Puxei. Precisava dela.',
  st_g9b5_rU: 'Veio. Aqui tudo é puxado. Ela veio.',
  st_g9b5_rQ: 'Para o lado. É a única direção que eu não faço.',
  st_g9b5_rF: '@iris Ninguém me puxa. Eu vim.',

  st_g9b6_k: 'O anel que ficou',
  st_g9b6_1: '~O anel que Casco segurou ainda está lá atrás, aberto, pequeno.',
  st_g9b6_2: '@eco Ele ficou por você. Olha o que custa você.',
  st_g9b6_3: '@poeira Ele ficou por ele. Ele disse.',
  st_g9b6_ask: 'Você volta para buscar o velho?',
  st_g9b6_oU: 'Volto. Depois da porta.',
  st_g9b6_oQ: 'Dá para voltar?',
  st_g9b6_oF: 'Não. Ele escolheu.',
  st_g9b6_rU: 'Depois da porta não tem "depois". Você sabe.',
  st_g9b6_rQ: 'Dá. Enquanto tiver dentro.',
  st_g9b6_rF: 'Escolheu. E você escolheu deixar. As duas contam.',

  st_g9b7_k: 'Com a voz dela',
  st_g9b7_1: '@eco Casco ficou. Íris queimou. O Cardume foi.',
  st_g9b7_2: '@eco Tudo que encosta em você fica menos.',
  st_g9b7_ask: '@eco Eu sou a coisa que custa. Diz que não.',
  st_g9b7_oU: 'Não é. Custa e vale.',
  st_g9b7_oQ: 'Quem te ensinou "custa"?',
  st_g9b7_oF: 'Cala a boca.',
  st_g9b7_rU: '@eco "Vale". Palavra dela. Não sua.',
  st_g9b7_rQ: '@eco Você. Na Forja. "Tudo custa."',
  st_g9b7_rF: '@eco Calei. Você continua ouvindo.',

  st_g9b8_ask: 'Se você chegar na porta e ela abrir, quem fecha atrás?',
  st_g9b8_oU: 'Eu. Se for preciso.',
  st_g9b8_oQ: 'Porta se fecha por dentro?',
  st_g9b8_oF: 'Que fique aberta.',
  st_g9b8_rU: 'Então você já entendeu o velho.',
  st_g9b8_rQ: 'Por fora. Só por fora. Eles estão do lado de fora.',
  st_g9b8_rF: 'Aberta cansa quem segura. Fechada apaga. Escolha uma.',

  st_g9b9_k: 'Os onze',
  st_g9b9_1: '@iris Lá na frente tem luzes paradas. Onze. Não entram.',
  st_g9b9_2: '@faisca Onze.',
  st_g9b9_3: '@poeira Os do Guardião.',
  st_g9b9_ask: 'Eles chegaram na porta e não escolheram. Você vai escolher?',
  st_g9b9_oU: 'Vou. Não sei o quê.',
  st_g9b9_oQ: 'Escolher sem saber é escolher?',
  st_g9b9_oF: 'Vou. Já escolhi.',
  st_g9b9_rU: 'É o bastante. Eles não sabiam nem isso.',
  st_g9b9_rQ: 'É o único jeito. Saber vem depois.',
  st_g9b9_rF: 'Cuidado. Os onze também tinham.',

  /* ---------------- chefe da galáxia ---------------- */
  st_g9b10_k: 'Ciclone',
  st_g9b10_1: '~O Ciclone é o puxão dos dois lados, girando no meio.',
  st_g9b10_2: 'Eu não quero nada. Eu sou o querer deles.',
  st_g9b10_3: 'Eles querem se encostar. Eu puxo.',
  st_g9b10_4: '@faisca E eu?',
  st_g9b10_5: 'Você é o que está entre.',
  st_g9b10_6: '@eco Sai do meio, e eles descansam.',
  st_g9b10_ask: 'Sai do caminho?',
  st_g9b10_oU: 'Não. Eu sou o caminho.',
  st_g9b10_oQ: 'Se eu sair, eles descansam?',
  st_g9b10_oF: 'Eu passo. Você é só vento.',
  st_g9b10_rU: 'Então vai ter que segurar. Sozinha, por enquanto.',
  st_g9b10_rQ: 'Descansam. E apagam tudo que você viu.',
  st_g9b10_rF: 'Vento é o que sobra quando alguém sai. Passa. Eu continuo.',

  /* ---------------- a palavra ---------------- */
  st_g9c_who: 'ancora', st_g9c_k: 'Uma palavra',
  st_g9c_1: '~Não tem bilhete. A beirada do Vórtice está perto o bastante para ler.',
  st_g9c_2: '~Nela, com a letra leve, uma palavra só:',
  st_g9c_3: '@ancora vem',
  st_g9c_4: '@poeira É ela. Ela chama.',
  st_g9c_5: '@faisca Vem para onde? Se eu for, fecha.',
  st_g9c_6: '@poeira Vem não é fecha.',
  st_g9c_7: '@iris Então vamos.'
});

Object.assign(HR.I18N.en, {
  st_g9_who: 'casco',
  st_g9_k: 'Chapter 9 · The Cyclone',
  st_g9_1: '~Everything at once: rising, turning, switching sides. It is space tightening.',
  st_g9_2: '~The line above has become a slit. You can see the rim on both sides.',
  st_g9_3: 'This is where it closes, kid. You can see the rim.',
  st_g9_ask: 'If it closes, what is left inside?',
  st_g9_oU: 'Nothing. Not even me.',
  st_g9_oQ: 'And outside?',
  st_g9_oF: 'I will open it again.',
  st_g9_rU: 'Not even you. That is what I read. I did not want to.',
  st_g9_rQ: 'The two of them. Touching. Like before you.',
  st_g9_rF: 'You never opened anything, kid. You were born.',

  st_g9v6_who: 'poeira', st_g9v6_k: 'The rim',
  st_g9v6_1: '~Dust goes out to the rim of the Vortex. She touches it. She does not go out.',
  st_g9v6_2: 'I touched it. It is warm.',
  st_g9v6_3: '@faisca How did you not go out?',
  st_g9v6_4: 'I am hers. A crumb that fell inside.',
  st_g9v6_5: '@faisca Since when do you know?',
  st_g9v6_6: 'Since "mother".',
  st_g9v6_7: '~And then, lower:',
  st_g9v6_8: 'One does not become two alone. Someone wanted it.',

  st_g9v3_who: 'casco', st_g9v3_k: 'This time he holds',
  st_g9v3_1: '~A ring starts closing before you reach it. Hull steps into it and holds.',
  st_g9v3_2: 'Go through.',
  st_g9v3_3: '@faisca Hull, come on.',
  st_g9v3_4: 'This time I hold. Go through, kid.',
  st_g9v3_5: '@faisca You said you were coming!',
  st_g9v3_6: 'I came. This far.',
  st_g9v3_7: '~You pass. Behind you, the ring stays open. He does not.',

  st_g9v9_who: 'poeira', st_g9v9_k: 'Her voice',
  st_g9v9_1: '~No face. No borrowed voice. The voice is yours.',
  st_g9v9_2: '@eco It is me. You.',
  st_g9v9_3: '@eco If I go, it closes slowly. They rest.',
  st_g9v9_4: 'That is not her.',
  st_g9v9_5: '@faisca How do you know?',
  st_g9v9_6: 'You do not ask to disappear.',
  st_g9v9_ask: '@eco Do you want them to rest?',
  st_g9v9_oU: 'I do. More than anything.',
  st_g9v9_oQ: 'Is resting touching?',
  st_g9v9_oF: 'I want them to see me.',
  st_g9v9_rU: '@eco Then go.',
  st_g9v9_rQ: '@eco And you, in the middle, are in the way.',
  st_g9v9_rF: '@eco They never saw you. Only the hole.',

  st_g9b1_ask: 'I pull toward the middle. Do you feel it?',
  st_g9b1_oU: 'I feel it. I am not going.',
  st_g9b1_oQ: 'Pull toward whom?',
  st_g9b1_oF: 'Pull. I pass.',
  st_g9b1_rU: 'Everyone feels it. Few say "I am not going".',
  st_g9b1_rQ: 'Toward the two. They pull. I turn.',
  st_g9b1_rF: 'Pass. I am not a wall. I am a wanting.',

  st_g9b2_ask: 'Everyone here stays for someone. Would you?',
  st_g9b2_oU: 'I stopped for someone. Twice.',
  st_g9b2_oQ: 'Is staying the same as holding?',
  st_g9b2_oF: 'No. I pass everyone.',
  st_g9b2_rU: 'Then you know what it is. Tiredness with a direction.',
  st_g9b2_rQ: 'It is. Staying is holding without hands.',
  st_g9b2_rF: 'Passing everyone is arriving alone. Is that what you want?',

  st_g9b3_1: '@poeira Cyclone. You pull the rim. I am of the rim.',
  st_g9b3_2: 'Then I pull you home.',
  st_g9b3_3: '@poeira Home is in here.',
  st_g9b3_ask: 'The speck chose inside. Would you choose outside?',
  st_g9b3_oU: 'No. I choose both.',
  st_g9b3_oQ: 'Can one choose both?',
  st_g9b3_oF: 'Outside. I always wanted out.',
  st_g9b3_rU: 'Both is not chosen. It is held. Like they do.',
  st_g9b3_rQ: 'One can try. It costs what they pay.',
  st_g9b3_rF: 'Getting out is closing. You know that now.',

  st_g9b4_k: 'Closed, no inside',
  st_g9b4_1: '~Hull is not here. His place on the road is empty in a specific way.',
  st_g9b4_ask: 'If the two rims touch, what is left?',
  st_g9b4_oU: 'Them. Only them.',
  st_g9b4_oQ: 'And what is inside?',
  st_g9b4_oF: 'Me. I always remain.',
  st_g9b4_rU: 'Them. No space. None of this.',
  st_g9b4_rQ: 'Inside exists only while there is a rim. Closed, there is no inside.',
  st_g9b4_rF: 'Remain where? There is no where left.',

  st_g9b5_k: 'Slowly',
  st_g9b5_1: '@iris Put me down here. I can fly a little.',
  st_g9b5_2: '@faisca You are cold.',
  st_g9b5_3: '@iris I am warm. I learned from someone slow.',
  st_g9b5_4: '~She flies beside you. Slowly. It is the first time she has flown slowly.',
  st_g9b5_ask: 'Iris flies at your pace. Did you pull her down?',
  st_g9b5_oU: 'No. She came.',
  st_g9b5_oQ: 'Is a pace downward?',
  st_g9b5_oF: 'I pulled. I needed her.',
  st_g9b5_rU: 'She came. Everything here is pulled. She came.',
  st_g9b5_rQ: 'Sideways. It is the one direction I do not do.',
  st_g9b5_rF: '@iris Nobody pulls me. I came.',

  st_g9b6_k: 'The ring that stayed',
  st_g9b6_1: '~The ring Hull held is still back there, open, small.',
  st_g9b6_2: '@eco He stayed for you. Look what you cost.',
  st_g9b6_3: '@poeira He stayed for himself. He said so.',
  st_g9b6_ask: 'Will you go back for the old one?',
  st_g9b6_oU: 'I will. After the door.',
  st_g9b6_oQ: 'Can one go back?',
  st_g9b6_oF: 'No. He chose.',
  st_g9b6_rU: 'After the door there is no "after". You know that.',
  st_g9b6_rQ: 'One can. While there is an inside.',
  st_g9b6_rF: 'He chose. And you chose to leave him. Both count.',

  st_g9b7_k: 'In her voice',
  st_g9b7_1: '@eco Hull stayed. Iris burned. The Shoal left.',
  st_g9b7_2: '@eco Everything that touches you becomes less.',
  st_g9b7_ask: '@eco I am the thing that costs. Say I am not.',
  st_g9b7_oU: 'Not true. It costs. It is worth.',
  st_g9b7_oQ: 'Who taught you "cost"?',
  st_g9b7_oF: 'Be quiet.',
  st_g9b7_rU: '@eco "Worth it". Her word. Not yours.',
  st_g9b7_rQ: '@eco You did. In the Forge. "Everything costs."',
  st_g9b7_rF: '@eco I stopped. You are still listening.',

  st_g9b8_ask: 'If you reach the door and it opens, who closes it behind you?',
  st_g9b8_oU: 'I do. If I must.',
  st_g9b8_oQ: 'Does a door close from inside?',
  st_g9b8_oF: 'Let it stay open.',
  st_g9b8_rU: 'Then you have understood the old one.',
  st_g9b8_rQ: 'From outside. Only outside. They are outside.',
  st_g9b8_rF: 'Open tires the ones holding. Closed puts it out. Pick one.',

  st_g9b9_k: 'The eleven',
  st_g9b9_1: '@iris Up ahead there are still lights. Eleven. They do not go in.',
  st_g9b9_2: '@faisca Eleven.',
  st_g9b9_3: '@poeira The Guardian ones.',
  st_g9b9_ask: 'They reached the door and did not choose. Will you choose?',
  st_g9b9_oU: 'I will. I do not know what.',
  st_g9b9_oQ: 'Is choosing without knowing choosing?',
  st_g9b9_oF: 'I will. I already have.',
  st_g9b9_rU: 'That is enough. They did not even know that.',
  st_g9b9_rQ: 'It is the only way. Knowing comes after.',
  st_g9b9_rF: 'Careful. The eleven had too.',

  st_g9b10_k: 'Cyclone',
  st_g9b10_1: '~The Cyclone is the pull of both sides, turning in the middle.',
  st_g9b10_2: 'I want nothing. I am their wanting.',
  st_g9b10_3: 'They want to touch. I pull.',
  st_g9b10_4: '@faisca And me?',
  st_g9b10_5: 'You are what is in between.',
  st_g9b10_6: '@eco Step out of the middle, and they rest.',
  st_g9b10_ask: 'Step out of the way?',
  st_g9b10_oU: 'No. I am the way.',
  st_g9b10_oQ: 'If I go, do they rest?',
  st_g9b10_oF: 'I pass. You are only wind.',
  st_g9b10_rU: 'Then you will have to hold. Alone, for now.',
  st_g9b10_rQ: 'They rest. And everything you saw goes out.',
  st_g9b10_rF: 'Wind is what is left when someone leaves. Pass. I go on.',

  st_g9c_who: 'ancora', st_g9c_k: 'One word',
  st_g9c_1: '~There is no note. The rim of the Vortex is close enough to read.',
  st_g9c_2: '~On it, in the light hand, a single word:',
  st_g9c_3: '@ancora come',
  st_g9c_4: '@poeira It is her. She is calling.',
  st_g9c_5: '@faisca Come where? If I go, it closes.',
  st_g9c_6: '@poeira Come is not close.',
  st_g9c_7: '@iris Then let us go.'
});

Object.assign(HR.I18N.es, {
  st_g9_who: 'casco',
  st_g9_k: 'Capítulo 9 · El Ciclón',
  st_g9_1: '~Todo a la vez: sube, gira, cambia de lado. Es el espacio apretando.',
  st_g9_2: '~La línea de allá arriba es ya una rendija. Se ve el borde de los dos lados.',
  st_g9_3: 'Aquí es donde cierra, niña. Se ve el borde.',
  st_g9_ask: 'Si cierra, ¿qué queda del lado de dentro?',
  st_g9_oU: 'Nada. Ni yo.',
  st_g9_oQ: '¿Y del lado de fuera?',
  st_g9_oF: 'Lo abro otra vez.',
  st_g9_rU: 'Ni tú. Eso fue lo que leí. No quise leerlo.',
  st_g9_rQ: 'Los dos. Pegados. Como antes de ti.',
  st_g9_rF: 'Tú nunca abriste nada, niña. Tú naciste.',

  st_g9v6_who: 'poeira', st_g9v6_k: 'El borde',
  st_g9v6_1: '~Polvo va hasta el borde del Vórtice. Lo toca. No se apaga.',
  st_g9v6_2: 'Lo toqué. Está tibio.',
  st_g9v6_3: '@faisca ¿Cómo no te apagaste?',
  st_g9v6_4: 'Soy suya. Una miga que cayó hacia dentro.',
  st_g9v6_5: '@faisca ¿Desde cuándo lo sabes?',
  st_g9v6_6: 'Desde "madre".',
  st_g9v6_7: '~Y después, más bajo:',
  st_g9v6_8: 'Uno no se vuelve dos solo. Alguien quiso.',

  st_g9v3_who: 'casco', st_g9v3_k: 'Esta vez él sujeta',
  st_g9v3_1: '~Un aro empieza a cerrarse antes de que llegues. Casco entra en él y sujeta.',
  st_g9v3_2: 'Pasa.',
  st_g9v3_3: '@faisca Casco, ven.',
  st_g9v3_4: 'Esta vez sujeto yo. Pasa, niña.',
  st_g9v3_5: '@faisca ¡Dijiste que venías!',
  st_g9v3_6: 'Vine. Hasta aquí.',
  st_g9v3_7: '~Pasas. Detrás, el aro queda abierto. Él no.',

  st_g9v9_who: 'poeira', st_g9v9_k: 'Su voz',
  st_g9v9_1: '~Ninguna cara. Ninguna voz prestada. La voz es la tuya.',
  st_g9v9_2: '@eco Soy yo. Tú.',
  st_g9v9_3: '@eco Si me voy, cierra despacio. Ellos descansan.',
  st_g9v9_4: 'No es ella.',
  st_g9v9_5: '@faisca ¿Cómo lo sabes?',
  st_g9v9_6: 'Tú no pides desaparecer.',
  st_g9v9_ask: '@eco ¿Quieres que descansen?',
  st_g9v9_oU: 'Quiero. Más que nada.',
  st_g9v9_oQ: '¿Descansar es tocarse?',
  st_g9v9_oF: 'Quiero que me vean.',
  st_g9v9_rU: '@eco Entonces vete.',
  st_g9v9_rQ: '@eco Y tú, en medio, estorbas.',
  st_g9v9_rF: '@eco Nunca te vieron. Solo el hueco.',

  st_g9b1_ask: 'Yo tiro hacia el medio. ¿Lo sientes?',
  st_g9b1_oU: 'Lo siento. No voy.',
  st_g9b1_oQ: '¿Tiras hacia quién?',
  st_g9b1_oF: 'Tira. Yo paso.',
  st_g9b1_rU: 'Todos lo sienten. Pocos dicen "no voy".',
  st_g9b1_rQ: 'Hacia los dos. Ellos tiran. Yo giro.',
  st_g9b1_rF: 'Pasa. No soy pared. Soy ganas.',

  st_g9b2_ask: 'Aquí todos se quedan por alguien. ¿Tú lo harías?',
  st_g9b2_oU: 'Ya paré por alguien. Dos veces.',
  st_g9b2_oQ: '¿Quedarse es lo mismo que sujetar?',
  st_g9b2_oF: 'No. Yo paso a todos.',
  st_g9b2_rU: 'Entonces sabes lo que es. Cansancio con dirección.',
  st_g9b2_rQ: 'Lo es. Quedarse es sujetar sin manos.',
  st_g9b2_rF: 'Pasar a todos es llegar sola. ¿Quieres eso?',

  st_g9b3_1: '@poeira Ciclón. Tiras del borde. Yo soy del borde.',
  st_g9b3_2: 'Entonces te llevo a casa.',
  st_g9b3_3: '@poeira Casa es aquí dentro.',
  st_g9b3_ask: 'El grano eligió dentro. ¿Tú elegirías fuera?',
  st_g9b3_oU: 'No. Yo elijo a los dos.',
  st_g9b3_oQ: '¿Se pueden elegir los dos?',
  st_g9b3_oF: 'Fuera. Siempre quise salir.',
  st_g9b3_rU: 'A los dos no se elige. Se sujeta. Como ellos.',
  st_g9b3_rQ: 'Se puede intentar. Cuesta lo que ellos pagan.',
  st_g9b3_rF: 'Salir es cerrar. Ya lo sabes.',

  st_g9b4_k: 'Cerrado, no hay dentro',
  st_g9b4_1: '~Casco no está. Su sitio en el camino queda vacío de una manera concreta.',
  st_g9b4_ask: 'Si los dos bordes se tocan, ¿qué queda?',
  st_g9b4_oU: 'Ellos. Solo ellos.',
  st_g9b4_oQ: '¿Y lo que está dentro?',
  st_g9b4_oF: 'Yo. Yo siempre quedo.',
  st_g9b4_rU: 'Ellos. Sin espacio. Sin nada de esto.',
  st_g9b4_rQ: 'Dentro existe mientras haya borde. Cerrado, no hay dentro.',
  st_g9b4_rF: '¿Quedas dónde? No sobra dónde.',

  st_g9b5_k: 'Despacio',
  st_g9b5_1: '@iris Bájame aquí. Puedo volar un poco.',
  st_g9b5_2: '@faisca Estás fría.',
  st_g9b5_3: '@iris Estoy tibia. Aprendí de una lenta.',
  st_g9b5_4: '~Vuela a tu lado. Despacio. Es la primera vez que vuela despacio.',
  st_g9b5_ask: 'Iris vuela a tu ritmo. ¿La tiraste hacia abajo?',
  st_g9b5_oU: 'No. Ella vino.',
  st_g9b5_oQ: '¿Un ritmo es hacia abajo?',
  st_g9b5_oF: 'La tiré. La necesitaba.',
  st_g9b5_rU: 'Vino. Aquí todo es tirado. Ella vino.',
  st_g9b5_rQ: 'Hacia el lado. Es la única dirección que no hago.',
  st_g9b5_rF: '@iris Nadie tira de mí. Yo vine.',

  st_g9b6_k: 'El aro que quedó',
  st_g9b6_1: '~El aro que sujetó Casco sigue allá atrás, abierto, pequeño.',
  st_g9b6_2: '@eco Se quedó por ti. Mira lo que cuestas.',
  st_g9b6_3: '@poeira Se quedó por él. Lo dijo.',
  st_g9b6_ask: '¿Vuelves a buscar al viejo?',
  st_g9b6_oU: 'Vuelvo. Después de la puerta.',
  st_g9b6_oQ: '¿Se puede volver?',
  st_g9b6_oF: 'No. Él eligió.',
  st_g9b6_rU: 'Después de la puerta no hay "después". Lo sabes.',
  st_g9b6_rQ: 'Se puede. Mientras haya dentro.',
  st_g9b6_rF: 'Eligió. Y tú elegiste dejarlo. Las dos cuentan.',

  st_g9b7_k: 'Con su voz',
  st_g9b7_1: '@eco Casco se quedó. Iris se quemó. El Cardumen se fue.',
  st_g9b7_2: '@eco Todo lo que te toca queda con menos.',
  st_g9b7_ask: '@eco Yo soy la cosa que cuesta. Di que no.',
  st_g9b7_oU: 'No lo eres. Cuesta y vale.',
  st_g9b7_oQ: '¿Quién te enseñó "cuesta"?',
  st_g9b7_oF: 'Cállate.',
  st_g9b7_rU: '@eco "Vale". Palabra de ella. No tuya.',
  st_g9b7_rQ: '@eco Tú. En la Forja. "Todo cuesta."',
  st_g9b7_rF: '@eco Me callé. Tú sigues oyendo.',

  st_g9b8_ask: 'Si llegas a la puerta y se abre, ¿quién cierra detrás?',
  st_g9b8_oU: 'Yo. Si hace falta.',
  st_g9b8_oQ: '¿Una puerta se cierra por dentro?',
  st_g9b8_oF: 'Que se quede abierta.',
  st_g9b8_rU: 'Entonces ya entendiste al viejo.',
  st_g9b8_rQ: 'Por fuera. Solo por fuera. Ellos están fuera.',
  st_g9b8_rF: 'Abierta cansa a quien sujeta. Cerrada apaga. Elige una.',

  st_g9b9_k: 'Los once',
  st_g9b9_1: '@iris Ahí delante hay luces quietas. Once. No entran.',
  st_g9b9_2: '@faisca Once.',
  st_g9b9_3: '@poeira Los del Guardián.',
  st_g9b9_ask: 'Llegaron a la puerta y no eligieron. ¿Tú vas a elegir?',
  st_g9b9_oU: 'Voy. No sé qué.',
  st_g9b9_oQ: '¿Elegir sin saber es elegir?',
  st_g9b9_oF: 'Voy. Ya elegí.',
  st_g9b9_rU: 'Con eso basta. Ellos ni eso sabían.',
  st_g9b9_rQ: 'Es el único modo. Saber viene después.',
  st_g9b9_rF: 'Cuidado. Los once también.',

  st_g9b10_k: 'Ciclón',
  st_g9b10_1: '~El Ciclón es el tirón de los dos lados, girando en el medio.',
  st_g9b10_2: 'Yo no quiero nada. Yo soy sus ganas.',
  st_g9b10_3: 'Ellos quieren tocarse. Yo tiro.',
  st_g9b10_4: '@faisca ¿Y yo?',
  st_g9b10_5: 'Tú eres lo que está en medio.',
  st_g9b10_6: '@eco Sal del medio, y descansan.',
  st_g9b10_ask: '¿Te apartas del camino?',
  st_g9b10_oU: 'No. Yo soy el camino.',
  st_g9b10_oQ: 'Si me voy, ¿descansan?',
  st_g9b10_oF: 'Yo paso. Tú solo eres viento.',
  st_g9b10_rU: 'Entonces tendrás que sujetar. Sola, por ahora.',
  st_g9b10_rQ: 'Descansan. Y se apaga todo lo que viste.',
  st_g9b10_rF: 'Viento es lo que queda cuando alguien se va. Pasa. Yo sigo.',

  st_g9c_who: 'ancora', st_g9c_k: 'Una palabra',
  st_g9c_1: '~No hay nota. El borde del Vórtice está bastante cerca para leerlo.',
  st_g9c_2: '~En él, con la letra leve, una sola palabra:',
  st_g9c_3: '@ancora ven',
  st_g9c_4: '@poeira Es ella. Ella llama.',
  st_g9c_5: '@faisca ¿Venir adónde? Si voy, cierra.',
  st_g9c_6: '@poeira Venir no es cerrar.',
  st_g9c_7: '@iris Entonces vamos.'
});
