/* =====================================================================
   ORBO v5.9 — texto da história: Galáxia 3 (Jardim · Colmeia · Gratidão)
   e as cenas do Ninho (fase 3-7-7). Ver docs/HISTORIA.md §12 e §22.
   ===================================================================== */
Object.assign(HR.I18N.pt, {
  skin_poeira: 'Poeira', flavor_skin_poeira: 'Todo grão já foi luz.',
  a_nest_stay: 'Quem fica', a_d_nest: 'Deixe de voar para ficar com quem não voa.',

  st_g3_1: '~O Jardim é a primeira coisa viva que você vê desde que saiu de casa.',
  st_g3_2: '~Aqui os anéis vêm em pares e trios, porque aqui nada anda sozinho.',
  st_g3_3: '~Um enxame de luzinhas se aproxima. Elas seguem quem brilha.',
  st_g3_ask: 'Bem-vinda. Você é de fora. Isso se resolve.',
  st_g3_oU: 'Estou de passagem. Obrigada pelo caminho.',
  st_g3_oQ: 'Resolve como?',
  st_g3_oF: 'Não vim ser resolvida.',
  st_g3_rU: 'De passagem. Todo mundo diz isso e fica.',
  st_g3_rQ: 'Com regra. É sempre com regra.',
  st_g3_rF: 'Então vai ser um jardim difícil para você.',

  st_g3v2_who: 'cardume',
  st_g3v2_1: 'Você brilha! A gente vai com você!',
  st_g3v2_2: '~Eles vão mesmo. Por enquanto.',
  st_g3v7_who: 'poeira',
  st_g3v7_1: 'Eu sou Poeira.',
  st_g3v7_2: 'Não brilho. E não atrapalho.',
  st_g3v9_who: 'casco',
  st_g3v9_1: 'A Colmeia não é má. É assustada.',
  st_g3v9_2: 'O pior portão do universo é o medo com razão.',

  st_g3b1_ask: 'Nós cuidamos de quem entra. Aceita?',
  st_g3b1_oU: 'Aceito, e agradeço.',
  st_g3b1_oQ: 'Cuidar tem regra?',
  st_g3b1_oF: 'Eu me cuido.',
  st_g3b1_rU: 'Agradecer. Que palavra antiga.',
  st_g3b1_rQ: 'Tem. Toda casa tem.',
  st_g3b1_rF: 'Todos dizem isso. Depois pedem pouso.',

  st_g3b2_ask: 'Aqui ninguém voa fora do par. Combinado?',
  st_g3b2_oU: 'Combinado, enquanto eu estiver aqui.',
  st_g3b2_oQ: 'E quem não tem par?',
  st_g3b2_oF: 'Eu voo como sei.',
  st_g3b2_rU: 'Justo. Você é de passagem.',
  st_g3b2_rQ: '…Esse é o problema, não é?',
  st_g3b2_rF: 'Então voe longe da colmeia.',

  st_g3b3_ask: 'Quem te ensinou a voar?',
  st_g3b3_oU: 'Minha mãe. E o caminho que ela deixou.',
  st_g3b3_oQ: 'Isso se aprende ou já vem?',
  st_g3b3_oF: 'Eu aprendi sozinha.',
  st_g3b3_rU: 'Um caminho é uma herança. Cuide dele.',
  st_g3b3_rQ: 'Vem um pouco. O resto alguém mostra.',
  st_g3b3_rF: 'Ninguém aprende sozinho. Nem nós.',

  st_g3b4_ask: 'Aquilo ali não brilha. Serve para quê?',
  st_g3b4_oU: 'Não sei. Ainda assim quero por perto.',
  st_g3b4_oQ: 'Precisa servir?',
  st_g3b4_oF: 'Para nada.',
  st_g3b4_rU: 'Perto é onde as coisas viram gente.',
  st_g3b4_rQ: 'No jardim, precisa.',
  st_g3b4_rF: 'Então estamos de acordo. É isso que dói.',

  st_g3b5_ask: 'Vamos medir a sua luz. Pode ser?',
  st_g3b5_oU: 'Pode. Ela é pequena mesmo.',
  st_g3b5_oQ: 'Medir para quê?',
  st_g3b5_oF: 'Mede a sua.',
  st_g3b5_rU: 'Pequena e inteira. Anotado.',
  st_g3b5_rQ: 'Para saber onde você cabe.',
  st_g3b5_rF: 'A nossa é a soma. Não cabe em régua.',

  st_g3b6_ask: 'O grão vai embora hoje. É o certo.',
  st_g3b6_oU: 'Então eu vou junto.',
  st_g3b6_oQ: 'Certo para quem?',
  st_g3b6_oF: 'Tanto faz.',
  st_g3b6_rU: '…Você mal chegou.',
  st_g3b6_rQ: 'Para o jardim. Sempre para o jardim.',
  st_g3b6_rF: 'É o que a maioria diz. Por isso é fácil.',

  st_g3b7_ask: 'Dizem que alguém, um dia, deixou de voar ali no ninho.',
  st_g3b7_oU: 'Por quê?',
  st_g3b7_oQ: 'Deixou de voar como?',
  st_g3b7_oF: 'Perdeu, então.',
  st_g3b7_rU: 'Ninguém soube. Só que ficou.',
  st_g3b7_rQ: 'Parou. No meio. De propósito.',
  st_g3b7_rF: 'Talvez. Ou ganhou outra coisa.',

  st_g3b8_ask: 'Se ficar com ele, você deixa de ser nossa.',
  st_g3b8_oU: 'Tudo bem. Obrigada mesmo assim.',
  st_g3b8_oQ: 'Vocês perdem o quê com isso?',
  st_g3b8_oF: 'Eu nunca fui de vocês.',
  st_g3b8_rU: 'Obrigada. De novo essa palavra.',
  st_g3b8_rQ: '…Uma a mais. E nós contamos tudo.',
  st_g3b8_rF: 'Não. E ainda assim comeu do jardim.',

  st_g3b9_ask: 'Você ouviu a história. Ainda nos julga?',
  st_g3b9_oU: 'Não. Medo antigo é pesado.',
  st_g3b9_oQ: 'Quantas vezes já aconteceu?',
  st_g3b9_oF: 'Julgo. Vocês viraram o portão.',
  st_g3b9_rU: 'É. E a gente passa esse medo adiante.',
  st_g3b9_rQ: 'Uma. Uma foi suficiente.',
  st_g3b9_rF: 'Viramos. O portão também tem medo.',

  st_g3b10_1: '~O enxame se fecha e se abre como uma coisa só.',
  st_g3b10_2: 'Você acha que nós somos duras.',
  st_g3b10_3: 'Nós fomos abertas uma vez. Perdemos metade.',
  st_g3b10_ask: 'Diga: o que a gente faz com quem chega de fora?',
  st_g3b10_oU: 'Recebe. Vocês também chegaram de algum lugar.',
  st_g3b10_oQ: 'Pergunta o nome antes de decidir.',
  st_g3b10_oF: 'Fecha. Foi o que fizeram com vocês.',
  st_g3b10_rU: '…Vá. Leve o grão. E não conte que a gente deixou.',
  st_g3b10_rQ: '…Nome. Nós tínhamos parado de perguntar.',
  st_g3b10_rF: '…É o que nós fazemos. Ainda assim dói ouvir de fora.',

  st_g3c_who: 'vela', st_g3c_k: 'Carta de Vela',
  st_g3c_1: '~Entre duas flores de luz, um bilhete dobrado.',
  st_g3c_2: 'Faísca: não existe luz que se acenda sozinha.',
  st_g3c_3: 'A sua começou com a minha, e a minha com a de alguém.',
  st_g3c_4: 'Diga obrigada enquanto dá tempo.',
  st_g3c_5: '— V.',

  st_nest_win_who: 'poeira',
  st_nest_win_1: 'Você voa bonito.',
  st_nest_win_2: 'Eu não consigo. Mas eu vi você passar.',
  st_nest_hint_who: 'poeira',
  st_nest_hint_1: 'Todo mundo passa por aqui.',
  st_nest_hint_2: 'Ninguém nunca fica.',
  st_nest_stay_who: 'poeira', st_nest_stay_k: 'O Ninho',
  st_nest_stay_1: '~Você para no meio do caminho. Não é queda: é escolha.',
  st_nest_stay_2: '~Desce até o ninho e fica ali, com ele.',
  st_nest_stay_3: 'Você perdeu por minha causa.',
  st_nest_stay_4: '~"Eu não perdi", você responde. "Eu fiquei."',
  st_nest_stay_5: '~O jardim inteiro se apaga devagar. Só vocês dois ficam acesos.'
});

Object.assign(HR.I18N.en, {
  skin_poeira: 'Dust', flavor_skin_poeira: 'Every speck was light once.',
  a_nest_stay: 'The one who stays', a_d_nest: 'Stop flying to stay with the one who cannot fly.',

  st_g3_1: '~The Garden is the first living thing you have seen since you left home.',
  st_g3_2: '~Here rings come in pairs and threes, because nothing here goes alone.',
  st_g3_3: '~A swarm of small lights comes closer. They follow whoever shines.',
  st_g3_ask: 'Welcome. You are from outside. That can be sorted out.',
  st_g3_oU: 'I am only passing through. Thank you for the road.',
  st_g3_oQ: 'Sorted out how?',
  st_g3_oF: 'I did not come to be sorted out.',
  st_g3_rU: 'Passing through. Everyone says that, and stays.',
  st_g3_rQ: 'With rules. It is always with rules.',
  st_g3_rF: 'Then this will be a hard garden for you.',

  st_g3v2_who: 'cardume',
  st_g3v2_1: 'You shine! We are coming with you!',
  st_g3v2_2: '~And they do come. For now.',
  st_g3v7_who: 'poeira',
  st_g3v7_1: 'I am Dust.',
  st_g3v7_2: 'I do not shine. And I do not get in the way.',
  st_g3v9_who: 'casco',
  st_g3v9_1: 'The Hive is not evil. It is frightened.',
  st_g3v9_2: 'The worst gate in the universe is fear with a good reason.',

  st_g3b1_ask: 'We take care of those who come in. Do you accept?',
  st_g3b1_oU: 'I accept, and I am grateful.',
  st_g3b1_oQ: 'Does caring come with rules?',
  st_g3b1_oF: 'I take care of myself.',
  st_g3b1_rU: 'Grateful. What an old word.',
  st_g3b1_rQ: 'It does. Every home has them.',
  st_g3b1_rF: 'They all say that. Then they ask to land.',

  st_g3b2_ask: 'Here nobody flies outside their pair. Agreed?',
  st_g3b2_oU: 'Agreed, while I am here.',
  st_g3b2_oQ: 'And those with no pair?',
  st_g3b2_oF: 'I fly the way I know.',
  st_g3b2_rU: 'Fair. You are passing through.',
  st_g3b2_rQ: '…That is the problem, is it not?',
  st_g3b2_rF: 'Then fly far from the hive.',

  st_g3b3_ask: 'Who taught you to fly?',
  st_g3b3_oU: 'My mother. And the road she left behind.',
  st_g3b3_oQ: 'Is that learned or does it come with you?',
  st_g3b3_oF: 'I learned on my own.',
  st_g3b3_rU: 'A road is an inheritance. Take care of it.',
  st_g3b3_rQ: 'A little comes with you. The rest someone shows you.',
  st_g3b3_rF: 'Nobody learns alone. Not even us.',

  st_g3b4_ask: 'That thing there does not shine. What is it for?',
  st_g3b4_oU: 'I do not know. I still want it near me.',
  st_g3b4_oQ: 'Does it have to be for something?',
  st_g3b4_oF: 'For nothing.',
  st_g3b4_rU: 'Near is where things become someone.',
  st_g3b4_rQ: 'In the garden, it does.',
  st_g3b4_rF: 'Then we agree. That is the part that hurts.',

  st_g3b5_ask: 'We will measure your light. May we?',
  st_g3b5_oU: 'You may. It really is small.',
  st_g3b5_oQ: 'Measure it for what?',
  st_g3b5_oF: 'Measure your own.',
  st_g3b5_rU: 'Small and whole. Noted.',
  st_g3b5_rQ: 'To know where you fit.',
  st_g3b5_rF: 'Ours is a sum. No ruler holds it.',

  st_g3b6_ask: 'The speck leaves today. It is the right thing.',
  st_g3b6_oU: 'Then I leave with it.',
  st_g3b6_oQ: 'Right for whom?',
  st_g3b6_oF: 'Whatever.',
  st_g3b6_rU: '…You only just arrived.',
  st_g3b6_rQ: 'For the garden. Always for the garden.',
  st_g3b6_rF: 'That is what most say. That is why it is easy.',

  st_g3b7_ask: 'They say someone, once, stopped flying at that nest.',
  st_g3b7_oU: 'Why?',
  st_g3b7_oQ: 'Stopped flying how?',
  st_g3b7_oF: 'Lost, then.',
  st_g3b7_rU: 'Nobody ever knew. Only that they stayed.',
  st_g3b7_rQ: 'Stopped. Mid-flight. On purpose.',
  st_g3b7_rF: 'Maybe. Or won something else.',

  st_g3b8_ask: 'If you keep it, you stop being one of ours.',
  st_g3b8_oU: 'That is all right. Thank you anyway.',
  st_g3b8_oQ: 'What do you lose with that?',
  st_g3b8_oF: 'I was never one of yours.',
  st_g3b8_rU: 'Thank you. That word again.',
  st_g3b8_rQ: '…One more gone. And we count everything.',
  st_g3b8_rF: 'No. And yet you ate from the garden.',

  st_g3b9_ask: 'You heard the story. Do you still judge us?',
  st_g3b9_oU: 'No. Old fear is heavy.',
  st_g3b9_oQ: 'How many times did it happen?',
  st_g3b9_oF: 'I do. You became the gate.',
  st_g3b9_rU: 'It is. And we hand that fear down.',
  st_g3b9_rQ: 'Once. Once was enough.',
  st_g3b9_rF: 'We did. The gate is afraid too.',

  st_g3b10_1: '~The swarm closes and opens as one single thing.',
  st_g3b10_2: 'You think we are hard.',
  st_g3b10_3: 'We were open once. We lost half of us.',
  st_g3b10_ask: 'Tell us: what do we do with those who come from outside?',
  st_g3b10_oU: 'You take them in. You came from somewhere too.',
  st_g3b10_oQ: 'You ask their name before deciding.',
  st_g3b10_oF: 'You close. It is what was done to you.',
  st_g3b10_rU: '…Go. Take the speck. And do not tell anyone we allowed it.',
  st_g3b10_rQ: '…A name. We had stopped asking.',
  st_g3b10_rF: '…That is what we do. It still hurts to hear it from outside.',

  st_g3c_who: 'vela', st_g3c_k: 'A letter from Sail',
  st_g3c_1: '~Between two flowers of light, a folded note.',
  st_g3c_2: 'Spark: no light ever lit itself.',
  st_g3c_3: 'Yours began with mine, and mine with somebody else\'s.',
  st_g3c_4: 'Say thank you while there is still time.',
  st_g3c_5: '— S.',

  st_nest_win_who: 'poeira',
  st_nest_win_1: 'You fly beautifully.',
  st_nest_win_2: 'I cannot. But I saw you go by.',
  st_nest_hint_who: 'poeira',
  st_nest_hint_1: 'Everybody comes through here.',
  st_nest_hint_2: 'Nobody ever stays.',
  st_nest_stay_who: 'poeira', st_nest_stay_k: 'The Nest',
  st_nest_stay_1: '~You stop halfway. It is not a fall: it is a choice.',
  st_nest_stay_2: '~You come down to the nest and stay there, with him.',
  st_nest_stay_3: 'You lost because of me.',
  st_nest_stay_4: '~"I did not lose," you answer. "I stayed."',
  st_nest_stay_5: '~The whole garden dims. Only you two stay lit.'
});

Object.assign(HR.I18N.es, {
  skin_poeira: 'Polvo', flavor_skin_poeira: 'Cada grano fue luz alguna vez.',
  a_nest_stay: 'Quien se queda', a_d_nest: 'Deja de volar para quedarte con quien no vuela.',

  st_g3_1: '~El Jardín es lo primero vivo que ves desde que saliste de casa.',
  st_g3_2: '~Aquí los anillos vienen en pares y tríos, porque nada anda solo.',
  st_g3_3: '~Un enjambre de lucecitas se acerca. Siguen a quien brilla.',
  st_g3_ask: 'Bienvenida. Eres de fuera. Eso se resuelve.',
  st_g3_oU: 'Solo estoy de paso. Gracias por el camino.',
  st_g3_oQ: '¿Se resuelve cómo?',
  st_g3_oF: 'No vine a que me resuelvan.',
  st_g3_rU: 'De paso. Todos dicen eso y se quedan.',
  st_g3_rQ: 'Con regla. Siempre con regla.',
  st_g3_rF: 'Entonces este será un jardín difícil para ti.',

  st_g3v2_who: 'cardume',
  st_g3v2_1: '¡Tú brillas! ¡Vamos contigo!',
  st_g3v2_2: '~Y van de verdad. Por ahora.',
  st_g3v7_who: 'poeira',
  st_g3v7_1: 'Yo soy Polvo.',
  st_g3v7_2: 'No brillo. Y no estorbo.',
  st_g3v9_who: 'casco',
  st_g3v9_1: 'La Colmena no es mala. Está asustada.',
  st_g3v9_2: 'El peor portón del universo es el miedo con razón.',

  st_g3b1_ask: 'Nosotras cuidamos a quien entra. ¿Aceptas?',
  st_g3b1_oU: 'Acepto, y lo agradezco.',
  st_g3b1_oQ: '¿Cuidar tiene reglas?',
  st_g3b1_oF: 'Yo me cuido sola.',
  st_g3b1_rU: 'Agradecer. Qué palabra antigua.',
  st_g3b1_rQ: 'Las tiene. Toda casa las tiene.',
  st_g3b1_rF: 'Todas dicen eso. Después piden posada.',

  st_g3b2_ask: 'Aquí nadie vuela fuera de su par. ¿Trato hecho?',
  st_g3b2_oU: 'Trato hecho, mientras esté aquí.',
  st_g3b2_oQ: '¿Y quien no tiene par?',
  st_g3b2_oF: 'Yo vuelo como sé.',
  st_g3b2_rU: 'Justo. Estás de paso.',
  st_g3b2_rQ: '…Ese es el problema, ¿no?',
  st_g3b2_rF: 'Entonces vuela lejos de la colmena.',

  st_g3b3_ask: '¿Quién te enseñó a volar?',
  st_g3b3_oU: 'Mi madre. Y el camino que dejó.',
  st_g3b3_oQ: '¿Eso se aprende o ya viene?',
  st_g3b3_oF: 'Aprendí sola.',
  st_g3b3_rU: 'Un camino es una herencia. Cuídalo.',
  st_g3b3_rQ: 'Algo viene. El resto alguien te lo muestra.',
  st_g3b3_rF: 'Nadie aprende solo. Ni nosotras.',

  st_g3b4_ask: 'Eso de ahí no brilla. ¿Para qué sirve?',
  st_g3b4_oU: 'No sé. Aun así lo quiero cerca.',
  st_g3b4_oQ: '¿Tiene que servir?',
  st_g3b4_oF: 'Para nada.',
  st_g3b4_rU: 'Cerca es donde las cosas se vuelven alguien.',
  st_g3b4_rQ: 'En el jardín, sí.',
  st_g3b4_rF: 'Entonces estamos de acuerdo. Eso es lo que duele.',

  st_g3b5_ask: 'Vamos a medir tu luz. ¿Se puede?',
  st_g3b5_oU: 'Se puede. Es pequeña, de verdad.',
  st_g3b5_oQ: '¿Medirla para qué?',
  st_g3b5_oF: 'Mide la tuya.',
  st_g3b5_rU: 'Pequeña y entera. Anotado.',
  st_g3b5_rQ: 'Para saber dónde cabes.',
  st_g3b5_rF: 'La nuestra es una suma. No cabe en una regla.',

  st_g3b6_ask: 'El grano se va hoy. Es lo correcto.',
  st_g3b6_oU: 'Entonces me voy con él.',
  st_g3b6_oQ: '¿Correcto para quién?',
  st_g3b6_oF: 'Me da igual.',
  st_g3b6_rU: '…Si acabas de llegar.',
  st_g3b6_rQ: 'Para el jardín. Siempre para el jardín.',
  st_g3b6_rF: 'Es lo que dice la mayoría. Por eso es fácil.',

  st_g3b7_ask: 'Dicen que alguien, un día, dejó de volar en ese nido.',
  st_g3b7_oU: '¿Por qué?',
  st_g3b7_oQ: '¿Dejó de volar cómo?',
  st_g3b7_oF: 'Perdió, entonces.',
  st_g3b7_rU: 'Nadie lo supo. Solo que se quedó.',
  st_g3b7_rQ: 'Se detuvo. A mitad. A propósito.',
  st_g3b7_rF: 'Quizá. O ganó otra cosa.',

  st_g3b8_ask: 'Si te quedas con él, dejas de ser nuestra.',
  st_g3b8_oU: 'Está bien. Gracias igual.',
  st_g3b8_oQ: '¿Ustedes qué pierden con eso?',
  st_g3b8_oF: 'Nunca fui de ustedes.',
  st_g3b8_rU: 'Gracias. Otra vez esa palabra.',
  st_g3b8_rQ: '…Una menos. Y nosotras contamos todo.',
  st_g3b8_rF: 'No. Y aun así comiste del jardín.',

  st_g3b9_ask: 'Oíste la historia. ¿Todavía nos juzgas?',
  st_g3b9_oU: 'No. El miedo viejo pesa.',
  st_g3b9_oQ: '¿Cuántas veces pasó?',
  st_g3b9_oF: 'Las juzgo. Se volvieron el portón.',
  st_g3b9_rU: 'Pesa. Y ese miedo lo pasamos adelante.',
  st_g3b9_rQ: 'Una. Una bastó.',
  st_g3b9_rF: 'Nos volvimos. El portón también tiene miedo.',

  st_g3b10_1: '~El enjambre se cierra y se abre como una sola cosa.',
  st_g3b10_2: 'Crees que somos duras.',
  st_g3b10_3: 'Estuvimos abiertas una vez. Perdimos la mitad.',
  st_g3b10_ask: 'Dinos: ¿qué hacemos con quien llega de fuera?',
  st_g3b10_oU: 'Recibirlo. Ustedes también llegaron de algún lado.',
  st_g3b10_oQ: 'Preguntar el nombre antes de decidir.',
  st_g3b10_oF: 'Cerrar. Es lo que les hicieron a ustedes.',
  st_g3b10_rU: '…Ve. Llévate el grano. Y no cuentes que lo permitimos.',
  st_g3b10_rQ: '…Un nombre. Habíamos dejado de preguntar.',
  st_g3b10_rF: '…Es lo que hacemos. Aun así duele oírlo de fuera.',

  st_g3c_who: 'vela', st_g3c_k: 'Carta de Vela',
  st_g3c_1: '~Entre dos flores de luz, una nota doblada.',
  st_g3c_2: 'Chispa: no existe luz que se encienda sola.',
  st_g3c_3: 'La tuya empezó con la mía, y la mía con la de alguien.',
  st_g3c_4: 'Da las gracias mientras haya tiempo.',
  st_g3c_5: '— V.',

  st_nest_win_who: 'poeira',
  st_nest_win_1: 'Vuelas bonito.',
  st_nest_win_2: 'Yo no puedo. Pero te vi pasar.',
  st_nest_hint_who: 'poeira',
  st_nest_hint_1: 'Todos pasan por aquí.',
  st_nest_hint_2: 'Nadie se queda nunca.',
  st_nest_stay_who: 'poeira', st_nest_stay_k: 'El Nido',
  st_nest_stay_1: '~Te detienes a mitad de camino. No es caída: es elección.',
  st_nest_stay_2: '~Bajas hasta el nido y te quedas ahí, con él.',
  st_nest_stay_3: 'Perdiste por mi culpa.',
  st_nest_stay_4: '~"No perdí", respondes. "Me quedé."',
  st_nest_stay_5: '~El jardín entero se apaga despacio. Solo ustedes dos siguen encendidos.'
});
