/* =====================================================================
   ORBO v5.9 — texto da história: comum + Galáxia 1 (Berço).
   Uma fala por chave. "~" no começo = narração (fica em itálico claro).
   Ver docs/HISTORIA.md §9 e §10.
   ===================================================================== */
Object.assign(HR.I18N.pt, {
  /* ---------------- comum ---------------- */
  st_cast_faisca: 'Faísca', st_cast_vela: 'Vela', st_cast_ancora: 'Âncora', st_cast_casco: 'Casco',
  st_cast_iris: 'Íris', st_cast_poeira: 'Poeira', st_cast_cardume: 'Cardume', st_cast_porta: 'A Porta',
  st_set: 'História', st_set_d: 'Cenas entre as fases. Pular nunca muda o jogo.',
  st_set_full: 'Completa', st_set_short: 'Curta', st_set_off: 'Desligada',
  st_ring_bonus: 'O anel de Vela: +{n} % de moedas no Infinito',

  /* ---------------- abertura ---------------- */
  st_open_k: 'A primeira noite', st_open_who: 'faisca',
  st_open_1: '~Antes de tudo havia três luzes e um anel pequeno.',
  st_open_2: '~A maior chamava a menor de Faísca.',
  st_open_3: '~"Uma casa precisa de vela e âncora", dizia ela. "E de uma faísca."',
  st_open_4: '~Na noite em que o céu abriu, Vela e Âncora foram puxados.',
  st_open_5: '~Faísca ficou. E o Berço fechou as portas.',
  st_open_6: '~No meio do Berço, uma coisa velha pulsa. E fala com você.',
  st_open_ask: 'Você entendeu o que aconteceu?',
  st_open_oU: 'Entendi que eles não voltam sozinhos.',
  st_open_oQ: 'Não. Por que o céu abriu?',
  st_open_oF: 'Entendi. E vou tirar os dois de lá.',
  st_open_rU: 'Então já sabe o mais difícil. O resto é caminho.',
  st_open_rQ: 'Guarde a pergunta. Ela pesa menos que a raiva.',
  st_open_rF: 'Todos dizem isso na primeira noite. Poucos na última.',

  /* ---------------- entrada da galáxia 1 ---------------- */
  st_g1_1: '~O Berço é morno. Aqui os anéis são grandes e vêm devagar.',
  st_g1_2: '~Foi feito assim: é onde luz nova aprende a voar.',
  st_g1_3: '~No meio dele, uma coisa velha pulsa, e tudo volta a dormir.',
  st_g1_ask: 'Dorme, faísca. Lá fora machuca.',
  st_g1_oU: 'Eu sei que machuca. Mesmo assim eu vou.',
  st_g1_oQ: 'Machuca mais do que ficar sem eles?',
  st_g1_oF: 'Então sai da frente.',
  st_g1_rU: 'Machuca de um jeito que não se conta. Vá.',
  st_g1_rQ: '…Não. Não machuca mais que isso.',
  st_g1_rF: 'Ninguém está na sua frente. Eu estou no seu caminho.',

  /* ---------------- visitas do elenco ---------------- */
  st_g1v3_who: 'casco',
  st_g1v3_1: 'Casco. Sou um casco. O nome pegou.',
  st_g1v3_2: 'Conheci a tua mãe. Voava torto e chegava primeiro.',
  st_g1v3_3: '~Ele não diz mais nada sobre isso. Por enquanto.',
  st_g1v6_who: 'casco',
  st_g1v6_1: 'Vai doer hoje. Não é castigo: é o caminho ficando sério.',
  st_g1v6_2: 'Quando doer, olhe o próximo anel. Só o próximo.',
  st_g1v9_who: 'casco',
  st_g1v9_1: 'Ele perdeu onze. Sabe o nome dos onze.',
  st_g1v9_2: 'Não é portão, menina. É um velho com medo.',

  /* ---------------- as dez conversas ---------------- */
  st_g1b1_ask: 'Para onde você pensa que vai?',
  st_g1b1_oU: 'Para onde eles foram. Devagar, se precisar.',
  st_g1b1_oQ: 'Para o lugar onde o céu abriu. Você sabe onde é?',
  st_g1b1_oF: 'Para o meio do escuro. E eu chego.',
  st_g1b1_rU: 'Devagar é como se chega longe.',
  st_g1b1_rQ: 'Sei. E é por isso que eu não quero que vá.',
  st_g1b1_rF: 'O escuro também já ouviu isso.',

  st_g1b2_ask: 'Quem você acha que desenhou esses anéis?',
  st_g1b2_oU: 'Alguém que passou antes de mim.',
  st_g1b2_oQ: 'Eles não aparecem sozinhos?',
  st_g1b2_oF: 'Não importa. Eu passo por eles.',
  st_g1b2_rU: 'Anéis não nascem. Alguém os abre.',
  st_g1b2_rQ: 'Nada aqui aparece sozinho. Nem você.',
  st_g1b2_rF: 'Passa. E não vê nenhum.',

  st_g1b3_ask: 'Vai levar esse casco amassado junto?',
  st_g1b3_oU: 'Ele conheceu minha mãe. Vou ouvir.',
  st_g1b3_oQ: 'Ele sabe alguma coisa que eu não sei?',
  st_g1b3_oF: 'Ele vai me atrasar.',
  st_g1b3_rU: 'Ouvir é a única coisa que ninguém faz por aqui.',
  st_g1b3_rQ: 'Sabe. E vai demorar a dizer.',
  st_g1b3_rF: 'Vai. Velho atrasa. E lembra.',

  st_g1b4_ask: 'Do que você tem medo?',
  st_g1b4_oU: 'De chegar tarde.',
  st_g1b4_oQ: 'Medo serve para quê?',
  st_g1b4_oF: 'De nada.',
  st_g1b4_rU: 'Esse medo é bom. Ele anda com você.',
  st_g1b4_rQ: 'Para você ir devagar onde é fundo.',
  st_g1b4_rF: 'Então você ainda não olhou direito.',

  st_g1b5_ask: 'Você me culpa por ter fechado as portas?',
  st_g1b5_oU: 'Não. Você tentou cuidar.',
  st_g1b5_oQ: 'Quantos você perdeu?',
  st_g1b5_oF: 'Culpo. Você prendeu todo mundo.',
  st_g1b5_rU: 'Tentei. Tentar não é a mesma coisa que acertar.',
  st_g1b5_rQ: 'Onze. Eu sei o nome dos onze.',
  st_g1b5_rF: 'Prendi. E mesmo assim perdi.',

  st_g1b6_ask: 'Doeu. Quer voltar agora?',
  st_g1b6_oU: 'Doeu. E eu continuo.',
  st_g1b6_oQ: 'Vai doer assim o caminho inteiro?',
  st_g1b6_oF: 'Não senti nada.',
  st_g1b6_rU: 'Foi o que eles disseram. Eu acreditei.',
  st_g1b6_rQ: 'Não. Vai doer de jeitos diferentes.',
  st_g1b6_rF: 'Sentiu. Só não quis contar.',

  st_g1b7_ask: 'E quando o caminho virar de cabeça para baixo?',
  st_g1b7_oU: 'Eu viro junto.',
  st_g1b7_oQ: 'Por que ele viraria?',
  st_g1b7_oF: 'Eu endireito o caminho.',
  st_g1b7_rU: 'Boa resposta. Guarde para a sétima galáxia.',
  st_g1b7_rQ: 'Porque nada aqui foi feito para o seu conforto.',
  st_g1b7_rF: 'Você vai tentar. Nove vezes.',

  st_g1b8_ask: 'O que você deixa aqui?',
  st_g1b8_oU: 'O anel do berço. Ele não cabe mais em mim.',
  st_g1b8_oQ: 'Preciso deixar alguma coisa?',
  st_g1b8_oF: 'Não deixo nada. Levo tudo.',
  st_g1b8_rU: 'Deixe. Eu guardo.',
  st_g1b8_rQ: 'Sempre. Só nem todo mundo escolhe o quê.',
  st_g1b8_rF: 'Então vai carregar peso à toa.',

  st_g1b9_ask: 'Já ouviu falar de mim lá fora?',
  st_g1b9_oU: 'Ouvi que você segurou muita gente. Inclusive eu.',
  st_g1b9_oQ: 'Ouvi. Isso te incomoda?',
  st_g1b9_oF: 'Ouvi que você é um portão.',
  st_g1b9_rU: 'Segurar era tudo que eu sabia fazer.',
  st_g1b9_rQ: 'Incomoda. Ainda assim eu pulso.',
  st_g1b9_rF: 'Portão. É uma palavra honesta.',

  st_g1b10_1: '~O Guardião não te ataca. Ele pulsa, e os anéis pulsam com ele.',
  st_g1b10_2: '~É o jeito dele de dizer: fica.',
  st_g1b10_3: 'Eu segurei todos vocês para que ninguém se perdesse.',
  st_g1b10_4: 'Perdi assim mesmo. Onze.',
  st_g1b10_ask: 'Me diga por que eu deveria abrir.',
  st_g1b10_oU: 'Porque segurar não é a mesma coisa que cuidar.',
  st_g1b10_oQ: 'Porque você também quer saber o que há lá fora.',
  st_g1b10_oF: 'Porque eu passo com licença ou sem.',
  st_g1b10_rU: '…Vá. Se encontrar algum dos onze, diga que eu esperei.',
  st_g1b10_rQ: '…Talvez. Então vá perguntar por mim.',
  st_g1b10_rF: '…Passe. E veja quanto pesa carregar isso sozinho.',

  /* ---------------- carta ---------------- */
  st_g1c_who: 'vela', st_g1c_k: 'Carta de Vela',
  st_g1c_1: '~Na saída do Berço, um anel ficou girando sozinho.',
  st_g1c_2: '~Dentro dele, com a letra dela:',
  st_g1c_3: 'Faísca: se você está lendo isto, já sabe voar.',
  st_g1c_4: 'Não corra. O caminho foi feito para o seu tamanho.',
  st_g1c_5: 'Deixei esse anel girando. É para treinar — e para quando sentir falta.',
  st_g1c_6: '— V.'
});

Object.assign(HR.I18N.en, {
  st_cast_faisca: 'Spark', st_cast_vela: 'Sail', st_cast_ancora: 'Anchor', st_cast_casco: 'Hull',
  st_cast_iris: 'Iris', st_cast_poeira: 'Dust', st_cast_cardume: 'The Shoal', st_cast_porta: 'The Door',
  st_set: 'Story', st_set_d: 'Scenes between levels. Skipping never changes the game.',
  st_set_full: 'Full', st_set_short: 'Short', st_set_off: 'Off',
  st_ring_bonus: "Sail's ring: +{n}% coins in Endless",

  st_open_k: 'The first night', st_open_who: 'faisca',
  st_open_1: '~In the beginning there were three lights and one small ring.',
  st_open_2: '~The biggest one called the smallest one Spark.',
  st_open_3: '~"A home needs a sail and an anchor," she said. "And a spark."',
  st_open_4: '~The night the sky opened, Sail and Anchor were pulled in.',
  st_open_5: '~Spark stayed. And the Cradle shut its doors.',
  st_open_6: '~In the middle of the Cradle something old pulses. And speaks.',
  st_open_ask: 'Do you understand what happened?',
  st_open_oU: 'I understand they are not coming back alone.',
  st_open_oQ: 'No. Why did the sky open?',
  st_open_oF: 'I do. And I am pulling them out of there.',
  st_open_rU: 'Then you know the hardest part. The rest is road.',
  st_open_rQ: 'Keep the question. It weighs less than anger.',
  st_open_rF: 'Everyone says that on the first night. Few on the last.',

  st_g1_1: '~The Cradle is warm. Here the rings are wide and slow.',
  st_g1_2: '~It was made that way: new light learns to fly here.',
  st_g1_3: '~In its middle something old pulses, and everything sleeps again.',
  st_g1_ask: 'Sleep, spark. Out there it hurts.',
  st_g1_oU: 'I know it hurts. I am going anyway.',
  st_g1_oQ: 'Does it hurt more than being without them?',
  st_g1_oF: 'Then get out of my way.',
  st_g1_rU: 'It hurts in a way no one tells. Go.',
  st_g1_rQ: '…No. Nothing hurts more than that.',
  st_g1_rF: 'No one is in your way. I am on your road.',

  st_g1v3_who: 'casco',
  st_g1v3_1: 'Hull. I am a hull. The name stuck.',
  st_g1v3_2: 'I knew your mother. Flew crooked and got there first.',
  st_g1v3_3: '~He says nothing more about it. For now.',
  st_g1v6_who: 'casco',
  st_g1v6_1: 'Today it will hurt. Not a punishment: the road getting serious.',
  st_g1v6_2: 'When it hurts, look at the next ring. Only the next one.',
  st_g1v9_who: 'casco',
  st_g1v9_1: 'He lost eleven. He knows all eleven names.',
  st_g1v9_2: 'He is not a gate, girl. He is an old thing that is afraid.',

  st_g1b1_ask: 'Where do you think you are going?',
  st_g1b1_oU: 'Where they went. Slowly, if I must.',
  st_g1b1_oQ: 'To where the sky opened. Do you know where that is?',
  st_g1b1_oF: 'Into the middle of the dark. And I will get there.',
  st_g1b1_rU: 'Slow is how you get far.',
  st_g1b1_rQ: 'I do. That is why I do not want you to go.',
  st_g1b1_rF: 'The dark has heard that one too.',

  st_g1b2_ask: 'Who do you think drew these rings?',
  st_g1b2_oU: 'Someone who came through before me.',
  st_g1b2_oQ: 'Do they not just appear?',
  st_g1b2_oF: 'Does not matter. I fly through them.',
  st_g1b2_rU: 'Rings are not born. Someone opens them.',
  st_g1b2_rQ: 'Nothing here appears on its own. Not even you.',
  st_g1b2_rF: 'You fly. And you see none of them.',

  st_g1b3_ask: 'Taking that dented hull with you?',
  st_g1b3_oU: 'He knew my mother. I will listen.',
  st_g1b3_oQ: 'Does he know something I do not?',
  st_g1b3_oF: 'He will slow me down.',
  st_g1b3_rU: 'Listening is the one thing nobody does around here.',
  st_g1b3_rQ: 'He does. And he will take his time saying it.',
  st_g1b3_rF: 'He will. Old things slow you down. And remember.',

  st_g1b4_ask: 'What are you afraid of?',
  st_g1b4_oU: 'Of arriving too late.',
  st_g1b4_oQ: 'What is fear for?',
  st_g1b4_oF: 'Nothing.',
  st_g1b4_rU: 'That fear is a good one. It walks with you.',
  st_g1b4_rQ: 'To make you go slow where it is deep.',
  st_g1b4_rF: 'Then you have not looked properly yet.',

  st_g1b5_ask: 'Do you blame me for closing the doors?',
  st_g1b5_oU: 'No. You were trying to care.',
  st_g1b5_oQ: 'How many did you lose?',
  st_g1b5_oF: 'I do. You locked everyone in.',
  st_g1b5_rU: 'I tried. Trying is not the same as getting it right.',
  st_g1b5_rQ: 'Eleven. I know all eleven names.',
  st_g1b5_rF: 'I locked them in. And lost them anyway.',

  st_g1b6_ask: 'That hurt. Want to go back now?',
  st_g1b6_oU: 'It hurt. And I am going on.',
  st_g1b6_oQ: 'Will it hurt like this the whole way?',
  st_g1b6_oF: 'I felt nothing.',
  st_g1b6_rU: 'That is what they said too. I believed them.',
  st_g1b6_rQ: 'No. It will hurt in different ways.',
  st_g1b6_rF: 'You felt it. You just did not want to say so.',

  st_g1b7_ask: 'And when the road turns upside down?',
  st_g1b7_oU: 'I turn with it.',
  st_g1b7_oQ: 'Why would it turn?',
  st_g1b7_oF: 'I will straighten the road out.',
  st_g1b7_rU: 'Good answer. Save it for the seventh galaxy.',
  st_g1b7_rQ: 'Because nothing here was made for your comfort.',
  st_g1b7_rF: 'You will try. Nine times.',

  st_g1b8_ask: 'What do you leave here?',
  st_g1b8_oU: 'The cradle ring. It does not fit me anymore.',
  st_g1b8_oQ: 'Do I have to leave something?',
  st_g1b8_oF: 'Nothing. I take it all.',
  st_g1b8_rU: 'Leave it. I will keep it.',
  st_g1b8_rQ: 'Always. Not everyone gets to choose what.',
  st_g1b8_rF: 'Then you will carry weight for nothing.',

  st_g1b9_ask: 'Have you heard of me, out there?',
  st_g1b9_oU: 'I heard you held a lot of us. Me included.',
  st_g1b9_oQ: 'I have. Does that bother you?',
  st_g1b9_oF: 'I heard you are a gate.',
  st_g1b9_rU: 'Holding was all I knew how to do.',
  st_g1b9_rQ: 'It does. I keep pulsing anyway.',
  st_g1b9_rF: 'A gate. That is an honest word.',

  st_g1b10_1: '~The Guardian does not attack. He pulses, and the rings pulse too.',
  st_g1b10_2: '~It is his way of saying: stay.',
  st_g1b10_3: 'I held every one of you so that nobody would be lost.',
  st_g1b10_4: 'I lost them anyway. Eleven.',
  st_g1b10_ask: 'Tell me why I should open.',
  st_g1b10_oU: 'Because holding is not the same as caring.',
  st_g1b10_oQ: 'Because you also want to know what is out there.',
  st_g1b10_oF: 'Because I am going through, with or without you.',
  st_g1b10_rU: '…Go. If you meet one of the eleven, say that I waited.',
  st_g1b10_rQ: '…Maybe. Then go and ask for me.',
  st_g1b10_rF: '…Go through. And see how heavy that gets, alone.',

  st_g1c_who: 'vela', st_g1c_k: 'A letter from Sail',
  st_g1c_1: '~At the edge of the Cradle, one ring kept turning by itself.',
  st_g1c_2: '~Inside it, in her handwriting:',
  st_g1c_3: 'Spark: if you are reading this, you already know how to fly.',
  st_g1c_4: 'Do not rush. The road was made for your size.',
  st_g1c_5: 'I left that ring turning. To practise — and for when you miss us.',
  st_g1c_6: '— S.'
});

Object.assign(HR.I18N.es, {
  st_cast_faisca: 'Chispa', st_cast_vela: 'Vela', st_cast_ancora: 'Ancla', st_cast_casco: 'Casco',
  st_cast_iris: 'Iris', st_cast_poeira: 'Polvo', st_cast_cardume: 'El Cardumen', st_cast_porta: 'La Puerta',
  st_set: 'Historia', st_set_d: 'Escenas entre fases. Saltarlas nunca cambia el juego.',
  st_set_full: 'Completa', st_set_short: 'Corta', st_set_off: 'Apagada',
  st_ring_bonus: 'El anillo de Vela: +{n} % de monedas en Infinito',

  st_open_k: 'La primera noche', st_open_who: 'faisca',
  st_open_1: '~Antes de todo había tres luces y un anillo pequeño.',
  st_open_2: '~La más grande llamaba Chispa a la más pequeña.',
  st_open_3: '~"Una casa necesita vela y ancla", decía. "Y una chispa."',
  st_open_4: '~La noche en que el cielo se abrió, Vela y Ancla fueron arrastrados.',
  st_open_5: '~Chispa se quedó. Y la Cuna cerró las puertas.',
  st_open_6: '~En medio de la Cuna algo viejo late. Y te habla.',
  st_open_ask: '¿Entendiste lo que pasó?',
  st_open_oU: 'Entendí que ellos no vuelven solos.',
  st_open_oQ: 'No. ¿Por qué se abrió el cielo?',
  st_open_oF: 'Entendí. Y voy a sacarlos de ahí.',
  st_open_rU: 'Entonces ya sabes lo más difícil. El resto es camino.',
  st_open_rQ: 'Guarda la pregunta. Pesa menos que la rabia.',
  st_open_rF: 'Todos dicen eso la primera noche. Pocos la última.',

  st_g1_1: '~La Cuna es tibia. Aquí los anillos son grandes y vienen despacio.',
  st_g1_2: '~Se hizo así: es donde la luz nueva aprende a volar.',
  st_g1_3: '~En el medio algo viejo late, y todo vuelve a dormir.',
  st_g1_ask: 'Duerme, chispa. Allá afuera duele.',
  st_g1_oU: 'Sé que duele. Aun así voy.',
  st_g1_oQ: '¿Duele más que quedarme sin ellos?',
  st_g1_oF: 'Entonces quítate del camino.',
  st_g1_rU: 'Duele de un modo que nadie cuenta. Ve.',
  st_g1_rQ: '…No. Nada duele más que eso.',
  st_g1_rF: 'Nadie está en tu camino. Yo soy tu camino.',

  st_g1v3_who: 'casco',
  st_g1v3_1: 'Casco. Soy un casco. El nombre se quedó.',
  st_g1v3_2: 'Conocí a tu madre. Volaba torcido y llegaba primero.',
  st_g1v3_3: '~No dice nada más sobre eso. Por ahora.',
  st_g1v6_who: 'casco',
  st_g1v6_1: 'Hoy va a doler. No es castigo: el camino se pone serio.',
  st_g1v6_2: 'Cuando duela, mira el próximo anillo. Solo el próximo.',
  st_g1v9_who: 'casco',
  st_g1v9_1: 'Perdió once. Sabe el nombre de los once.',
  st_g1v9_2: 'No es un portón, niña. Es un viejo con miedo.',

  st_g1b1_ask: '¿A dónde crees que vas?',
  st_g1b1_oU: 'A donde ellos fueron. Despacio, si hace falta.',
  st_g1b1_oQ: 'A donde se abrió el cielo. ¿Sabes dónde es?',
  st_g1b1_oF: 'Al medio de lo oscuro. Y voy a llegar.',
  st_g1b1_rU: 'Despacio es como se llega lejos.',
  st_g1b1_rQ: 'Lo sé. Por eso no quiero que vayas.',
  st_g1b1_rF: 'Lo oscuro también ya escuchó eso.',

  st_g1b2_ask: '¿Quién crees que dibujó estos anillos?',
  st_g1b2_oU: 'Alguien que pasó antes que yo.',
  st_g1b2_oQ: '¿No aparecen solos?',
  st_g1b2_oF: 'No importa. Yo paso por ellos.',
  st_g1b2_rU: 'Los anillos no nacen. Alguien los abre.',
  st_g1b2_rQ: 'Nada aquí aparece solo. Ni tú.',
  st_g1b2_rF: 'Pasas. Y no ves ninguno.',

  st_g1b3_ask: '¿Vas a llevar ese casco abollado contigo?',
  st_g1b3_oU: 'Conoció a mi madre. Voy a escucharlo.',
  st_g1b3_oQ: '¿Sabe algo que yo no sé?',
  st_g1b3_oF: 'Me va a atrasar.',
  st_g1b3_rU: 'Escuchar es lo único que nadie hace por aquí.',
  st_g1b3_rQ: 'Lo sabe. Y va a tardar en decirlo.',
  st_g1b3_rF: 'Sí. Lo viejo atrasa. Y recuerda.',

  st_g1b4_ask: '¿A qué le tienes miedo?',
  st_g1b4_oU: 'A llegar tarde.',
  st_g1b4_oQ: '¿Para qué sirve el miedo?',
  st_g1b4_oF: 'A nada.',
  st_g1b4_rU: 'Ese miedo es bueno. Camina contigo.',
  st_g1b4_rQ: 'Para ir despacio donde es hondo.',
  st_g1b4_rF: 'Entonces todavía no miraste bien.',

  st_g1b5_ask: '¿Me culpas por haber cerrado las puertas?',
  st_g1b5_oU: 'No. Intentabas cuidar.',
  st_g1b5_oQ: '¿Cuántos perdiste?',
  st_g1b5_oF: 'Te culpo. Encerraste a todos.',
  st_g1b5_rU: 'Lo intenté. Intentar no es lo mismo que acertar.',
  st_g1b5_rQ: 'Once. Sé el nombre de los once.',
  st_g1b5_rF: 'Los encerré. Y aun así los perdí.',

  st_g1b6_ask: 'Dolió. ¿Quieres volver ahora?',
  st_g1b6_oU: 'Dolió. Y sigo.',
  st_g1b6_oQ: '¿Va a doler así todo el camino?',
  st_g1b6_oF: 'No sentí nada.',
  st_g1b6_rU: 'Eso mismo dijeron ellos. Les creí.',
  st_g1b6_rQ: 'No. Va a doler de otras formas.',
  st_g1b6_rF: 'Lo sentiste. Solo no quisiste contarlo.',

  st_g1b7_ask: '¿Y cuando el camino se dé vuelta?',
  st_g1b7_oU: 'Me doy vuelta con él.',
  st_g1b7_oQ: '¿Por qué se daría vuelta?',
  st_g1b7_oF: 'Yo enderezo el camino.',
  st_g1b7_rU: 'Buena respuesta. Guárdala para la séptima galaxia.',
  st_g1b7_rQ: 'Porque nada aquí se hizo para tu comodidad.',
  st_g1b7_rF: 'Lo vas a intentar. Nueve veces.',

  st_g1b8_ask: '¿Qué dejas aquí?',
  st_g1b8_oU: 'El anillo de la cuna. Ya no me cabe.',
  st_g1b8_oQ: '¿Tengo que dejar algo?',
  st_g1b8_oF: 'Nada. Me llevo todo.',
  st_g1b8_rU: 'Déjalo. Yo lo guardo.',
  st_g1b8_rQ: 'Siempre. Solo que no todos eligen qué.',
  st_g1b8_rF: 'Entonces vas a cargar peso al pedo.',

  st_g1b9_ask: '¿Oíste hablar de mí allá afuera?',
  st_g1b9_oU: 'Oí que sostuviste a mucha gente. A mí también.',
  st_g1b9_oQ: 'Oí. ¿Eso te molesta?',
  st_g1b9_oF: 'Oí que eres un portón.',
  st_g1b9_rU: 'Sostener era lo único que yo sabía hacer.',
  st_g1b9_rQ: 'Me molesta. Y aun así late.',
  st_g1b9_rF: 'Portón. Es una palabra honesta.',

  st_g1b10_1: '~El Guardián no ataca. Late, y los anillos laten con él.',
  st_g1b10_2: '~Es su manera de decir: quédate.',
  st_g1b10_3: 'Los sostuve a todos para que nadie se perdiera.',
  st_g1b10_4: 'Los perdí igual. Once.',
  st_g1b10_ask: 'Dime por qué debería abrir.',
  st_g1b10_oU: 'Porque sostener no es lo mismo que cuidar.',
  st_g1b10_oQ: 'Porque tú también quieres saber qué hay afuera.',
  st_g1b10_oF: 'Porque paso con permiso o sin él.',
  st_g1b10_rU: '…Ve. Si encuentras a uno de los once, dile que esperé.',
  st_g1b10_rQ: '…Quizá. Entonces ve a preguntar por mí.',
  st_g1b10_rF: '…Pasa. Y mira cuánto pesa cargar eso solo.',

  st_g1c_who: 'vela', st_g1c_k: 'Carta de Vela',
  st_g1c_1: '~A la salida de la Cuna quedó un anillo girando solo.',
  st_g1c_2: '~Dentro, con su letra:',
  st_g1c_3: 'Chispa: si estás leyendo esto, ya sabes volar.',
  st_g1c_4: 'No corras. El camino se hizo a tu medida.',
  st_g1c_5: 'Dejé ese anillo girando. Para entrenar — y para cuando extrañes.',
  st_g1c_6: '— V.'
});
